# cografya_data_1.py - Q88 to Q96 (90 questions)

# Q88: Coğrafi Konum - Matematik Konum
q88_list = [
    ("Türkiye 36°-42° Kuzey paralelleri ile 26°-45° Doğu meridyenleri arasında yer alır. Buna göre Türkiye'nin en doğusu ile en batısı arasındaki yerel saat farkı kaç dakikadır?", "76 dakika", ["60 dakika", "45 dakika", "80 dakika", "90 dakika"], "45 - 26 = 19 boylam farkı vardır. İki boylam arası 4 dakika olduğundan: 19 · 4 = 76 dakika yerel saat farkı oluşur."),
    ("21 Haziran tarihinde Türkiye'de en uzun gündüz süresi aşağıdaki şehirlerin hangisinde yaşanır?", "Sinop", ["Hatay", "Antalya", "İzmir", "Ankara"], "21 Haziran'da kuzeye gidildikçe gündüz süresi uzar; en kuzeydeki ilimiz Sinop'tur."),
    ("21 Aralık tarihinde Türkiye'de en uzun gündüz (veya en kısa gece) hangi ilimizde yaşanır?", "Hatay", ["Sinop", "Trabzon", "Edirne", "Kars"], "21 Aralık'ta güneye gidildikçe gündüz süresi uzar; en güneydeki ilimiz Hatay'dır."),
    ("Türkiye'de güneyden kuzeye doğru gidildikçe aşağıdakilerden hangisi GERÇEKLEŞMEZ?", "Güneş ışınlarının geliş açısının büyümesi", ["Gölge boylarının uzaması", "Çizgisel hızın azalması", "Yerçekiminin artması", "Grup ve tan (şafak) süresinin uzaması"], "Kuzeye gidildikçe Güneş ışınlarının geliş açısı küçülür, büyümez."),
    ("Türkiye Kuzey Yarım Küre'de Orta Kuşakta (36°-42° K) yer aldığı için güneye bakan yamaçlar kuzeye göre daha fazla ısınır. Bu coğrafi kavrama ne ad verilir?", "Bakı etkisi", ["Yükselti etkisi", "Karasallık etkisi", "Enlem etkisi", "Rüzgâr etkisi"], "Güneşe dönük yamaçların daha sıcak olmasına bakı etkisi denir."),
    ("Türkiye'nin ılıman kuşakta yer alması sonucu yıl içinde dört mevsimin belirgin olarak yaşanması Türkiye'nin hangi özelliğinin sonucudur?", "Mutlak (Matematik) konumunun", ["Göreceli (Özel) konumunun", "Jeopolitik konumunun", "Üç tarafının denizle çevrili olmasının", "Asya ile Avrupa arasında köprü olmasının"], "Dört mevsimin belirgin yaşanması Akdeniz iklim kuşağında ve Orta Kuşak'ta olmanın sonucudur."),
    ("Türkiye'de gece ve gündüz sürelerinin tüm yurtta eşit (12 saat gündüz, 12 saat gece) olduğu ekinoks tarihleri hangileridir?", "21 Mart - 23 Eylül", ["21 Haziran - 21 Aralık", "1 Ocak - 1 Temmuz", "23 Nisan - 29 Ekim", "15 Temmuz - 30 Ağustos"], "Ekinoks tarihlerinde Güneş ışınları Ekvator'a dik gelir ve tüm dünyada gece-gündüz eşittir."),
    ("Türkiye'nin 2. ve 3. saat dilimlerinde yer almasına rağmen yıl boyunca kullandığı ulusal (ortak) saat hangi meridyenin yerel saatidir?", "45° Doğu Meridyeni (Iğdır - GMT+3)", ["30° Doğu Meridyeni (İzmit - GMT+2)", "26° Doğu Meridyeni (Çanakkale)", "36° Doğu Meridyeni (Sivas)", "42° Doğu Meridyeni (Hakkari)"], "Kalıcı yaz saati uygulamasıyla 45° Doğu Iğdır saati kullanılmaktadır."),
    ("Türkiye'de cisimlerin gölgesinin öğle vakti hiçbir zaman sıfır olmamasının ve daima kuzeyi göstermesinin sebebi nedir?", "Dönencelerin dışında (Yengeç Dönencesi'nin kuzeyinde) yer alması", ["Karasal olması", "Ortalama yükseltisinin fazla olması", "Ekinoks tarihlerinin yaşanması", "Dağların doğu-batı yönlü uzanması"], "Güneş ışınları dönenceler dışına asla 90 derecelik dik açıyla gelmez."),
    ("Güneşin Türkiye'de en erken doğduğu ve en erken battığı ilimiz hangisidir?", "Iğdır", ["Çanakkale", "Edirne", "İzmir", "Muğla"], "En doğudaki ilimiz Iğdır olduğu için yerel saat en ileridir ve Güneş en erken doğar.")
]

# Q89: Özel Konum ve Jeolojik Yapı
q89_list = [
    ("Türkiye arazisinin büyük bir kısmının III. ve IV. jeolojik zamanlarda oluşmuş genç bir arazi olmasının kanıtı aşağıdakilerden hangisi DEĞİLDİR?", "Taş kömürü yataklarının bulunması (I. Zaman)", ["Aktif fay hatları ve sık depremler yaşanması", "Linyit, bor ve petrol yataklarının yaygınlığı", "Ortalama yükseltisinin fazla ve engebeli olması", "Jeotermal kaynakların ve kaplıcaların bolluğu"], "Taş kömürü I. Jeolojik Zaman'a (Paleozoik) ait yaşlı arazilerde oluşur."),
    ("Türkiye'de I. Jeolojik Zaman'da (Paleozoik) oluşmuş, sert, deprem riski düşük masif arazilerden biri aşağıdakilerden hangisidir?", "Yıldız Dağları (Istranca) Masifi", ["Kuzey Anadolu Fay Kuşağı", "Batı Anadolu Grabenleri", "Erzincan Ovası", "Gediz Havzası"], "Yıldız, Menteşe, Saruhan, Kırşehir, Bitlis, Mardin başlıca masif arazilerdir."),
    ("İstanbul ve Çanakkale boğazlarının oluşması ve Egeid karasının çökerek Ege Denizi'nin meydana gelmesi hangi jeolojik zamanda gerçekleşmiştir?", "IV. Jeolojik Zaman (Kuvaterner)", ["I. Zaman (Paleozoik)", "II. Zaman (Mezozoik)", "III. Zaman (Tersiyer)", "Prekambriyen"], "Boğazlar ve Ege Denizi en son jeolojik zamanda oluşmuştur."),
    ("Türkiye'nin Asya, Avrupa ve Afrika kıtaları arasında bir kavşak noktası olması, petrol ve doğalgaz boru hatlarına ev sahipliği yapması hangi özelliğidir?", "Jeopolitik ve göreceli (özel) konumu", ["Mutlak matematik konumu", "Enlem etkisi", "Boylam farkı", "İklim kuşağı"], "Stratejik kıtalararası köprü konumu jeopolitik önemini artırır."),
    ("Türkiye'de kısa mesafelerde iklim, bitki örtüsü ve tarım ürünü çeşitliliğinin görülmesinin TEMEL sebebi nedir?", "Yerşekillerinin ve yükseltinin kısa mesafede hızla değişmesi", ["Boylam farkının fazla olması", "Orta Kuşak'ta yer alması", "Kuzey Yarım Küre'de bulunması", "Güneş ışınlarının açısı"], "Yerşekillerindeki çeşitlilik yerel mikroklima alanları yaratır."),
    ("Alp-Himalaya kıvrım kuşağında yer alan Türkiye'nin dağ kuşakları genel olarak hangi jeolojik zamanda kıvrılarak yükselmiştir?", "III. Jeolojik Zaman (Tersiyer)", ["I. Zaman", "II. Zaman", "IV. Zaman", "Kambriyen"], "Toroslar ve Kuzey Anadolu Dağları III. zamanda kıvrılmıştır."),
    ("Türkiye'de kaplıca, ılıca ve jeotermal kaynakların en yaygın olduğu ve kırıklı fay yapısının en fazla görüldüğü coğrafi bölge hangisidir?", "Ege Bölgesi", ["İç Anadolu Bölgesi", "Karadeniz Bölgesi", "Doğu Anadolu Bölgesi", "Güneydoğu Anadolu"], "Graben sahaları boyunca zengin jeotermal akışkan mevcuttur."),
    ("Türkiye arazisinin IV. Jeolojik Zaman'da toptan yükselmesine (epirojenez) kanıt olarak ne gösterilebilir?", "Yüksek düzlükler olan platoların ve akarsu taraçalarının yaygın olması", ["Taş kömürünün çıkarılması", "Volkanik göllerin bulunması", "Buzul göllerinin varlığı", "Maki bitki örtüsü"], "Peneplenleşen Anadolu toptan yükselerek yüksek plato haline gelmiştir."),
    ("Türkiye'de buzul şekillerine (sirk gölleri, buzul vadileri) yalnızca 2.500-3.000 metrenin üzerindeki yüksek dağ zirvelerinde rastlanmasının sebebi nedir?", "Matematik konumu (Orta Kuşak'ta olması) ve yüksekliği", ["Enlem derecesinin sıfır olması", "Deniz seviyesinde buzulların erimemesi", "Föhn rüzgârlarının esmesi", "Sibirya yüksek basıncı"], "Orta kuşakta deniz seviyesinde buzul oluşamaz, sadece yüksek zirvelerde bulunur."),
    ("Türkiye'nin ortalama yükseltisinin en az olduğu ve fiziki haritalarda yeşil rengin en çok kullanıldığı coğrafi bölge hangisidir?", "Marmara Bölgesi", ["Ege Bölgesi", "İç Anadolu Bölgesi", "Karadeniz Bölgesi", "Doğu Anadolu Bölgesi"], "0-500 metre arası yeşil renkle gösterilir; Marmara en alçak bölgemizdir.")
]

# Q90: Dağlar (Kıvrım, Kırık, Volkanik)
q90_list = [
    ("Ege Bölgesi'nde sert tabakaların kırılması sonucu yükselen kısımlara horst, çöken çukurluklara ise graben denir. Aşağıdakilerden hangisi bir 'horst' (kırık dağı) örneğidir?", "Madra ve Yunt Dağları", ["Köroğlu Dağları", "Kaçkar Dağları", "Erciyes Dağı", "Bey Dağları"], "Kaz, Madra, Yunt, Bozdağlar, Aydın Dağları ve Menteşe horst dağlarıdır."),
    ("Akdeniz Bölgesi'nde yer alan ve kırılma (horst) sonucu oluşan Amanos (Nur) Dağları'nın graben çukurluğunda hangi verimli ova yer alır?", "Amik Ovası", ["Gediz Ovası", "Bakırçay Ovası", "Çukurova", "Silifke Ovası"], "Amanos Dağları horst, Amik Ovası grabendir."),
    ("Türkiye'nin en yüksek zirvesi olan (5.137 m) ve volkanik kökenli bir stratovolkan olan dağ hangisidir?", "Ağrı Dağı", ["Cilo Dağı", "Süphan Dağı", "Erciyes Dağı", "Kaçkar Dağı"], "Büyük Ağrı Dağı sönmüş bir volkan dağıdır."),
    ("İç Anadolu Bölgesi'nde yer alan volkanik dağlar hangi seçenekte bir arada verilmiştir?", "Erciyes, Hasan Dağı, Melendiz, Karadağ, Karacadağ", ["Ağrı, Tendürek, Süphan, Nemrut", "Kaz, Madra, Yunt, Bozdağlar", "Kaçkar, Canik, Küre, Ilgaz", "Tahtalı, Binboğa, Aladağlar"], "Kuzeydoğu-güneybatı doğrultulu bir hat boyunca sıralanmışlardır."),
    ("Güneydoğu Anadolu Bölgesi'nde bazaltik lavların geniş alana yayılmasıyla oluşan ve kalkan şeklinde yayvan bir volkan olan dağ hangisidir?", "Karacadağ (Diyarbakır-Şanlıurfa)", ["Erciyes", "Nemrut", "Tendürek", "Hasan Dağı"], "Lavların çok akışkan olması nedeniyle kalkan volkan tipindedir."),
    ("Manisa Kula yöresinde yer alan ve Türkiye'nin EN GENÇ volkanik arazisi olup UNESCO Jeoparkı ilan edilen alan hangisidir?", "Kula Volkanları (Yanık Ülke / Katakekaumene)", ["Kapadokya Peribacaları", "Pamukkale Travertenleri", "Nemrut Krateri", "Meke Maarı"], "Türkiye'nin ilk ve tek UNESCO tescilli jeoparkıdır."),
    ("Karadeniz kıyı kuşağı boyunca uzanan Kuzey Anadolu Dağları ile Akdeniz'deki Toros Dağları oluşum türü bakımından hangi dağ tipine girer?", "Kıvrım Dağları (Orojenez)", ["Kırık Dağları", "Volkanik Dağlar", "Masif Dağlar", "Buzul Dağları"], "Alp-Himalaya orojenezi ile tortul tabakaların yan basınçlarla kıvrılması sonucu oluşmuştur."),
    ("Kuzey Anadolu Dağları'nın en yüksek kesimini oluşturan ve üzerinde buzul gölleri bulunan dağ sırası hangisidir?", "Kaçkar Dağları (Rize)", ["Canik Dağları", "Küre Dağları", "Köroğlu Dağları", "Ilgaz Dağları"], "Doğu Karadeniz'de yer alan Kaçkarlar 3.932 metreye ulaşır."),
    ("Orta Karadeniz bölümünde yer alan ve kıyı ile iç kesim arasındaki ulaşımı kolaylaştıran, yükseltisi en az olan dağ sırası hangisidir?", "Canik Dağları (Samsun)", ["Kaçkar Dağları", "Küre Dağları", "Giresun Dağları", "Kop Dağı"], "Canik Dağları alçak olduğu için Samsun'un hinterlandı çok geniştir."),
    ("Batı Toroslar ile Orta Torosları birbirinden ayıran ve karstik aşınım şekillerinin en yaygın olduğu dağ sırası hangisidir?", "Bey Dağları ve Geyik Dağları", ["Amanos Dağları", "Bolu Dağları", "Samanlı Dağları", "Mercan Dağları"], "Antalya bölümünde karstik kireçtaşı araziler üzerinde yükselir.")
]

# Q91: Platolar ve Ovalar
q91_list = [
    ("Akdeniz Bölgesi'nde kalkerli (kireçtaşı) arazilerin erimesiyle oluşan, tarıma elverişsiz, nüfusun çok seyrek olduğu ve kıl keçisi yetiştiriciliğinin yapıldığı KARSTİK platolar hangileridir?", "Teke ve Taşeli Platoları", ["Haymana ve Cihanbeyli Platoları", "Erzurum-Kars Platoları", "Çatalca-Kocaeli Platoları", "Bozok ve Obruk Platoları"], "Karstik kayaçların suyu sızdırması yüzünden yüzey suyu fakiridir."),
    ("Yaz yağışlarıyla yeşeren çayırların altında zengin çernezyom (kara toprak) örtüsüne sahip, büyükbaş mera hayvancılığının yapıldığı VOLKANİK plato hangisidir?", "Erzurum-Kars ve Ardahan Platosu", ["Teke Platosu", "Haymana Platosu", "Bozok Platosu", "Gaziantep Platosu"], "Lav örtülü yüksek volkanik bazalt platosudur."),
    ("Türkiye'nin sanayileşmiş, nüfus yoğunluğu en fazla olan, yükseltisi en az aşınım platosu hangisidir?", "Çatalca-Kocaeli Platosu", ["Bozok Platosu", "Yazılıkaya Platosu", "Cihanbeyli Platosu", "Şanlıurfa Platosu"], "Marmara'da yer alan peneplen platosudur."),
    ("İç Anadolu Bölgesi'nde tahıl tarımının (buğday, arpa) ve küçükbaş hayvancılığın yaygın olduğu tabaka düzlüğü platolarından biri hangisidir?", "Haymana ve Cihanbeyli Platosu", ["Teke Platosu", "Taşeli Platosu", "Kars Platosu", "Ardahan Platosu"], "Ankara ve Konya havzalarındaki geniş düzlüklerdir."),
    ("Akarsuların taşıdığı alüvyonları denizin içine biriktirmesiyle oluşan Türkiye'nin EN BÜYÜK delta ovası hangisidir?", "Çukurova (Seyhan ve Ceyhan)", ["Bafra Ovası", "Çarşamba Ovası", "Gediz Ovası", "Silifke Ovası"], "Akdeniz'deki en verimli tarım ovamızdır."),
    ("Karadeniz Bölgesi'nde Kızılırmak ve Yeşilırmak nehirlerinin oluşturduğu kıyı delta ovaları sırasıyla hangileridir?", "Bafra (Kızılırmak) - Çarşamba (Yeşilırmak)", ["Çarşamba - Bafra", "Çukurova - Silifke", "Gediz - Menemen", "Dikili - Balat"], "Samsun il sınırları içindeki zengin tarım deltalarıdır."),
    ("Ege Bölgesi'nde akarsuların getirdiği alüvyonlarla oluşan delta ovaları hangi seçenekte doğru eşleştirilmiştir?", "Bakırçay-Dikili, Gediz-Menemen, K. Menderes-Selçuk, B. Menderes-Balat", ["Seyhan-Çukurova", "Kızılırmak-Bafra", "Yeşilırmak-Çarşamba", "Göksu-Silifke"], "Ege'nin graben hatları ucundaki verimli delta ovalarıdır."),
    ("Akdeniz Bölgesi'nde Göksu Nehri'nin taşıdığı alüvyonlarla oluşturduğu delta ovası hangisidir?", "Silifke Ovası (Mersin)", ["Çukurova", "Amik Ovası", "Antalya Ovası", "Dörtyol Ovası"], "Göksu Deltası aynı zamanda uluslararası Ramsar sulak alanıdır."),
    ("Karstik erime sonucu oluşan ve 'Polye' adı verilen karstik ovalar (TAKKE şifresi: Tefenni, Acıpayam, Korkuteli, Kestel, Elmalı, Muğla) en çok hangi coğrafi bölgede yer alır?", "Akdeniz Bölgesi", ["Marmara Bölgesi", "Karadeniz Bölgesi", "Doğu Anadolu", "İç Anadolu"], "Kalker erimesiyle oluşan çanak tabanlarındaki ovalardır."),
    ("Doğu Anadolu'da fay hatları boyunca çöküntü alanlarında yer alan çöküntü (tektonik) ovalarından biri aşağıdakilerden hangisidir?", "Erzincan ve Muş Ovaları", ["Bafra Ovası", "Çukurova", "Silifke Ovası", "Menemen Ovası"], "Kuzey Anadolu ve Doğu Anadolu fay hatları üzerindeki tektonik ovalardır.")
]

# Q92: Su Varlığı - Akarsular
q92_list = [
    ("Türkiye'nin sınırları içerisinden doğup yine Türkiye sınırları içerisinde denize dökülen EN UZUN akarsuyumuz hangisidir?", "Kızılırmak (1.355 km)", ["Yeşilırmak", "Sakarya", "Fırat", "Dicle"], "Sivas'tan doğup Samsun Bafra'dan Karadeniz'e dökülür."),
    ("Türkiye sınırları içinden doğup yurt dışında (Basra Körfezi) denize dökülen ve su potansiyeli en yüksek akarsu sistemi hangisidir?", "Fırat ve Dicle Nehirleri", ["Aras ve Kura", "Kızılırmak", "Asi Nehri", "Meriç Nehri"], "Mezopotamya'ya hayat veren Fırat ve Dicle Şattülarap'ta birleşir."),
    ("Kaynağını Türkiye'den alarak Hazar Denizi'ne (kapalı havza) dökülen akarsularımız hangileridir?", "Aras ve Kura Nehirleri", ["Fırat ve Dicle", "Seyhan ve Ceyhan", "Çoruh ve Kelkit", "Zap ve Botan"], "Hazar kapalı havzasına dökülürler."),
    ("Kaynağını yurt dışından alarak Türkiye topraklarından Akdeniz'e dökülen akarsu hangisidir?", "Asi Nehri (Lübnan'dan doğar)", ["Meriç Nehri", "Kızılırmak", "Gediz", "Manavgat"], "Lübnan ve Suriye'den geçip Hatay Samandağ'dan denize dökülür."),
    ("Bulgaristan'dan doğup Türkiye-Yunanistan sınırını çizerek Ege Denizi'ne dökülen nehir hangisidir?", "Meriç Nehri", ["Asi Nehri", "Çoruh Nehri", "Aras Nehri", "Fırat Nehri"], "Edirne ve Trakya'nın en önemli akarsuyudur."),
    ("Türkiye'deki akarsuların akış hızı ve hidroelektrik potansiyellerinin yüksek olmasının TEMEL sebebi nedir?", "Ortalama yükseltinin ve yatak eğiminin fazla olması", ["Boylarının uzun olması", "Rejimlerinin düzenli olması", "Debilerinin her mevsim sabit kalması", "Denizlere dökülmeleri"], "Yatak eğimi fazla olduğu için aşındırma gücü ve hidroelektrik potansiyeli çok yüksektir."),
    ("Türkiye'deki akarsular üzerinde kural olarak taşımacılık ve ulaşım yapılamamasının sebebi nedir?", "Yatak eğimlerinin fazla ve rejimlerinin düzensiz olması", ["Sularının tuzlu olması", "Üzerinde baraj olmaması", "Geniş vadilerde akmaları", "Denize ulaşamamaları"], "Denge profiline ulaşmadıkları için gemi taşımacılığına elverişli değillerdir."),
    ("Yıl boyunca bol ve düzenli yağış alması nedeniyle Türkiye'de akarsu rejimi EN DÜZENLİ olan bölge hangisidir?", "Karadeniz Bölgesi (Örn: Çoruh, Fırtına)", ["Akdeniz Bölgesi", "Ege Bölgesi", "İç Anadolu Bölgesi", "Güneydoğu Anadolu"], "Her mevsim yağış aldığından rejimleri nispeten düzenlidir."),
    ("Hem taban seviyesinin yükselmesi hem de yatak eğiminin azalması sonucu akarsuyun S harfi şeklinde büklümler çizerek akmasına ne ad verilir?", "Menderes", ["Kanyon vadi", "Dev kazanı", "Çentik vadi", "Peribacası"], "Ege akarsularında (Büyük ve Küçük Menderes) tipik olarak görülür."),
    ("Karasal iklim bölgelerinde sel sularının bitki örtüsünden yoksun eğimli yamaçları aşındırmasıyla oluşan yarıntılı arazi şekline ne ad verilir?", "Kırgıbayır (Badlands)", ["Kanyon", "Delta", "Tombolo", "Falez"], "İç Anadolu'da ve Nallıhan çevresinde yaygındır.")
]

# Q93: Göller ve Kıyı Tipleri
q93_list = [
    ("Türkiye'nin yüzölçümü bakımından en büyük gölü olan, suları sodalı olan ve Nemrut volkanının lavlarının akarsu vadisini tıkamasıyla oluşan volkanik set gölü hangisidir?", "Van Gölü", ["Tuz Gölü", "Beyşehir Gölü", "Eğirdir Gölü", "İznik Gölü"], "İnci kefali balığının yaşadığı sodalı kapalı havza gölüdür."),
    ("Türkiye'nin yüzölçümü bakımından ikinci büyük gölü olan, derinliği az, yaz aylarında buharlaşmayla alanı daralan tektonik gölümüz hangisidir?", "Tuz Gölü", ["Van Gölü", "Beyşehir Gölü", "Sapanca Gölü", "Burdur Gölü"], "Türkiye tuz ihtiyacının önemli kısmını karşılar."),
    ("Türkiye'nin EN BÜYÜK tatlı su gölü olan ve dışarıya gideğeni (akıntısı) bulunduğu için suları tatlı olan göl hangisidir?", "Beyşehir Gölü (Konya-Isparta)", ["Eğirdir Gölü", "Tuz Gölü", "Van Gölü", "Uluabat Gölü"], "Gideğeni olan göllerin suları tatlı kalır."),
    ("Kalker ve jips gibi eriyebilen kayaçların çökmesiyle oluşan ve Türkiye'nin Maldivleri olarak bilinen derin karstik gölümüz hangisidir?", "Salda Gölü (Burdur)", ["Manyas Gölü", "Abant Gölü", "Tortum Gölü", "Mogan Gölü"], "Magnezyum zengini beyaz kumsallarıyla ünlü karstik göldür."),
    ("Bitlis Tatvan'da yer alan, sönmüş volkan ağzındaki patlama çanağında oluşan ve Avrupalı Seçkin Destinasyonlar (EDEN) ödüllü krater gölü hangisidir?", "Nemrut Krater Gölü", ["Meke Gölü", "Gölcük Gölü", "Acıgöl", "Salda Gölü"], "Dünyanın ikinci, Türkiye'nin en büyük kaldera gölüdür."),
    ("Heyelan sonucu kayan kütlelerin vadinin önünü kapatmasıyla oluşan 'Heyelan Set Gölleri' (Abant, Yedigöller, Tortum, Sera, Zinav) en çok hangi bölgede yer alır?", "Karadeniz Bölgesi", ["Akdeniz Bölgesi", "İç Anadolu", "Güneydoğu Anadolu", "Ege Bölgesi"], "Bol yağış ve killi toprak nedeniyle heyelan set gölleri Karadeniz'dedir."),
    ("Dalgaların getirdiği kumulların koy veya körfezlerin önünü kapatmasıyla oluşan kıyı set göllerine (lagün / denizkulağı) örnek hangisidir?", "Terkos (Durusu), Büyükçekmece ve Küçükçekmece", ["Beyşehir ve Eğirdir", "Van ve Erçek", "Sapanca ve İznik", "Manyas ve Uluabat"], "İstanbul kıyılarındaki klasik lagün gölleridir."),
    ("Dağların denize paralel uzandığı Karadeniz ve Akdeniz kıyılarında görülen, falezlerin (yalıyar) yaygın olduğu kıyı tipi hangisidir?", "Boyuna kıyı tipi", ["Enine kıyı tipi", "Dalmaçya kıyı tipi", "Ría kıyı tipi", "Limanlı kıyı tipi"], "Kıyı ile iç kesim arasında ulaşım geçitlerle sağlanır."),
    ("Dağların denize dik uzandığı Ege kıyılarında görülen, girinti-çıkıntı, koy, körfez ve doğal liman sayısının en fazla olduğu kıyı tipi hangisidir?", "Enine kıyı tipi", ["Boyuna kıyı tipi", "Dalmaçya kıyı tipi", "Kalanklı kıyı tipi", "Haliç kıyı tipi"], "Kıta sahanlığı geniş, falezler azdır."),
    ("Antalya Kaş ile Finike arasında kıyıya paralel adacıkların yer aldığı ve Hırvatistan kıyılarına benzeyen kıyı tipi hangisidir?", "Dalmaçya kıyı tipi", ["Ría kıyı tipi", "Boyuna kıyı tipi", "Enine kıyı tipi", "Limanlı kıyı tipi"], "Sular altında kalan dağ zirveleri adacıklara dönüşmüştür.")
]

# Q94: İklim - Basınç ve Rüzgârlar
q94_list = [
    ("Türkiye'yi kış aylarında etkileyen, Doğu Anadolu ve Sibirya üzerinden gelen, havanın aşırı soğuk ve ayaz olmasına yol açan TERMEK yüksek basınç merkezi hangisidir?", "Sibirya Termik Yüksek Basıncı", ["İzlanda Dinamik Alçak Basıncı", "Asor Dinamik Yüksek Basıncı", "Basra Termik Alçak Basıncı", "Muson Alçak Basıncı"], "Kış mevsiminde karasallıkla kutupsal ayaz getirir."),
    ("Türkiye'yi yaz aylarında Güneydoğu'dan etkileyen, çöl sıcaklarını getiren ve buharlaşmayı şiddetlendiren termik alçak basınç merkezi hangisidir?", "Basra Termik Alçak Basıncı", ["Asor Yüksek Basıncı", "Sibirya Yüksek Basıncı", "İzlanda Alçak Basıncı", "Akdeniz Basıncı"], "Basra Körfezi üzerinden aşırı sıcak ve kuru hava taşır."),
    ("Kuzeybatıdan esen, Balkanlar üzerinden gelen soğuk, fırtınalı yerel rüzgâr hangisidir (KAYIP SAKAL şifresine göre)?", "Karayel", ["Yıldız", "Poyraz", "Samyeli", "Lodos"], "Kuzeybatıdan eserek kışın kar yağışı getirir."),
    ("Güneybatıdan esen, kış aylarında havanın ılıklaşmasına, karların aniden eriyerek su baskınlarına ve soba zehirlenmelerine neden olan rüzgâr hangisidir?", "Lodos", ["Poyraz", "Karayel", "Kıble", "Keşişleme"], "Göz yaşartan, deniz ulaşımını aksatan ılık güneybatı rüzgârıdır."),
    ("Güneydoğudan esen, sıcak ve kuru hava getirerek tarım ürünlerini kurutan ve 'Keşişleme' adıyla da bilinen yerel rüzgâr hangisidir?", "Samyeli (Keşişleme)", ["Lodos", "Kıble", "Poyraz", "Karayel"], "Suriye çöllerinden kuru ve sıcak hava taşır."),
    ("Bir dağ yamacını aşarak diğer yamaçtan aşağıya doğru inerken sürtünmeyle her 100 metrede sıcaklığı 1°C artıran, havayı kurutan rüzgâra ne ad verilir?", "Föhn rüzgârı (Bakır sattıran)", ["Meltem rüzgârı", "Poyraz", "Karayel", "Lodos"], "Rize'de turunçgil ve Iğdır'da pamuk yetişmesine olanak sağlayan mikroklima rüzgârıdır."),
    ("Ege Denizi'nde yaz aylarında gündüzleri denizden karaya doğru esen serinletici yerel rüzgâra denizciler ne ad verir?", "İmbat (Deniz meltemi)", ["Etezien", "Lodos", "Sirokko", "Hamsin"], "Günlük sıcaklık ve basınç farkıyla oluşan meltem rüzgârıdır."),
    ("Türkiye'de dağların kıyıya paralel uzandığı yerlerde (Karadeniz ve Akdeniz) nemli havanın iç kesimlere sokulamamasının doğal sonucu nedir?", "Kıyı ile iç kesimler arasında büyük sıcaklık ve iklim farkı oluşması", ["Akarsuların debisinin artması", "Kıta sahanlığının genişlemesi", "Güneşlenme süresinin her yerde eşit olması", "Gölge boylarının kısalması"], "İç kesimler deniz etkisinden yoksun kalarak karasallaşır."),
    ("Türkiye'de yıllık sıcaklık farkının EN AZ olduğu (nem oranı en yüksek) ve yıllık sıcaklık farkının EN FAZLA olduğu bölgeler sırasıyla hangileridir?", "Karadeniz (En az) - Doğu Anadolu (En fazla)", ["Akdeniz - Ege", "Marmara - İç Anadolu", "Güneydoğu - Ege", "Akdeniz - Karadeniz"], "Nemlilik sıcaklık farkını azaltır (Karadeniz); şiddetli karasallık farkı artırır (Erzurum-Kars)."),
    ("Akdeniz kıyılarında deniz suyu sıcaklığının ve tuzluluk oranının Karadeniz kıyılarından daha yüksek olmasının TEMEL sebebi nedir?", "Enlem etkisi (Ekvator'a daha yakın olması ve Güneş ışınlarını daha büyük açıyla alması)", ["Boylam farkı", "Akarsu sayısının azlığı", "Rüzgârların yönü", "Deniz derinliği"], "Enlem derecesi küçüldükçe sıcaklık ve buharlaşma artar, tuzluluk yükselir.")
]

# Q95: İklim Tipleri ve Yağış
q95_list = [
    ("Nemli hava kütlelerinin dağ yamaçlarına çarparak yükselmesiyle oluşan 'Orografik (Yamaç) Yağışları' Türkiye'de en çok hangi kıyıda görülür?", "Doğu ve Batı Karadeniz Kıyıları (Rize, Trabzon, Zonguldak)", ["Ege Kıyıları", "İç Anadolu", "Güneydoğu Anadolu", "Marmara Ergene"], "Denize paralel uzanan yüksek dağ yamaçları bol yamaç yağışı alır."),
    ("Isınan havanın dikey olarak yükselip soğumasıyla oluşan 'Konveksiyonel (Yükselim) Yağışları' ve ilkbaharda görülen 'Kırkikindi Yağışları' en çok nerede etkilidir?", "İç Anadolu ve Erzurum-Kars Platosu", ["Rize kıyıları", "Antalya kıyıları", "Mersin kıyıları", "Çanakkale"], "İlkbaharda İç Anadolu'da, yaz aylarında Erzurum-Kars'ta konveksiyonel yağış görülür."),
    ("Farklı sıcaklıktaki iki hava kütlesinin (sıcak ve soğuk) karşılaşma alanlarında oluşan 'Cephesel (Frontal) Yağışlar' kışın en çok hangi iklim bölgesinde görülür?", "Akdeniz İklim Bölgesi (Akdeniz, Ege ve Güney Marmara)", ["Doğu Anadolu", "Güneydoğu Anadolu", "Karadeniz Bölgesi", "İç Anadolu"], "Türkiye'nin Orta Kuşak'ta bulunmasının doğrudan kanıtı cephe yağışlarıdır."),
    ("Yıllık 2.400 mm'yi aşan yağış miktarıyla Türkiye'nin EN ÇOK yağış alan ili hangisidir?", "Rize", ["Giresun", "Muğla", "Antalya", "Zonguldak"], "Kaçkar Dağları'nın dik yamaçları olağanüstü nem tutar."),
    ("Etrafı yüksek dağlarla çevrili çukur bir ova olması sebebiyle yıllık 300 mm'nin altında yağış alarak Türkiye'nin EN AZ yağış alan yöresi neresidir?", "Tuz Gölü Çevresi ve Iğdır Ovası", ["Şanlıurfa", "Konya", "Kars", "Edirne"], "Çevre dağların rüzgârları engellemesiyle yağış gölgesinde kalır."),
    ("Her mevsim yağışlı, yıllık sıcaklık farkı az, doğal bitki örtüsü geniş yapraklı ve iğne yapraklı orman olan iklim türü hangisidir?", "Karadeniz İklimi", ["Akdeniz İklimi", "Karasal İklim", "Step İklimi", "Sert Karasal İklim"], "Türkiye'nin en ılıman ve nemli iklimidir."),
    ("Yazları sıcak ve kurak, kışları ılık ve yağışlı geçen; doğal bitki örtüsü zeytin, defne, mersin, zakkum gibi bodur ağaççıklardan oluşan 'Maki' olan iklim hangisidir?", "Akdeniz İklimi", ["Karasal İklim", "Karadeniz İklimi", "Tundra İklimi", "Step İklimi"], "Akdeniz ikliminin karakteristik bitki örtüsü makidir (tahrip edilince garig oluşur)."),
    ("Yazları sıcak ve kurak, kışları soğuk ve kar yağışlı; ilkbaharda yeşerip yazın kuruyan 'Bozkır (Step)' bitki örtüsüne sahip iklim türü hangisidir?", "İç Anadolu Karasal (Step) İklimi", ["Sert Karasal İklim", "Akdeniz İklimi", "Karadeniz İklimi", "Muson İklimi"], "Türkiye'de etki alanı en geniş olan iklim tipidir."),
    ("Yazları serin ve yağışlı, kışları çok sert, uzun ve donlu geçen; doğal bitki örtüsü 'Alpin Çayırlar' olan iklim bölgesi neresidir?", "Erzurum-Kars ve Ardahan Bölgesi (Sert Karasal)", ["Konya Bölümü", "Güneydoğu Anadolu", "Yıldız Dağları", "Menteşe Yöresi"], "Yaz yağışları sayesinde uzun boylu çayırlar gelişir."),
    ("Karadeniz ormanlarının tahrip edilmesiyle kıyıda oluşan yalancı maki formasyonuna ne ad verilir?", "Psödomaki", ["Garig", "Antropojen bozkır", "Tayga", "Tundra"], "Kızılcık, böğürtlen gibi nemli çalı topluluklarıdır.")
]

# Q96: Toprak Tipleri
q96_list = [
    ("Akdeniz iklim bölgesinde kalker (kireçtaşı) kayaçlar üzerinde oluşan, bileşimindeki demir oksit nedeniyle kırmızı renkli olan toprak tipi hangisidir?", "Terra Rossa (Kırmızı Akdeniz Toprağı)", ["Çernezyom", "Kahverengi Orman", "Podzol", "Laterit"], "Kalker üzerinde gelişen kireçli ama demirli topraklardır."),
    ("Erzurum-Kars platosundaki çayır bitki örtüsü altında oluşan, organik madde (humus) bakımından son derece zengin 'Kara Toprak' olarak bilinen zonal toprak hangisidir?", "Çernezyom Toprakları", ["Terra Rossa", "Bozkır Toprağı", "Alüvyal Toprak", "Regosol"], "Dünyanın en verimli yerli zonal toprağı kabul edilir."),
    ("Karadeniz'in gür ormanları altında kimyasal çözünmenin etkisiyle oluşan, humusça zengin ve yıkanmış toprak türü hangisidir?", "Kahverengi Orman Toprağı", ["Podzol", "Tundra", "Terra Rossa", "Kestane Renkli Bozkır"], "Geniş yapraklı orman altındaki nemli topraklardır."),
    ("Batı Karadeniz'in (Bolu, Kastamonu) yüksek ve soğuk iğne yapraklı ormanları altında aşırı yıkanmayla oluşan kül rengi soğuk toprak hangisidir?", "Podzol Toprak", ["Çernezyom", "Terra Rossa", "Alüvyal", "Rendzina"], "Aşırı yıkanmış asidik orman toprağıdır."),
    ("İç Anadolu ve Doğu Anadolu'daki bozkır alanlarında yıllık yağış azlığı nedeniyle kireç ve tuzun toprak yüzeyinde biriktiği toprak türü hangisidir?", "Kahverengi ve Kestane Renkli Bozkır (Step) Toprakları", ["Terra Rossa", "Kahverengi Orman", "Alüvyal", "Podzol"], "Tahıl tarımına uygun ancak sulama isteyen topraklardır."),
    ("Akarsuların taşıdığı mineralleri deltalar ve vadi tabanlarında biriktirmesiyle oluşan, horizonsuz (katmansız) ve tarımsal verimi en yüksek AZONAL toprak hangisidir?", "Alüvyal Topraklar", ["Lös Topraklar", "Moren Topraklar", "Regosol Topraklar", "Kolüvyal Topraklar"], "Çukurova, Bafra, Gediz gibi alanlardaki zengin topraklardır."),
    ("Volkanik arazilerde (kumlu ve tüflü depolar üzerinde) oluşan, patates ve bağcılık tarımına son derece elverişli azonal toprak hangisidir?", "Regosol Topraklar (Nevşehir-Niğde yöresi)", ["Moren", "Lös", "Alüvyal", "Kolüvyal"], "Kapadokya ve volkanik eteklerdeki gözenekli topraklardır."),
    ("Eski göl tabanlarındaki killi depolar üzerinde oluşan, kurak dönemde yarılan ve içine dökülen taşları kışın yüzeye fırlattığı için 'Taş Doğan' veya 'Dönen Toprak' denen toprak hangisidir?", "Vertisol Topraklar (Muş, Ergene ve Konya Havzası)", ["Rendzina", "Halomorfik", "Hidromorfik", "Terra Rossa"], "Ayçiçeği tarımının yoğun yapıldığı killi intrazonal topraktır."),
    ("Yumuşak kireçtaşları üzerinde oluşan ve alt katında kireç birikimi bulunan intrazonal toprak hangisidir?", "Rendzina Toprakları", ["Vertisol", "Halomorfik", "Çernezyom", "Podzol"], "Marmara ve Ege'de yaygındır."),
    ("Kurak ve yarı kurak bölgelerde taban suyunun buharlaşmasıyla tuz ve karbonatın toprak yüzeyinde kabuklaşması sonucu oluşan tuzlu topraklara ne ad verilir?", "Halomorfik Topraklar (Tuz Gölü çevresi)", ["Hidromorfik Topraklar", "Kalsimorfik Topraklar", "Alüvyal Topraklar", "Vertisoller"], "Tuzcul bitkilerin yetiştiği tarıma elverişsiz topraklardır.")
]
