# cografya_data_2.py - Q97 to Q105 (90 questions)

# Q97: Doğal Afetler
q97_list = [
    ("Türkiye'de can ve mal kaybına en çok neden olan, Saros Körfezi'nden başlayıp Marmara Denizi, Düzce, Bolu, Tokat, Erzincan üzerinden Van'a kadar uzanan en aktif fay kuşağı hangisidir?", "Kuzey Anadolu Fay Hattı (KAF)", ["Doğu Anadolu Fay Hattı (DAF)", "Batı Anadolu Fay Hattı (BAF)", "Tuz Gölü Fayı", "Ecemiş Fayı"], "Türkiye'nin en uzun ve en yıkıcı deprem kuşağıdır."),
    ("Eğim, aşırı yağış, killi toprak ve tabakaların eğim yönünde uzanması sebebiyle Türkiye'de heyelan olaylarının EN ÇOK görüldüğü coğrafi bölge hangisidir?", "Doğu Karadeniz Bölümü (Trabzon, Rize, Artvin)", ["İç Anadolu", "Güneydoğu Anadolu", "Ege Bölgesi", "Marmara Ergene"], "İlkbaharda karların erimesi ve yağışlar heyelanları tetikler."),
    ("Bitki örtüsünün tahrip edildiği, kurak ve yarı kurak İç ve Güneydoğu Anadolu bölgelerinde toprağın üst katmanının rüzgâr ve yüzey sularıyla süpürülmesine ne ad verilir?", "Erozyon", ["Heyelan", "Kaya düşmesi", "Çığ", "Deprem"], "Sessiz afet olarak bilinen ve tarım arazilerini çölleştiren afettir."),
    ("Eğimli arazilerde biriken kar kütlelerinin yamaçtan aşağı kaymasıyla oluşan 'Çığ' felaketleri Türkiye'de en çok hangi bölgemizde görülür?", "Doğu Anadolu Bölgesi (Hakkari, Bitlis, Van, Tunceli)", ["Ege Bölgesi", "Marmara Bölgesi", "Güneydoğu Anadolu", "Akdeniz Kıyıları"], "Yüksek engebeli araziler ve yoğun kar yağışı çığ riskini artırır."),
    ("Yaz kuraklığı ve yüksek sıcaklıklar nedeniyle Türkiye'de orman yangını riskinin EN YÜKSEK olduğu kıyı kuşağı hangisidir?", "Akdeniz ve Ege Kıyı Kuşağı", ["Doğu Karadeniz", "Batı Karadeniz", "İç Anadolu", "Doğu Anadolu"], "Kızılçam ormanları ve yaz kuraklığı yangın hassasiyetini zirveye çıkarır."),
    ("Türkiye'de deprem riskinin EN DÜŞÜK olduğu masif veya oturmuş arazilerden biri aşağıdakilerden hangisidir?", "Mardin Eşiği ve Konya-Karaman Çevresi", ["Hatay Çukuru", "Bursa ve Kocaeli", "İzmir ve Manisa", "Erzincan ve Muş"], "Mardin masifi ve Konya kapalı havzası deprem tehlikesi en az olan yerlerdendir."),
    ("Akarsu yataklarının yerleşime açılması ve yetersiz menfezler nedeniyle ani ve yıkıcı sel/taşkınların en sık yaşandığı bölge hangisidir?", "Karadeniz Kıyı Kuşağı (Giresun, Kastamonu Bozkurt, Sinop)", ["Güneydoğu Anadolu", "İç Anadolu", "Ege Grabenleri", "Doğu Anadolu"], "Dar vadi tabanlarına kurulan yerleşimler sel felaketine maruz kalır."),
    ("Erozyonla mücadele etmek ve toprağı korumak için alınması gereken EN ETKİLİ tedbir aşağıdakilerden hangisidir?", "Ağaçlandırma yapmak ve bitki örtüsünü korumak", ["Tarlaları eğim doğrultusunda dik sürmek", "Nadas alanlarını genişletmek", "Meralarda aşırı otlatma yapmak", "Ormanları tarım arazisine dönüştürmek"], "Bitki örtüsü kökleriyle toprağı tutar ve süpürülmeyi engeller."),
    ("Eğimli yamaçlarda erozyonu azaltmak için tarlaların eğime dik sürülmesi ve basamaklar yapılması yöntemine ne ad verilir?", "Taraçalama (Sekileme)", ["Nadas", "Nöbetleşe ekim", "Anız yakma", "Derin sürme"], "Basamaklar suyun akış hızını keserek toprağın taşınmasını önler."),
    ("Karstik arazilerde yeraltı mağara tavanlarının çökmesi sonucu aniden oluşan devasa çukurlara ne ad verilir?", "Obruk (Konya Ovası obrukları)", ["Kanyon", "Düden", "Polye", "Uvala"], "Aşırı yeraltı suyu çekimi obruk oluşumunu hızlandırmaktadır.")
]

# Q98: Nüfusun Dağılışı ve Yapısı
q98_list = [
    ("Türkiye'de sanayi, ticaret, ulaşım ve finans sektörlerinin yoğunlaşması nedeniyle nüfus yoğunluğunun EN FAZLA olduğu bölge hangisidir?", "Marmara Bölgesi (Çatalca-Kocaeli Bölümü)", ["Doğu Anadolu", "Karadeniz", "İç Anadolu", "Güneydoğu Anadolu"], "İstanbul ve Kocaeli sanayi ve göç merkezi olduğu için nüfus yoğunluğu çok yüksektir."),
    ("Akdeniz Bölgesi'nde yer almasına rağmen karstik yapısı, engebeli yerşekilleri ve toprak yetersizliği nedeniyle nüfusu ÇOK SEYREK olan yöre hangisidir?", "Teke ve Taşeli Platosu", ["Çukurova", "Antalya Ovası", "İskenderun", "Tarsus"], "Kalkerli zemin suyu tutamadığı için yerleşim seyrektir."),
    ("Ege Bölgesi'nde yer almasına rağmen dağların denize paralel uzandığı, ana ulaşım yollarına sapa kaldığı için nüfusu seyrek olan alan neresidir?", "Menteşe Yöresi (Muğla)", ["Gediz Havzası", "Bakırçay Havzası", "İzmir Körfezi", "Büyük Menderes"], "Engebeli yerşekilleri ve çıkmaz sokak konumu nüfusu sınırlandırmıştır."),
    ("Marmara Bölgesi'nde yer almasına rağmen dağlık yerşekilleri ve ulaşım yollarından uzak kalması sebebiyle seyrek nüfuslu olan yöre hangisidir?", "Yıldız Dağları (Istranca) Bölümü", ["Çatalca", "Kocaeli", "Bursa Çevresi", "Güney Marmara"], "Trakya'nın Karadeniz kıyısındaki dağlık kesimidir."),
    ("Türkiye'de kuraklık ve su yetersizliği nedeniyle nüfusun seyrek olduğu İç Anadolu yöresi neresidir?", "Tuz Gölü Çevresi", ["Ankara Çevresi", "Eskişehir", "Kayseri", "Konya Merkez"], "Yıllık yağışın en az olduğu kurak tuzcul sahadır."),
    ("Doğu Anadolu'da yükselti, engebe ve kış mevsiminin çok sert geçmesi nedeniyle nüfus yoğunluğu en az olan bölüm hangisidir?", "Hakkari Bölümü", ["Yukarı Fırat", "Malatya Ovası", "Elazığ Çevresi", "Erzincan Ovası"], "Sarp dağlık arazi ve sert iklim yerleşmeyi engeller."),
    ("Bir ülkede doğum oranlarının azalması, ortanca yaşın yükselmesi ve yaşlı nüfus oranının artması o ülkenin hangi özelliğini gösterir?", "Gelişmişlik seviyesinin arttığını ve demografik dönüşüm yaşadığını", ["Geri kalmış bir ülke olduğunu", "Nüfusunun hızla tükendiğini", "Tarımsal üretimin bittiğini", "İç göçlerin durduğunu"], "Doğum oranlarının düşmesi modern sanayi toplumlarının temel özelliğidir."),
    ("Türkiye'de çalışan nüfusun sektörel dağılımında EN BÜYÜK paya sahip olan sektör hangisidir?", "Hizmet sektörü (%55'in üzeri)", ["Tarım sektörü", "Sanayi sektörü", "Madencilik", "İnşaat"], "Gelişmiş ülkelerde olduğu gibi çalışanların yarıdan fazlası hizmet sektöründedir."),
    ("Türkiye'de kadın ve erkek nüfus oranları genel olarak dengeli olmakla birlikte, sürekli DIŞ GÖÇ VEREN illerimizde hangi nüfus oranı belirgin şekilde daha yüksektir?", "Kadın nüfus oranı", ["Erkek nüfus oranı", "Çocuk nüfus oranı", "Genç nüfus oranı", "Sanayi işçisi"], "Erkek nüfus çalışmak amacıyla büyük şehirlere göç ettiğinden kırsalda kadın oranı artar."),
    ("Türkiye'de 'aktif (çalışma çağındaki) nüfus' hangi yaş grubunu ifade eder?", "15 - 64 yaş grubu", ["0 - 14 yaş grubu", "65 yaş ve üzeri", "18 - 25 yaş grubu", "20 - 45 yaş grubu"], "Uluslararası standartlarda 15-64 yaş arası çalışma çağındaki nüfustur.")
]

# Q99: Göçler ve Yerleşme Tipleri
q99_list = [
    ("Türkiye'de kırsal kesimde su kaynaklarının bol, arazinin çok engebeli olduğu Doğu Karadeniz'de görülen yerleşme dokusu hangisidir?", "Dağınık kır yerleşmesi", ["Toplu kır yerleşmesi", "Çizgisel yerleşme", "Dairesel yerleşme", "Işınsal yerleşme"], "Evler yamaçlara serpilmiş olup tarla başlarına kurulmuştur."),
    ("Su kaynaklarının kısıtlı, yerşekillerinin düz ve sade olduğu İç ve Güneydoğu Anadolu'da görülen yerleşme tipi hangisidir?", "Toplu kır yerleşmesi", ["Dağınık yerleşme", "Merkezi yerleşme", "Teras yerleşmesi", "Kıyı yerleşmesi"], "Evler kuyu ve çeşme başlarında birbirine bitişik toplanmıştır."),
    ("Karadeniz Bölgesi'nde kırsal meskenlerde geleneksel yapı malzemesi olarak en çok ne kullanılmıştır?", "Ahşap (Orman ve ağaç malzemesi)", ["Kerpiç", "Kalker taşı", "Tuğla", "Volkanik taş"], "Gür orman varlığı ahşap mimariyi hâkim kılmıştır."),
    ("İç Anadolu ve Güneydoğu Anadolu'da kurak iklim nedeniyle killi toprağın samanla karıştırılıp güneşte kurutulmasıyla yapılan mesken malzemesi nedir?", "Kerpiç", ["Ahşap", "Kalker", "Granit", "Betonarme"], "Yazın serin, kışın ılık tutan geleneksel kerpiç evlerdir."),
    ("Akdeniz Bölgesi'nde ve Kapadokya yöresinde kırsal evlerin yapımında yaygın olarak kullanılan doğal malzeme hangisidir?", "Taş malzeme (Kalker ve volkanik tüf)", ["Ahşap", "Kerpiç", "Bambu", "Sazlık"], "Yöredeki kalker ve volkanik tüf taş ustalığını geliştirmiştir."),
    ("Köy altı yerleşmelerinden idari olarak köye bağlı, SÜREKLİ (devamlı) nitelik taşıyan yerleşmelere örnek hangisidir?", "Mahalle, Mezra, Divan, Çiftlik", ["Yayla, Kom, Ağıl", "Oba, Dam, Dalyan", "Yayla, Ağıl, Oba", "Kom, Dam, Dalyan"], "Bu yerleşmelerde yıl boyunca kalınır ve tarım yapılır."),
    ("Batı Karadeniz'de birkaç mahallenin birleşmesiyle oluşan, sürekli köy altı yerleşmesi türü hangisidir?", "Divan", ["Mezra", "Kom", "Oba", "Ağıl"], "Bolu, Kastamonu, Sinop ve Samsun yöresine özgü sürekli yerleşmedir."),
    ("Doğu Anadolu'da genellikle hayvancılık amacıyla kurulan, taş veya kerpiçten yapılmış geçici köy altı yerleşmesi hangisidir?", "Kom", ["Divan", "Çiftlik", "Mahalle", "Dalyan"], "Erzurum, Kars, Ağrı yöresinde yaygın geçici hayvancılık barınağıdır."),
    ("Toroslar'da göçebe Yörüklerin kıl çadırlarda hayvancılık yaptığı geçici köy altı yerleşmesine ne ad verilir?", "Oba", ["Divan", "Mezra", "Çiftlik", "Mahalle"], "Akdeniz kuşağında konargöçer hayvancılık yerleşmesidir."),
    ("Muğla ve Akdeniz kıyılarında balık üretimi ve avcılığı amacıyla kurulan geçici kıyı yerleşmesine ne ad verilir?", "Dalyan", ["Dam", "Ağıl", "Kom", "Divan"], "Köyceğiz ve Dalyan lagünlerinde yaygındır.")
]

# Q100: Tarım Ürünleri
q100_list = [
    ("Yetişme döneminde (ilkbahar) yağış, olgunlaşma döneminde (yaz) sıcaklık ve kuraklık isteyen, Türkiye'de ekim alanı ve üretimi en fazla olan tahıl hangisidir?", "Buğday", ["Çavdar", "Pirinç", "Mısır", "Yulaf"], "Her mevsim yağış alan Karadeniz kıyılarında yetişemez; İç Anadolu liderdir."),
    ("Soğuğa ve kuraklığa buğdaydan daha dayanıklı olan, malt sanayisinde (bira) ve yem sanayisinde kullanılan tahıl hangisidir?", "Arpa", ["Pirinç", "Mısır", "Pamuk", "Tütün"], "İç ve Doğu Anadolu'da geniş alanlarda üretilir."),
    ("Sulama imkânlarının artmasıyla (GAP ve Çukurova) üretimi hızla artan, nem ve su isteği yüksek olan, Karadeniz'de doğal olarak yetişen tahıl hangisidir?", "Mısır", ["Arpa", "Buğday", "Çavdar", "Yulaf"], "Akdeniz ve Güneydoğu'da sulamayla birinci veya ikinci ürün olarak ekilir."),
    ("Akarsu vadi tabanlarında bol su içinde (tava) yetiştirilen, sıtma sivrisineği üremesine neden olduğu için üretimi devlet kontrolünde olan tahıl hangisidir?", "Pirinç (Çeltik)", ["Mısır", "Haşhaş", "Tütün", "Kenevir"], "Edirne Meriç vadisi, Samsun Bafra ve Çarşamba başlıca üretim alanıdır."),
    ("Yetişme döneminde su, hasat döneminde mutlak kuraklık ve yüksek sıcaklık isteyen, GAP ile birlikte Şanlıurfa'nın Türkiye birincisi olduğu lif ve yağ bitkisi hangisidir?", "Pamuk", ["Tütün", "Şeker Pancarı", "Çay", "Fındık"], "Güneydoğu Anadolu pamuk üretiminde Ege ve Çukurova'yı geçerek birinci olmuştur."),
    ("Doğu Karadeniz'in bol yağışlı, asitli topraklarında yetişen, Türkiye'de cumhuriyet döneminde Zihni Derin öncülüğünde üretimine başlanan sanayi bitkisi hangisidir?", "Çay (Rize, Trabzon, Artvin)", ["Tütün", "Kahve", "Pamuk", "Zeytin"], "Mikroklima ve yıkanmış kireçsiz toprak ister."),
    ("Uyuşturucu madde elde edilebildiği için ekimi ve ticareti Toprak Mahsulleri Ofisi (TMO) ve devletin sıkı kontrolünde olan, Afyonkarahisar ve çevresinde üretilen sanayi bitkisi hangisidir?", "Haşhaş", ["Şeker Pancarı", "Tütün", "Ayçiçeği", "Pamuk"], "Tıbbi morfin ve tohumluk yağ sanayisinde kullanılır."),
    ("Çabuk bozulduğu için fabrikaları daima ekim alanlarının hemen yakınına kurulan, küspesi hayvan yemi olarak değerlendirilen sanayi bitkisi hangisidir?", "Şeker Pancarı", ["Pamuk", "Tütün", "Kenevir", "Çay"], "İç Anadolu başta olmak üzere karasal bölgelerde sulamayla yetiştirilir; kıyılarda ekonomik değeri yüksek ürünler tercih edilir."),
    ("Türkiye'de üretimi devlet kontrolünde olan (kaliteyi korumak amacıyla) ve Ege, Karadeniz (Samsun) ile Güneydoğu'da yetiştirilen sanayi bitkisi hangisidir?", "Tütün", ["Şeker Pancarı", "Mısır", "Pamuk", "Buğday"], "Kalitesiz tütün üretimini önlemek için kotalı devlet kontrolü uygulanır."),
    ("Trakya (Ergene Havzası) başta olmak üzere Türkiye'de sıvı yağ sanayisinin en temel hammaddesi olan ve üretiminde Tekirdağ, Edirne ve Konya'nın önde olduğu yağ bitkisi hangisidir?", "Ayçiçeği", ["Zeytin", "Soya Fasulyesi", "Kolza", "Susam"], "Ergene Havzası ayçiçeği üretiminin kalbidir.")
]

# Q101: Meyvecilik ve Hayvancılık
q101_list = [
    ("Kış ılıklığı isteyen, tipik Akdeniz iklimi bitkisi olan ve sofralık zeytinde Güney Marmara'nın (Gemlik), yağlık zeytinde ise Ege'nin (Aydın, İzmir, Balıkesir) lider olduğu meyve hangisidir?", "Zeytin", ["Fındık", "İncir", "Turunçgiller", "Elma"], "Akdeniz ikliminin maki formasyonundaki ana ağacıdır."),
    ("Dünya üretim ve ihracatında Türkiye'nin açık ara birinci sırada olduğu, don olaylarına hassas, nemli Karadeniz iklimini seven meyve hangisidir?", "Fındık (Ordu, Giresun, Trabzon, Düzce)", ["Kayısı", "İncir", "Üzüm", "Ceviz"], "Dünya fındık ihtiyacının %70'e yakınını Türkiye karşılar."),
    ("Karasal iklime ve soğuğa en dayanıklı olan, Türkiye'nin hemen her bölgesinde yetişebilen ve üretiminde Isparta, Karaman ve Niğde'nin başı çektiği meyve hangisidir?", "Elma", ["Muz", "Turunçgil", "Zeytin", "İncir"], "Geniş yetişme alanına sahip, ihracatta önemli bir meyvedir."),
    ("Kurutularak ihraç edilen ve üretiminde Türkiye'nin dünya birincisi olduğu, Akdeniz iklimine özgü Ege Bölgesi (Aydın) meyvesi hangisidir?", "İncir", ["Fındık", "Elma", "Portakal", "Muz"], "Soğuğa duyarlı olup Aydın Büyük Menderes havzasında yoğunlaşmıştır."),
    ("Dünya kuru kayısı üretim ve ihracatının başkenti kabul edilen ve coğrafi işaret tescili bulunan Doğu Anadolu ilimiz hangisidir?", "Malatya", ["Elazığ", "Erzincan", "Kars", "Van"], "Malatya kayısısı dünya çapında bir markadır."),
    ("Bozkır (step) alanlarında yetiştirilen, Türkiye'de sayısı en fazla olan küçükbaş hayvan türü hangisidir?", "Koyun", ["Kıl Keçisi", "Tiftik Keçisi", "Manda", "Sığır"], "İç Anadolu, Doğu Anadolu ve Güneydoğu'da yaygındır."),
    ("Akdeniz'in engebeli kalkerli dağlarında (Toroslar) orman sürgünleri ve makilerle beslenen, tırmanma yeteneği yüksek küçükbaş hayvan hangisidir?", "Kıl Keçisi (Teke ve Taşeli)", ["Merinos Koyunu", "Tiftik Keçisi", "Karaman Koyunu", "Dağlıç"], "Ormanlara zarar verdiği gerekçesiyle otlatılması kontrol altındadır."),
    ("Yünü (tiftik / mohair) için beslenen ve anavatanı İç Anadolu (özellikle Ankara ve çevresi) olan keçi türü hangisidir?", "Tiftik Keçisi (Ankara Keçisi)", ["Kıl Keçisi", "Kıvırcık Koyun", "Dağlıç", "Sakız Koyunu"], "Dünyaca ünlü tiftik yünü üretilir."),
    ("Yaz yağışlarıyla yeşeren gür çayırların bulunduğu Erzurum-Kars ve Karadeniz yaylalarında yoğun olarak yapılan hayvancılık türü hangisidir?", "Büyükbaş Mera Hayvancılığı (Sığır)", ["Küçükbaş Hayvancılık", "İpek Böcekçiliği", "Kıl Keçisi", "Kümes Hayvancılığı"], "Doğal çayırlara bağlı açık alan sığırcılığıdır."),
    ("Büyük tüketici kitlesine (pazara) yakınlık nedeniyle büyükşehirlerin (İstanbul, İzmir, Ankara, Bursa, Bolu) çevresinde modern tesislerde kurulan hayvancılık kolları hangileridir?", "Besi/Ahır Hayvancılığı ve Kümes Hayvancılığı", ["Mera Hayvancılığı", "Arıcılık", "Kıl Keçisi Yetiştiriciliği", "İpek Böcekçiliği"], "İklimden bağımsız, pazara yakınlık esastır.")
]

# Q102: Madenler
q102_list = [
    ("Dünya toplam rezervlerinin yaklaşık %73'üne Türkiye'nin sahip olduğu; roket yakıtı, cam, seramik ve deterjan sanayisinde kullanılan stratejik maden hangisidir?", "Bor Mineralleri (Balıkesir Bigadiç, Kütahya Emet, Eskişehir Kırka, Bursa)", ["Krom", "Bakır", "Boksit", "Demir"], "Eti Maden tarafından işletilen Türkiye'nin en değerli madenidir."),
    ("Ağır sanayinin hammaddesi olan ve en zengin yatakları Sivas Divriği ile Malatya Hekimhan-Hasançelebi'de bulunan maden hangisidir?", "Demir", ["Bakır", "Krom", "Kurşun", "Cıva"], "Karabük, Ereğli ve İskenderun demir-çelik fabrikalarında işlenir."),
    ("Paslanmaz çelik üretiminde kullanılan, sert ve parlak bir metal olan, Elazığ Guleman ve Muğla Fethiye-Köyceğiz'de çıkarılan maden hangisidir?", "Krom (Ferrokrom tesisleri: Elazığ ve Antalya)", ["Boksit", "Bor", "Demir", "Manganez"], "Türkiye dünya krom üretiminde önemli ihracatçılardandır."),
    ("Elektrik ve elektronik sanayisinin vazgeçilmez iletken metali olan; Artvin Murgul, Kastamonu Küre ve Elazığ Maden'de (Ergani) çıkarılan maden hangisidir?", "Bakır (Samsun ve Artvin'de işlenir)", ["Demir", "Çinko", "Krom", "Kurşun"], "Samsun'da hammaddeye değil, ulaşım ve limana bağlı izabe tesisi vardır."),
    ("Alüminyumun hammaddesi olan, hafifliği nedeniyle uçak ve otomotiv sanayisinde kullanılan, Konya Seydişehir'de çıkarılıp işlenen maden hangisidir?", "Boksit", ["Bor", "Krom", "Kükürt", "Barit"], "Seydişehir Alüminyum Tesisleri'nde işlenir."),
    ("Doğada sıvı halde bulunan tek metal maden olup termometre ve ilaç sanayisinde kullanılan, Konya Sarayönü ve İzmir Ödemiş'te çıkarılan maden hangisidir?", "Cıva", ["Kurşun", "Asbest", "Kükürt", "Mermer"], "Sağlığa zararları nedeniyle üretimi kısıtlanmıştır."),
    ("Gübre sanayisinin en temel hammaddesi olan ve Mardin Mazıdağı'nda çıkarılıp işlenen maden hangisidir?", "Fosfat", ["Kükürt", "Tuz", "Linyit", "Zımpara Taşı"], "Mazıdağı Fosfat Tesisleri entegre üretim yapar."),
    ("Türkiye'nin ihracatında ilk sırada yer alan yapı ve kaplama taşı olup Afyonkarahisar, Marmara Adası, Denizli ve Bilecik'te zengin yatakları bulunan maden hangisidir?", "Mermer (Kalker başkalaşımı)", ["Granit", "Bazalt", "Andezit", "Tüf"], "Dünya mermer pazarında Türkiye lider ülkelerdendir."),
    ("Petrol ve doğalgaz sondaj kuyularında yoğunluk artırıcı çamur olarak kullanılan, Antalya Alanya ve Gazipaşa'da çıkarılan maden hangisidir?", "Barit", ["Boksit", "Bor", "Krom", "Lületaşı"], "Yüksek yoğunluklu ve suda çözünmeyen bir madendir."),
    ("Eskişehir yöresine özgü olan, pipo, ağızlık ve süs eşyası yapımında kullanılan beyaz renkli gözenekli süs taşı hangisidir?", "Lületaşı", ["Oltu Taşı", "Kehribar", "Zümrüt", "Mermer"], "Erzurum Oltu Taşı ise siyah renkli tespih yapımında kullanılır.")
]

# Q103: Enerji Kaynakları
q103_list = [
    ("I. Jeolojik Zaman'da (Paleozoik) oluşmuş, kalori değeri çok yüksek olan ve Zonguldak havzasında çıkarılarak Çatalağzı termik santralinde ve demir-çelik fabrikalarında kullanılan enerji kaynağı hangisidir?", "Taş Kömürü", ["Linyit", "Petrol", "Doğalgaz", "Asfaltit"], "Demiri eritmek için yüksek ısı sağlayan kok kömürü elde edilir."),
    ("III. Jeolojik Zaman'da oluşmuş, Türkiye'de rezervi en yaygın olan kömür türü olup Manisa Soma, Muğla Yatağan, Kütahya Seyitömer ve Maraş Afşin-Elbistan santrallerinde elektrik üretiminde kullanılan yakıt hangisidir?", "Linyit", ["Taş Kömürü", "Antrasit", "Turba", "Petrol"], "Termik santrallerde elektrik üretiminde en çok kullanılan yerli kaynaktır."),
    ("Türkiye'de İLK petrol rezervinin 1940 yılında Raman Dağı'nda bulunduğu ve günümüzde en çok çıkarıldığı Güneydoğu Anadolu ilimiz hangisidir?", "Batman", ["Diyarbakır", "Siirt", "Mardin", "Şanlıurfa"], "Batman Rafinerisi ilk kurulan yerli rafineridir."),
    ("Trakya'da Kırklareli Hamitabat ve Tekirdağ Hayrabolu'da çıkarılan, ayrıca Karadeniz Sakarya Gaz Sahası'nda zengin rezervleri keşfedilen temiz fosil yakıt hangisidir?", "Doğalgaz", ["Petrol", "Linyit", "Kaya Gazı", "Taş Kömürü"], "Hamitabat ve Ovaakça'da doğalgaz çevrim santralleri bulunur."),
    ("Yerin derinliklerindeki sıcak su ve buhar gücünden elde edilen jeotermal enerji ile elektrik üreten İLK tesisimiz nerede kurulmuştur?", "Denizli Sarayköy (ve Aydın Germencik)", ["Balıkesir Gönen", "Afyon Sandıklı", "Ankara Kızılcahamam", "Yalova Armutlu"], "Ege graben sahaları jeotermal enerjinin merkezidir."),
    ("Güneşlenme süresi bakımından Türkiye'de potansiyelin EN YÜKSEK olduğu bölge ile EN DÜŞÜK olduğu bölge sırasıyla hangileridir?", "Güneydoğu Anadolu (En yüksek) - Karadeniz (En düşük)", ["Akdeniz - İç Anadolu", "Ege - Marmara", "İç Anadolu - Doğu Anadolu", "Akdeniz - Ege"], "Karadeniz'de bulutluluk fazla olduğu için güneş potansiyeli çok düşüktür."),
    ("Rüzgâr enerjisinden elektrik üreten İLK modern rüzgâr santrali (RES) hangi il ve ilçemizde kurulmuştur?", "İzmir Çeşme (Alaçatı)", ["Çanakkale Bozcaada", "Balıkesir Bandırma", "Manisa Soma", "Hatay Belen"], "Ege ve Marmara rüzgâr enerjisinde lider bölgelerdir."),
    ("Fırat Nehri üzerinde kurulu olan ve Türkiye'nin gövde hacmi ve elektrik üretim kapasitesi bakımından EN BÜYÜK hidroelektrik santrali (HES) hangisidir?", "Atatürk Barajı", ["Keban Barajı", "Karakaya Barajı", "Deriner Barajı", "Oymapınar Barajı"], "GAP projesinin amiral gemisi dev hidroelektrik santralidir."),
    ("Çoruh Nehri üzerinde inşa edilen ve 275 metre gövde yüksekliğiyle Türkiye'nin en yüksek barajlarından biri olan HES hangisidir?", "Yusufeli Barajı (Artvin)", ["Atatürk Barajı", "Keban Barajı", "Hirfanlı Barajı", "Altınkaya Barajı"], "Çoruh Havzası derin vadileriyle yüksek HES potansiyeline sahiptir."),
    ("Mersin Gülnar'da (Akkuyu) inşası devam eden Türkiye'nin İLK nükleer güç santrali projesi hangisidir?", "Akkuyu Nükleer Güç Santrali", ["Sinop Nükleer Santrali", "İğneada Santrali", "Soma Santrali", "Hamitabat Santrali"], "Baz yük elektrik ihtiyacını karşılamak amacıyla inşa edilmektedir.")
]

# Q104: Sanayi ve Ulaşım
q104_list = [
    ("Türkiye'nin İLK ağır demir-çelik fabrikası olan ve taş kömürü havzasına (enerji kaynağına) yakınlık nedeniyle kurulan tesis hangisidir?", "Karabük Demir-Çelik Fabrikası (KARDEMİR)", ["İskenderun Demir-Çelik (İSDEMİR)", "Ereğli Demir-Çelik (ERDEMİR)", "Sivas Demir-Çelik", "İzmir Demir-Çelik"], "1937'de temeli atılan ilk ağır sanayi tesisimizdir."),
    ("İskenderun Demir-Çelik Fabrikası'nın (İSDEMİR) Akdeniz kıyısına kurulmasında etkili olan TEMEL faktör nedir?", "Liman ve deniz ulaşımı kolaylığı (Ulaşım / Hinterlant)", ["Demir madenine yakınlık", "Taş kömürüne yakınlık", "Pazara yakınlık", "İklim şartları"], "İthal kömür ve maden sevkiyatı için liman avantajı seçilmiştir."),
    ("İzmir Aliağa'da yer alan TÜPRAŞ petrol rafinerisinin ve petrokimya tesisinin (PETKİM) kuruluş yerinin belirlenmesinde hangi faktör belirleyicidir?", "Liman ve deniz yolu ulaşımı", ["Petrol kuyularına yakınlık", "Tatlı su bolluğu", "İşgücü ucuzluğu", "Maden zenginliği"], "Deniz yoluyla gelen ham petrolü işlemek için kurulmuştur."),
    ("İç Anadolu'da yer alan Kırıkkale Orta Anadolu Rafinerisi'nin kuruluşunda hangi faktör temel rol oynamıştır?", "Güvenlik ve stratejik iç bölge konumu", ["Petrol madenine yakınlık", "Liman kolaylığı", "Kömür havzası olması", "İklimi"], "Savaş durumunda kıyı bombardımanından uzak iç bölge seçilmiştir."),
    ("Türkiye'de sanayileşmenin en gelişmiş olduğu Marmara Bölgesi'nde otomotiv, elektrikli ev aletleri ve tekstil üretiminin kalbi olan şehirler hangileridir?", "Kocaeli, Bursa, Sakarya, İstanbul", ["Edirne, Kırklareli", "Çanakkale, Balıkesir", "Yalova, Bilecik", "Tekirdağ, Düzce"], "Geniş pazar, sermaye, nitelikli işgücü ve ulaşım ağları sanayiyi toplamıştır."),
    ("Bir limanın demiryolu ve karayolu bağlantılarıyla gerisinde kalan iç kesimlerle kurduğu ekonomik etki alanına ne ad verilir?", "Liman Hinterlandı (Art bölgesi)", ["Serbest bölge", "Karasuyu", "Kıta sahanlığı", "Münhasır ekonomik bölge"], "Hinterlandı geniş olan limanlar hızla büyür ve ticaret hacmi artar."),
    ("Karadeniz Bölgesi'nde doğal liman olmasına rağmen ardında Canik gibi alçak dağlar bulunmayan, yüksek Küre Dağları yüzünden iç kesimle demiryolu bağlantısı kurulamayan ve hinterlandı dar kalan liman hangisidir?", "Sinop Limanı", ["Samsun Limanı", "Trabzon Limanı", "Zonguldak Limanı", "İnebolu Limanı"], "Doğal bir liman olmasına rağmen sanayi ve ticarette gelişememiştir."),
    ("Karadeniz Bölgesi'nde demiryolu bağlantısı bulunan ve hinterlandı EN GENİŞ olan ticaret limanı hangisidir?", "Samsun Limanı", ["Sinop Limanı", "Rize Limanı", "Giresun Limanı", "Hopa Limanı"], "Canik Dağları alçak olduğu için iç kesimlerle demiryolu bağı güçlüdür."),
    ("Türkiye'de demiryolu ağı BULUNMAYAN kıyı şehirlerimiz hangi seçenekte bir arada verilmiştir?", "Antalya, Muğla, Trabzon, Rize, Sinop, Çanakkale", ["İzmir, Mersin, İskenderun", "Samsun, Kocaeli, Balıkesir", "Tekirdağ, Zonguldak, Hatay", "Adana, Bursa, Sakarya"], "Bu şehirlerin dağlık yapısı veya ana hatlara uzaklığı nedeniyle demiryolu hattı yoktur."),
    ("Doğu Karadeniz'i Doğu Anadolu'ya ve İran transit ticaret yoluna bağlayan, dünyanın en uzun çift tüplü karayolu tünellerinden biri olan tünel hangisidir?", "Yeni Zigana Tüneli (Trabzon - Gümüşhane)", ["Ovit Tüneli", "Ilgaz Tüneli", "Cankurtaran Tüneli", "Bolu Tüneli"], "14,5 km uzunluğundaki stratejik transit tüneldir.")
]

# Q105: Bölgesel Kalkınma Projeleri ve Turizm
q105_list = [
    ("Fırat ve Dicle nehirlerinin sularını sulama ve hidroelektrik üretimine kazandırarak Güneydoğu Anadolu'yu kalkındırmayı amaçlayan Türkiye'nin EN KAPSAMLI bölgesel kalkınma projesi hangisidir?", "GAP (Güneydoğu Anadolu Projesi)", ["DAP", "DOKAP", "KOP", "ZBK"], "Şanlıurfa, Gaziantep, Diyarbakır, Mardin, Batman, Siirt, Adıyaman, Kilis ve Şırnak'ı kapsar."),
    ("Konya Kapalı Havzası'ndaki kuraklık ve yeraltı suyu yetersizliğini çözmek amacıyla Göksu Nehri'nin sularını Mavi Tünel ile ovaya aktaran proje hangisidir?", "KOP (Konya Ovası Projesi)", ["GAP", "DAP", "DOKAP", "YHGP"], "Konya, Karaman, Aksaray, Niğde, Kırıkkale, Kırşehir, Nevşehir ve Yozgat'ı kapsar."),
    ("Taş kömürü üretiminin modernize edilmesi, Filyos Vadisi liman ve sanayi projesi ile kardemir/erdemir entegrasyonunu hedefleyen bölgesel proje hangisidir?", "ZBK (Zonguldak - Bartın - Karabük Projesi)", ["DOKAP", "DAP", "GAP", "KOP"], "Batı Karadeniz ağır sanayi ve kömür kalkınma projesidir."),
    ("Doğu Karadeniz'de yayla turizmini (Yeşil Yol), kıyı-iç kesim ulaşımını ve balıkçılık/tarımı geliştirmeyi hedefleyen proje hangisidir?", "DOKAP (Doğu Karadeniz Projesi)", ["GAP", "ZBK", "KOP", "DAP"], "Samsun'dan Artvin'e kadar olan Karadeniz illerini ve Tokat/Amasya'yı kapsar."),
    ("Doğu Anadolu'da mera hayvancılığını, et ve süt kombinalarını modernleştirmeyi ve kış turizmini geliştirmeyi amaçlayan proje hangisidir?", "DAP (Doğu Anadolu Projesi)", ["GAP", "KOP", "DOKAP", "ZBK"], "En çok ili (16 il) kapsayan dev kalkınma projesidir."),
    ("Türkiye'de UNESCO Dünya Kültür Mirası Listesi'nde yer alan, hem doğal hem kültürel (KARMA) miras alanı olarak tescillenen iki eşsiz varlığımız hangileridir?", "Göreme Milli Parkı/Kapadokya ve Pamukkale/Hierapolis", ["Nemrut Dağı ve Truva", "Divriği Ulu Camii ve Safranbolu", "Efes ve Bergama", "Göbeklitepe ve Arslantepe"], "Dünyada nadir görülen hem doğal oluşum hem tarihi yerleşim alanlarıdır."),
    ("Şanlıurfa'da yer alan, günümüzden 12 bin yıl öncesine tarihlenen ve 'Tarihin Sıfır Noktası' kabul edilen neolitik inanç merkezi hangisidir?", "Göbeklitepe", ["Çatalhöyük", "Alacahöyük", "Yassıhöyük", "Hacılar"], "İnsanlık tarihinin bilinen en eski anıtsal tapınak kompleksidir."),
    ("Konya Çumra'da yer alan, evlerin bitişik inşa edildiği, sokak bulunmayan ve çatıdan girilen dünyanın en eski yerleşik kent yerleşmelerinden biri hangisidir?", "Çatalhöyük Neolitik Kenti", ["Göbeklitepe", "Troya", "Gordion", "Sardes"], "UNESCO Dünya Mirası Listesi'ndeki ilk şehir yerleşimidir."),
    ("Türkiye'nin İLK milli parkı ilan edilen (1948) tarihi ve doğal sit alanı neresidir?", "Yozgat Çamlığı Milli Parkı", ["Beydağları Sahil Milli Parkı", "Soğuksu Milli Parkı", "Kuşcenneti Milli Parkı", "Köprülü Kanyon"], "Cumhuriyet döneminde koruma altına alınan ilk milli parkımızdır."),
    ("Antalya ile Fethiye arasında uzanan, antik kentlerin içinden geçen ve dünyanın en iyi uzun mesafe yürüyüş rotalarından biri kabul edilen tarihi yol hangisidir?", "Likya Yolu", ["Kral Yolu", "İpek Yolu", "Karya Yolu", "Aziz Pavlus Yolu"], "Akdeniz'in eşsiz koyları ve antik kentlerini birbirine bağlar.")
]
