# tarih_data_2.py - Q70 to Q78 (90 questions)

# Q70: Yavuz ve Kanuni Dönemleri
q70_list = [
    ("1514 yılında Yavuz Sultan Selim ile Safevi hükümdarı Şah İsmail arasında yapılan ve Doğu Anadolu'yu güvenceye alan zafer hangisidir?", "Çaldıran Zaferi", ["Mercidabık Zaferi", "Ridaniye Zaferi", "Turnadağ Zaferi", "Otlukbeli Zaferi"], "Safevi tehlikesi önlenmiş, Tebriz'e kadar girilmiştir."),
    ("1516 Mercidabık ve 1517 Ridaniye Savaşları ile Memlük Devleti'ne son vererek Halifeliği Osmanlı'ya kazandıran padişah kimdir?", "Yavuz Sultan Selim", ["Kanuni Sultan Süleyman", "Fatih Sultan Mehmet", "II. Selim", "III. Murat"], "Suriye, Filistin, Mısır ve Hicaz fethedilmiş, kutsal emanetler İstanbul'a getirilmiştir."),
    ("1526 yılında Kanuni Sultan Süleyman komutasındaki Osmanlı ordusunun Macar krallığını iki saatte bozguna uğrattığı tarihi meydan savaşı hangisidir?", "Mohaç Meydan Muharebesi", ["Preveze Deniz Zaferi", "Zigetvar Seferi", "Varna Savaşı", "Çaldıran Savaşı"], "Tarihin en kısa süren ve en kesin meydan savaşlarından biridir."),
    ("1538 yılında Barbaros Hayrettin Paşa komutasındaki Osmanlı donanmasının Andrea Doria komutasındaki Haçlı donanmasını yok ettiği ve Akdeniz'i Türk Gölü yaptığı deniz zaferi hangisidir?", "Preveze Deniz Zaferi", ["İnebahtı Deniz Savaşı", "Çeşme Baskını", "Navarin Baskını", "Sinop Baskını"], "28 Eylül günü günümüzde Türk Deniz Kuvvetleri Günü olarak kutlanır."),
    ("1533 yılında Avusturya ile imzalanan ve Avusturya Arşidükü'nün Osmanlı Sadrazamına denk sayıldığı tarihi antlaşma hangisidir?", "İstanbul (İbrahim Paşa) Antlaşması", ["Zitvatorok Antlaşması", "Karlofça Antlaşması", "Pasarofça Antlaşması", "Vasvar Antlaşması"], "Osmanlı Devleti Avrupa üzerindeki siyasi ve hukuki üstünlüğünü tescillemiştir."),
    ("Kanuni Sultan Süleyman'ın 1566 yılında çıktığı ve kuşatma devam ederken vefat ettiği son seferi hangisidir?", "Zigetvar Seferi", ["Rodos Seferi", "Belgrad Seferi", "Viyana Kuşatması", "Irak Seferi"], "Zigetvar Kalesi fethedilmiş, Kanuni'nin naaşı otağında muhafaza edilmiştir."),
    ("1535 yılında Kanuni döneminde Fransa'ya verilen ticari ve hukuki ayrıcalıklara (kapitülasyonlar) verilen ad nedir?", "İmtiyazat-ı Mahsusa", ["Ahidname", "Hatt-ı Hümayun", "Ferman", "Berat"], "Her iki hükümdarın sağlığı süresince geçerli olmak şartıyla dostluk antlaşması yapılmıştır."),
    ("Portekizlilerin Hint Okyanusu'ndaki hâkimiyetini kırmak amacıyla Piri Reis, Seydi Ali Reis gibi denizcilerin katıldığı seferler hangisidir?", "Hint Deniz Seferleri", ["Akdeniz Seferleri", "Kırım Seferleri", "Mora Seferleri", "Karadeniz Seferleri"], "Okyanus şartlarına uygun olmayan kadırgalar nedeniyle istenen tam sonuç alınamamıştır."),
    ("Piri Reis'in Kanuni Sultan Süleyman'a sunduğu, Akdeniz kıyılarını ve adalarını tanıtan ünlü denizcilik kılavuzu hangisidir?", "Kitab-ı Bahriye", ["Mir'atü'l-Memalik", "Cihannüma", "Seyahatname", "Keşfü'z-Zünun"], "Piri Reis'in en önemli coğrafi ve denizcilik başyapıtıdır."),
    ("Seydi Ali Reis'in Hindistan dönüşü kaleme aldığı edebiyatımızdaki ilk gezi ve anı kitaplarından biri olan eseri hangisidir?", "Mir'atü'l-Memalik (Memleketlerin Aynası)", ["Kitab-ı Bahriye", "Tuhfetü'l-Kibar", "Tarih-i Cevdet", "Babürname"], "Hindistan'dan karayoluyla İstanbul'a dönüş macerasını anlatır.")
]

# Q71: Divan-ı Hümayun ve Görevlileri
q71_list = [
    ("Osmanlı Devleti'nde padişahtan sonraki en yetkili kişi olan, padişahın mührünü taşıyan ve sefere çıktığında 'Serdar-ı Ekrem' unvanını alan devlet adamı kimdir?", "Sadrazam (Vezir-i Azam)", ["Şeyhülislam", "Kazasker", "Kaptan-ı Derya", "Nişancı"], "Sadrazam hükümdarın mutlak vekilidir."),
    ("Divan-ı Hümayun'da adalet, eğitim ve kadı-müderris atamalarından sorumlu olan, tutanakları denetleyen görevli kimdir?", "Kazasker (Kadıasker)", ["Şeyhülislam", "Defterdar", "Nişancı", "Reisülküttab"], "Rumeli ve Anadolu kazaskeri olmak üzere ikiye ayrılırdı."),
    ("Osmanlı'da devletin tüm maliye işlerinden, bütçenin hazırlanmasından, gelir-gider dengesinden sorumlu divan üyesi kimdir?", "Defterdar", ["Kazasker", "Nişancı", "Sadrazam", "Kaptan-ı Derya"], "Rumeli ve Anadolu defterdarı olarak hazineden sorumluydular."),
    ("Padişahın ferman ve beratlarına 'Tuğra' çeken, fethedilen arazileri 'Tahrir Defterleri'ne kaydeden divan üyesi kimdir?", "Nişancı", ["Reisülküttab", "Defterdar", "Kazasker", "Çavuşbaşı"], "Örfi hukukun uzmanı ve tapu-tahrir kayıtlarının sorumlusuydu."),
    ("Başlangıçta Nişancı'ya bağlı kâtip iken XVII. yüzyıldan itibaren dış ilişkilerden ve diplomasiden sorumlu Dışişleri Bakanı konumuna gelen görevli kimdir?", "Reisülküttab", ["Kazasker", "Sadrazam", "Defterdar", "Şeyhülislam"], "Modern dönemin Hariciye Nazırı'nın temelidir."),
    ("Divanda alınan kararların ve kanunların İslam dinine uygun olup olmadığına dair fetva veren ilmiye sınıfının başı kimdir?", "Şeyhülislam (Müftü)", ["Kazasker", "Sadrazam", "Nakibüleşraf", "Müderris"], "Protokolde sadrazama denk kabul edilirdi."),
    ("Osmanlı'da deniz kuvvetlerinin (donanmanın) başkomutanı olup XVI. yüzyıldan itibaren Divan-ı Hümayun'un asil üyesi olan makam hangisidir?", "Kaptan-ı Derya", ["Yeniçeri Ağası", "Cebecibaşı", "Topçubaşı", "Levend"], "Barbaros Hayrettin Paşa ile birlikte divan üyesi olmuştur."),
    ("Divan toplantılarının güvenliğini sağlayan ve gerektiğinde İstanbul'un asayişinden sorumlu olan komutan kimdir?", "Yeniçeri Ağası", ["Subaşı", "Bostancıbaşı", "Asesbaşı", "Muhtesip"], "Vezir rütbesinde ise divan toplantılarına katılırdı."),
    ("Osmanlı bürokrasisinde yönetici sınıf içinde yer alan 'Seyfiye' (askeri ve idari) sınıfına mensup olan görevli hangisidir?", "Sadrazam ve Beylerbeyi", ["Kazasker ve Şeyhülislam", "Defterdar ve Nişancı", "Müderris ve Kadı", "Kâtip ve Reisülküttab"], "Seyfiye kılıç ehlidir; yönetim ve ordu mensuplarıdır."),
    ("Osmanlı'da eğitim, din ve hukuk işlerini yürüten 'İlmiye' sınıfına mensup olan görevli hangisidir?", "Kazasker, Şeyhülislam, Kadı, Müderris", ["Sadrazam, Vezir", "Defterdar, Nişancı", "Kaptan-ı Derya", "Beylerbeyi, Sancakbeyi"], "İlmiye medrese kökenli din ve adalet mensuplarıdır.")
]

# Q72: Taşra Teşkilatı ve Toprak Sistemi
q72_list = [
    ("Osmanlı Devleti'nde gelirleri devlet memurlarına ve askerlere hizmetleri karşılığında bırakılan, yıllık geliri 100 bin akçeden fazla olan dirlik toprağı hangisidir?", "Has", ["Zeamet", "Tımar", "Vakıf", "Yurtluk"], "Has padişah, hanedan üyeleri ve vezirlere verilirdi."),
    ("Yıllık geliri 20 bin ile 100 bin akçe arasında olan ve orta dereceli memurlara (subaşı, kadı) verilen dirlik toprağı hangisidir?", "Zeamet", ["Has", "Tımar", "Ocaklık", "Paşmaklık"], "Zeamet orta dereceli kadrolara tahsis edilirdi."),
    ("Tımar sahiplerinin dirlik gelirlerinin her 3.000 veya 5.000 akçesi için sefere götürmekle yükümlü olduğu zırhlı atlı askere ne ad verilir?", "Cebelü", ["Yeniçeri", "Sipahi", "Azap", "Akıncı"], "Tımar sisteminde hazineden para çıkmadan atlı ordu yetiştirilirdi."),
    ("Vergi gelirlerinin ihale yoluyla peşin olarak mültezimlere satılması esasına dayanan ve merkeze uzak eyaletlerde uygulanan sisteme ne ad verilir?", "İltizam sistemi", ["Tımar sistemi", "Dirlik sistemi", "Vakıf sistemi", "Gulam sistemi"], "Mültezimler vergiyi peşin öder ve bölgeden toplardı."),
    ("İltizam hakkının bir kişiye ömür boyu (kayd-ı hayat şartıyla) verilmesi usulüne ne ad verilir?", "Malikâne sistemi", ["İltizam sistemi", "Tımar sistemi", "Esham sistemi", "Müsadere sistemi"], "XVIII. yüzyılda hazinenin nakit ihtiyacı için getirilmiştir."),
    ("Tımar sisteminin uygulandığı, vergilerin doğrudan memurlara maaş olarak bırakıldığı ve tahrir defterine kaydedildiği eyalet türü hangisidir?", "Salyanesiz (Yıllıksız) Eyaletler", ["Salyaneli (Yıllıklı) Eyaletler", "İmtiyazlı Eyaletler", "Muaf Eyaletler", "Özel Yönetimli Eyaletler"], "Anadolu, Rumeli, Karaman, Sivas salyanesiz eyaletlerdendir."),
    ("Tımar sisteminin uygulanmadığı, vergilerin iltizam usulüyle toplanıp merkeze yıllık (salyane) yollandığı eyalet türü hangisidir?", "Salyaneli (Yıllıklı) Eyaletler", ["Salyanesiz Eyaletler", "İmtiyazlı Eyaletler", "Bağlı Beylikler", "Dirlik Eyaletleri"], "Mısır, Trablusgarp, Tunus, Cezayir, Yemen salyaneli eyaletlerdir."),
    ("İç işlerinde serbest, dış işlerinde Osmanlı'ya bağlı olan, Kırım, Eflak, Boğdan ve Erdel gibi özel statülü eyaletlere ne ad verilir?", "İmtiyazlı (Özel Yönetimli) Eyaletler", ["Salyaneli Eyaletler", "Salyanesiz Eyaletler", "Dirlik Eyaletleri", "Merkez Eyaletleri"], "Kırım asker gönderir vergi vermezdi; Hicaz ise ikisinden de muaftı."),
    ("Osmanlı taşra yönetiminde en büyük idari birim olan 'Eyalet'in başındaki yönetici kimdir?", "Beylerbeyi", ["Sancakbeyi", "Kadı", "Subaşı", "Muhtar"], "Eyaletin başında Beylerbeyi bulunurdu (Rumeli Beylerbeyi Anadolu'dan kıdemliydi)."),
    ("Osmanlı'da hem adalet işlerini yürüten hem de kazanın mülki amiri ve belediye başkanı konumunda olan görevli kimdir?", "Kadı", ["Subaşı", "Naib", "Beylerbeyi", "Müderris"], "Kadılar doğrudan Kazasker tarafından atanırdı ve idari bağımsızlıkları vardı.")
]

# Q73: Ordu, Donanma, Hukuk
q73_list = [
    ("I. Murat döneminde temelleri atılan, Hristiyan çocukların Türk-İslam terbiyesiyle yetiştirilerek orduya ve saray bürokrasisine kazandırıldığı sisteme ne ad verilir?", "Devşirme sistemi", ["Tımar sistemi", "İltizam sistemi", "Pençik sistemi", "Ahilik sistemi"], "Devşirmelerin zekileri Enderun'a, güçlüleri Yeniçeri Ocağı'na alınırdı."),
    ("Yeniçerilerin üç ayda bir aldıkları maaşa ve her padişah değişikliğinde aldıkları bahşişe sırasıyla ne ad verilir?", "Ulufe - Cülus Bahşişi", ["Cebelü - Cizye", "Haraç - İane", "Maaş - İkramiye", "Dirhem - Dinar"], "Yeniçeriler ulufe maaşı ve cülus bahşişi alırlardı."),
    ("Osmanlı Devleti'nde üstün yetenekli devlet adamı yetiştirmek amacıyla Topkapı Sarayı içinde kurulan saray okuluna ne ad verilir?", "Enderun Mektebi", ["Medrese", "Rüştiye", "İdadi", "Darülfünun"], "Sarayın iç bölümünde yer alan bürokrat mektebidir."),
    ("Osmanlı Devleti'nde esnaf ve zanaatkârların mesleki dayanışma kurduğu, usta-çırak ilişkisini yönettiği ve kalite denetimi yaptığı teşkilata ne ad verilir?", "Lonca Teşkilatı", ["Ahilik", "Menzil Teşkilatı", "Derbent Teşkilatı", "Mekkari Şebekesi"], "Loncada üretilen malların fiyatı narh sistemiyle belirlenirdi."),
    ("Devletin piyasadaki temel tüketim mallarına azami satış fiyatı koyması uygulamasına ne ad verilir?", "Narh sistemi", ["İltizam sistemi", "Gedik sistemi", "Müsadere sistemi", "İaşecilik"], "Fahiş fiyat artışlarını ve karaborsayı önlemek için uygulanırdı."),
    ("Osmanlı'da ölen veya suç işleyen devlet adamlarının haksız kazançla edindiği mallarına devlet tarafından el konulması uygulamasına ne ad verilir?", "Müsadere sistemi", ["Menzil sistemi", "Gedik sistemi", "Malikâne sistemi", "İstimâlet politikası"], "Fatih ile kurumsallaşmış, II. Mahmut tarafından kaldırılmıştır."),
    ("Osmanlı fetihlerinde fethedilen bölge halkına hoşgörülü davranma, din ve vicdan özgürlüğü tanıyarak devlete bağlama politikasına ne ad verilir?", "İstimâlet (Hoşgörü) Politikası", ["İskân Politikası", "Müsadere", "İltizam", "Gaza ve Cihat"], "Balkan fetihlerinin kalıcı olmasında temel etkendir."),
    ("Fethedilen Balkan topraklarına Anadolu'dan Türkmen ailelerin yerleştirilmesi suretiyle bölgenin Türkleşmesini sağlayan siyasete ne ad verilir?", "İskân Politikası", ["İstimâlet", "Tımar", "Pençik", "Devşirme"], "Balkanlarda demografik dengeyi sağlamıştır."),
    ("Osmanlı donanmasının tarihte İLK KEZ yakıldığı ve Sokullu Mehmet Paşa'nın 'Biz Kıbrıs'ı alarak sizin kolunuzu kestik...' dediği deniz felaketi hangisidir?", "İnebahtı Baskını (1571)", ["Çeşme Baskını (1770)", "Navarin Baskını (1827)", "Sinop Baskını (1853)", "Preveze Savaşı"], "Haçlı donanması Osmanlı donanmasını İnebahtı'da yakmıştır."),
    ("Ahmet Cevdet Paşa başkanlığındaki bir komisyon tarafından hazırlanan, İslam hukukuna dayalı ilk medeni kanun hangisidir?", "Mecelle", ["Kanun-i Esasi", "Sened-i İttifak", "Tanzimat Fermanı", "Kanunname-i Âli Osman"], "1868-1876 yılları arasında hazırlanmış borçlar ve eşya hukukudur.")
]

# Q74: XVII. Yüzyıl Duraklama Dönemi
q74_list = [
    ("1590 yılında Safeviler ile imzalanan ve Osmanlı Devleti'nin DOĞUDA EN GENİŞ sınırlara ulaştığı antlaşma hangisidir?", "Ferhat Paşa Antlaşması", ["Nasuh Paşa Antlaşması", "Serav Antlaşması", "Kasr-ı Şirin Antlaşması", "Amasya Antlaşması"], "Tebriz, Karabağ ve Gürcistan Osmanlı'da kalmıştır."),
    ("1672 yılında Lehistan ile imzalanan ve Osmanlı Devleti'nin BATIDA EN GENİŞ sınırlara ulaştığı antlaşma hangisidir?", "Bucaş Antlaşması", ["Karlofça Antlaşması", "Pasarofça Antlaşması", "Zitvatorok Antlaşması", "Hotin Antlaşması"], "Podolya ve Ukrayna Osmanlı egemenliğine girmiştir."),
    ("1639 yılında imzalanan, Zağros Dağları'nı sınır kabul eden ve günümüz Türkiye-İran sınırını büyük ölçüde belirleyen antlaşma hangisidir?", "Kasr-ı Şirin Antlaşması", ["Ferhat Paşa Antlaşması", "Nasuh Paşa Antlaşması", "Serav Antlaşması", "Kerden Antlaşması"], "IV. Murat'ın Bağdat Fethi sonrasında imzalanmıştır."),
    ("1606 yılında Avusturya ile imzalanan ve Osmanlı padişahının Avusturya arşidüküne denk sayılmasıyla Osmanlı'nın diplomatik üstünlüğünü kaybettiği antlaşma hangisidir?", "Zitvatorok Antlaşması", ["İstanbul Antlaşması", "Karlofça Antlaşması", "Vasvar Antlaşması", "Bucaş Antlaşması"], "1533 İstanbul Antlaşması'ndaki protokol üstünlüğü sona ermiştir."),
    ("İlk kez yeniçeri ocağını kaldırmayı düşünen, saray dışından evlenerek sarayı halka açan ancak yeniçeriler tarafından Yedikule Zindanları'nda şehit edilen genç padişah kimdir?", "Genç Osman (II. Osman)", ["IV. Murat", "I. Ahmet", "IV. Mehmet", "II. Mustafa"], "Hotin Seferi sonrası yeniçerilerin disiplinsizliğini görüp ıslahat planlamıştır."),
    ("Bağdat ve Revan Fatihi olarak anılan, gece sokağa çıkma, içki ve tütün yasağı koyan, Koçi Bey ve Kâtip Çelebi'ye risaleler hazırlatan kudretli padişah kimdir?", "IV. Murat", ["Genç Osman", "I. Ahmet", "I. İbrahim", "IV. Mehmet"], "Devlet otoritesini sert tedbirlerle yeniden sağlamıştır."),
    ("Osmanlı Devleti'nde veraset sisteminde köklü değişiklik yaparak 'Ekber ve Erşed' (En yaşlı ve en olgun hanedan üyesinin tahta geçmesi) kuralını getiren ve kafes sistemini başlatan padişah kimdir?", "I. Ahmet", ["III. Mehmet", "II. Osman", "IV. Murat", "Fatih Sultan Mehmet"], "Taht kavgalarını ve kardeş katlini önlemeyi amaçlamıştır."),
    ("Sadrazamlık teklifini saraya şartlar öne sürerek (kararlarına karışılmaması, atamalarda serbestlik vb.) kabul eden ilk Osmanlı sadrazamı kimdir?", "Köprülü Mehmet Paşa", ["Tarhuncu Ahmet Paşa", "Köprülü Fazıl Ahmet Paşa", "Merzifonlu Kara Mustafa Paşa", "Sokullu Mehmet Paşa"], "Köprülüler dönemi duraklama içinde yükselme devri olarak bilinir."),
    ("Osmanlı tarihinde İLK modern bütçe taslağını hazırlayan ancak saray harcamalarını kısıtladığı için rakipleri tarafından idam ettirilen devlet adamı kimdir?", "Tarhuncu Ahmet Paşa", ["Köprülü Mehmet Paşa", "Koçi Bey", "Lala Mustafa Paşa", "Koca Sinan Paşa"], "Gelir-gider dengesini ilk kez denk bütçeyle kurmuştur."),
    ("1683 yılında II. Viyana Kuşatması'nda başarısız olarak idam edilen ve 16 yıl sürecek 'Kutsal İttifak' savaşlarını başlatan sadrazam kimdir?", "Merzifonlu Kara Mustafa Paşa", ["Köprülü Fazıl Ahmet Paşa", "Köprülü Mehmet Paşa", "Kara İbrahim Paşa", "Süleyman Paşa"], "Kuşatmanın hezimetle bitmesi üzerine Belgrad'da boğdurulmuştur.")
]

# Q75: XVIII. Yüzyıl Gerileme Dönemi ve Islahatlar
q75_list = [
    ("1699 yılında imzalanan, Osmanlı Devleti'nin batıda İLK KEZ büyük çapta toprak kaybettiği ve gerileme dönemini başlatan antlaşma hangisidir?", "Karlofça Antlaşması", ["Pasarofça Antlaşması", "Küçük Kaynarca Antlaşması", "İstanbul Antlaşması", "Zitvatorok Antlaşması"], "Avusturya, Venedik ve Lehistan ile imzalanmıştır; 25 yıl garantörlük verilmiştir."),
    ("1718 yılında Avusturya ve Venedik ile imzalanan ve Osmanlı Devleti'nin Batı'nın üstünlüğünü kabul ederek 'Lale Devri'ne girdiği antlaşma hangisidir?", "Pasarofça Antlaşması", ["Karlofça Antlaşması", "Belgrad Antlaşması", "Prut Antlaşması", "Küçük Kaynarca Antlaşması"], "Belgrad Avusturya'ya bırakılmış, barış politikası benimsenmiştir."),
    ("1774 yılında Rusya ile imzalanan, Kırım'ın bağımsız olduğu, Rusya'ya savaş tazminatı ve kapitülasyon verildiği en ağır antlaşmalardan biri hangisidir?", "Küçük Kaynarca Antlaşması", ["Yaş Antlaşması", "Prut Antlaşması", "Belgrad Antlaşması", "Edirne Antlaşması"], "Halkı Müslüman bir toprak ilk kez kaybedilmiş, halifelik kurumu siyasi araç olarak kullanılmıştır."),
    ("1792 yılında imzalanan ve Kırım'ın KESİN olarak Rusya'ya ait olduğunu Osmanlı Devleti'nin kabul ettiği antlaşma hangisidir?", "Yaş Antlaşması", ["Küçük Kaynarca Antlaşması", "Aynalıkavak Tenkihnamesi", "Bükreş Antlaşması", "Edirne Antlaşması"], "Dağılma döneminin başlangıcı kabul edilir."),
    ("1718-1730 yılları arasında süren, padişahı III. Ahmet, sadrazamı Nevşehirli Damat İbrahim Paşa, şairi Nedim olan zevk ve yenilik devri hangisidir?", "Lale Devri", ["Nizam-ı Cedid Devri", "Tanzimat Devri", "Fetret Devri", "Meşrutiyet Devri"], "1730 Patrona Halil İsyanı ile sona ermiştir."),
    ("Lale Devri'nde İbrahim Müteferrika ve Sait Efendi öncülüğünde kurulan ilk sivil Türk matbaasında basılan İLK eser hangisidir?", "Vankulu Lügati", ["Kitab-ı Bahriye", "Tuhfetü'l-Kibar", "Tarih-i Naima", "Cihannüma"], "Dini kitaplar hariç ilmi ve edebi eserler basılmıştır."),
    ("Fransa'dan getirilen Humbaracı Ahmet Paşa (Comte de Bonneval) öncülüğünde orduda ilk kez Batı tarzı askeri ıslahat yapan padişah kimdir?", "I. Mahmut", ["III. Ahmet", "III. Mustafa", "I. Abdülhamid", "III. Selim"], "Kara Mühendishanesi (Hendesehane) kurulmuştur."),
    ("Cülus bahşişini kaldıran, yeniçeri sayımı yaptıran ve ilk iç borçlanma senedi olan 'Esham' sistemini uygulamaya koyan padişah kimdir?", "I. Abdülhamid", ["I. Mahmut", "III. Mustafa", "III. Selim", "II. Mahmut"], "Ulufe alım-satımını da yasaklamıştır."),
    ("Nizam-ı Cedid adıyla Batı tarzı modern bir ordu kuran, ilk daimi elçilikleri (Londra) açan ve Akka'da Napolyon'u yenen padişah kimdir?", "III. Selim", ["II. Mahmut", "I. Abdülhamid", "III. Ahmet", "Abdülmecid"], "Cezzar Ahmet Paşa Akka Kalesi'nde Napolyon'u hezimete uğratmıştır."),
    ("III. Selim döneminde Nizam-ı Cedid ordusunun ve yapılan askeri ıslahatların masraflarını karşılamak amacıyla kurulan özel hazine hangisidir?", "İrad-ı Cedid Hazinesi", ["Hazine-i Hassa", "Beytülmal", "Hazine-i Amire", "Tekalif-i Milliye"], "1807 Kabakçı Mustafa İsyanı ile bu ordu ve hazine lağvedilmiştir.")
]

# Q76: XIX. Yüzyıl Dağılma Dönemi ve Siyasi Olaylar
q76_list = [
    ("Osmanlı Devleti'ne karşı milliyetçilik akımının etkisiyle İLK isyan eden azınlık ve İLK bağımsızlık kazanan azınlık sırasıyla hangileridir?", "Sırplar (İlk isyan) - Yunanlar (İlk bağımsızlık)", ["Yunanlar - Sırplar", "Bulgarlar - Rumenler", "Arnavutlar - Araplar", "Ermeniler - Sırplar"], "Sırplar 1804'te ilk isyanı çıkarmış; Yunanlar 1829 Edirne Antlaşması ile ilk bağımsız olan azınlık olmuştur."),
    ("1833 yılında Mehmet Ali Paşa tehlikesine karşı Rusya ile imzalanan ve Boğazlar meselesini ilk kez uluslararası bir sorun haline getiren ittifak antlaşması hangisidir?", "Hünkâr İskelesi Antlaşması", ["Kütahya Antlaşması", "Londra Boğazlar Sözleşmesi", "Balta Limanı Antlaşması", "Paris Antlaşması"], "Osmanlı 'Denize düşen yılana sarılır' diyerek Rusya'dan yardım istemiştir."),
    ("1838 yılında İngiltere ile imzalanan, gümrük vergilerini düşürerek Osmanlı Devleti'ni Batı'nın açık pazarı haline getiren ticaret sözleşmesi hangisidir?", "Balta Limanı Ticaret Sözleşmesi", ["Hünkâr İskelesi Antlaşması", "Londra Antlaşması", "Paris Antlaşması", "Sevr Antlaşması"], "Osmanlı yerli sanayisine en büyük darbeyi vuran kapitülasyon antlaşmasıdır."),
    ("1841 yılında imzalanarak Boğazları uluslararası statüye kavuşturan ve Osmanlı'nın Boğazlar üzerindeki tek başına egemenlik hakkını sona erdiren sözleşme hangisidir?", "Londra Boğazlar Sözleşmesi", ["Hünkâr İskelesi Antlaşması", "Paris Antlaşması", "Berlin Antlaşması", "Montrö Sözleşmesi"], "Boğazlar barış zamanında tüm savaş gemilerine kapatılmıştır."),
    ("1853-1856 Kırım Savaşı sonrasında imzalanan ve Osmanlı Devleti'nin İLK KEZ bir 'Avrupa Devleti' sayıldığı, toprak bütünlüğünün Avrupa devletlerinin garantisine bırakıldığı antlaşma hangisidir?", "Paris Barış Antlaşması (1856)", ["Berlin Antlaşması", "Londra Antlaşması", "Edirne Antlaşması", "Ayastefanos Antlaşması"], "Karadeniz tarafsız hale getirilmiş, Osmanlı galipken mağlup muamelesi görmüştür."),
    ("Osmanlı Devleti tarihindeki İLK dış borcu hangi savaş sırasında ve hangi devletten almıştır?", "Kırım Savaşı (1854) - İngiltere", ["93 Harbi - Rusya", "Balkan Savaşı - Fransa", "Trablusgarp Savaşı - İtalya", "I. Dünya Savaşı - Almanya"], "Abdülmecid döneminde İngiltere'den borçlanma yapılmıştır."),
    ("Kırım Savaşı sırasında Selimiye Kışlası'nda modern hemşireliğin temellerini atan 'Lambalı Kadın' olarak tanınan İngiliz sağlıkçı kimdir?", "Florence Nightingale", ["Clara Barton", "Marie Curie", "Emmeline Pankhurst", "Mother Teresa"], "Yaralı askerlerin tedavisinde gösterdiği özveriyle hemşireliğin kurucusu olmuştur."),
    ("1877-1878 Osmanlı-Rus Savaşı'nda (93 Harbi) Plevne'de Rus ordularını aylarca durdurarak destan yazan ve 'Plevne Kahramanı' unvanını alan komutan kimdir?", "Gazi Osman Paşa", ["Ahmet Muhtar Paşa", "Süleyman Hüsnü Paşa", "Enver Paşa", "Mahmut Şevket Paşa"], "Gösterdiği kahramanlık dünya askeri literatürüne geçmiştir."),
    ("93 Harbi'nde Erzurum Aziziye Tabyası'nı Ruslara karşı savunan milli mücadelemizin sembol kadın kahramanı kimdir?", "Nene Hatun", ["Kara Fatma", "Şerife Bacı", "Halide Edip", "Gördesli Makbule"], "Erzurum halkıyla birlikte satır ve küreklerle tabyayı kurtarmıştır."),
    ("1878 Berlin Antlaşması ile Osmanlı Devleti'nden ayrılarak bağımsızlık kazanan Balkan devletleri hangileridir?", "Sırbistan, Karadağ, Romanya", ["Yunanistan, Bulgaristan", "Arnavutluk, Makedonya", "Bosna-Hersek, Hırvatistan", "Slovenya, Macaristan"], "Berlin Antlaşması ile bu üç devlet resmen bağımsız olmuştur.")
]

# Q77: XIX. Yüzyıl Demokratikleşme ve Islahatlar
q77_list = [
    ("1808 yılında II. Mahmut ile Âyanlar arasında imzalanan ve padişahın yetkilerini tarihte İLK KEZ sınırlandıran belge hangisidir?", "Sened-i İttifak", ["Tanzimat Fermanı", "Islahat Fermanı", "Kanun-i Esasi", "Gülhane Hatt-ı Hümayunu"], "İngiltere'deki Magna Carta'ya benzetilen ilk anayasal belgedir."),
    ("1826 yılında II. Mahmut tarafından Yeniçeri Ocağı'nın kanlı bir şekilde kaldırılması olayına tarihte ne ad verilir?", "Vaka-i Hayriye (Hayırlı Olay)", ["Vaka-i Vakvakiye", "Kuleli Vakası", "31 Mart Vakası", "Çırağan Baskını"], "Yeniçeri Ocağı yerine Asakir-i Mansure-i Muhammediye ordusu kurulmuştur."),
    ("İlk resmi gazete Takvim-i Vekayi'yi çıkaran, ilk nüfus sayımını yapan, divanı kaldırıp nazırlıkları (bakanlıklar) kuran padişah kimdir?", "II. Mahmut", ["III. Selim", "Abdülmecid", "Abdülaziz", "II. Abdülhamid"], "Tımar ve müsadereyi kaldırmış, köy ve mahalle muhtarlıklarını kurmuştur."),
    ("3 Kasım 1839 tarihinde Mustafa Reşit Paşa tarafından Gülhane Parkı'nda okunan, kanun önünde tüm vatandaşların eşitliğini ilan eden ferman hangisidir?", "Tanzimat Fermanı", ["Islahat Fermanı", "Sened-i İttifak", "Kanun-i Esasi", "Ferman-ı Ali"], "Padişah kendi gücünün üstünde kanun gücünün olduğunu kabul etmiştir."),
    ("1856 yılında ilan edilen ve özellikle gayrimüslim tebaaya geniş haklar tanıyan, 'gâvura gâvur denmeyecek' sözüyle özetlenen ferman hangisidir?", "Islahat Fermanı", ["Tanzimat Fermanı", "Sened-i İttifak", "Kanun-i Esasi", "Adalet Fermanı"], "Cizye vergisi kaldırılmış, gayrimüslimlere memur olma hakkı tanınmıştır."),
    ("23 Aralık 1876 tarihinde ilan edilen, Türk tarihinin İLK yazılı anayasası hangisidir?", "Kanun-i Esasi", ["Teşkilat-ı Esasiye", "1924 Anayasası", "Sened-i İttifak", "Tanzimat Fermanı"], "Mithat Paşa öncülüğünde hazırlanmış, Meclis-i Mebusan açılmıştır."),
    ("I. Meşrutiyet Dönemi'nde Osmanlı parlamentosunu oluşturan iki meclis hangileridir?", "Meclis-i Mebusan (Halk) ve Meclis-i Âyan (Padişah)", ["Millet Meclisi ve Senato", "Divan ve Kurultay", "Temsil Heyeti ve Şura", "Bakanlar Kurulu ve Danıştay"], "Mebuslar halk tarafından, âyan üyeleri ise padişah tarafından ömür boyu seçilirdi."),
    ("1881 yılında Osmanlı Devleti'nin iflas etmesi (Muharrem Kararnamesi) üzerine alacaklı devletlerin borçları tahsil etmek için kurduğu mali teşkilat hangisidir?", "Düyun-ı Umumiye İdaresi", ["Hilal-i Ahmer", "Ziraat Bankası", "Osmanlı Bankası", "Darüşşafaka"], "Devletin vergi gelirlerine el koyarak ekonomik bağımsızlığı yok etmiştir."),
    ("1908 yılında II. Meşrutiyet'in ilanından sonra rejime karşı çıkan ve Selanik'ten gelen 'Hareket Ordusu' tarafından bastırılan gerici ayaklanma hangisidir?", "31 Mart Vakası (1909)", ["Bab-ı Âli Baskını", "Kuleli Vakası", "Şeyh Sait İsyanı", "Menemen Olayı"], "Mustafa Kemal bu orduda Kurmay Başkanı olarak görev almıştır; II. Abdülhamid tahttan indirilmiştir."),
    ("II. Abdülhamid döneminde İslam birliği (Panislamizm) politikasını güçlendirmek için Şam ile Medine arasında inşa edilen demiryolu hattı hangisidir?", "Hicaz Demiryolu", ["Bağdat Demiryolu", "Rumeli Demiryolu", "İzmir-Aydın Demiryolu", "Anadolu Demiryolu"], "Tamamen Müslümanların bağışlarıyla inşa edilmiştir.")
]

# Q78: XX. Yüzyıl Başları (Trablusgarp, Balkan Savaşları, Bab-ı Âli)
q78_list = [
    ("Mustafa Kemal'in sömürgeciliğe karşı İLK savaşı kabul edilen, 'Gazeteci Şerif Bey' takma adıyla Derne ve Tobruk'ta yerel halkı örgütlediği savaş hangisidir?", "Trablusgarp Savaşı (1911-1912)", ["I. Balkan Savaşı", "Çanakkale Savaşı", "Kafkas Cephesi", "Sakarya Meydan Muharebesi"], "İtalya'ya karşı gönüllü subaylar gerilla taktiği uygulamıştır."),
    ("1912 yılında imzalanan, Trablusgarp ve Bingazi'nin İtalya'ya bırakıldığı, On İki Ada'nın geçici olarak İtalya'ya verildiği ve Osmanlı'nın Kuzey Afrika'daki son toprağını kaybettiği antlaşma hangisidir?", "Uşi Antlaşması", ["Ouchy Antlaşması (Uşi)", "Londra Antlaşması", "Bükreş Antlaşması", "İstanbul Antlaşması"], "Trablusgarp halkı dini açıdan Osmanlı halifesine bağlı kalmıştır."),
    ("I. Balkan Savaşı'nda Osmanlı Devleti'ne karşı birleşen dört Balkan devleti hangileridir?", "Bulgaristan, Yunanistan, Sırbistan, Karadağ", ["Bulgaristan, Romanya, Sırbistan, Yunanistan", "Romanya, Karadağ, Arnavutluk, Sırbistan", "Yunanistan, Karadağ, Rusya, Bulgaristan", "Avusturya, Sırbistan, Karadağ, Romanya"], "Karadağ'ın Osmanlı'ya savaş açmasıyla başlamıştır."),
    ("I. Balkan Savaşı'nın yarattığı otorite boşluğundan yararlanarak Osmanlı Devleti'nden ayrılarak bağımsızlığını ilan eden EN SON Balkan devleti hangisidir?", "Arnavutluk", ["Bulgaristan", "Yunanistan", "Sırbistan", "Romanya"], "Arnavutluk'un ayrılmasıyla Osmanlıcılık fikri tamamen çökmüştür."),
    ("I. Balkan Savaşı devam ederken Enver Paşa liderliğindeki İttihatçıların hükümet darbesiyle Kamil Paşa hükümetini devirip iktidarı ele geçirdiği olay hangisidir?", "Bab-ı Âli Baskını (1913)", ["31 Mart Vakası", "Kuleli Vakası", "Çırağan Baskını", "Genç Türkler Hareketi"], "Türk siyasi tarihindeki ilk hükümet darbesi kabul edilir."),
    ("I. Balkan Savaşı'nda en fazla payı alarak güçlenen Bulgaristan'a karşı diğer Balkan devletlerinin (Yunanistan, Sırbistan, Karadağ ve Romanya) savaş açtığı muharebe hangisidir?", "II. Balkan Savaşı", ["I. Balkan Savaşı", "Trablusgarp Savaşı", "Kırım Savaşı", "93 Harbi"], "Romanya I. Balkan Savaşı'nda olmayıp II. Balkan Savaşı'na katılmıştır."),
    ("II. Balkan Savaşı sırasında fırsattan yararlanarak Edirne ve Kırklareli'yi geri alan ve 'Edirne Fatihi' unvanını kazanan Osmanlı subayı kimdir?", "Enver Paşa", ["Mustafa Kemal Paşa", "Cemal Paşa", "Talat Paşa", "Rauf Orbay"], "Edirne Midye-Enez hattından geri alınmıştır."),
    ("I. Balkan Savaşı sırasında 'Hamidiye Kruvazörü' ile Yunan donanmasına karşı Ege ve Akdeniz'de destansı akınlar düzenleyen 'Hamidiye Kahramanı' kimdir?", "Rauf Orbay", ["Ali Çetinkaya", "Fevzi Çakmak", "İsmet İnönü", "Kazım Karabekir"], "Dünya denizcilik tarihinde ilk korsan akın taktiği olarak incelenir."),
    ("Balkan Savaşları sonrasında Batı Trakya Türklerinin azınlık haklarını, mülkiyet ve dini hürriyetlerini güvence altına alan 1913 antlaşması hangisidir?", "İstanbul ve Atina Antlaşmaları", ["Londra Antlaşması", "Bükreş Antlaşması", "Uşi Antlaşması", "Mondros Mütarekesi"], "Günümüz Türkiye-Bulgaristan sınırı Meriç Nehri olarak belirlenmiştir."),
    ("Mustafa Kemal'in Balkan Savaşları sonrasında atandığı ve yabancı elçilerle diplomatik temaslarda bulunduğu askeri görev yeri neresidir?", "Sofya Askeri Ataşeliği", ["Şam 5. Ordu", "Trablusgarp Komutanlığı", "Manastır Kolordusu", "İstanbul Karargâhı"], "Yarbay rütbesine burada terfi etmiş, parlamento sistemini incelemiştir.")
]
