# tarih_data_3.py - Q79 to Q87 (90 questions)

# Q79: I. Dünya Savaşı Cepheleri
q79_list = [
    ("Osmanlı Devleti'nin I. Dünya Savaşı'nda toprak kazanmak ve Turan idealini gerçekleştirmek amacıyla açtığı İLK taarruz cephesi hangisidir?", "Kafkas Cephesi", ["Kanal Cephesi", "Çanakkale Cephesi", "Irak Cephesi", "Suriye-Filistin Cephesi"], "Enver Paşa komutasındaki Sarıkamış Harekâtı bu cephede gerçekleşmiştir."),
    ("18 Mart 1915'te Çanakkale Boğazı'nda İtilaf donanmasını püskürten ve '18 Mart Kahramanı' unvanını alan Müstahkem Mevki Komutanı kimdir?", "Cevat Çobanlı Paşa", ["Mustafa Kemal Paşa", "Enver Paşa", "Esat Paşa", "Fahrettin Paşa"], "Nusret Mayın Gemisi'nin döşediği mayınlarla büyük zafer kazanılmıştır."),
    ("Çanakkale Kara Savaşları'nda Anafartalar, Conkbayırı ve Arıburnu'nda 'Ben size taarruzu değil, ölmeyi emrediyorum!' diyerek düşmanı durduran komutan kimdir?", "Mustafa Kemal Paşa", ["Cevat Paşa", "Kazım Karabekir", "İsmet İnönü", "Fevzi Çakmak"], "Bu zaferle Mustafa Kemal milli mücadelenin doğal lideri olarak tanınmıştır."),
    ("1916 yılında Irak Cephesi'nde Halil Kut Paşa komutasındaki Osmanlı ordusunun General Townshend dahil 13 bin İngiliz askerini esir aldığı tarihi zafer hangisidir?", "Kut'ül Amare Zaferi", ["Selman-ı Pak Muharebesi", "Çanakkale Zaferi", "Gazze Zaferi", "Kafkas Zaferi"], "İngiliz ordusunun I. Dünya Savaşı'nda uğradığı en ağır hezimetlerden biridir."),
    ("Medine'yi İngiliz destekli Şerif Hüseyin kuvvetlerine karşı 2 yıl 7 ay boyunca çekirge yiyerek savunan ve 'Çöl Kaplanı / Medine Müdafii' unvanını alan komutan kimdir?", "Fahrettin Paşa (Türkkan)", ["Halil Paşa", "Cemal Paşa", "Nuri Paşa", "Cevat Paşa"], "Kutsal emanetleri güvenle İstanbul'a ulaştırmıştır."),
    ("1915 yılında Kafkas Cephesi gerisinde Ermeni çetelerinin isyan ve katliamlarını önlemek amacıyla çıkarılan göç kanununun adı nedir?", "Tehcir (Sevk ve İskân) Kanunu", ["Hıyanet-i Vataniye Kanunu", "Firariler Kanunu", "Tekalif-i Milliye", "Mecelle"], "Güvenliği sağlamak için Ermeni nüfus Suriye ve Lübnan bölgesine nakledilmiştir."),
    ("Bolşevik İhtilali sonrası savaştan çekilen Sovyet Rusya ile Osmanlı ve müttefikleri arasında imzalanan, Kars, Ardahan ve Batum'un (Elviye-i Selase) Osmanlı'ya geri verildiği antlaşma hangisidir?", "Brest-Litovsk Antlaşması (1918)", ["Mondros Mütarekesi", "Gümrü Antlaşması", "Moskova Antlaşması", "Kars Antlaşması"], "Rusya I. Dünya Savaşı'ndan resmen çekilmiştir."),
    ("Mustafa Kemal'in I. Dünya Savaşı'nda savaştığı cephelerin KRONOLOJİK sırası aşağıdakilerden hangisidir?", "Çanakkale - Kafkas - Suriye-Filistin", ["Kafkas - Çanakkale - Suriye", "Suriye - Çanakkale - Kafkas", "Çanakkale - Suriye - Kafkas", "Kanal - Kafkas - Çanakkale"], "1915 Çanakkale (Albay), 1916 Kafkas (Tuğgeneral), 1917-1918 Suriye-Filistin (Yıldırım Orduları)."),
    ("Almanya'nın isteğiyle İngiltere'nin Hindistan sömürge yollarını kesmek ve Mısır'ı geri almak amacıyla Cemal Paşa komutasında açılan taarruz cephesi hangisidir?", "Kanal (Süveyş) Cephesi", ["Kafkas Cephesi", "Irak Cephesi", "Hicaz Cephesi", "Galiçya Cephesi"], "İki kez düzenlenen kanal harekâtı başarısızlıkla sonuçlanmıştır."),
    ("Osmanlı Devleti'nin kendi toprakları dışında müttefiklerine (Almanya, Avusturya, Bulgaristan) yardım etmek amacıyla asker gönderdiği cepheler hangileridir?", "Galiçya, Romanya, Makedonya", ["Kafkas, Kanal, Irak", "Çanakkale, Hicaz, Yemen", "Suriye, Filistin, Trablusgarp", "Kırım, Mora, Girit"], "Bu cepheler sınır dışı yardım cepheleridir.")
]

# Q80: Mondros, İşgaller, Cemiyetler
q80_list = [
    ("30 Ekim 1918 tarihinde Limni Adası'nda Rauf Orbay ile Amiral Calthorpe arasında imzalanan ve Osmanlı'yı fiilen bitiren ateşkes antlaşması hangisidir?", "Mondros Ateşkes Antlaşması", ["Mudanya Ateşkesi", "Sevr Antlaşması", "Lozan Antlaşması", "Uşi Antlaşması"], "Ağır maddelerle Anadolu işgale açık hale getirilmiştir."),
    ("Mondros Ateşkes Antlaşması'nın İtilaf Devletleri'ne güvenliklerini tehdit eden herhangi bir stratejik noktayı işgal etme hakkı tanıyan ve Anadolu'yu işgale açan en tehlikeli maddesi hangisidir?", "7. Madde", ["24. Madde", "1. Madde", "10. Madde", "15. Madde"], "İşgallere hukuki kılıf uydurulan maddedir."),
    ("Mondros'un Vilayet-i Sitte'de (6 doğu ili: Erzurum, Van, Bitlis, Diyarbakır, Elazığ, Sivas) bir karışıklık çıkarsa buraların işgal edileceğini belirten (Ermeni devleti kurmayı amaçlayan) maddesi hangisidir?", "24. Madde", ["7. Madde", "12. Madde", "5. Madde", "18. Madde"], "Doğu Anadolu'da Ermenistan devleti kurma planıdır."),
    ("Mondros Mütarekesi'nden sonra Anadolu'da İLK işgal edilen Osmanlı toprağı neresidir?", "Musul (İngiltere)", ["İzmir (Yunanistan)", "Adana (Fransa)", "Antalya (İtalya)", "Urfa (İngiltere)"], "3 Kasım 1918'de İngilizler petrol bölgesi Musul'u işgal etmiştir."),
    ("15 Mayıs 1919'da İzmir'i işgal eden Yunan askerlerine ilk kurşunu sıkarak şehit düşen Hukuk-ı Beşer gazetesi başyazarı kimdir?", "Hasan Tahsin (Osman Nevres)", ["Ali Çetinkaya", "Sütçü İmam", "Şahin Bey", "Yörük Ali Efe"], "Batı Anadolu'da silahlı direnişi başlatan sembol isimdir."),
    ("İzmir'in işgalinin haksız olduğunu, bölgede Türklerin Rumlardan çoğunlukta olduğunu belirten İLK uluslararası rapor hangisidir?", "Amiral Bristol Raporu", ["General Harbord Raporu", "Milne Hattı Raporu", "Sandler Raporu", "King-Crane Raporu"], "Milli mücadelenin haklılığını kanıtlayan ilk uluslararası belgedir."),
    ("Doğu Anadolu'da Ermenilerin çoğunlukta olmadığını, Türk nüfusun fazla olduğunu ve katliam yapmadığını belgeleyen ABD'li generalin hazırladığı rapor hangisidir?", "General Harbord Raporu", ["Amiral Bristol Raporu", "Milne Raporu", "Sandler Raporu", "Hrisantos Raporu"], "Doğu illerini inceleyen resmi rapordur."),
    ("Milli Mücadele aleyhine çalışan, saltanat ve hilafete bağlı kalarak İngiliz mandasını savunan zararlı cemiyet hangisidir?", "İngiliz Muhipleri ve Sulh-i Selamet-i Osmaniye", ["Kilikyalılar", "Trakya Paşaeli", "Milli Kongre", "Redd-i İlhak"], "Milli mücadeleye açıkça karşı çıkmışlardır."),
    ("Milli Mücadele döneminde basın-yayın yoluyla işgalleri protesto eden ve 'Kuvayımilliye' tabirini ilk kez kullanan yararlı cemiyet hangisidir?", "Milli Kongre Cemiyeti", ["Kilikyalılar Cemiyeti", "Redd-i İlhak Cemiyeti", "Doğu Anadolu Müdafaa-i Hukuk", "Trakya Paşaeli"], "Dr. Esat Işık öncülüğünde kurulan aydınlar cemiyetidir."),
    ("Adana, Çukurova ve çevresini Fransız ve Ermeni işgaline karşı savunmak amacıyla kurulan yararlı cemiyet hangisidir?", "Kilikyalılar Cemiyeti", ["Trabzon Muhafaza-i Hukuk", "Anadolu Kadınları Cemiyeti", "Karakol Cemiyeti", "Gizli Karakol"], "İsmi yabancı gibi dursa da vatansever bir milli cemiyettir.")
]

# Q81: Millî Mücadele Hazırlık (Genelgeler ve Kongreler)
q81_list = [
    ("Mustafa Kemal'in 19 Mayıs 1919'da Samsun'a çıktıktan sonra işgalleri protesto etmek amacıyla mitingler düzenlenmesini istediği İLK genelge hangisidir?", "Havza Genelgesi", ["Amasya Genelgesi", "Erzurum Kongresi", "Sivas Kongresi", "Amasya Protokolü"], "Milli bilinci uyandırmak için yayımlanan ilk belgedir."),
    ("Kurtuluş Savaşı'nın gerekçesini, amacını ve yöntemini belirten bir 'İhtilal Beyannamesi' niteliğindeki tarihi belge hangisidir?", "Amasya Genelgesi (22 Haziran 1919)", ["Havza Genelgesi", "Erzurum Kongresi", "Sivas Kongresi", "Misak-ı Millî"], "'Vatanın bütünlüğü, milletin istiklali tehlikededir... Milletin istiklalini yine milletin azim ve kararı kurtaracaktır.' maddesi yer alır."),
    ("Amasya Genelgesi'nden sonra İstanbul Hükümeti tarafından görevden alınan ve 'Artık sine-i millette bir fert olarak kalacağım' diyerek askerlikten istifa eden Mustafa Kemal'in İLK sivil faaliyeti hangi kongredir?", "Erzurum Kongresi", ["Sivas Kongresi", "Amasya Görüşmesi", "Balıkesir Kongresi", "Pozantı Kongresi"], "Erzurum Kongresi'ne sivil vatandaş olarak başkanlık etmiştir."),
    ("Toplanış bakımından bölgesel, aldığı kararlar bakımından milli olan ve ilk kez 'Milli sınırlar içinde vatan bir bütündür, bölünemez' ilkesini kabul eden kongre hangisidir?", "Erzurum Kongresi", ["Sivas Kongresi", "Amasya Genelgesi", "Balıkesir Kongresi", "Alaşehir Kongresi"], "Manda ve himaye ilk kez burada reddedilmiştir."),
    ("Hem toplanış hem aldığı kararlar bakımından MİLLİ olan, tüm milli cemiyetlerin 'Anadolu ve Rumeli Müdafaa-i Hukuk Cemiyeti' adı altında birleştirildiği kongre hangisidir?", "Sivas Kongresi (4-11 Eylül 1919)", ["Erzurum Kongresi", "Balıkesir Kongresi", "Pozantı Kongresi", "Amasya Kongresi"], "Manda ve himaye kesin olarak reddedilmiştir."),
    ("Sivas Kongresi'nde Temsil Heyeti'nin Ali Fuat Cebesoy'u Batı Cephesi Komutanlığı'na ataması Temsil Heyeti'nin hangi gücü İLK KEZ kullandığını gösterir?", "Yürütme yetkisi", ["Yasama yetkisi", "Yargı yetkisi", "Diplomasi yetkisi", "Askeri vesayet"], "Hükümet gibi hareket ederek yürütme yetkisini kullanmıştır."),
    ("Sivas Kongresi'nden sonra Damat Ferit Paşa hükümetinin istifa etmesi Temsil Heyeti'nin İstanbul Hükümeti'ne karşı kazandığı hangi tür İLK zaferdir?", "İlk siyasi zafer", ["İlk askeri zafer", "İlk ekonomik zafer", "İlk hukuki zafer", "İlk uluslararası zafer"], "Milli mücadelenin İstanbul üzerindeki ilk büyük siyasi başarısıdır."),
    ("Sivas Kongresi kararlarını halka duyurmak amacıyla çıkarılan ve milli mücadelenin ilk yarı-resmi yayın organı olan gazete hangisidir?", "İrade-i Milliye Gazetesi", ["Hâkimiyet-i Milliye", "Ceride-i Resmiye", "Tasvir-i Efkâr", "İkdam"], "Sivas'ta kurulmuş, Ankara'ya taşınınca adı Hâkimiyet-i Milliye olmuştur."),
    ("İstanbul Hükümeti'nin (Salih Paşa) Temsil Heyeti'ni ve Mustafa Kemal'i İLK KEZ hukuken ve resmen tanıdığı diplomatik gelişme hangisidir?", "Amasya Görüşmeleri (Protokolü)", ["Bilecik Görüşmesi", "Sivas Kongresi", "Havza Görüşmesi", "Mudanya Mütarekesi"], "Salih Paşa ile Mustafa Kemal Amasya'da masaya oturmuştur."),
    ("Mustafa Kemal'in milli mücadelenin lideri olarak katıldığı EN SON kongre hangisidir?", "Pozantı Kongresi (Adana)", ["Sivas Kongresi", "Erzurum Kongresi", "Alaşehir Kongresi", "Afyon Kongresi"], "Adana yöresindeki Fransız işgaline karşı düzenlenen Pozantı Kongresi'dir.")
]

# Q82: Son Osmanlı Mebusan Meclisi ve I. TBMM
q82_list = [
    ("12 Ocak 1920'de toplanan Son Osmanlı Mebusan Meclisi'nde Felah-ı Vatan grubu öncülüğünde 28 Ocak 1920'de kabul edilen tarihi milli ant hangisidir?", "Misak-ı Millî (Milli Ant)", ["Teşkilat-ı Esasiye", "Sevr Barış Antlaşması", "Amasya Genelgesi", "Kuvayımilliye Andı"], "Kapitülasyonların kaldırılması, sınırlar ve Boğazlar ilk kez netleştirilmiştir."),
    ("Misak-ı Millî kararlarının ilan edilmesi üzerine İtilaf Devletleri 16 Mart 1920'de nereyi RESMEN işgal etmiş ve meclisi basarak mebusları Malta'ya sürgün etmiştir?", "İstanbul", ["İzmir", "Ankara", "Sivas", "Bursa"], "İstanbul'un işgali TBMM'nin Ankara'da açılmasına meşru zemin hazırlamıştır."),
    ("23 Nisan 1920 tarihinde Ankara'da açılan I. TBMM'nin en yaşlı üye sıfatıyla açılış konuşmasını yapan Sinop Milletvekili kimdir?", "Şerif Bey", ["Mustafa Kemal Paşa", "Celal Bayar", "Ali Fuat Cebesoy", "Rauf Orbay"], "İlk meclis başkanı geçici olarak Şerif Bey olmuştur."),
    ("I. TBMM'nin çıkardığı İLK KANUN aşağıdakilerden hangisidir?", "Ağnam Resminin Artırılmasına Dair Kanun", ["Hıyanet-i Vataniye Kanunu", "Firariler Kanunu", "Meni İsrafat Kanunu", "Nisab-ı Müzakere Kanunu"], "Küçükbaş hayvan vergisini 4 katına çıkaran kanundur."),
    ("I. TBMM'ye karşı çıkan iç isyanları bastırmak, asker kaçaklarını cezalandırmak ve meclisin otoritesini korumak amacıyla kurulan mahkemeler hangisidir?", "İstiklal Mahkemeleri", ["Divan-ı Harp", "Yüce Divan", "Sıkıyönetim Mahkemeleri", "Şeriyye Mahkemeleri"], "Üyeleri milletvekillerinden seçilen olağanüstü mahkemelerdir."),
    ("İstanbul Hükümeti'nin desteklediği, doğrudan TBMM'yi yok etmek ve hilafeti korumak amacıyla kurulan orduya ne ad verilir?", "Kuvay-ı İnzibatiye (Hilafet Ordusu)", ["Kuvayımilliye", "Kuvay-ı Seyyare", "Hareket Ordusu", "Asakir-i Mansure"], "Süleyman Şefik Paşa komutasında TBMM kuvvetlerine saldırmıştır."),
    ("10 Ağustos 1920'de imzalanan ancak TBMM tarafından 'vatan hainliği' sayılarak onaylanmayan ve hukuken geçersiz (ölü doğmuş) kalan antlaşma hangisidir?", "Sevr Barış Antlaşması", ["Mondros Mütarekesi", "Lozan Barış Antlaşması", "Gümrü Antlaşması", "Brest-Litovsk Antlaşması"], "Mebusan Meclisi onaylamadığı için hukuken geçersizdir."),
    ("20 Ocak 1921 tarihinde kabul edilen, 'Egemenlik kayıtsız şartsız milletindir' ilkesini getiren Türkiye Devleti'nin İLK anayasası hangisidir?", "Teşkilat-ı Esasiye Kanunu (1921 Anayasası)", ["Kanun-i Esasi", "1924 Anayasası", "1961 Anayasası", "Sened-i İttifak"], "Kuvvetler birliği ve meclis hükümeti sistemini benimsemiştir."),
    ("12 Mart 1921 tarihinde TBMM kürsüsünde Milli Eğitim Bakanı Hamdullah Suphi Tanrıöver tarafından okunarak milli marş kabul edilen eserin şairi kimdir?", "Mehmet Akif Ersoy", ["Ziya Gökalp", "Tevfik Fikret", "Yahya Kemal", "Namık Kemal"], "Şiiri Türk ordusuna ithaf etmiştir."),
    ("I. TBMM hükümetinin ilk Genelkurmay Başkanı (Erkan-ı Harbiye Reisi) kimdir?", "İsmet İnönü", ["Fevzi Çakmak", "Kazım Karabekir", "Refet Bele", "Ali Fuat Cebesoy"], "Daha sonra Batı Cephesi Komutanlığı görevini yürütmüştür.")
]

# Q83: Doğu ve Güney Cepheleri, İlk Antlaşmalar
q83_list = [
    ("Doğu Cephesi'nde 15. Kolordu Komutanı olarak Ermenileri mağlup eden ve 'Yetimler Babası' olarak anılan komutan kimdir?", "Kazım Karabekir Paşa", ["Ali Fuat Paşa", "İsmet İnönü", "Fevzi Çakmak", "Rauf Orbay"], "Doğu Anadolu'yu Ermeni işgalinden kurtarmıştır."),
    ("3 Aralık 1920'de Ermenistan ile imzalanan, TBMM'nin uluslararası alanda kazandığı İLK askeri ve siyasi zafer olan ve Sevr'i geçersiz sayan ilk antlaşma hangisidir?", "Gümrü Barış Antlaşması", ["Moskova Antlaşması", "Kars Antlaşması", "Batum Antlaşması", "Ankara Antlaşması"], "Ermenistan Sevr hayallerinden vazgeçen ilk devlet olmuştur."),
    ("TBMM'yi ve Misak-ı Millî'yi tanıyan İLK DEVLET aşağıdakilerden hangisidir?", "Ermenistan", ["Sovyet Rusya", "Fransa", "Afganistan", "İtalya"], "Gümrü Antlaşması ile Ermenistan ilk tanıyan devlet olmuştur."),
    ("Güney Cephesi'nde Fransız işgaline karşı ilk silahlı direniş 19 Aralık 1918'de nerede başlamıştır?", "Hatay Dörtyol", ["Maraş", "Antep", "Urfa", "Adana"], "Kara Mehmet Çavuş tarafından Fransızlara karşı sıkılmıştır."),
    ("Maraş'ta Fransız ve Ermeni askerlerinin Türk kadınlarına saldırması üzerine ilk kurşunu sıkarak Maraş direnişini başlatan halk kahramanı kimdir?", "Sütçü İmam", ["Şahin Bey", "Ali Saip Bey", "Rıdvan Hoca", "Yörük Ali"], "Maraş'ın kurtuluş mücadelesinin sembolüdür."),
    ("Antep savunmasında Fransız kuvvetlerine karşı köprüyü savunurken 'Düşman cesedimi çiğnemeden Antep'e giremez!' diyerek şehit düşen kahraman komutan kimdir?", "Şahin Bey (Mehmet Sait)", ["Sütçü İmam", "Kılıç Ali", "Ali Saip Bey", "Arslan Bey"], "Antep savunmasının efsanevi lideridir."),
    ("20 Ekim 1921 tarihinde Fransa ile imzalanan, Güney Cephesi'ni kapatan ve Hatay hariç Suriye sınırını belirleyen tarihi antlaşma hangisidir?", "Ankara Antlaşması", ["Gümrü Antlaşması", "Moskova Antlaşması", "Kars Antlaşması", "Mudanya Mütarekesi"], "Fransa TBMM'yi tanıyan İLK İtilaf Devleti olmuştur."),
    ("TBMM tarafından kahramanlıklarından dolayı 'Gazi' unvanı verilen ilk şehir hangisidir?", "Gaziantep (1921)", ["Kahramanmaraş (1973)", "Şanlıurfa (1984)", "İnebolu", "Kütahya"], "1921 yılında meclis kararıyla Gazi unvanı verilmiştir."),
    ("Milli Mücadele'de cepheye cephane taşırken bebeğinin üzerindeki battaniyeyi mermilere örten ve donarak şehit olan kahraman Türk kadını kimdir?", "Şerife Bacı", ["Nene Hatun", "Kara Fatma", "Gördesli Makbule", "Halide Edip"], "Kastamonu-İnebolu hattındaki İstiklal Yolu'nun sembolüdür."),
    ("Milli Mücadele'de silah ve mühimmatın Karadeniz üzerinden Ankara'ya ulaştırıldığı tarihi lojistik rotaya ne ad verilir?", "İstiklal Yolu (İnebolu - Kastamonu - Ilgaz - Çankırı - Ankara)", ["Tarihi İpek Yolu", "Kral Yolu", "Bağdat Yolu", "Kilikya Hattı"], "Kurtuluş Savaşı'nın en kritik ikmal ve lojistik damarıdır.")
]

# Q84: Batı Cephesi Muharebeleri
q84_list = [
    ("Batı Cephesi'nde düzenli ordunun Yunan kuvvetlerine karşı kazandığı İLK askeri zafer hangisidir?", "I. İnönü Zaferi (Ocak 1921)", ["II. İnönü Zaferi", "Sakarya Meydan Muharebesi", "Büyük Taarruz", "Gediz Muharebesi"], "İsmet Paşa komutasındaki yeni kurulan düzenli ordu Yunanlıları durdurmuştur."),
    ("I. İnönü Zaferi'nden sonra TBMM'yi tanıyan İLK Müslüman devlet hangisidir?", "Afganistan", ["Pakistan", "İran", "Irak", "Mısır"], "1 Mart 1921'de Ankara'da dostluk antlaşması imzalanmıştır."),
    ("16 Mart 1921'de Sovyet Rusya ile imzalanan, büyük bir Avrupa devletinin TBMM'yi tanıdığı ve Batum'un Gürcistan'a bırakılmasıyla Misak-ı Millî'den İLK TAVİZİN verildiği antlaşma hangisidir?", "Moskova Antlaşması", ["Gümrü Antlaşması", "Kars Antlaşması", "Brest-Litovsk Antlaşması", "Lozan Antlaşması"], "Batum Misak-ı Millî'den verilen ilk tavizdir."),
    ("I. İnönü Zaferi'nin ardından İtilaf Devletleri'nin Sevr Antlaşması'nı yumuşatarak TBMM'ye kabul ettirmek amacıyla topladığı konferans hangisidir?", "Londra Konferansı (1921)", ["Paris Konferansı", "San Remo Konferansı", "Lozan Konferansı", "Cenevre Konferansı"], "Bekir Sami Bey TBMM heyetine başkanlık etmiş, İtilaf Devletleri TBMM'yi hukuken tanımıştır."),
    ("Mustafa Kemal'in 'Siz orada yalnız düşmanı değil, milletin makûs (ters giden) talihini de yendiniz' dediği tarihi zafer hangisidir?", "II. İnönü Zaferi (Nisan 1921)", ["I. İnönü Zaferi", "Sakarya Meydan Muharebesi", "Büyük Taarruz", "Mudanya Mütarekesi"], "İsmet Paşa'ya çektiği tarihi kutlama telgrafıdır."),
    ("Kurtuluş Savaşı'nda düzenli ordunun Batı Cephesi'nde aldığı TEK yenilgi olan, Afyon, Kütahya ve Eskişehir'in işgal edildiği muharebe hangisidir?", "Kütahya-Eskişehir Muharebeleri", ["I. İnönü Savaşı", "Gediz Muharebesi", "Aslıhanlar Savaşı", "Dumlupınar Muharebesi"], "Türk ordusu yok olmaktan kurtulmak için Sakarya Nehri'nin doğusuna çekilmiştir."),
    ("Kütahya-Eskişehir Muharebeleri'nin en buhranlı günlerinde Ankara'da toplanan ve eğitime verilen büyük önemi gösteren kongre hangisidir?", "I. Maarif (Eğitim) Kongresi", ["İktisat Kongresi", "Sivas Kongresi", "Sanayi Kongresi", "Hukuk Kongresi"], "Mustafa Kemal cepheden gelerek kongrenin açılış konuşmasını yapmıştır."),
    ("Kütahya-Eskişehir yenilgisi üzerine 5 Ağustos 1921'de meclis tarafından Mustafa Kemal'e üç aylığına verilen olağanüstü askeri yetki hangisidir?", "Başkomutanlık Yetkisi", ["Gazi Unvanı", "Mareşal Rütbesi", "Meclis Başkanlığı", "Cumhurbaşkanlığı"], "Mustafa Kemal meclisin tüm yetkilerini şahsında toplamıştır."),
    ("Başkomutan Mustafa Kemal'in ordunun acil ihtiyaçlarını (giyecek, yiyecek, taşıt, cephane) halktan karşılamak amacıyla yayımladığı emirler hangisidir?", "Tekalif-i Milliye Emirleri (Milli Yükümlülükler)", ["Hıyanet-i Vataniye", "Firariler Kanunu", "Teşkilat-ı Esasiye", "Meni Müskirat"], "Türk milletinin topyekûn fedakârlığının en somut belgesidir."),
    ("Kurtuluş Savaşı sırasında İtalya hangi zaferden sonra Anadolu'dan tamamen çekilme kararı almıştır?", "Sakarya Meydan Muharebesi", ["I. İnönü", "II. İnönü", "Büyük Taarruz", "Kütahya-Eskişehir"], "Sakarya zaferinden sonra İtalyanlar Anadolu'yu tamamen boşaltmıştır.")
]

# Q85: Sakarya, Büyük Taarruz, Mudanya, Lozan
q85_list = [
    ("Mustafa Kemal'in 'Hattı müdafaa yoktur, sathı müdafaa vardır. O satıh bütün vatandır.' emrini verdiği ve 22 gün 22 gece süren dünya tarihinin en uzun meydan savaşı hangisidir?", "Sakarya Meydan Muharebesi (1921)", ["Büyük Taarruz", "I. İnönü", "Kütahya-Eskişehir", "Dumlupınar"], "1683 II. Viyana'dan beri süren Türk geri çekilişi son bulmuştur."),
    ("Sakarya Zaferi'nden sonra TBMM tarafından Mustafa Kemal Paşa'ya hangi unvan ve rütbe verilmiştir?", "Gazi Unvanı ve Mareşallik Rütbesi", ["Başkomutanlık", "Paşalık", "Cumhurbaşkanlığı", "İstiklal Madalyası"], "19 Eylül 1921'de kanunla tevcih edilmiştir."),
    ("Sakarya Zaferi sonrasında Kafkas Cumhuriyetleri (Azerbaycan, Ermenistan, Gürcistan) ile imzalanan ve Doğu sınırımızı KESİN olarak çizen antlaşma hangisidir?", "Kars Antlaşması (13 Ekim 1921)", ["Moskova Antlaşması", "Gümrü Antlaşması", "Brest-Litovsk Antlaşması", "Ankara Antlaşması"], "Doğu sınırımız kesinleşmiştir."),
    ("26 Ağustos 1922'de başlayan, 30 Ağustos'ta Dumlupınar'da zaferle taçlanan ve Mustafa Kemal'in 'Ordular! İlk hedefiniz Akdeniz'dir, ileri!' emrini verdiği muharebe hangisidir?", "Büyük Taarruz (Başkomutanlık Meydan Muharebesi)", ["Sakarya Meydan Muharebesi", "İnönü Zaferi", "Dumlupınar Zaferi", "İzmir'in Kurtuluşu"], "Yunan ordusu tamamen bozguna uğratılmış, 9 Eylül'de İzmir kurtarılmıştır."),
    ("11 Ekim 1922'de imzalanan, Doğu Trakya, Boğazlar ve İstanbul'un SAVAŞ YAPILMADAN diplomatik yolla kurtarılmasını sağlayan ateşkes antlaşması hangisidir?", "Mudanya Ateşkes Antlaşması", ["Mondros Mütarekesi", "Lozan Antlaşması", "Ankara Antlaşması", "Sevr Antlaşması"], "İsmet Paşa'nın diplomatik başarısıyla Osmanlı resmen ve fiilen son bulmuştur."),
    ("Lozan Barış Konferansı'na İtilaf Devletleri'nin hem TBMM'yi hem İstanbul Hükümeti'ni birlikte çağırarak ikilik çıkarmak istemesi üzerine 1 Kasım 1922'de ne kaldırılmıştır?", "Saltanat", ["Halifelik", "Şeriye Vekâleti", "Mebusan Meclisi", "Divan"], "Osmanlı Devleti hukuken resmen sona ermiştir."),
    ("24 Temmuz 1923'te imzalanan Lozan Barış Antlaşması'nda İsmet İnönü heyetinin TAVİZ VERMEMEK üzere kesin talimat aldığı iki temel konu hangileridir?", "Kapitülasyonlar ve Ermeni Yurdu Meselesi", ["Boğazlar ve Musul", "Hatay ve Kıbrıs", "Borçlar ve Nüfus Mübadelesi", "Patrikhane ve Adalar"], "Milli bağımsızlıktan asla taviz verilmemiştir."),
    ("Lozan Barış Antlaşması ile Türkiye'nin Yunanistan'dan savaş tazminatı olarak aldığı yer neresidir?", "Karaağaç ve Bosnaköy", ["Selanik", "Gümülcine", "Midilli", "Dedeağaç"], "Yunanistan'ın yaptığı tahribata karşılık tazminat olarak verilmiştir."),
    ("Lozan Barış Antlaşması'nda Türkiye ile İngiltere arasında çözülemeyen ve dokuz ay içinde ikili görüşmelere bırakılan tek sınır meselesi hangisidir?", "Irak Sınırı (Musul Meselesi)", ["Suriye Sınırı", "Yunanistan Sınırı", "İran Sınırı", "Bulgaristan Sınırı"], "Musul meselesi daha sonra Milletler Cemiyeti'ne taşınmıştır."),
    ("Lozan Barış Antlaşması'nı onaylayan meclis hangisidir?", "II. TBMM", ["I. TBMM", "Mebusan Meclisi", "Kurucu Meclis", "Milli Birlik Komitesi"], "Görüşmeleri I. TBMM başlatmış, onaylamayı yeni seçilen II. TBMM yapmıştır.")
]

# Q86: Atatürk İnkılapları ve İlkeleri
q86_list = [
    ("29 Ekim 1923'te Cumhuriyetin ilanıyla Türkiye Cumhuriyeti'nin İLK Cumhurbaşkanı, İLK Başbakanı ve İLK Meclis Başkanı sırasıyla kimler olmuştur?", "Mustafa Kemal Atatürk - İsmet İnönü - Fethi Okyar", ["İsmet İnönü - Fevzi Çakmak - Kazım Karabekir", "Mustafa Kemal - Rauf Orbay - Celal Bayar", "Celal Bayar - Adnan Menderes - Refik Koraltan", "Fevzi Çakmak - İsmet İnönü - Ali Fuat"], "Hükümet bunalımı (Sonbahar Krizi) çözülerek kabine sistemine geçilmiştir."),
    ("3 Mart 1924 tarihinde kabul edilen ve Türkiye'de eğitimin milli, laik ve tek çatı altında birleştirilmesini sağlayan devrim kanunu hangisidir?", "Tevhid-i Tedrisat Kanunu", ["Maarif Teşkilatı Kanunu", "Harf İnkılabı", "Medreselerin Kapatılması", "Millet Mektepleri Kanunu"], "Tüm okullar Milli Eğitim Bakanlığı'na bağlanmıştır."),
    ("3 Mart 1924'te çıkarılan diğer kanunlarla aşağıdakilerden hangisi GERÇEKLEŞTİRİLMEMİŞTİR?", "Harf İnkılabı yapılması (1928)", ["Halifeliğin kaldırılması", "Şeriye ve Evkaf Vekâleti'nin kaldırılması", "Erkan-ı Harbiye Vekâleti'nin kaldırılması", "Osmanlı Hanedanı'nın yurt dışına çıkarılması"], "Harf İnkılabı 1928 yılındadır, 3 Mart 1924 kanunları arasında değildir."),
    ("17 Şubat 1926'da İsviçre'den uyarlanarak kabul edilen, tek eşle evlilik, resmi nikâh ve kadınlara mirasta eşitlik getiren kanun hangisidir?", "Türk Medeni Kanunu", ["Borçlar Kanunu", "Ceza Kanunu", "Ticaret Kanunu", "Mecelle"], "Hukuk birliği sağlanmış ve laik hukuk düzenine geçilmiştir; siyasi haklar içermez."),
    ("Türk kadınına tanınan siyasi hakların KRONOLOJİK sırası (BMW şifresi) aşağıdakilerden hangisidir?", "Belediye (1930) - Muhtarlık (1933) - Vekillik/Milletvekilliği (1934)", ["Muhtarlık - Belediye - Vekillik", "Vekillik - Belediye - Muhtarlık", "Belediye - Vekillik - Muhtarlık", "Köy - Şehir - Meclis"], "Kadınlar 1930'da belediye, 1933'te muhtar, 1934'te milletvekili seçme-seçilme hakkı almıştır."),
    ("1 Kasım 1928'de kabul edilen Yeni Türk Harflerini halka öğretmek amacıyla 24 Kasım 1928'de açılan ve Atatürk'e 'Başöğretmen' unvanı verilen okullar hangisidir?", "Millet Mektepleri", ["Köy Enstitüleri", "Halkevleri", "Darülfünun", "Rüştiyeler"], "Okuma-yazma seferberliği başlatılmıştır; 24 Kasım Öğretmenler Günü kabul edilir."),
    ("1925 yılında kabul edilen, köylünün üzerindeki ağır vergi yükünü kaldıran ve Halkçılık ilkesiyle doğrudan ilgili olan vergi hangisidir?", "Aşar (Öşür) Vergisi", ["Ağnam Vergisi", "Cizye", "Haraç", "Varlık Vergisi"], "Köylünün refahını artıran en büyük mali devrimdir."),
    ("Atatürk ilkelerinden hangisi sınıf mücadelesini reddeder, kanun önünde eşitliği ve sosyal adaleti savunur?", "Halkçılık", ["Devletçilik", "Milliyetçilik", "Laiklik", "Cumhuriyetçilik"], "Halkçılık ayrıcalıksız, kaynaşmış bir toplum hedefler."),
    ("Cumhuriyetin ilk yıllarında özel sektörün sermaye ve teknik yetersizliği nedeniyle temel sanayi yatırımlarının bizzat devlet eliyle yapılmasını öngören ilke hangisidir?", "Devletçilik", ["Halkçılık", "Milliyetçilik", "Cumhuriyetçilik", "İnkılapçılık"], "Karma ekonomik modeli ve I. Beş Yıllık Sanayi Planı'nı hayata geçirmiştir."),
    ("1937 yılında anayasaya giren Atatürk'ün altı temel ilkesi aşağıdakilerden hangisinde tam olarak verilmiştir?", "Cumhuriyetçilik, Milliyetçilik, Halkçılık, Devletçilik, Laiklik, İnkılapçılık", ["Demokrasi, Eşitlik, Hürriyet, Adalet, Laiklik, Barış", "Bağımsızlık, Birlik, Vatanseverlik, Reform, Halkçılık, Devletçilik", "Saltanat, Hilafet, Meşrutiyet, Ordu, Millet, Hukuk", "Liberalizm, Sosyalizm, Milliyetçilik, Devletçilik, Halkçılık, Laiklik"], "CHP'nin amblemindeki altı ok bu ilkeleri simgeler.")
]

# Q87: Atatürk Dönemi Dış Politika ve Çağdaş Türk Tarihi
q87_list = [
    ("20 Temmuz 1936'da imzalanarak Boğazlar Komisyonu'nu kaldıran, Boğazlarda tam Türk egemenliğini ve asker bulundurma hakkını sağlayan tarihi sözleşme hangisidir?", "Montrö Boğazlar Sözleşmesi", ["Lozan Boğazlar Sözleşmesi", "Londra Sözleşmesi", "Sadabat Paktı", "Balkan Antantı"], "Boğazlar tamamen Türk askeri ve hukuki kontrolüne geçmiştir."),
    ("1934 yılında İtalya ve Almanya'nın yayılmacı tehditlerine karşı Türkiye, Yunanistan, Yugoslavya ve Romanya arasında kurulan savunma paktı hangisidir?", "Balkan Antantı (TAYYAR)", ["Sadabat Paktı", "Bağdat Paktı", "NATO", "Varşova Paktı"], "Türkiye batı sınırını güvenceye almıştır."),
    ("1937 yılında İtalya'nın Habeşistan saldırısı üzerine Türkiye, İran, Irak ve Afganistan arasında Tahran'da imzalanan güvenlik paktı hangisidir?", "Sadabat Paktı", ["Balkan Antantı", "Bağdat Paktı", "Centrall Pakt", "Akdeniz Paktı"], "Türkiye doğu sınırını güvenceye almıştır."),
    ("Atatürk'ün 'Kırk asırlık Türk yurdu düşman elinde esir kalamaz' ve 'Şahsi meselemdir' dediği, 1939 yılında anavatana katılan toprak parçası neresidir?", "Hatay (Tayfur Sökmen Cumhurbaşkanı)", ["Musul", "Kerkük", "Batum", "Kıbrıs"], "1938'de Hatay Cumhuriyeti kurulmuş, 1939'da TBMM'ye katılmıştır."),
    ("Türkiye Cumhuriyeti'nin 1932 yılında dünya barışına katkı sağlamak amacıyla İspanya ve Yunanistan'ın davetiyle üye olduğu uluslararası teşkilat hangisidir?", "Milletler Cemiyeti (Cemiyet-i Akvam)", ["Birleşmiş Milletler", "NATO", "Avrupa Konseyi", "Varşova Paktı"], "Davet üzerine katılan tek devlettir."),
    ("1926 Ankara Antlaşması ile Musul ve Kerkük'ün İngiliz mandasındaki Irak'a bırakılmasına zemin hazırlayan içerideki gerici isyan hangisidir?", "Şeyh Sait İsyanı (1925)", ["Menemen Olayı", "İzmir Suikastı", "Bozkurt-Lotus Olayı", "Bursa Olayı"], "İsyan nedeniyle ordu meşgul olmuş, Musul masada kaybedilmiştir."),
    ("Fransız gemisi ile Türk gemisinin çarpışması sonucu doğan ve Lahey Adalet Divanı'nda Türk tezinin kabul edilmesiyle sonuçlanan uluslararası deniz hukuku zaferi hangisidir?", "Bozkurt-Lotus Olayı (Mahmut Esat Bozkurt)", ["Vagon-Li Olayı", "Razgrad Olayı", "Bursa Olayı", "Menemen Olayı"], "Kabotaj Kanunu'nun haklılığı tescil edilmiştir."),
    ("Türkiye Cumhuriyeti 1950 yılında hangi savaşa asker göndererek 1952 yılında NATO'ya (Kuzey Atlantik İttifakı) tam üye olmuştur?", "Kore Savaşı (Tugay Komutanı Tahsin Yazıcı)", ["Vietnam Savaşı", "Körfez Savaşı", "İkinci Dünya Savaşı", "Kıbrıs Barış Harekâtı"], "Kunayri Muharebesi'ndeki kahramanlıklarla NATO üyeliği onaylanmıştır."),
    ("1974 yılında Başbakan Bülent Ecevit ve Başbakan Yardımcısı Necmettin Erbakan liderliğinde 'Ayşe Tatile Çıksın' parolasıyla düzenlenen askeri harekât hangisidir?", "Kıbrıs Barış Harekâtı", ["Kore Harekâtı", "Fırat Kalkanı", "Zeytin Dalı", "Kandil Operasyonu"], "Kıbrıs Türklerinin can ve mal güvenliği sağlanmıştır; Rauf Denktaş ilk cumhurbaşkanı olmuştur."),
    ("1991 yılında Sovyetler Birliği'nin dağılmasıyla bağımsızlığını kazanan Türk cumhuriyetleri hangileridir?", "Azerbaycan, Kazakistan, Özbekistan, Türkmenistan, Kırgızistan", ["Tacikistan, Gürcistan, Ermenistan, Ukrayna", "Makedonya, Bosna, Kosova, Arnavutluk", "Kırım, Çeçenistan, Dağıstan, Tataristan", "Macaristan, Bulgaristan, Romanya, Moğolistan"], "Türkiye bu kardeş devletlerin bağımsızlığını ilk tanıyan devlettir.")
]
