# tarih_data_1.py - Q61 to Q69 (90 questions)

# Q61: İslamiyet Öncesi Türk Tarihi - Kurucular ve Hükümdarlar
q61_list = [
    ("Tarihte bilinen ilk Türk devleti olan Asya Hun Devleti'nin teşkilatlı kurucusu ve orduya 'onlu sistemi' kazandıran hükümdar kimdir?", "Mete Han", ["Teoman", "Bumin Kağan", "Attila", "İlteriş Kağan"], "Asya Hun Devleti'ne en parlak dönemini yaşatan ve MÖ 209'da onlu sistemi kuran Mete Han'dır."),
    ("I. Göktürk Devleti'nin kurucusu olan ve 'İl Kağan' unvanını alan hükümdar kimdir?", "Bumin Kağan", ["İstemi Yabgu", "Mukan Kağan", "Kutluk Kağan", "Bilge Kağan"], "Bumin Kağan, Avar hâkimiyetine son vererek Ötüken merkezli Göktürk Devleti'ni kurmuştur."),
    ("Çin esaretine son vererek II. Göktürk Devleti'ni kuran ve 'derleyen, toplayan' anlamına gelen 'İlteriş' unvanını alan hükümdar kimdir?", "Kutluk Kağan", ["Tonyukuk", "Kül Tigin", "Baga Tarkan", "Kapgan Kağan"], "Kutluk Kağan, 17 arkadaşıyla bağımsızlık mücadelesi başlatıp devleti yeniden kurduğu için İlteriş unvanını almıştır."),
    ("Uygur Devleti'nin kurucusu olan ve başkenti Ötüken'den Karabalgasun'a taşıyan ilk hükümdar kimdir?", "Kutluk Bilge Kül Kağan", ["Bögü Kağan", "Moyen-Çur", "Baga Tarkan", "Tapar Kağan"], "Uygurların kurucusu Kutluk Bilge Kül Kağan'dır."),
    ("Uygurların Maniheizm dinini resmi din olarak kabul ettiği dönemin hükümdarı kimdir?", "Bögü Kağan", ["Moyen-Çur", "Kutluk Bilge Kül Kağan", "Bilge Kağan", "Bumin Kağan"], "762 yılında Çin seferi sonrasında Mani dinini kabul eden hükümdar Bögü Kağan'dır."),
    ("Avrupa Hun Devleti'ne en parlak dönemini yaşatan, 'Tanrının Kırbacı' olarak anılan ve Margos Barışı'nı imzalayan hükümdar kimdir?", "Attila", ["Balamir", "Uldız", "Rua", "Dengizik"], "Doğu ve Batı Roma'yı vergiye bağlayan büyük Avrupa Hun hükümdarı Attila'dır."),
    ("Avar Devleti'nin en güçlü hükümdarı olan ve Sasanilerle iş birliği yaparak İstanbul'u kuşatan ilk Türk hükümdarı kimdir?", "Bayan Han", ["Teoman", "Kutluk Kağan", "Mete Han", "İlteriş"], "Avarlar, Bayan Han liderliğinde 619 ve 626 yıllarında İstanbul'u kuşatmıştır."),
    ("Kendi adına para bastıran ilk Türk hükümdarı olan Türgiş hükümdarı kimdir?", "Baga Tarkan", ["Sulu Kağan", "Bumin Kağan", "Mukan Kağan", "İstemi Yabgu"], "Türgiş hükümdarı Baga Tarkan kendi adına madeni para (yarmak) bastırmıştır."),
    ("Musevilik dinini kabul eden tek Türk devleti olan Hazarların başında bulunan hükümdarlara ne ad verilirdi?", "Hakan / Kagan", ["Tarkan", "Tigin", "Ayguçı", "İnanç"], "Hazarlar da diğer Türk devletleri gibi hakanlar tarafından yönetilmiştir."),
    ("İslamiyeti kabul eden ilk Türk topluluğu (boyu) aşağıdakilerden hangisidir?", "Karluklar", ["Oğuzlar", "Peçenekler", "Kıpçaklar", "Kırgızlar"], "751 Talas Savaşı'nda Müslüman Arapların yanında yer alan Karluklar, İslamiyeti kabul eden ilk Türk boyudur.")
]

# Q62: İslamiyet Öncesi Kültür ve Medeniyet
q62_list = [
    ("İslamiyet öncesi Türk devletlerinde hükümdara devleti yönetme yetkisinin Tanrı tarafından verildiğine inanılan anlayışa ne ad verilir?", "Kut anlayışı", ["Töre", "Kurultay", "Yarlıg", "Balbal"], "Kut, Gök Tanrı tarafından hükümdara verildiğine inanılan siyasi iktidar ve yönetme gücüdür."),
    ("İslamiyet öncesi Türk devletlerinde devlet işlerinin görüşülüp karara bağlandığı meclise ne ad verilirdi?", "Kurultay (Toy)", ["Divan", "Hükümet", "Ayguçı", "Toygun"], "Devlet işlerinin görüşüldüğü danışma meclisine Kurultay veya Toy denirdi."),
    ("İslamiyet öncesi Türklerde sözlü hukuk kurallarına ve toplumsal düzeni sağlayan geleneklere ne ad verilirdi?", "Töre", ["Kut", "Yargu", "Tigin", "Toy"], "Töre; hükümdarın da uymak zorunda olduğu yazısız örfi hukuk kurallarıdır."),
    ("Türk tarihinin ve edebiyatının ilk yazılı belgeleri kabul edilen Orhun (Göktürk) Yazıtları hangi kağan ve devlet adamları adına dikilmiştir?", "Bilge Kağan, Kül Tigin, Vezir Tonyukuk", ["Bumin Kağan, İstemi Yabgu", "Mete Han, Teoman", "Attila, Balamir", "Bögü Kağan, Moyen-Çur"], "Yazıtlar II. Göktürk Dönemi'nde Bilge Kağan, Kül Tigin ve Tonyukuk adına dikilmiştir."),
    ("İslamiyet öncesi Türklerde ölen kahramanların mezarlarının başına hayattayken öldürdüğü düşman sayısı kadar dikilen taşlara ne ad verilirdi?", "Balbal", ["Kurgan", "Yuğ", "Kurultay", "Otağ"], "Mezar taşı niteliğindeki küçük yontma taş heykellere balbal adı verilirdi."),
    ("Eski Türklerde ölen kişinin ardından düzenlenen cenaze törenine ve okunan ağıtlara sırasıyla ne ad verilir?", "Yuğ - Sagu", ["Kurgan - Koşuk", "Toy - Sav", "Balbal - Destan", "Kurultay - Yazıt"], "Cenaze törenine 'yuğ', yakılan ağıta ise 'sagu' denirdi."),
    ("İslamiyet öncesi Türk devletlerinde hükümdarın erkek çocuklarına verilen unvan aşağıdakilerden hangisidir?", "Tigin", ["Ayguçı", "İnanç", "Ataman", "Şad"], "Hükümdar çocuklarına tigin denir, onların eğitiminden sorumlu kişiye ataman veya inanç denirdi."),
    ("Eski Türklerde devletin Doğu-Batı şeklinde iki koldan yönetilmesi esasına dayanan idari sisteme ne ad verilir?", "İkili teşkilat", ["Onlu sistem", "Töre sistemi", "Federal meclis", "Kut sistemi"], "Doğuda asıl kağan, batıda ise hanedandan bir prens (genellikle Yabgu) bulunurdu."),
    ("Uygurların Türk kültür ve medeniyetine getirdiği EN ÖNEMLİ yenilik aşağıdakilerden hangisidir?", "Yerleşik hayata geçerek mimari ve matbaa faaliyetleri başlatmaları", ["İlk kez ordu kurmaları", "Atı ilk kez evcilleştirmeleri", "Demiri ilk kez işlemeleri", "İlk Türk meclisini açmaları"], "Uygurlar Maniheizm etkisiyle yerleşik hayata geçmiş, şehirler, tapınaklar ve kütüphaneler kurmuştur."),
    ("İslamiyet öncesi Türklerde 'hükümet başkanına (başbakana)' verilen unvan hangisidir?", "Ayguçı", ["Buyruk", "Tudun", "Bitikçi", "Yabgu"], "Eski Türklerde vezir veya hükümet başkanına Ayguçı adı verilirdi.")
]

# Q63: Diğer Türk Devletleri ve Boyları
q63_list = [
    ("Bizans ordusunda ücretli askerlik yaparken 1071 Malazgirt Savaşı'nda Selçuklu tarafına geçerek savaşın kazanılmasında rol oynayan Türk topluluğu hangisidir?", "Peçenekler", ["Avarlar", "Hazarlar", "Kırgızlar", "Akhunlar"], "Peçenekler ve Uzlar Malazgirt'te Selçuklu tarafına geçmiştir."),
    ("Doğu Avrupa'da Hristiyanlığı kabul eden, Rus knezliklerinin Karadeniz'e inmesini engelleyen ve 'Codex Cumanicus' adlı sözlüğü bırakan Türk topluluğu hangisidir?", "Kıpçaklar (Kumanlar)", ["Peçenekler", "Uygurlar", "Hazarlar", "Bulgarlar"], "Kıpçakların İtalyan ve Alman misyonerlerle hazırladığı sözlük Codex Cumanicus'tur."),
    ("Tarihte kurulan ilk Türk devleti olmamakla birlikte Kafkaslar ve Karadeniz'in kuzeyinde 'Hazar Barış Çağı'nı (Pax Hazarica) yaşatan devlet hangisidir?", "Hazarlar", ["Avarlar", "Bulgarlar", "Macarlar", "Kırgızlar"], "Ticareti geliştiren, dini hoşgörüsü yüksek Hazarlar bu dönemi yaşatmıştır."),
    ("Dünyanın en uzun destanı kabul edilen Manas Destanı hangi Türk boyuna aittir?", "Kırgızlar", ["Uygurlar", "Kazaklar", "Özbekler", "Türkmenler"], "Manas Destanı Kırgızlara ait olup hâlen yaşayan canlı bir destandır."),
    ("İslam ordularının (Hz. Osman dönemi) Kafkaslara ve Hazar havzasına girişini engelleyen Türk devleti hangisidir?", "Hazarlar", ["Avarlar", "Göktürkler", "Türgişler", "Hunlar"], "Belenhar Savaşı'nda Hz. Osman ordularını durduran Hazarlardır."),
    ("Emevi ordularının Orta Asya'ya girişini engelleyen ve Müslümanlarla savaşan Türk devleti hangisidir?", "Türgişler", ["Hazarlar", "Karluklar", "Uygurlar", "Akhunlar"], "Sulu Kağan liderliğindeki Türgişler Emevileri durdurarak Orta Asya'nın Araplaşmasını engellemiştir."),
    ("Tuna Bulgar Devleti'nin Hristiyanlığı kabul ederek Slavlaştığı dönemin hükümdarı kimdir?", "Boris Han", ["Asparuh", "Kurum Han", "Almış Han", "Simbir"], "Tuna Bulgarları Boris Han zamanında Hristiyanlığı seçerek Türklük özelliklerini kaybetmiştir."),
    ("İslamiyeti resmi din olarak kabul eden ilk Türk devleti olan İtil (Volga) Bulgar Devleti'nin hükümdarı kimdir?", "Almış Han", ["Boris Han", "Asparuh", "Bayan Han", "Teoman"], "İtil Bulgarları Almış Han zamanında Abbasilerden heyet isteyerek İslamiyeti kabul etmiştir."),
    ("Cengiz Han liderliğindeki Moğol İmparatorluğu'na itaat eden ilk Müslüman Türk topluluğu hangisidir?", "Karluklar", ["Kırgızlar", "Uygurlar", "Oğuzlar", "Harezmşahlar"], "Karluklar Moğollara bağlanan ilk Müslüman Türk boyudur (ilk Türk topluluğu ise Kırgızlardır)."),
    ("Hristiyanlığı kabul ederek Avrupa'da kurulan ve ilk Türk-Macar akrabalığını başlatan devlet hangisidir?", "Macarlar", ["Avarlar", "Bulgarlar", "Peçenekler", "Hazarlar"], "Macarlar Arpad liderliğinde Hristiyanlığı kabul edip asimile olmuşlardır.")
]

# Q64: İlk Türk-İslam Devletleri Siyasi Tarih
q64_list = [
    ("Orta Asya'da kurulan ilk Müslüman Türk devleti olan ve Satuk Buğra Han (Abdülkerim) zamanında İslamiyeti kabul eden devlet hangisidir?", "Karahanlılar", ["Gazneliler", "Büyük Selçuklular", "Tolunoğulları", "İhşidiler"], "Karahanlılar 840-1212 yılları arasında Orta Asya'da hüküm sürmüş ilk Müslüman Türk devletidir."),
    ("Hindistan'a 17 sefer düzenleyerek İslamiyetin Hindistan coğrafyasında yayılmasını sağlayan ve Sultan unvanını kullanan ilk Türk hükümdarı kimdir?", "Gazneli Mahmud", ["Alparslan", "Tuğrul Bey", "Melikşah", "Satuk Buğra Han"], "Gazneli Mahmud Abbasi halifesini korumuş ve Sultan unvanını alan ilk hükümdar olmuştur."),
    ("1040 yılında Selçuklular ile Gazneliler arasında yapılan ve Gaznelilerin yıkılış sürecine, Büyük Selçuklu Devleti'nin ise resmen kurulmasına yol açan savaş hangisidir?", "Dandanakan Savaşı", ["Pasinler Savaşı", "Malazgirt Savaşı", "Katvan Savaşı", "Nesa Savaşı"], "Dandanakan Savaşı Büyük Selçuklu Devleti'nin kuruluşunu tescillemiştir."),
    ("1048 yılında Büyük Selçuklu Devleti ile Bizans arasında yapılan İLK BÜYÜK meydan savaşı hangisidir?", "Pasinler Savaşı", ["Malazgirt Savaşı", "Dandanakan Savaşı", "Miryokefalon Savaşı", "Yassıçemen Savaşı"], "Tuğrul Bey döneminde İbrahim Yinal komutasında Bizans mağlup edilmiştir."),
    ("26 Ağustos 1071 tarihinde Sultan Alparslan komutasındaki Selçuklu ordusunun Bizans'ı yenerek Anadolu'nun kapılarını Türklere açtığı tarihi zafer hangisidir?", "Malazgirt Zaferi", ["Pasinler Savaşı", "Miryokefalon Savaşı", "Dandanakan Savaşı", "Kösedağ Savaşı"], "Malazgirt ile Anadolu'nun fethi süreci resmen başlamıştır."),
    ("Büyük Selçuklu Devleti'ne en parlak dönemini yaşatan, sınırları Seyhun'dan Akdeniz'e kadar genişleten hükümdar kimdir?", "Melikşah", ["Alparslan", "Tuğrul Bey", "Sultan Sencer", "Berkyaruk"], "Melikşah ve veziri Nizamülmülk dönemi Selçukluların zirve dönemidir."),
    ("Büyük Selçuklu Devleti'nin 'Son Büyük Sultanı' kabul edilen ve 1141 Katvan Savaşı'nda Karahitaylara yenilen hükümdar kimdir?", "Sultan Sencer", ["Melikşah", "Alparslan", "Tuğrul Bey", "Mahmud"], "Sultan Sencer'in ölümüyle Büyük Selçuklu Devleti dağılmıştır."),
    ("Mısır'da kurulan İLK Türk-İslam devleti aşağıdakilerden hangisidir?", "Tolunoğulları", ["İhşidiler (Akşitler)", "Eyyubiler", "Memlükler", "Fatımiler"], "868 yılında Tolunoğlu Ahmet tarafından Mısır'da kurulan ilk devlettir."),
    ("Hicaz bölgesine (Mekke ve Medine) hâkim olan İLK Türk devleti hangisidir?", "İhşidiler (Akşitler)", ["Tolunoğulları", "Memlükler", "Eyyubiler", "Osmanlılar"], "Muhammed bin Togaç (Akşit) tarafından kurulan İhşidiler Hicaz'a hâkim ilk Türk devletidir."),
    ("1187 Hıttin Savaşı ile Kudüs'ü Haçlıların elinden geri alarak III. Haçlı Seferi'ne neden olan Müslüman komutan kimdir?", "Selahaddin Eyyubi", ["Baybars", "Nureddin Zengi", "Alparslan", "Kutuz"], "Selahaddin Eyyubi Kudüs fatihi olarak İslam dünyasının en saygın liderlerindendir.")
]

# Q65: İlk Türk-İslam Kültür ve Medeniyeti - Eserler ve Bilim
q65_list = [
    ("Yusuf Has Hacib tarafından Karahanlı hükümdarı Tamgaç Buğra Han'a sunulan, 'Mutluluk Veren Bilgi' anlamına gelen ilk Türk-İslam siyasetnamesi hangisidir?", "Kutadgu Bilig", ["Divanü Lugati't-Türk", "Atabetü'l-Hakayık", "Divan-ı Hikmet", "Şehname"], "Kutadgu Bilig edebiyatımızın ilk siyasetnamesi ve ilk mesnevisidir."),
    ("Kaşgarlı Mahmud tarafından Abbasi halifesine sunulan, ilk Türkçe sözlük ve ilk Türk dünyası haritasını içeren eser hangisidir?", "Divanü Lugati't-Türk", ["Kutadgu Bilig", "Atabetü'l-Hakayık", "Divan-ı Hikmet", "Muhakemetü'l-Lugateyn"], "Araplara Türkçeyi öğretmek amacıyla yazılmış ansiklopedik sözlüktür."),
    ("Edip Ahmet Yükneki tarafından kaleme alınan ve 'Hakikatlerin Eşiği' anlamına gelen ahlak ve öğüt kitabı hangisidir?", "Atabetü'l-Hakayık", ["Kutadgu Bilig", "Divan-ı Hikmet", "Risaletü'n-Nushiyye", "Makalat"], "Atabetü'l-Hakayık didaktik bir ahlak kitabıdır."),
    ("Hoca Ahmet Yesevi'nin dervişlerine tasavvufu ve İslam ahlakını öğretmek için hece ölçüsüyle yazdığı şiirleri toplayan eser hangisidir?", "Divan-ı Hikmet", ["Kutadgu Bilig", "Divanü Lugati't-Türk", "Mesnevi", "Garibname"], "İlk Türk mutasavvıfı Ahmet Yesevi'nin eseri Divan-ı Hikmet'tir."),
    ("Avrupa'da 'Alpharabius' olarak bilinen, Birleşmiş Milletler fikrini ilk ortaya atan ve 'Muallim-i Sani' (İkinci Öğretmen) unvanını alan Türk-İslam filozofu kimdir?", "Farabi", ["İbn-i Sina", "Biruni", "Gazali", "Harezmi"], "Aristo'dan sonra ikinci öğretmen kabul edilen felsefeci Farabi'dir."),
    ("Tıp alanında yazdığı 'El-Kanun fi't-Tıbb' (Tıbbın Kanunu) adlı eseri yüzyıllarca Avrupa üniversitelerinde ders kitabı olarak okutulan, Batı'da 'Avicenna' olarak tanınan hekim kimdir?", "İbn-i Sina", ["Farabi", "Razi", "İbn-i Rüşd", "Cezeri"], "Tıbbın üstadı İbn-i Sina Avicenna adıyla bilinir."),
    ("Gazneli Mahmud'un 'Sarayımın en değerli hazinesi' dediği, dünyanın çapını ve yarıçapını gerçeğe çok yakın hesaplayan büyük bilgin kimdir?", "Biruni", ["Farabi", "İbn-i Sina", "Uluğ Bey", "Harezmi"], "Matematik, coğrafya ve astronomi dehası Biruni'dir."),
    ("Cebir biliminin kurucusu kabul edilen, '0' (sıfır) rakamını ve 'X' bilinmeyenini matematiğe kazandıran İslam bilgini kimdir?", "Harezmi", ["Ömer Hayyam", "Ali Kuşçu", "Biruni", "Farabi"], "Cebir kitabının yazarı ve algoritmanın isim babası Harezmi'dir."),
    ("Büyük Selçuklu Veziri Nizamülmülk tarafından Bağdat'ta kurulan ve dönemin ilk modern üniversitesi kabul edilen medreseler hangisidir?", "Nizamiye Medreseleri", ["Sahn-ı Seman", "Gökmedrese", "Yağıbasan Medresesi", "Cacabey Medresesi"], "Bâtınilik faaliyetleriyle mücadele için kurulan medreseler Nizamiye Medreseleridir."),
    ("Celali Takvimi'ni hazırlayan, Melikşah'a sunan ve rubaileriyle dünya edebiyatında tanınan Selçuklu bilgini kimdir?", "Ömer Hayyam", ["Nizamülmülk", "Enveri", "Kaşgarlı Mahmud", "Zemahşeri"], "Gökbilimci ve şair Ömer Hayyam Güneş yılı esaslı Celali Takvimi'ni yapmıştır.")
]

# Q66: Anadolu Selçuklu Devleti
q66_list = [
    ("1176 yılında II. Kılıçarslan komutasındaki Selçuklu ordusunun Bizans'ı mağlup ederek Anadolu'nun kesin Türk yurdu olduğunu tescillediği zafer hangisidir?", "Miryokefalon Savaşı", ["Malazgirt Savaşı", "Pasinler Savaşı", "Kösedağ Savaşı", "Yassıçemen Savaşı"], "Miryokefalon ile Bizans'ın Türkleri Anadolu'dan atma ümidi tamamen tükenmiştir."),
    ("Anadolu Selçuklu Devleti'nin kurucusu olan ve devleti İznik merkezli olarak teşkilatlandıran hükümdar kimdir?", "Kutalmışoğlu Süleyman Şah", ["I. Kılıçarslan", "I. Mesut", "II. Kılıçarslan", "Melikşah"], "Devletin temellerini 1077'de atan Süleyman Şah'tır."),
    ("I. Haçlı Seferi sonucunda başkent İznik kaybedilince Anadolu Selçuklu Devleti'nin başkenti nereye taşınmıştır?", "Konya", ["Sivas", "Kayseri", "Antalya", "Alanya"], "I. Kılıçarslan başkenti Konya'ya taşımıştır."),
    ("Anadolu Selçuklu Devleti'nde ilk altın parayı bastıran ve ülkeyi 11 oğlu arasında paylaştıran hükümdar kimdir?", "II. Kılıçarslan", ["I. Mesut", "Alâeddin Keykubad", "I. Gıyaseddin Keyhüsrev", "Süleyman Şah"], "II. Kılıçarslan ekonomik ve askeri olarak devleti zirveye taşımıştır."),
    ("Anadolu Selçuklu Devleti'ne en parlak dönemini yaşatan, Sinop ve Alanya'yı fethedip Kırım'daki Sudak Limanı'na deniz aşırı sefer düzenleyen hükümdar kimdir?", "I. Alâeddin Keykubad", ["II. Kılıçarslan", "I. İzzettin Keykavus", "Gıyaseddin Keyhüsrev", "Rükneddin Süleyman"], "Alâeddin Keykubad dönemi Anadolu Selçuklularının zirve dönemidir."),
    ("1243 yılında Moğollar (İlhanlılar) ile Anadolu Selçuklu Devleti arasında yapılan ve Selçukluların yıkılış sürecine girmesine neden olan savaş hangisidir?", "Kösedağ Savaşı", ["Miryokefalon Savaşı", "Yassıçemen Savaşı", "Katvan Savaşı", "Ayn Calut Savaşı"], "Kösedağ mağlubiyetiyle Anadolu Selçukluları Moğol hâkimiyetine girmiş ve II. Beylikler Dönemi başlamıştır."),
    ("Anadolu Selçuklu tarihinde devleti derinden sarsan ve merkezi otoriteyi zayıflatan ilk büyük sosyo-dini nitelikli isyan hangisidir?", "Baba İshak İsyanı", ["Şeyh Bedrettin İsyanı", "Celali İsyanları", "Şahkulu İsyanı", "Patrona Halil İsyanı"], "1240'ta patlak veren bu isyan Kösedağ yenilgisine zemin hazırlamıştır."),
    ("Anadolu Selçuklularında kervansaraylarda kalan tüccarların mallarının zarar görmesi durumunda zararını karşılayan dünyadaki ilk sigortacılık sistemini kim kurmuştur?", "Anadolu Selçuklu Devleti", ["Bizans İmparatorluğu", "Venedikliler", "Cenevizliler", "Memlükler"], "Ticareti teşvik etmek amacıyla devlet sigortası uygulanmıştır."),
    ("Anadolu'da kurulan ilk Türk donanması ve ilk tersane hangi Selçuklu hükümdarı zamanında Sinop ve Alanya'da inşa edilmiştir?", "I. İzzettin Keykavus ve Alâeddin Keykubad", ["II. Kılıçarslan", "Süleyman Şah", "I. Kılıçarslan", "I. Mesut"], "Akdeniz ve Karadeniz'de tersaneler kurularak donanma teşkilatı oluşturulmuştur."),
    ("1230 yılında Anadolu Selçukluları ile Harezmşahlar arasında yapılan ve Harezmşahların yıkılmasına yol açan savaş hangisidir?", "Yassıçemen Savaşı", ["Kösedağ Savaşı", "Miryokefalon Savaşı", "Dandanakan Savaşı", "Katvan Savaşı"], "Bu savaş tampon bölgeyi yok ederek Moğolların Anadolu kapılarına dayanmasına yol açmıştır.")
]

# Q67: I. ve II. Anadolu Beylikleri
q67_list = [
    ("1071 Malazgirt Savaşı'ndan sonra Anadolu'da kurulan İLK Türk beyliği ve Erzurum merkezli Saltukluların kurucusu kimdir?", "Ebulkasım Saltuk Bey", ["Danişment Gazi", "Mengücek Gazi", "Artuk Bey", "Çaka Bey"], "Saltuklular Anadolu'da kurulan ilk Türk beyliğidir."),
    ("Tarihte İLK Türk denizcisi kabul edilen ve 1081 yılında İzmir'de ilk Türk donanmasını kuran beylik hükümdarı kimdir?", "Çaka Bey", ["Umur Bey", "Karesi Bey", "Saruhan Bey", "Barbaros Hayrettin"], "1081 yılı Türk Deniz Kuvvetleri'nin kuruluş yılı kabul edilir."),
    ("Anadolu'da kurulan ilk medrese olan Tokat Niksar'daki 'Yağıbasan Medresesi' hangi beylik tarafından yapılmıştır?", "Danişmentliler", ["Saltuklular", "Mengücekliler", "Artuklular", "Karamanoğulları"], "Yağıbasan Medresesi Anadolu'daki ilk tıp ve eğitim medresesidir."),
    ("UNESCO Dünya Kültür Mirası Listesi'nde yer alan muhteşem taş işçiliğine sahip Divriği Ulu Camii ve Darüşşifası hangi beylik döneminde inşa edilmiştir?", "Mengücekliler", ["Artuklular", "Danişmentliler", "Saltuklular", "Eretna Devleti"], "Sivas Divriği'deki eser Mengüceklilere aittir."),
    ("Diyarbakır, Mardin ve Batman çevresinde hüküm süren, Malabadi Köprüsü'nü inşa eden ve ünlü bilim insanı El-Cezeri'yi himaye eden beylik hangisidir?", "Artuklular", ["Danişmentliler", "Saltuklular", "Mengücekliler", "Akkoyunlular"], "Mardin Artukluları dönemi bilim ve mimaride parlak bir çağdır."),
    ("Kendilerini Anadolu Selçuklu Devleti'nin tek meşru mirasçısı olarak gören ve Osmanlı Devleti'ni en çok uğraştıran II. dönem Anadolu beyliği hangisidir?", "Karamanoğulları", ["Germiyanoğulları", "Karesioğulları", "Candaroğulları", "Dulkadiroğulları"], "Karamanoğlu Mehmet Bey Türkçeyi ilk kez resmi devlet dili ilan etmiştir."),
    ("Osmanlı Devleti'ne katılan İLK Anadolu beyliği olup Osmanlı'nın donanma sahibi olmasını sağlayan beylik hangisidir?", "Karesioğulları", ["Saruhanoğulları", "Aydınoğulları", "Menteşeoğulları", "Germiyanoğulları"], "Orhan Bey döneminde katılmış, Hacı İlbey ve Evrenos Bey gibi komutanlar Osmanlı'ya geçmiştir."),
    ("Osmanlı Devleti'ne çeyiz ve vasiyet yoluyla katılan Kütahya merkezli beylik hangisidir?", "Germiyanoğulları", ["Hamitoğulları", "Karamanoğulları", "Aydınoğulları", "Eşrefoğulları"], "I. Murat zamanında topraklarının bir kısmı çeyizle, II. Murat zamanında tamamı vasiyetle katılmıştır."),
    ("Topraklarının bir kısmını para karşılığında (80 bin altın) Osmanlı Devleti'ne satan Isparta-Antalya merkezli beylik hangisidir?", "Hamitoğulları", ["Germiyanoğulları", "Karesioğulları", "Saruhanoğulları", "Menteşeoğulları"], "I. Murat döneminde toprakları satın alınmıştır."),
    ("1515 Turnadağ Savaşı ile Osmanlı topraklarına katılarak Anadolu Türk siyasi birliğinin KESİN olarak sağlandığı son beylik hangisidir?", "Dulkadiroğulları", ["Ramazanoğulları", "Karamanoğulları", "Candaroğulları", "Germiyanoğulları"], "Yavuz Sultan Selim Maraş merkezli Dulkadiroğulları Beyliği'ne son vermiştir.")
]

# Q68: Osmanlı Kuruluş Dönemi
q68_list = [
    ("1302 yılında Osman Bey komutasındaki Osmanlı kuvvetleri ile Bizans tekfurları arasında yapılan ve Osmanlı'nın İLK resmi savaşı kabul edilen muharebe hangisidir?", "Koyunhisar (Bafeus) Savaşı", ["Maltepe (Pelekanon) Savaşı", "Sırpsındığı Savaşı", "I. Kosova Savaşı", "Çirmen Savaşı"], "Halil İnalcık'a göre Osmanlı Devleti'nin gerçek kuruluş tarihi bu zaferle başlar."),
    ("Bursa'yı fethederek başkent yapan ve ilk Osmanlı gümüş akçesini bastıran hükümdar kimdir?", "Orhan Bey", ["Osman Bey", "I. Murat", "Yıldırım Bayezid", "Çelebi Mehmet"], "Bursa 1326 yılında Orhan Bey tarafından fethedilmiştir."),
    ("Bizans'a yapılan yardım karşılığında alınan ve Osmanlı Devleti'nin Rumeli'deki İLK toprak parçası olan kale hangisidir?", "Çimpe Kalesi", ["Gelibolu Kalesi", "Edirne Kalesi", "Kilitbahir Kalesi", "Seddülbahir Kalesi"], "1353'te Çimpe Kalesi'nin alınmasıyla Rumeli fetihleri başlamıştır."),
    ("Haçlılar ile Osmanlı Devleti arasında yapılan İLK meydan savaşı hangisidir?", "Sırpsındığı Savaşı", ["I. Kosova Savaşı", "Niğbolu Savaşı", "Varna Savaşı", "II. Kosova Savaşı"], "1364 yılında I. Murat döneminde Hacı İlbey komutasında kazanılmıştır."),
    ("İlk kez topun kullanıldığı ve savaş meydanını gezerken bir Sırp askeri tarafından şehit edilen I. Murat'ın zafer kazandığı savaş hangisidir?", "I. Kosova Savaşı", ["II. Kosova Savaşı", "Niğbolu Savaşı", "Sırpsındığı Savaşı", "Varna Savaşı"], "1389'da I. Murat zafer sonrası şehit düşmüştür."),
    ("1396 yılında Haçlı ordusunu büyük bir hezimete uğratarak Abbasi halifesi tarafından kendisine 'Sultan-ı İklim-i Rum' unvanı verilen Osmanlı padişahı kimdir?", "Yıldırım Bayezid", ["I. Murat", "Fatih Sultan Mehmet", "Orhan Bey", "II. Murat"], "Niğbolu Zaferi sonrası bu şerefli unvan verilmiştir."),
    ("1402 Ankara Savaşı'nda Timur'a esir düşen Yıldırım Bayezid'in ardından Osmanlı'da 11 yıl süren ve 'Fetret Devri' olarak adlandırılan döneme son vererek devleti yeniden toparlayan 'İkinci Kurucu' kimdir?", "Çelebi Mehmet (I. Mehmet)", ["II. Murat", "Fatih Sultan Mehmet", "Süleyman Çelebi", "Musa Çelebi"], "Kardeşleriyle taht mücadelesini kazanıp birliği sağlamıştır."),
    ("Osmanlı tarihinde ilk dini ve sosyal nitelikli isyan kabul edilen hareket hangisidir?", "Şeyh Bedrettin İsyanı", ["Baba İshak İsyanı", "Celali İsyanları", "Şahkulu İsyanı", "Buçuktepe İsyanı"], "Çelebi Mehmet döneminde bastırılan isyandır."),
    ("1444 yılında II. Murat komutasındaki Osmanlı ordusunun Haçlıları mağlup ettiği tarihi savaş hangisidir?", "Varna Savaşı", ["II. Kosova Savaşı", "Niğbolu Savaşı", "Sırpsındığı Savaşı", "I. Kosova Savaşı"], "Genç şehzade II. Mehmet'in tahtı babasına devretmesiyle kazanılan zaferdir."),
    ("1448 yılında II. Murat'ın Haçlıları ikinci kez yenerek Avrupalıların Türkleri Balkanlardan atma ümidini kesin olarak bitirdiği savaş hangisidir?", "II. Kosova Savaşı", ["Varna Savaşı", "I. Kosova Savaşı", "Niğbolu Savaşı", "Mohaç Meydan Muharebesi"], "Balkanların kesin Türk yurdu olduğu kanıtlanmıştır.")
]

# Q69: Osmanlı Yükselme Dönemi - Fatih ve II. Bayezid
q69_list = [
    ("29 Mayıs 1453 tarihinde İstanbul'u fethederek Orta Çağ'ı kapatıp Yeni Çağ'ı açan ve 'Fatih' unvanını alan padişah kimdir?", "II. Mehmet (Fatih Sultan Mehmet)", ["II. Bayezid", "Yavuz Sultan Selim", "Kanuni Sultan Süleyman", "I. Murat"], "İstanbul fethi dünya tarihini değiştiren evrensel bir olaydır."),
    ("1475 yılında Gedik Ahmet Paşa tarafından fethedilerek Karadeniz'in bir 'Türk Gölü' haline gelmesini sağlayan stratejik yarımada neresidir?", "Kırım", ["Mora", "Girit", "Kıbrıs", "Rodos"], "Kırım'ın fethiyle Karadeniz ticareti tamamen Osmanlı kontrolüne geçmiştir."),
    ("1473 yılında Fatih Sultan Mehmet ile Akkoyunlu hükümdarı Uzun Hasan arasında yapılan ve Akkoyunluların yıkılış sürecini başlatan savaş hangisidir?", "Otlukbeli Savaşı", ["Çaldıran Savaşı", "Turnadağ Savaşı", "Mercidabık Savaşı", "Mohaç Savaşı"], "Doğu Anadolu'nun güvenliği sağlanmıştır."),
    ("Fatih Sultan Mehmet tarafından hazırlanan, devletin bekası için kardeş katline cevaz veren ve divana sadrazamların başkanlık etmesini öngören ilk Osmanlı yazılı kanunnamesi hangisidir?", "Kanunname-i Âli Osman", ["Mecelle", "Sened-i İttifak", "Tanzimat Fermanı", "Kanun-i Esasi"], "Merkeziyetçi mutlak otoriteyi zirveye taşıyan kanundur."),
    ("İstanbul'un fethinde Bizans'a denizden gelecek yardımları önlemek amacıyla Boğaz'ın en dar yerine Fatih tarafından yaptırılan hisar hangisidir?", "Rumeli Hisarı (Boğazkesen)", ["Anadolu Hisarı (Güzelcehisar)", "Seddülbahir Kalesi", "Kilitbahir Kalesi", "Yedikule Zindanları"], "Yıldırım'ın yaptırdığı Anadolu Hisarı'nın tam karşısına inşa edilmiştir."),
    ("Fatih Sultan Mehmet'in fethettiği yerlerdeki gayrimüslim halka can, mal ve din özgürlüğü tanıdığını bildiren ünlü belgesi (Ahidname) hangi bölge halkına verilmiştir?", "Bosna Fransisken Rahipleri", ["Atina Halkı", "Mora Rumları", "Trabzon Komnenosları", "Kırım Tatarları"], "İnsan hakları ve inanç hürriyetinin erken bir anıtıdır."),
    ("II. Bayezid döneminde taht kavgası başlatarak Rodos Şövalyelerine ve Papalığa sığınan, iç sorunken uluslararası bir dış sorun haline gelen şehzade kimdir?", "Cem Sultan", ["Şehzade Mustafa", "Şehzade Bayezid", "Şehzade Korkut", "Şehzade Ahmet"], "Cem Sultan Olayı nedeniyle fetihler duraklamış, II. Bayezid dönemi 'Yükselme içinde duraklama' olmuştur."),
    ("1511 yılında Safevilerin kışkırtmasıyla Antalya ve Teke yöresinde II. Bayezid'e karşı çıkan büyük Şii isyanı hangisidir?", "Şahkulu İsyanı", ["Şeyh Bedrettin İsyanı", "Celali İsyanları", "Babai İsyanı", "Canberdi Gazali İsyanı"], "Bu isyan Yavuz'un babasını tahttan indirmesine zemin hazırlamıştır."),
    ("1492 yılında İspanya'daki Engizisyon zulmünden kaçan Musevileri (Sefarad Yahudileri) Osmanlı topraklarına kabul eden padişah kimdir?", "II. Bayezid", ["Fatih Sultan Mehmet", "Yavuz Sultan Selim", "Kanuni Sultan Süleyman", "II. Murat"], "Kemal Reis komutasındaki gemilerle Osmanlı'ya getirilmişlerdir."),
    ("Fatih döneminde Semerkant'tan İstanbul'a davet edilen, Ayasofya Medresesi başmüderrisliği yapan ünlü astronom ve matematikçi kimdir?", "Ali Kuşçu", ["Kadızade-i Rumi", "Uluğ Bey", "Takiyüddin", "Mirim Çelebi"], "Ali Kuşçu Osmanlı'da matematik ve astronomi ekolünü kurmuştur.")
]
