# turkce_data_1.py - Q1 to Q10
deyimler = [
    ("göz boyamak", "Gösterişle aldatmak, iyi gibi göstermek", "Tüccar vitrine kaliteli kumaşları koyarak müşterilerin <u>gözünü boyamaya</u> çalıştı."),
    ("ayaklarına kara sular inmek", "Çok yürümekten veya ayakta kalmaktan aşırı yorulmak", "Tüm gün resmi dairelerde evrak peşinde koşmaktan <u>ayaklarına kara sular inmişti</u>."),
    ("pabucu dama atılmak", "Kendinden üstün birinin gelmesiyle gözden düşmek, değerini yitirmek", "Yeni model telefon piyasaya sürülünce bir önceki modelin <u>pabucu dama atıldı</u>."),
    ("kılı kırk yarmak", "Aşırı titiz, titizlikle ve en ince ayrıntısına kadar incelemek", "Sayıştay denetçisi belediye harcamalarını incelerken adeta <u>kılı kırk yarıyordu</u>."),
    ("çantada keklik", "Zahmetsizce ve kesinlikle elde edilecek gözüyle bakılan durum", "Rakibini <u>çantada keklik</u> gören futbol takımı, beklemediği bir mağlubiyet aldı."),
    ("küplere binmek", "Aşırı derecede öfkelenmek, çok sinirlenmek", "Hazırladığı raporun silindiğini öğrenen müdür <u>küplere bindi</u>."),
    ("can kulağıyla dinlemek", "Büyük bir dikkat ve ilgiyle dinlemek", "Öğrenciler tecrübeli hocanın sınav tüyolarını <u>can kulağıyla dinledi</u>."),
    ("içi içine sığmamak", "Aşırı sevinç, heyecan veya sabırsızlık duymak", "Atama listesinde adını görünce sevinçten <u>içi içine sığmıyordu</u>."),
    ("eli ayağı dolaşmak", "Heyecandan veya panikten ne yapacağını şaşırmak", "Mülakat salonuna çağrılınca heyecandan <u>eli ayağı dolaştı</u>."),
    ("burun kıvırmak", "Küçümsemek, beğenmemek, değer vermemek", "Kendisine sunulan cazip iş teklifine bile kibirle <u>burun kıvırmıştı</u>.")
]

atasozleri = [
    ("Ayağını yorganına göre uzat", "Giderlerini gelirine ve imkânlarına uydur", "Tutumlu olmak ve bütçeyi aşmamak"),
    ("Damlaya damlaya göl olur", "Küçük tasarruflar birikerek büyük varlıklar meydana getirir", "Birikim yapmanın ve sabırlı olmanın önemi"),
    ("Ağaç yaşken eğilir", "İnsanlar çocuk yaşta daha kolay eğitilir ve biçimlendirilir", "Çocukluk çağındaki terbiyenin kalıcılığı"),
    ("Tatlı dil yılanı deliğinden çıkarır", "Gönül alıcı, yumuşak konuşma en zor insanları bile ikna eder", "Nezaketin ve doğru iletişimin gücü"),
    ("Gülme komşuna, gelir başına", "Başkalarının düştüğü kötü duruma sevinilmemelidir", "Empati ve başkalarının felaketine sevinmeme"),
    ("Rüzgâr eken fırtına biçer", "Kötülük yapan kimse sonunda katbekat büyük felaketle karşılaşır", "Davranışların sonuçlarının ağırlığı"),
    ("İşleyen demir pas tutmaz", "Sürekli çalışan kimse zindeliğini ve becerisini korur", "Çalışkanlığın insan üzerindeki olumlu etkisi"),
    ("Taşıma su ile değirmen dönmez", "Dışarıdan gelen geçici yardımlarla sürekli bir iş yürütülemez", "Kendi öz kaynaklarına dayanma gerekliliği"),
    ("Sütten ağzı yanan yoğurdu üfleyerek yer", "Zarar gören kimse benzer durumlarda aşırı temkinli davranır", "Tecrübeden ders çıkarıp ihtiyatlı olma"),
    ("Ak akçe kara gün içindir", "Helal kazançla biriktirilen para, darlık zamanında harcanır", "Zor zamanlar için para biriktirmenin gereği")
]

cok_anlamli = [
    ("açmak", "I. Sabah dükkânın kepenklerini açtı.\nII. Yeni boya odanın havasını açtı.\nIII. Bu konu beni pek açmadı.\nIV. Sınav yaklaşınca ders kitaplarını açtı.\n\n'Açmak' sözcüğü numaralanmış cümlelerde kaç farklı anlamda kullanılmıştır?", "4", ["1", "2", "3", "5"], "I'de kilidini kaldırmak, II'de ferahlık/canlılık vermek, III'te ilgisini çekmemek, IV'te okumaya başlamak anlamında kullanılmıştır; 4 farklı anlam vardır."),
    ("kesmek", "I. Usta kumaşı cetvelle ölçüp kesti.\nII. Borcu ödenmeyen su hattını kesti.\nIII. Rüzgâr aniden kesildi.\nIV. Bu ilaç başımın ağrısını kesti.\n\n'Kesmek' sözcüğü numaralanmış cümlelerde kaç farklı anlamda kullanılmıştır?", "4", ["1", "2", "3", "5"], "I'de ayırmak, II'de akışını durdurmak, III'te dinmek, IV'te gidermek anlamındadır; 4 farklı anlam vardır."),
    ("düşmek", "I. Çocuğun elindeki dondurma yere düştü.\nII. Enflasyon son aylarda düştü.\nIII. Mirastan payımıza eski bir konak düştü.\nIV. Bu zor görev sana düşer.\n\n'Düşmek' sözcüğü bu cümlelerde kaç farklı anlamda kullanılmıştır?", "4", ["1", "2", "3", "5"], "I'de yerçekimiyle inmek, II'de azalmak, III'te hisseye isabet etmek, IV'te ödev/görev olarak verilmek anlamındadır."),
    ("çekmek", "I. Arabayı yolun sağına çekti.\nII. Ağır masayı tek başına çekti.\nIII. Yıllarca gurbette hasret çekti.\nIV. Pamuklu kazak yıkanınca çekti.\n\n'Çekmek' sözcüğü kaç farklı anlamda kullanılmıştır?", "4", ["1", "2", "3", "5"], "I'de park etmek, II'de sürüklemek, III'te katlanmak, IV'te boyutları küçülmek anlamındadır."),
    ("tutmak", "I. Balıkçılar denizden koca bir ağ balık tuttu.\nII. Tuttuğu takım şampiyon oldu.\nIII. Hesapladığımız masraflar çok tuttu.\nIV. Verilen sözlerin tutulması gerekir.\n\n'Tutmak' sözcüğü kaç farklı anlamda kullanılmıştır?", "4", ["1", "2", "3", "5"], "I'de yakalamak, II'de desteklemek, III'te miktara ulaşmak, IV'te yerine getirmek anlamındadır."),
    ("çıkmak", "I. Merdivenleri hızlıca çıktı.\nII. Bahçedeki fidanlar filiz çıkardı.\nIII. Yapılan zamlardan sonra bütçe açık verdi.\nIV. Tayini Ankara'ya çıktı.\n\n'Çıkmak' sözcüğü kaç farklı anlamda kullanılmıştır?", "4", ["1", "2", "3", "5"], "I'de yukarı yürümek, II'de belirmek, III'te yetmemek, IV'te resmi görevlendirme gerçekleşmek anlamındadır."),
    ("basmak", "I. Gaz pedalına sonuna kadar bastı.\nII. Şehri aniden sis bastı.\nIII. Matbaa yeni kitabı bastı.\nIV. Kırk yaşına bastı.\n\n'Basmak' sözcüğü kaç farklı anlamda kullanılmıştır?", "4", ["1", "2", "3", "5"], "I'de baskı uygulamak, II'de kaplamak, III'te yayımlamak, IV'te bir yaşa girmek anlamındadır."),
    ("atmak", "I. Çöpleri çöp kutusuna attı.\nII. Yeni anlaşmaya imza attı.\nIII. Kalbi heyecandan küt küt atıyordu.\nIV. Sıkıntılı günleri geride attık.\n\n'Atmak' sözcüğü kaç farklı anlamda kullanılmıştır?", "4", ["1", "2", "3", "5"], "I'de fırlatmak, II'de imza koymak, III'te nabız vurmak, IV'te geride bırakmak anlamındadır."),
    ("bırakmak", "I. Anahtarı masaya bıraktı.\nII. Sigarayı tamamen bıraktı.\nIII. Babası ona miras bıraktı.\nIV. Saçlarını uzamaya bıraktı.\n\n'Bırakmak' sözcüğü kaç farklı anlamda kullanılmıştır?", "4", ["1", "2", "3", "5"], "I'de koymak, II'de terk etmek, III'te miras kılmak, IV'te kendi haline koymak anlamındadır."),
    ("kaçırmak", "I. Trafiğe takılınca treni kaçırdı.\nII. Ağzından gizli sırrı kaçırdı.\nIII. Yemeğin tuzunu fazla kaçırmış.\nIV. Elindeki fırsatı kaçırdı.\n\n'Kaçırmak' sözcüğü kaç farklı anlamda kullanılmıştır?", "4", ["1", "2", "3", "5"], "I'de yetişememek, II'de istemeden söylemek, III'te ölçüyü aşmak, IV'te değerlendirememek anlamındadır.")
]

mecazlar = [
    ("Aşağıdaki cümlelerin hangisinde altı çizili sözcük <u>mecaz anlamda</u> kullanılmıştır?", "Bize karşı sergilediği <u>soğuk</u> tavırlar hepimizi derinden üzdü.", ["Güneşin kavurucu sıcağında <u>soğuk</u> bir bardak su içti.", "Kış aylarında <u>soğuk</u> rüzgârlar pencere aralıklarından sızıyordu.", "Derin dondurucudan çıkan etler henüz çok <u>soğuktu</u>.", "Buzdolabının bozulmasıyla içindeki içecekler <u>ısınmıştı</u>."], "Soğuk sözcüğü sıcaklığın düşüklüğü değil, 'ilgisiz, sevimsiz' anlamında mecazlaşmıştır."),
    ("Aşağıdaki cümlelerin hangisinde <u>mecaz anlamlı</u> bir sözcük KULLANILMAMIŞTIR?", "Sabah erkenden kütüphaneye gidip akşama kadar ders çalıştı.", ["Söylediği <u>ağır</u> sözler arkadaşının kalbini kırdı.", "Girdiği yeni ortamda kendine <u>sıcak</u> bir dost çevresi edindi.", "Bu projenin arkasındaki <u>karanlık</u> eller bir bir açığa çıkıyor.", "Olaylara daima <u>dar</u> bir çerçeveden bakmaktan kurtulamadı."], "Tüm sözcükler ilk akla gelen gerçek anlamlarıyla kullanılmıştır."),
    ("Aşağıdaki cümlelerin hangisinde 'keskin' sözcüğü mecaz anlamıyla kullanılmıştır?", "Sorunları anında kavrayan çok <u>keskin</u> bir zekâsı vardı.", ["Mutfaktaki <u>keskin</u> bıçakla ekmekleri dilimledi.", "Marangoz tahtayı <u>keskin</u> bir testereyle biçti.", "Kayaların <u>keskin</u> kenarları ayakkabısını yırttı.", "Cam kırıkları son derece <u>keskin</u> olduğundan dikkatle toplandı."], "Zekânın keskin olması, çabuk kavrayan anlamında mecazdır."),
    ("Aşağıdaki cümlelerin hangisinde 'tatlı' sözcüğü gerçek anlamının dışında (mecaz) kullanılmıştır?", "Yıllar sonra karşılaştığı torununa <u>tatlı</u> bir tebessümle baktı.", ["Bayramda misafirlere fıstıklı <u>tatlı</u> ikram ettiler.", "Çilek reçeli bu sene oldukça <u>tatlı</u> olmuş.", "Çayına iki kaşık <u>tatlı</u> şurup ilave etti.", "Pazardan aldığımız elmalar sulu ve <u>tatlıydı</u>."], "Tatlı tebessüm, hoş, sevimli, cana yakın anlamında mecazdır."),
    ("Aşağıdaki cümlelerin hangisinde 'derin' sözcüğü soyut/mecaz anlam taşımaktadır?", "Felsefi metinler üzerinde <u>derin</u> düşüncelere daldı.", ["Köyün hemen yanından <u>derin</u> bir vadi geçiyordu.", "Yüzme bilmeyenlerin <u>derin</u> sulara girmesi tehlikelidir.", "İşçiler temel için bahçeye <u>derin</u> bir kuyu kazdılar.", "Gölün en <u>derin</u> noktası kırk metreyi buluyordu."], "Derin düşünce mecaz/soyut bir kavramdır."),
    ("Aşağıdaki cümlelerin hangisinde altı çizili sözcük mecaz anlamda kullanılmıştır?", "Girdiği her ortamda saygınlık uyandıran <u>parlak</u> bir kariyeri vardı.", ["Salondaki avizenin <u>parlak</u> ışığı gözlerimizi kamaştırdı.", "Cilalanan ahşap masa ışıl ışıl ve <u>parlaktı</u>.", "Gökyüzünde gecenin en <u>parlak</u> yıldızı parıldıyordu.", "Yeni aldığı saatin gümüş kordonu gayet <u>parlaktı</u>."], "Parlak kariyer, başarılı anlamında mecazdır."),
    ("Aşağıdaki cümlelerin hangisinde 'kırmak' sözcüğü mecaz anlamda kullanılmıştır?", "Yaptığı yersiz eleştirilerle arkadaşının hevesini <u>kırdı</u>.", ["Rüzgâr sert esince pencerenin camını <u>kırdı</u>.", "Çocuk koşarken sehpadaki porselen vazoyu <u>kırdı</u>.", "Odunları sobaya sığacak boyutlarda baltayla <u>kırdı</u>.", "Cevizleri taşla tek tek <u>kırdı</u>."], "Heves kırmak, şevkini söndürmek anlamında mecazdır."),
    ("Aşağıdaki cümlelerin hangisinde 'kuru' sözcüğü mecaz anlamda kullanılmıştır?", "Hiçbir kanıta dayanmayan <u>kuru</u> bir iddiadan öteye gidemedi.", ["Sonbaharda ağaçların <u>kuru</u> yaprakları yollara döküldü.", "Islanan ceketini kaloriferin üzerine koyarak <u>kuru</u> hale getirdi.", "Fırından yeni çıkmış <u>kuru</u> ekmekleri çorbaya doğradı.", "Yaz aylarında derelerin yatakları tamamen <u>kuru</u> kalır."], "Kuru iddia, temelsiz ve dayanaksız anlamında mecazdır."),
    ("Aşağıdaki cümlelerin hangisinde 'pişmek' sözcüğü mecaz anlamda kullanılmıştır?", "Yıllarca sahada çalışarak mesleğin her alanında iyice <u>pişti</u>.", ["Fırındaki tepsi böreği nar gibi kızararak <u>pişti</u>.", "Kısık ateşte kaynayan sebze yemeği bir saatte <u>pişti</u>.", "Mangaldaki etler henüz tam olarak <u>pişmedi</u>.", "Çömlekte yapılan kuru fasulye lokum gibi <u>pişmişti</u>."], "Meslekte pişmek, deneyim ve ustalık kazanmak anlamında mecazdır."),
    ("Aşağıdaki cümlelerin hangisinde 'uyanmak' sözcüğü mecaz anlamda kullanılmıştır?", "Okuduğu bu kitap sayesinde zihninde yepyeni fikirler <u>uyandı</u>.", ["Çalar saatin sesiyle sabah yedide güçlükle <u>uyandı</u>.", "Gürültüden korkan bebek uykusundan ağlayarak <u>uyandı</u>.", "Gece boyunca sık sık <u>uyanıp</u> su içti.", "Güneş doğarken bütün köy ahalisi <u>uyanmıştı</u>."], "Zihinde fikirlerin uyanması, belirmek anlamında mecazdır.")
]

soz_obekleri = [
    ("Yazar, son romanında 'kelimelerin sırtına binen yükü hafifletmeyi' amaçladığını belirtiyor.", "Ağdalı ve karmaşık dilden kaçınıp duru, yalın bir anlatımı tercih etmek", ["Tarihi olayları tarafsızca aktarmak", "Karakterlerin psikolojik tahlillerini derinleştirmek", "Geleneksel temaları modern formlarla harmanlamak", "Okuyucuyu sürekli merakta bırakacak kurgular kurmak"], "Kelimelerin yükünü hafifletmek; süslü anlatımdan sıyrılarak sade bir üsluba yönelmektir."),
    ("Bir eleştirmenimiz, 'Kendi sesini bulamamış şair, başkalarının yankısı olmaktan kurtulamaz.' demiştir.", "Özgün bir üslup yakalayamayanların taklitçi kalacağı", ["Şiirde duygunun akıldan üstün olduğu", "Gelenekten yararlanmanın şiiri güçlendirdiği", "Toplumsal sorunlara duyarsız kalınamayacağı", "Şiir dilinin günlük konuşma dilinden farklı olması gerektiği"], "Kendi sesini bulamamak ve yankı olmak taklitçiliği ifade eder."),
    ("Roman kahramanını anlatırken 'aynayı topluma tutan bir tanık' nitelemesi kullanılmıştır.", "Toplumun gerçeklerini olduğu gibi, tarafsızca yansıtmak", ["Bireyin iç dünyasındaki karmaşaları irdelemek", "Hayal gücüne dayalı kurgular üretmek", "Geçmiş ile gelecek arasında köprü kurmak", "Toplumun aksayan yönlerini mizahi dille yermek"], "Ayna tutmak; nesnel bir biçimde yansıtmaktır."),
    ("Bir denemeci, 'Düşüncelerini kalıplara dökmekten kaçınan yazar, okurunu da özgürleştirir.' ifadesini kullanıyor.", "Kalıplaşmış, dogmatik düşünce kalıplarından uzak durmak", ["Belli bir ideolojinin savunuculuğunu yapmak", "Biçimsel kurallara sıkı sıkıya bağlı kalmak", "Eserlerinde sadece soyut konuları ele almak", "Halkın anlayamayacağı kapalı bir dil kullanmak"], "Kalıplardan kaçınmak; basmakalıp yargılardan uzak durmaktır."),
    ("Usta yazar, 'Eserlerimde zamanın yıpratıcı çarkına direnecek tohumlar ekiyorum.' demektedir.", "Kalıcı ve ölümsüz, geleceğe kalacak nitelikte eserler vermek", ["Güncel olayları hızlıca okura ulaştırmak", "Popüler kültürün beklentilerini karşılamak", "Dönemin edebi akımlarına öncülük etmek", "Maddi kazanç sağlamak amacıyla yazmak"], "Zamanın çarkına direnmek kalıcılık demektir."),
    ("Şair, 'Mısralarımda sözcükleri adeta bir kuyumcu titizliğiyle işliyorum.' demektedir.", "Sözcük seçiminde ve kullanımında olağanüstü titiz ve özenli davranmak", ["Çok sayıda şiiri kısa sürede kaleme almak", "Daha önce hiç duyulmamış sözcükler türetmek", "Sadece aruz ölçüsünün kurallarına uymak", "Maddi değeri yüksek konuları işlemek"], "Kuyumcu titizliği azami özen ve seçicilik demektir."),
    ("Bir yazar için 'Kendi fildişi kulesine çekilip dünyayı pencereden izliyor.' denmesi ne anlama gelir?", "Toplumdan ve hayatın canlı gerçeklerinden kopup yalnızlaşmak", ["Geniş kitlelere hitap eden eserler üretmek", "Saray hayatını ve soyluları konu edinmek", "Toplumsal adaletsizliklere karşı bayrak açmak", "Mimari eserler üzerine araştırmalar yapmak"], "Fildişi kule; toplumdan soyutlanmış yaşamı ifade eder."),
    ("Tiyatro eleştirmeni, 'Bu oyun seyircinin zihninde bir kıvılcım çakmayı başarıyor.' diyor.", "İzleyicide yeni düşünceler, farkındalık ve sorgulama uyandırmak", ["İzleyicilere neşeli anlar yaşatmak", "Tarihi gerçekleri birebir öğretmek", "Dekor ve ışık efektleriyle göz kamaştırmak", "Oyuncuların teknik yetersizliklerini gizlemek"], "Kıvılcım çakmak; uyanış ve sorgulama başlatmaktır."),
    ("Bir edebiyatçı, 'Edebiyat, hayatın eksik bıraktığı yerleri tamamlama sanatıdır.' görüşünü savunuyor.", "Edebiyatın yaşamdaki duygusal ve ruhsal boşlukları gidermesi", ["Gerçek hayatı birebir kopyalaması", "İnsanları hayal dünyasına hapsedip gerçekten koparması", "Yalnızca mutlu sonla biten hikâyeler anlatması", "Tarih biliminin yerine geçmesi"], "Eksik yerleri tamamlamak ruhsal boşlukları gidermektir."),
    ("Ressam hakkında söylenen 'Fırçasını boyaya değil, doğrudan duygularına batırıyor.' sözüyle ne anlatılmak istenmiştir?", "Eserlerinde teknik kaygılardan ziyade samimi duyguları ve coşkuyu yansıtmak", ["Tablolarında sadece pahalı boyalar kullanmak", "Resim sanatının akademik kurallarına harfiyen uymak", "Yalnızca doğa manzaralarını resmetmek", "Renklerin uyumunu matematiksel olarak hesaplamak"], "Fırçayı duygulara batırmak samimiyet ve duygusal yoğunluk demektir.")
]
