# turkce_data_4.py - Q19 to Q24
anlatim_bozuklugu = [
    ("Aşağıdaki cümlelerin hangisinde <u>gereksiz sözcük kullanımından</u> kaynaklanan bir anlatım bozukluğu vardır?", "Kardeşimle birlikte iki yıldır karşılıklı <u>mektuplaşıyoruz</u>.", ["Kitap okumayı çok seven biriydi.", "Sınavda başarılı olmak için çok çalıştı.", "Bahçedeki ağaçlar ilkbaharda çiçek açtı.", "Yarın sabah erkenden yola çıkacağız."], "Mektuplaşmak zaten karşılıklıdır."),
    ("Aşağıdaki cümlelerin hangisinde <u>sözcüğün yanlış anlamda kullanılmasından</u> kaynaklanan bir bozukluk vardır?", "Bu yıl aşırı yağışlar yüzünden barajlardaki su seviyesi önemli ölçüde <u>çoğaldı</u>.", ["Öğrenciler kütüphanede ders çalışıyordu.", "Güneş batarken sahil boyunca yürüdük.", "Tüm hazırlıklar zamanında tamamlandı.", "Soruları dikkatle inceleyip çözdü."], "Su seviyesi çoğalmaz, yükselir."),
    ("Aşağıdaki cümlelerin hangisinde <u>mantık ve sıralama hatasından</u> kaynaklanan bir bozukluk vardır?", "Bırakın bir bardak çay yapmayı, mükemmel ziyafet sofraları bile <u>hazırlayamaz</u>.", ["Evdeki tüm eşyaları tek tek temizledi.", "Yolcular otobüsün gelmesini bekledi.", "Sınav sonuçları nihayet açıklandı.", "Bahçedeki gülleri özenle suladı."], "Kolay ile zorun yeri karışmıştır."),
    ("Aşağıdaki cümlelerin hangisinde <u>çelişen sözcüklerin kullanılmasından</u> kaynaklanan bir bozukluk vardır?", "<u>Şüphesiz</u> bu zor sınavı tüm arkadaşların kazanmış <u>olmalı</u>.", ["Düzenli çalışan herkes başarılı olur.", "Kitap okumak insanı zenginleştirir.", "Güneş doğarken yola çıkmayı planlıyoruz.", "Tüm sorunları konuşarak çözdük."], "'Şüphesiz' ile 'olmalı' çelişmektedir."),
    ("Aşağıdaki cümlelerin hangisinde <u>özne-yüklem uyuşmazlığından</u> kaynaklanan bir bozukluk vardır?", "Kuşlar yüksek ağaçların dallarında neşeyle <u>ötüşüyorlar</u>.", ["Öğrenciler sınıfta ders dinliyorlar.", "Çocuklar bahçede top oynuyorlar.", "İnsanlar durakta otobüs bekliyor.", "Köylüler tarlada ekin biçiyorlar."], "İnsan dışı çoğul öznelerde yüklem tekil olur."),
    ("Aşağıdaki cümlelerin hangisinde <u>tamlama yanlışlığından</u> kaynaklanan bir anlatım bozukluğu vardır?", "Toplantıda <u>askerî</u> ve <u>kamu kuruluşları</u> temsilcileri hazır bulundu.", ["Eski ve yeni kitapları raflara dizdi.", "Sarı ve kırmızı güller açtı.", "Büyük ve geniş caddelerden geçtik.", "Yerli ve yabancı turistler şehri gezdi."], "'Askerî kuruluşları' denemez."),
    ("Aşağıdaki cümlelerin hangisinde <u>ek eylem eksikliğinden</u> kaynaklanan bir bozukluk vardır?", "Kardeşi çok zeki fakat çalışkan <u>değildi</u>.", ["Dün akşam bize uğradı ve kahve içti.", "Soruları okudu ve cevapladı.", "Bahçeye indi ve çiçekleri suladı.", "Kitabı aldı ve okumaya başladı."], "'zekiydi fakat çalışkan değildi' olmalıdır."),
    ("Aşağıdaki cümlelerin hangisinde <u>nesne eksikliğinden</u> kaynaklanan bir bozukluk vardır?", "Arkadaşına her zaman inanır ve tüm kalbiyle <u>desteklerdi</u>.", ["Kitabı okudu ve kütüphaneye teslim etti.", "Çiçekleri suladı ve güneşe koydu.", "Mektubu yazdı ve postaneye gitti.", "Odayı havalandırdı ve kapıyı kapattı."], "'ve onu desteklerdi' olmalıdır."),
    ("Aşağıdaki cümlelerin hangisinde <u>dolaylı tümleç eksikliği</u> vardır?", "Düşman şehri kuşattı ama bir türlü <u>giremedi</u>.", ["Kitabı aldı ve hemen okudu.", "Soruyu çözdü ve tahtaya yazdı.", "Kapıyı açtı ve içeri girdi.", "Pencereyi kapattı ve perdeyi çekti."], "'şehre giremedi' olmalıdır."),
    ("Aşağıdaki cümlelerin hangisinde <u>anlam belirsizliğinden</u> kaynaklanan bir bozukluk vardır?", "<u>Gelişini</u> heyecanla ve büyük bir sevinçle bekliyorduk.", ["Senin dün kütüphaneye gittiğini öğrendim.", "Onun bu projede çok emeği geçmişti.", "Bizim eve ne zaman geleceksiniz?", "Onların sınavı başarılı geçmiş."], "Senin gelişini mi, onun gelişini mi belirsizdir.")
]

cumle_anlam_iliskileri = [
    ("Aşağıdaki cümlelerin hangisinde bir <u>amaç-sonuç</u> ilişkisi vardır?", "Atatürk ilkelerini genç nesillere aktarabilmek <u>için</u> seminer düzenlendi.", ["Kar yağışı aniden bastırınca yollar kapandı.", "Düzenli çalışırsan sınavı rahatlıkla kazanırsın.", "Yorgunluktan koltuğun üzerinde uyuyakalmıştı.", "Güneş açtığı için piknik yapmaya karar verdik."], "Seminerin yapılma gayesi aktarmaktır."),
    ("Aşağıdaki cümlelerin hangisinde bir <u>neden-sonuç</u> ilişkisi vardır?", "Yoğun kar yağışı nedeniyle şehirlerarası seferler iptal edildi.", ["Sınavı kazanmak amacıyla gece gündüz çalıştı.", "Hava güzel olursa balığa gideriz.", "Kendini geliştirmek maksadıyla kurslara katıldı.", "Daha iyi bir gelecek adına çabalıyor."], "İptal edilmenin gerekçesi kar yağışıdır."),
    ("Aşağıdaki cümlelerin hangisinde <u>koşula bağlılık</u> söz konusudur?", "İnsanlarla empati kurarak konuşursan sorunları çok daha kolay çözersin.", ["Erken kalktığından bütün gün esnedi.", "Arkadaşını görmek için hastaneye gitti.", "Yollar buzlandığı için kaza meydana geldi.", "Kitap okumayı sevdiği için kütüphaneye gitti."], "-sa/-se şart kipiyle koşul bildirilmiştir."),
    ("Aşağıdaki cümlelerin hangisinde <u>örtülü anlam</u> vardır?", "Bu yılki mezuniyet törenine <u>Ahmet de</u> katıldı.", ["Güneş doğarken köylüler tarlaya gitti.", "Kütüphanede sessizce ders çalışıyorlardı.", "Tarihi köprünün restorasyonu tamamlandı.", "Akşam olunca lambalar yandı."], "Başkalarının da katıldığı anlaşılmaktadır."),
    ("Aşağıdaki cümlelerin hangisinde bir <u>varsayım</u> anlamı vardır?", "<u>Diyelim ki</u> yarınki sınav ertelendi, bu durumda ne yapacaksın?", ["Belki yarın akşam size gelebiliriz.", "Keşke ben de sizinle tatile çıksaydım.", "Sanırım bu işin üstesinden gelebiliriz.", "Galiba toplantı saatinde değişiklik oldu."], "Gerçekleşmemiş durumu olmuş kabul etmektir."),
    ("Aşağıdaki cümlelerin hangisinde bir <u>eleştiri</u> söz konusudur?", "Yazar son eserinde karakterleri son derece yüzeysel ve yapay işlemiş.", ["Roman dört yüz sayfadan oluşuyor.", "Kitap geçen hafta tüm kitapçılarda çıktı.", "Eser akıcı bir üslupla yazılmış.", "Yazar yurt dışında edebiyat eğitimi almış."], "Karakterlerin yüzeyselliği olumsuz eleştirilmiştir."),
    ("Aşağıdaki cümlelerin hangisinde bir <u>öz eleştiri</u> vardır?", "Zamanı doğru yönetemediğim için sınavdaki son iki soruyu yetiştiremedim.", ["Arkadaşım toplantıya yine geç kaldı.", "Trafik yüzünden işe vaktinde gidemedik.", "Hava yağmurlu olduğu için gidemedik.", "Öğretmen sınavı çok zor hazırlamıştı."], "Kendi hatasını dile getirme durumudur."),
    ("Aşağıdaki cümlelerin hangisinde bir <u>ön yargı (peşin hüküm)</u> anlamı vardır?", "Bu yönetmenin çekeceği yeni filmin de gişede hüsrana uğrayacağından eminim.", ["Yarın vizyona girecek filmin biletleri bitti.", "Film uluslararası festivalde ödül aldı.", "Filmin müzikleri çok beğenildi.", "Sinema salonu tamamen doluydu."], "Olay gerçekleşmeden kesin hüküm verilmiştir."),
    ("Aşağıdaki cümlelerin hangisinde <u>küçümseme</u> anlamı vardır?", "İki satır yazı yazdı diye kendini usta bir romancı sanıyor.", ["Azıcık aşım, ağrısız başım.", "Küçücük bir kulübede yaşıyordu.", "Bir dilim ekmekle karnını doyurdu.", "Kısa bir tatil yapıp döndü."], "Yetenek ve başarının değersiz görülmesidir."),
    ("Aşağıdaki cümlelerin hangisinde <u>azımsama</u> anlamı vardır?", "Bu kadar ağır işe karşılık bize sadece bu kadarcık ücret mi layık görüldü?", ["Kendini bir şey sananlara tahammül edemiyorum.", "O da güya ressam olacakmış.", "Bize tepeden bakmayı marifet sanıyor.", "Sen kim, bu projeyi bitirmek kim!"] , "Miktarca az bulma durumudur.")
]

oznel_nesnel = [
    ("Aşağıdaki cümlelerin hangisi <u>kanıtlanabilirlik açısından (öznel/nesnel)</u> diğerlerinden farklıdır?", "Müzede sergilenen bu tarihi vazonun üzerinde büyüleyici desenler vardı.", ["Türkiye'nin başkenti Ankara'dır.", "Roman toplam dört yüz sayfadan oluşmaktadır.", "Yazarın son kitabı geçen ay yayımlandı.", "Dünya, Güneş etrafında 365 günde döner."], "'Büyüleyici' kişisel beğeni içeren öznel bir ifadedir."),
    ("Aşağıdaki cümlelerin hangisinde <u>öznel bir değerlendirme</u> yapılmıştır?", "Sanatçının sıcacık sesi dinleyen herkesin yüreğine dokunuyor.", ["Konser dün akşam sekizde başladı.", "Salonda bin kişi vardı.", "Sanatçı sahnede iki saat şarkı söyledi.", "Konser biletleri bir hafta önce bitti."], "'Sıcak ses, yüreğe dokunmak' öznel bir yargıdır."),
    ("Aşağıdaki cümlelerin hangisi <u>nesnel bir yargı</u> bildirmektedir?", "Eserde geçen olaylar 19. yüzyıl Osmanlı coğrafyasında geçmektedir.", ["Yazarın anlatımı son derece akıcıdır.", "Karakterlerin tahlilleri kusursuzdur.", "Bu kitap edebiyatımızın en güzel eseridir.", "Herkesin okuması gereken bir başyapıttır."], "Eserin zamanı kanıtlanabilir nesnel olgudur."),
    ("Aşağıdaki cümlelerin hangisinde hem <u>öznel</u> hem <u>nesnel</u> ögeler bir arada kullanılmıştır?", "Yazarın beş yüz sayfalık bu son romanı, okuru büyüleyen eşsiz bir anlatıma sahip.", ["Türkiye üç tarafı denizlerle çevrili bir yarımadadır.", "Atatürk 1881 yılında doğmuştur.", "Kitapta yirmi farklı hikâye yer almaktadır.", "Ankara İç Anadolu Bölgesi'ndedir."], "'beş yüz sayfalık' nesnel, 'büyüleyen eşsiz anlatım' özneldir."),
    ("Aşağıdaki cümlelerin hangisi kanıtlanabilirlik açısından <u>nesneldir</u>?", "Atatürk Orman Çiftliği 1925 yılında Gazi Mustafa Kemal tarafından kurulmuştur.", ["Ankara Türkiye'nin en güzel şehridir.", "Sonbahar insana hüzün veren en etkileyici mevsimdir.", "Klasik müzik insanı dinlendiren en soylu uğraştır.", "Yazarın üslubu herkesi hayran bırakacak kadar kusursuzdur."], "Resmi tarihi belgeyle doğrulanabilir bilgidir."),
    ("Aşağıdaki cümlelerin hangisinde yazar <u>kişisel düşüncesini</u> katmamıştır?", "UNESCO, Göbeklitepe'yi 2018 yılında Dünya Mirası Listesi'ne almıştır.", ["Göbeklitepe insanlık tarihinin en büyüleyici keşfidir.", "Kazı alanını gezen herkes derin hayranlık duyar.", "Oradaki dikilitaşlar gizemlerle doludur.", "Dünyanın en etkileyici açık hava müzesi burasıdır."], "UNESCO kararı tarafsız ve belgelidir."),
    ("Aşağıdaki cümlelerin hangisi <u>öznel bir yargı</u> içermektedir?", "Şairin mısralarındaki derin ahenk insanı başka diyarlara götürüyor.", ["Şiir kitabı toplam altmış sayfadır.", "Kitapta otuz şiir yer alıyor.", "Kitabın ilk baskısı 2020'de yapılmıştır.", "Yazar kitabını annesine ithaf etmiştir."], "'Derin ahenk' kişisel yorumdur."),
    ("Aşağıdaki cümlelerin hangisi nesnel bir veri içermektedir?", "TÜİK verilerine göre Türkiye'nin nüfusu 85 milyonu aşmıştır.", ["Şehir hayatı insanı ruhen yıpratan en zor yaşamdır.", "Köyde yaşamak ömrü uzatan en keyifli tercihtir.", "Teknoloji insanları yalnızlaştıran en tehlikeli şeydir.", "Eski bayramların tadı şimdikilerde kesinlikle yoktur."], "TÜİK resmi sayısı nesneldir."),
    ("Aşağıdaki cümlelerin hangisinde yoruma yer verilmemiştir?", "Toplantıya katılan heyet üyeleri bildiri metnini oy birliğiyle imzaladı.", ["Toplantıda son derece parlak fikirler ortaya atıldı.", "Konuşmacının sunumu herkesi büyüledi.", "Tarihi salondaki atmosfer insanı geçmişe götürüyordu.", "Raporun sonuç bölümü muazzam bir çalışmaydı."], "İmzalama eylemi nesnel bir olgudur."),
    ("Aşağıdaki cümlelerin hangisi doğrudan nesnel bir tanımdır?", "Üç kenarı ve üç iç açısı olan kapalı geometrik şekle üçgen denir.", ["Üçgen, geometrinin en zarif şeklidir.", "Resim yapmak ruhu dinlendiren en güzel sanattır.", "Tarih, geçmişe tutulan büyüleyici bir fenerdir.", "Müzik, ruhun en yüce gıdasıdır."], "Matematiksel tanım nesneldir.")
]

ana_fikir = [
    ("Okumak sadece boş zamanları değerlendirme aracı değildir. Aksine o, insanın kendi içine yaptığı en uzun yolculuktur. Bir kitap okurken başkalarının deneyimlerinde kendi eksiklerimizi keşfederiz. Kitap okumayan toplumların sığ sularda debelenmesi bundandır.\n\nBu parçada asıl vurgulanmak istenen düşünce nedir?", "Okumanın insanı bilinçlendiren ve içsel gelişimini sağlayan vazgeçilmez bir eylem olduğu", ["Kitap okumanın sadece boş zamanlarda yapılacağı", "Gelişmişliğin basılan kitap sayısıyla ölçüldüğü", "Romanın psikolojiyi en iyi anlatan tür olduğu", "Tarih kitaplarının geçmişi öğrettiği"], "Okumanın insanı dönüştüren işlevi ana fikirdir."),
    ("Sanatta özgünlük, başkalarının yürüdüğü yollardan yürüyerek değil; kendi patikasını açarak elde edilir. Bir ustanın gölgesinde kalan fidan güneş göremez ve serpilip boy atamaz. Sanatçı ustalardan beslenmeli fakat kendi sesini bulmalıdır.\n\nBu parçanın ana düşüncesi nedir?", "Gerçek sanatçının taklitçilikten kurtulup kendine has bir üslup yakalaması gerektiği", ["Ustalara saygı duymayanların başarılı olamayacağı", "Gelenekten bütünüyle kopmanın imkânsız olduğu", "Genç sanatçıların ustaları harfiyen örnek alması gerektiği", "Özgünlüğün doğuştan gelen bir yetenek olduğu"], "Taklitten kurtulup kendi sesini bulma ana fikirdir."),
    ("Eleştiri, bir eseri yerin dibine batırmak veya onu göklere çıkarmak değildir. Gerçek eleştiri; eserin güçlü ve zayıf yönlerini nesnel ölçütlerle teraziye koymak, okura yeni pencereler aralamaktır. Yıkıcı eleştiri sanatı kurutur, yapıcı eleştiri geliştirir.\n\nBu parçada eleştiriyle ilgili anlatılmak istenen temel düşünce nedir?", "Eleştirinin nesnel ölçütlerle eseri değerlendirerek sanata ve okura kılavuzluk etmesi gerektiği", ["Eleştirmenlerin sadece kusurları ortaya koyması gerektiği", "Övgü dolu yazıların edebiyata katkı sağlamadığı", "Yazarların eleştirilere daima açık olması gerektiği", "Eleştirinin ancak yazar öldükten sonra yapılacağı"], "Eleştirinin nesnel terazi olma misyonu ana fikirdir."),
    ("Zaman, geri dönüşü olmayan yegâne sermayemizdir. Parayı kaybeden yeniden kazanabilir, sağlığını kaybeden tıp sayesinde şifa bulabilir; fakat yitirilen tek bir saniyeyi dahi geri getirmek mümkün değildir. Buna rağmen en cömertçe harcanan şey zamandır.\n\nBu parçada asıl anlatılmak istenen nedir?", "Zamanın telafisi olmayan en değerli varlık olduğu ve bilinçli kullanılması gerektiği", ["Maddi kayıpların daha kolay telafi edildiği", "Tıbbın gelişmesiyle ömrün uzadığı", "İnsanların geçmişe duyduğu özlemin gereksiz olduğu", "Geleceği planlamanın bugünden önemli olduğu"], "Zamanın telafisiz değeri ana fikirdir."),
    ("Başarı, tesadüflerin bir araya gelmesiyle oluşan bir piyango değildir. O, hedefe kilitlenmiş bir iradenin, ter dökerek geçirilen uykusuz gecelerin ve yaşanan sayısız yenilgiye rağmen ayağa kalkabilme azminin meyvesidir.\n\nBu parçada başarının hangi yönü vurgulanmaktadır?", "Disiplinli emek, azim ve zorluklar karşısında yılmamakla elde edildiği", ["Büyük hedeflere şansla ulaşılabileceği", "Yetenekli insanların çalışmadan başarabileceği", "Başarıda çevre desteğinin tek belirleyici olduğu", "Yenilgilerin insanı başarıdan uzaklaştırdığı"], "Emek ve pes etmemek ana fikirdir."),
    ("Dil, bir milletin hafızası ve ruhudur. Kendi dilini yozlaşmaya terk eden, yabancı kelimelerin istilasına seyirci kalan bir millet, zamanla milli kimliğini de kaybeder. Dili korumak, vatan topraklarını korumak kadar kutsal bir savunmadır.\n\nBu parçada asıl anlatılmak istenen nedir?", "Ana dilin korunmasının milli kimliğin ve bağımsızlığın devamı için hayati olduğu", ["Yabancı dillerin öğrenilmesine karşı çıkılması gerektiği", "Dilin sadece iletişim aracı olarak görülmesi gerektiği", "Eski kelimelerin dilden tamamen atılması gerektiği", "Yabancı terim kullanmanın çağdaşlık olduğu"], "Dil bilinci ile milli varlık bağı ana fikirdir."),
    ("Mutluluk dış dünyadaki lüks eşyalarda değil; insanın iç huzurunda ve elindekilerin kıymetini bilmesindedir. Doyumsuz bir ihtirasla sürekli daha fazlasını isteyen insan, elindeki hazineleri göremez ve ömrünü serap peşinde tüketir.\n\nBu parçada vurgulanan temel düşünce nedir?", "Gerçek mutluluğun kanaatkârlıkta ve içsel tatminde saklı olduğu", ["Maddi refahın mutluluğun ön koşulu olduğu", "Büyük hayaller kurmanın insanı mutlu ettiği", "İnsanların toplumdan uzaklaşarak huzur bulabileceği", "Başarılı insanların daima mutlu olduğu"], "Kanaat ve iç huzur ana fikirdir."),
    ("Çocuk eğitiminde nasihatlerden ziyade sergilenen davranışlar belirleyicidir. Kitap okumayan bir anne babanın çocuğuna 'Oku!' demesi tesir etmez. Çocuklar söylenenleri değil, gördüklerini taklit ederek karakterlerini inşa ederler.\n\nBu parçada asıl vurgulanmak istenen nedir?", "Çocukların eğitiminde model olmanın kuru sözlerden çok daha etkili olduğu", ["Çocuklara erken yaşta okuma kazandırılması gerektiği", "Ebeveynlerin çocuklara karşı sert olması gerektiği", "Okulların aileden daha üstün olduğu", "Nasihat vermenin en etkili terbiye yolu olduğu"], "Model olmanın gücü ana fikirdir."),
    ("Tarih bilinci, sadece geçmişteki savaşları ezberlemek değildir. O, bugünü doğru anlamak ve geleceğe güvenle yürümek için geçmişin tecrübelerinden ders çıkarma sanatıdır. Geçmişini bilmeyen toplumlar aynı hataları tekrar yaşarlar.\n\nBu parçanın ana düşüncesi nedir?", "Tarih öğreniminin bugünü ve geleceği inşa etmek için bir rehber olduğu", ["Tarihin sadece zaferlerle dolu bir alan olduğu", "Eski savaş stratejilerinin günümüzde de geçerli olduğu", "Tarih biliminin sadece belgelere dayandığı", "Geçmişte yapılan hataların unutulması gerektiği"], "Tarihin geleceğe rehberliği ana fikirdir."),
    ("Gerçek dostluk, iyi günlerde sofrayı paylaşmakla değil; kara günlerde derdi bölüşmekle sınanır. Hayatın fırtınalı anlarında yanınızda duran tek bir dost; sahte kalabalıkların hepsinden daha kıymetlidir.\n\nBu parçada dostlukla ilgili asıl anlatılmak istenen nedir?", "Dostluğun gerçek değerinin zor zamanlarda ortaya çıktığı", ["Geniş arkadaş çevresine sahip olmanın önemi", "İnsanların menfaatleri için dostluk kurduğu", "Dostların birbirine maddi yardımda bulunması gerektiği", "Zamanla tüm dostlukların zayıfladığı"], "Zor gün dostluğu ana fikirdir.")
]

degilmemistir = [
    ("Kapadokya, volkanik lavların rüzgâr ve yağmurla aşınması sonucu oluşmuştur. Bölge, yer altı şehirleri, kaya kiliseleri ve vadileriyle eşsizdir. Her yıl binlerce turist sıcak hava balonlarıyla bu coğrafyayı kuşbakışı izlemektedir.\n\nBu parçada Kapadokya ile ilgili olarak hangisine <u>değinilmemiştir</u>?", "Bölgedeki otellerin konaklama fiyatlarına", ["Peribacalarının jeolojik oluşumuna", "Bölgedeki tarihi yapılara", "Turistlerin balonlarla gezdiğine", "Volkanik dağların etkisine"], "Konaklama fiyatlarına yer verilmemiştir."),
    ("Zeytin ağacı, binlerce yıldır Akdeniz'in simgesi olmuş, mitolojide ölümsüzlüğü temsil etmiştir. Kuraklığa olağanüstü dirençlidir. Hem meyvesi sofralık tüketilir hem de yağı kalp-damar sağlığı için doğal bir ilaçtır.\n\nBu parçadan zeytin ağacı ile ilgili hangisi <u>çıkarılamaz</u>?", "Dünya zeytin üretiminde Türkiye'nin lider olduğu", ["Akdeniz'de ölümsüzlüğü simgelediği", "Kuraklığa dirençli olduğu", "Yağının sağlık için faydalı olduğu", "Meyvesinin ve yağının tüketildiği"], "Türkiye'nin liderliğine değinilmemiştir."),
    ("Mimar Sinan, Osmanlı mimarisinin zirvesidir. Çıraklık eseri Şehzade, kalfalık eseri Süleymaniye ve ustalık eseri Selimiye Camii ile tarihe geçmiştir. Eserlerinde estetik ile akustiği ve deprem dayanıklılığını birleştirmiştir.\n\nBu parçada Mimar Sinan ile ilgili hangisine <u>değinilmemiştir</u>?", "Eserlerin inşasında çalışan işçi sayısına", ["Mimarlık kariyerindeki üç büyük eserine", "Estetik ile mühendisliği birleştirdiğine", "Depreme karşı önlem aldığına", "Osmanlı'nın önemli mimarı olduğuna"], "İşçi sayısına değinilmemiştir."),
    ("Piri Reis'in 1513 yılında ceylan derisine çizdiği dünya haritası, günümüzde bile bilim dünyasını hayrete düşürmektedir. Harita; Batı Avrupa, Batı Afrika ve Güney Amerika kıyılarını doğrulukla göstermektedir.\n\nBu parçadan Piri Reis haritasıyla ilgili hangisine <u>ulaşılamaz</u>?", "Haritanın günümüzde hangi müzede sergilendiğine", ["Hangi tarihte çizildiğine", "Neyin üzerine çizildiğine", "Hangi kıtaları gösterdiğine", "Doğruluğunun hayranlık uyandırdığına"], "Müze bilgisine yer verilmemiştir."),
    ("Lale Devri, barış ve yenilik arayışının dönemidir. 1718 Pasarofça ile başlayıp 1730 Patrona Halil İsyanı ile bitmiştir. Bu dönemde ilk Türk matbaası kurulmuş, çiçek aşısı uygulanmıştır.\n\nBu parçadan Lale Devri ile ilgili hangisi <u>çıkarılamaz</u>?", "Bu dönemde askeri alanda büyük fetihler yapıldığı", ["Hangi antlaşmayla başlayıp bittiği", "Barış ve yenilik dönemi olduğu", "İlk matbaanın kurulduğu", "Sağlıkta adımlar atıldığı"], "Fetih yapılmadığı belirtilmektedir."),
    ("Anadolu Selçuklularında ticaret için kervansaraylar yapılmıştır. Tüccarlara üç gün ücretsiz yemek, barınma sağlanmış ve eşkıya saldırısına uğrayanların zararları devletçe tazmin edilmiştir.\n\nBu parçada kervansaraylarla ilgili hangisine <u>değinilmemiştir</u>?", "Kervansarayları inşa eden mimarların kimliğine", ["Ücretsiz hizmetlerin süresine", "Ticareti geliştirmek için yapıldığına", "Zararların tazmin edildiğine", "Barınma sağlandığına"], "Mimarların adına değinilmemiştir."),
    ("Divanü Lugati't-Türk, Kaşgarlı Mahmud tarafından 11. yüzyılda Araplara Türkçeyi öğretmek için yazılmıştır. Türklerin folkloru, tarihi ve coğrafyası hakkında paha biçilmez bir kaynaktır.\n\nBu parçadan eserle ilgili hangisi <u>çıkarılamaz</u>?", "Eserin günümüze ulaşan tek nüshasının nerede saklandığı", ["Yazılış amacı ve yazarı", "Hangi yüzyılda yazıldığı", "Zengin bir kültür kaynağı olduğu", "Folklor bilgileri sunduğu"], "Nüshanın saklandığı yere değinilmemiştir."),
    ("Ahilik teşkilatı, 13. yüzyılda esnaf birliği olarak kurulmuştur. Malların kalitesini denetlemiş, fiyatları belirlemiş ve üyeler arasında dayanışma sağlamıştır.\n\nBu parçada Ahilik ile ilgili hangisine <u>değinilmemiştir</u>?", "Osmanlı ordusundaki yeniçeri sayısına", ["Kuruluş amacına", "Kalite denetimi yaptığına", "Fiyatları belirlediğine", "Dayanışma sağladığına"], "Yeniçeri sayısına değinilmemiştir."),
    ("Erzurum Kongresi'nde ilk kez 'Milli sınırlar içinde vatan bir bütündür, bölünemez.' kararı alınmış, manda ve himaye kesin olarak reddedilmiştir.\n\nBu parçadan kongreyle ilgili hangisi <u>çıkarılamaz</u>?", "Kongreye kaç delegenin katıldığı", ["Vatanın bölünmezliği ilkesi", "Manda ve himayenin reddi", "Milli kararlar alındığı", "Toplanış özellikleri"], "Delege sayısı belirtilmemiştir."),
    ("Lozan Barış Antlaşması ile kapitülasyonlar kaldırılmış, yabancı okullar Türk kanunlarına bağlanmış ve devletin bağımsızlığı tescil edilmiştir.\n\nBu parçada Lozan ile ilgili hangisine <u>değinilmemiştir</u>?", "Antlaşmanın imzalandığı binanın mimarisine", ["Kapitülasyonların kaldırıldığına", "Yabancı okulların denetimine", "Bağımsızlığın tesciline", "Devletin haklarının korunduğuna"], "Bina mimarisine değinilmemiştir.")
]

akisi_bozan = [
    ("(I) Bozkırda ilkbahar kısa sürer ama büyük bir coşkuyla gelir. (II) Karların ardından her yanı rengârenk çiçekler bürür. (III) Türkiye'de küçükbaş hayvancılık en çok İç Anadolu'da yaygındır. (IV) Güneşle birlikte dereler coşkuyla akar. (V) Çocuklar kırlarda neşeyle koşar.\n\nAkışı bozan cümle hangisidir?", "III", ["I", "II", "IV", "V"], "Hayvancılık bilgisi doğa tasvirinin akışını bozmaktadır."),
    ("(I) Kitap fuarları okur ile yazar arasındaki engelleri kaldıran buluşma alanıdır. (II) Okurlar yazarlarla sohbet edip kitap imzalatır. (III) Düzenlenen paneller kültürel hayatı zenginleştirir. (IV) Kâğıt maliyetlerindeki artış yayıncıları zorlamaktadır. (V) Bu şölen edebiyat ilgisini artırır.\n\nAkışı bozan cümle hangisidir?", "IV", ["I", "II", "III", "V"], "Kâğıt fiyatları fuarın atmosferiyle bağdaşmamaktadır."),
    ("(I) Klasik Türk musikisi yüzyılların birikimini taşıyan asil bir sanattır. (II) Makamlar insan ruhuna dinginlik verir. (III) Ney ve tanbur bu müziğin temel sazlarıdır. (IV) Gençler günümüzde pop müzik dinlemektedir. (V) Bu zengin miras geleceğe aktarılmalıdır.\n\nAkışı bozan cümle hangisidir?", "IV", ["I", "II", "III", "V"], "Pop müzik dinleme tercihi akışı bozmuştur."),
    ("(I) Safranbolu geleneksel Türk kent dokusunu yaşatan canlı bir müzedir. (II) Çarşıda geleneksel bakırcılık zanaatı sürmektedir. (III) İlçe UNESCO Dünya Mirası Listesi'ndedir. (IV) Konaklar ahşap işçiliğiyle dikkat çeker. (V) Safranbolu'nun nüfusu hızla artmaktadır.\n\nAkışı bozan cümle hangisidir?", "V", ["I", "II", "III", "IV"], "Nüfus verisi mimari tasvirin akışını bozmuştur."),
    ("(I) Sabah yürüyüşleri kalp sağlığını korumanın en pratik yoludur. (II) Güne hafif sporla başlamak metabolizmayı hızlandırır. (III) Yürüyüş stresi azaltır. (IV) Plansız şehirleşme yeşil alanları yok etmektedir. (V) Haftada en az üç gün yürümek önerilir.\n\nAkışı bozan cümle hangisidir?", "IV", ["I", "II", "III", "V"], "Şehirleşme eleştirisi sağlık tavsiyesinin akışını bozmuştur."),
    ("(I) Ebru sanatı suyun üzerine yapılan kadim bir süsleme sanatıdır. (II) Kitre suyun yoğunluğunu artırır. (III) Fırçalar at kılı ve gül dalından yapılır. (IV) Kimyasal boyalar yerine toprak boyalar tercih edilir. (V) Camilerin restorasyonunda hattatlar çalışır.\n\nAkışı bozan cümle hangisidir?", "V", ["I", "II", "III", "IV"], "Hattatlar ve restorasyon ebru sanatının akışını bozmuştur."),
    ("(I) Şiir dili günlük dilin kalıplarını kırarak derin anlamlar kurar. (II) Şair sözcüklere çağrışım yükler. (III) Bu yüzden şiir tercümesi en zor edebi faaliyettir. (IV) Roman çevirmek teknik olarak daha kolaydır. (V) Şiirin ahengini başka dilde aynı güçle kurmak zordur.\n\nAkışı bozan cümle hangisidir?", "IV", ["I", "II", "III", "V"], "Roman çevirisi şiir konusunun akışını bozmuştur."),
    ("(I) Karadeniz Bölgesi bol yağış sayesinde gür ormanlara sahiptir. (II) Yamaçlar gürgen ve ladin ağaçlarıyla kaplıdır. (III) Bu bitki örtüsü zengin arıcılık sağlar. (IV) Sahil yolu ulaşımı kolaylaştırmıştır. (V) Ormanlar doğaseverler için eşsizdir.\n\nAkışı bozan cümle hangisidir?", "IV", ["I", "II", "III", "V"], "Ulaşım projesi orman tasvirinin akışını bozmuştur."),
    ("(I) Divan edebiyatında gazel aşk konusunu işleyen temel nazım şeklidir. (II) Beyit sayısı 5-15 arasındadır. (III) Son beyitte mahlas geçer. (IV) Halk edebiyatında koşmalar 11'li heceyledir. (V) En güzel beytine beytü'l-gazel denir.\n\nAkışı bozan cümle hangisidir?", "IV", ["I", "II", "III", "V"], "Halk şiiri koşması gazel konusunun akışını bozmuştur."),
    ("(I) Kahve 16. yüzyılda Osmanlı'ya girmiş ve zengin bir kültür oluşturmuştur. (II) Türk kahvesi pişirme tarzıyla özgündür. (III) Kahvehaneler aydınların toplanma yeri olmuştur. (IV) Brezilya kahve üretiminde liderdir. (V) Türk kahvesi UNESCO miras listesindedir.\n\nAkışı bozan cümle hangisidir?", "IV", ["I", "II", "III", "V"], "Brezilya kahve üretimi akışı bozmuştur.")
]
