# turkce_data_2.py - Q6 to Q11
yazimlar = [
    ("Yeni açılan tesiste görev alan uzmanlar, dünkü toplantıda <u>birçok</u> (I) konuyu ele aldı. Hazırlıkların <u>laboratuar</u> (II) aşamasında aksaklık yaşansa da ekip <u>özveriyle</u> (III) çalışarak <u>her şeyi</u> (IV) zamanında <u>teslim etti</u> (V).", "II", ["I", "III", "IV", "V"], "'laboratuar' değil, TDK'ye göre doğru yazımı 'laboratuvar' şeklindedir."),
    ("Yazarın <u>orjinal</u> (I) elyazmalarını inceleyen kurul, <u>birtakım</u> (II) yeni bulgulara ulaştı. Kütüphanedeki <u>baş başa</u> (III) geçen saatler, araştırmacıların <u>pek çok</u> (IV) gizemi <u>aydınlatmasını</u> (V) sağladı.", "I", ["II", "III", "IV", "V"], "'orjinal' değil, TDK kurallarına göre 'orijinal' şeklinde yazılmalıdır."),
    ("Şehrin tarihi sokaklarında yürürken <u>yanı sıra</u> (I) uzanan asırlık çınarları seyrettik. Gezide bize eşlik eden <u>klavuz</u> (II) rehber, <u>hiçbir</u> (III) detayı atlamadan <u>hoşsohbet</u> (IV) bir tavırla <u>bilgi verdi</u> (V).", "II", ["I", "III", "IV", "V"], "'klavuz' değil, TDK'ye göre 'kılavuz' olmalıdır."),
    ("Sabah erkenden kalkıp <u>tıraş</u> (I) olan genç memur, dolabındaki <u>kıravatı</u> (II) özenle bağladı. Masasındaki <u>resmî</u> (III) evrakları düzenlerken <u>art arda</u> (IV) gelen telefonlara da <u>cevap verdi</u> (V).", "II", ["I", "III", "IV", "V"], "'kıravat' değil, doğru yazımı 'kravat' şeklindedir."),
    ("Olay yerine hızla intikal eden <u>komser</u> (I), çevredeki tanıkları dinledi. Olayın <u>farkında</u> (II) olan mahalle sakinleri, <u>art niyetli</u> (III) kişilerin <u>suçüstü</u> (IV) yakalanmasından <u>memnun oldu</u> (V).", "I", ["II", "III", "IV", "V"], "'komser' değil, TDK imla kılavuzuna göre 'komiser' olmalıdır."),
    ("Uzun yolculuk boyunca cep telefonunun <u>şarzı</u> (I) bitmesin diye uğraştı. Otobüsün <u>egzoz</u> (II) dumanından rahatsız olunca pencereyi <u>biraz</u> (III) araladı ve <u>hiç kimseye</u> (IV) hissettirmeden <u>uyuyakaldı</u> (V).", "I", ["II", "III", "IV", "V"], "'şarz' değil, doğru yazımı 'şarj' olmalıdır."),
    ("Trafik denetimlerinde araçların <u>egzos</u> (I) emisyon ölçümleri titizlikle yapıldı. Kurallara uymayan sürücülere <u>idari para cezası</u> (II) kesilirken <u>herhangi bir</u> (III) tolerans <u>tanınmadı</u> (IV) ve tutanaklar <u>düzenlendi</u> (V).", "I", ["II", "III", "IV", "V"], "'egzos' değil, doğru yazılışı 'egzoz' şeklindedir."),
    ("Yıllardır özenle biriktirdiği pul <u>kolleksiyonunu</u> (I) müzayedede sergiledi. Sergiye katılan <u>bilim insanları</u> (II), nadide parçalara <u>büyük bir</u> (III) hayranlıkla bakarken <u>hiçbir</u> (IV) fırsatı <u>kaçırmadı</u> (V).", "I", ["II", "III", "IV", "V"], "'kolleksiyon' değil, tek l ile 'koleksiyon' yazılmalıdır."),
    ("Üniversitede düzenlenen panele katılan <u>ünvanlı</u> (I) profesörler önemli tebliğler sundu. Salonu dolduran <u>öğrenciler</u> (II), konuşmaları <u>not alarak</u> (III) dikkatle dinledi ve <u>ara sıra</u> (IV) sorular <u>yöneltti</u> (V).", "I", ["II", "III", "IV", "V"], "TDK güncel kılavuzuna göre 'ünvan' değil 'unvan' şeklinde yazılır."),
    ("Resmî törende <u>başöğretmen</u> (I) Atatürk'ün ilkeleri yâd edildi. Meydanda toplanan <u>kalabalık</u> (II), marşlara <u>coşkuyla</u> (III) eşlik ederken tören alanında <u>herbiri</u> (IV) gururla bayrak <u>dalgalandırdı</u> (V).", "IV", ["I", "II", "III", "V"], "'herbiri' bitişik değil, 'her biri' şeklinde ayrı yazılmalıdır.")
]

buyuk_harf = [
    ("Aşağıdaki cümlelerin hangisinde 'de/da' bağlacının yazımıyla ilgili bir YANLIŞLIK yapılmıştır?", "Kitapta ki bilgilerin doğruluğunu teyit etmek gerekir.", ["Sen de bizimle birlikte kütüphaneye gelmek ister misin?", "Evde de işte de her zaman disiplinli bir insandı.", "Sınavda başarılı olmak için çok çalıştı da ancak istediği puanı alamadı.", "Dün akşam bize uğradı da fazla kalamadan gitti."], "'-ki' sıfat yapan aitlik ekidir ve bitişik yazılmalıdır (Kitaptaki)."),
    ("Aşağıdaki cümlelerin hangisinde büyük harflerin yazımıyla ilgili bir YANLIŞLIK yapılmıştır?", "Güneydoğu anadolu Bölgesi'nde yaz ayları oldukça kurak geçer.", ["Van Gölü çevresinde son yıllarda ekoturizm gelişmektedir.", "Toplantıya Türk Dil Kurumu Başkanı da bizzat katıldı.", "Kurtuluş Savaşı yıllarında Anadolu halkı tek yürek oldu.", "Kuzey Kıbrıs Türk Cumhuriyeti Akdeniz'in önemli bir adasıdır."], "Yer adlarında yön ve bölge adları büyük yazılır: 'Güneydoğu Anadolu Bölgesi' olmalıdır."),
    ("Aşağıdaki cümlelerin hangisinde 'ki' bağlacının yazımıyla ilgili bir YANLIŞLIK yapılmıştır?", "Duydumki unutmuşsun gözlerimin rengini.", ["Mademki gelmeyecektin, neden önceden haber vermedin?", "Oysaki bu konuda hepimiz ona sonuna kadar güvenmiştik.", "Evdeki hesap çarşıya uymayınca bütçe açık verdi.", "Anladım ki hiç kimse sen değil."], "'Duydum ki' şeklinde bağlaç olan ki ayrı yazılmalıdır."),
    ("Aşağıdaki cümlelerin hangisinde kısaltmalara gelen eklerle ilgili bir YANLIŞLIK yapılmıştır?", "TDK'nın yeni kılavuzunda bazı kelimelerin yazımı değişti.", ["Dün akşam TRT'den yapılan resmi açıklamayı izledik.", "TBMM'nin açılışının 100. yılı coşkuyla kutlandı.", "MEB'e bağlı okullarda yeni dönem başladı.", "TÜBİTAK'ın desteklediği proje sergilendi."], "Kısaltmalarda 'TDK'nin' olmalıdır; 'TDK'nın' yanlıştır."),
    ("Aşağıdaki cümlelerin hangisinde sayıların yazımı ile ilgili bir YANLIŞLIK yapılmıştır?", "Ahmet Bey bu şirkette tam onbeş yıldır aralıksız çalışıyor.", ["Yarışmada 5'inci olarak teselli ödülü kazandı.", "Cumhuriyet 29 Ekim 1923'te ilan edildi.", "Okulun 2'nci katında buluşacağız.", "Saat 14.30'da başlayacak konferansa davetliyiz."], "Metin içindeki sayılar ayrı yazılır: 'on beş' olmalıdır."),
    ("Aşağıdaki cümlelerin hangisinde birleşik fiillerin yazımı ile ilgili bir YANLIŞLIK yapılmıştır?", "Tüm aramalara rağmen kayıp cüzdan bir türlü farkedilmedi.", ["Kendisine yapılan bu büyük haksızlığı asla affetmedi.", "Zor durumdaki adama hemen yardım etti.", "Beklenmedik misafir gelince evi alelacele terk etti.", "Miras kalan eski konağı kardeşine devretti."], "Ses olayı olmayan birleşik fiiller ayrı yazılır: 'fark edilmedi' olmalıdır."),
    ("Aşağıdaki cümlelerin hangisinde yön adlarının yazımı ile ilgili bir YANLIŞLIK yapılmıştır?", "Tatile çıkarken Güneye doğru inmeyi planlıyoruz.", ["Türkiye'nin doğu kesimlerinde kar yağışı var.", "Balkanlar üzerinden gelen hava Batı Karadeniz'i etkiledi.", "Kuzeydoğu Anadolu'da hayvancılık gelişmiştir.", "Şehrin batısına yeni konutlar yapılıyor."], "Tek başına yön adı küçük yazılır: 'güneye doğru' olmalıdır."),
    ("Aşağıdaki cümlelerin hangisinde kurum ve kuruluş adlarının yazımı ile ilgili bir YANLIŞLIK yapılmıştır?", "Türk Tarih Kurumu'na yeni araştırmacılar alındı.", ["Çankaya Lisesi Müdürlüğüne dilekçe verdi.", "Ankara Üniversitesi Rektörlüğü onayladı.", "Yeşilay Derneği mücadelede öncüdür.", "Devlet Su İşleri Genel Müdürlüğü barajı bitirdi."], "Kurum adlarına gelen ekler kesmeyle ayrılmaz: 'Türk Tarih Kurumuna' olmalıdır."),
    ("Aşağıdaki cümlelerin hangisinde unvan ve saygı sözcüklerinin yazımı ile ilgili bir YANLIŞLIK yapılmıştır?", "Avukat Kemal bey duruşmada müvekkilini savundu.", ["Doktor Ayşe Hanım hastaları karşıladı.", "Sayın Bakan kurdeleyi kesti.", "Mahallemizin muhtarı Ali Efendi sevilen biriydi.", "Gazi Mustafa Kemal Paşa önderlik etti."], "Kişi adından sonraki saygı sözü büyük başlar: 'Kemal Bey' olmalıdır."),
    ("Aşağıdaki cümlelerin hangisinde ikilemelerin yazımı ile ilgili bir YANLIŞLIK yapılmıştır?", "Çocuklar bahçede güle-oynaya neşeyle koşuşturuyordu.", ["Olayın ayrıntılarını enine boyuna tartıştılar.", "Pazardan irili ufaklı elmalar satın aldı.", "Yalan yanlış bilgilerle kamuoyunu yanılttılar.", "Eski dostlar baş başa verip dertleştiler."], "İkilemeler ayrı yazılır, araya işaret girmez: 'güle oynaya' olmalıdır.")
]

noktalama_paragraflar = [
    ("Tarihi konağın bahçesi ( ) asırlık çınarlar ( ) hanımelleri ve ıhlamur kokuları ( ) Burası insana huzur veren bir sığınaktı ( )\n\nBu parçada parantezle belirtilen yerlere sırasıyla hangi noktalama işaretleri getirilmelidir?", ": , ... .", [", , . .", "; , . !", ", ; ... .", ": ; . ..."], "Açıklama yapılacak yere iki nokta (:), eş görevli sözcükler arasına virgül (,), eksiltili cümlenin sonuna üç nokta (...), tamamlanmış cümlenin sonuna nokta (.) getirilir."),
    ("Genç yazar heyecanla sordu ( ) ( ) Bu kitabın basımı ne zaman tamamlanacak ( ) ( )\n\nBu parçada parantezle belirtilen yerlere sırasıyla hangi noktalama işaretleri getirilmelidir?", ": \" ? \"", [", ' . '", "; \" ! \"", ": ' ? '", ", \" . \""], "Konuşmadan önce iki nokta, doğrudan alıntı başına ve sonuna tırnak işareti, soru cümlesi sonuna soru işareti gelir."),
    ("Pazardan elma ( ) armut ( ) portakal ( ) bakkaldan un ( ) şeker ve çay aldı ( )\n\nParantezli yerlere sırasıyla hangi noktalama işaretleri gelmelidir?", ", , ; , .", [", , , , .", "; , : , .", ", ; , ; .", ", , : , !"], "İki farklı grubu (pazar ve bakkal alışverişini) ayırmak için noktalı virgül (;) kullanılır."),
    ("Eyvah ( ) cüzdanımı evde unuttum ( ) Şimdi ne yapacağım ( )\n\nParantezli yerlere sırasıyla hangi noktalama işaretleri gelmelidir?", ", ! ?", ["! . ?", "! ! .", ", . ?", "; ! ."], "Küçük harfle devam ettiği için virgülden sonra ünlem son kısma konur."),
    ("Romancı ( ) toplumu gözlemleyen ( ) sorunları irdeleyen ve geleceğe ışık tutan bir aydındır ( )\n\nParantezli yerlere sırasıyla hangi işaretler gelmelidir?", ", , .", ["; , .", ", ; .", ": , .", "- - ."], "Özneden sonra virgül, eş görevli sıfatlar arasına virgül, cümle sonuna nokta gelir."),
    ("İstanbul ( ) Ankara ve İzmir gibi metropoller hızla büyüyor ( ) ancak altyapı yetersiz kalıyor ( )\n\nParantezli yerlere hangi işaretler gelmelidir?", ", , .", ["; , .", ", ; .", ": . .", "- - !"], "Şehirler arasına virgül, cümle sonuna nokta konur."),
    ("Çocukluğumun geçtiği o kasaba ( ) dar sokaklar ( ) taş evler ve dost canlısı komşular ( )\n\nParantezli yerlere sırasıyla hangi işaretler gelmelidir?", ": , ...", [", , .", "; , ...", ": ; .", ", ; !"], "Açıklamadan önce iki nokta, eş ögeler arasına virgül, yüklemsiz cümle sonuna üç nokta konur."),
    ("Yazarın en beğendiğim yönü şudur ( ) Okuyucuyu hiçbir zaman küçümsemez ( ) ona daima saygı duyar ( )\n\nParantezli yerlere sırasıyla hangi işaretler gelmelidir?", ": , .", ["; , .", ", ; .", ": ; .", ". , !"], "Açıklama için iki nokta, sıralı cümle arasına virgül, sona nokta konur."),
    ("Kütüphanede herkes çıt çıkarmadan çalışıyordu ( ) sadece sayfaların çevrilme sesi duyuluyordu ( )\n\nParantezli yerlere hangi işaretler gelmelidir?", "; .", [", .", ": .", "- .", ". ..."], "Sıralı cümleleri bağlamak için noktalı virgül ve nokta gelir."),
    ("Sabahları yürüyüş yapmak ( ) zihni açar ( ) vücudu dinç tutar ve stresi azaltır ( )\n\nParantezli yerlere sırasıyla hangi işaretler gelmelidir?", ", , .", ["; , .", ", ; .", ": , .", "- , ."], "Özneyi ayırmak için virgül, yüklemler arasına virgül ve nokta konur.")
]

ses_unlu = [
    ("Aşağıdaki cümlelerin hangisinde <u>ünlü düşmesi</u> gerçekleşmiş bir sözcük vardır?", "Bebek annesinin <u>koynunda</u> mışıl mışıl uyuyordu.", ["Güneşli günlerde parkta çocuk sesleri yankılanırdı.", "Bahçedeki ağaçların dalları meyvelerle dolup taşıyordu.", "Kütüphanede sessizce kitap okuyan öğrencileri izledi.", "Denizin dalgaları kıyıdaki kayalıklara çarpıyordu."], "Koyun-u -> koynu sözcüğünde ikinci hecedeki dar ünlü 'u' düşmüştür."),
    ("Aşağıdaki sözcüklerin hangisinde <u>ünlü daralması</u> vardır?", "Ablam bahçedeki çiçekleri her sabah özenle <u>suluyor</u>.", ["Çocuklar bahçede top oynuyor.", "Kitap okumayı çok seviyor.", "Yarın sabah erkenden yola çıkıyor.", "Ders çalışırken müzik dinliyor."], "Sula-mak fiili -yor eki aldığında geniş ünlü 'a', dar ünlü 'u'ya dönüşmüştür."),
    ("Aşağıdaki cümlelerin hangisinde <u>ünlü düşmesine</u> uğramış bir sözcük YOKTUR?", "Okulun bahçesinde neşeyle koşan öğrencileri tebessümle izledi.", ["Kayıp eşyalarını bulmak için tüm odaları aradı.", "Sabırla bekleyen yolcular otobüsün gelmesiyle hareketlendi.", "Gözlerini ufuktaki karlı dağların zirvesine dikmişti.", "Aklına gelen parlak fikri hemen not defterine yazdı."], "A seçeneğinde hiçbir sözcükte ünlü düşmesi yoktur."),
    ("Aşağıdaki cümlelerin hangisinde hem <u>ünlü düşmesi</u> hem <u>ünsüz yumuşaması</u> gerçekleşmiş bir sözcük vardır?", "Küçük çocuk korkudan annesinin <u>göğsüne</u> sarıldı.", ["Kitabın kapağını dikkatlice kapattı.", "Aklını başına toplayıp sınava odaklandı.", "Yüreğindeki sevgi gözlerinden okunuyordu.", "Burnunun ucundaki gözlüğü düzeltti."], "göğüs-ü -> göğsü sözcüğünde ünlü düşmesi vardır."),
    ("Aşağıdaki cümlelerin hangisinde <u>ünlü daralmasına</u> uğramış bir sözcük vardır?", "Öğretmeninin sorduğu soruya doğru cevap vermek için günlerdir <u>bekliyor</u>.", ["Her akşam yarım saat kitap okuyor.", "Hafta sonları yürüyüşe çıkıyor.", "Kuşlar sıcak ülkelere doğru uçuyor.", "Yaz gelince yaylalara göçüyor."], "Bekle-mek fiilinde 'e' ünlüsü 'i'ye daralmıştır (bekliyor)."),
    ("Aşağıdaki altı çizili sözcüklerin hangisinde türetilirken <u>ünlü düşmesi</u> meydana gelmiştir?", "Gözleri yollarda kalan annenin hasreti günden güne <u>sarardı</u>.", ["Karnı acıkan çocuklar masaya oturdu.", "Boynu bükük bir şekilde kenarda bekledi.", "Ağzındaki lokmayı çiğnemeden yuttu.", "Burnu kanayan sporcuya ilk yardım yapıldı."], "Sarı-ar-dı -> sarardı sözcüğünde türetme esnasında 'ı' düşmüştür."),
    ("Aşağıdaki cümlelerin hangisinde 'etmek/olmak' yardımcı fiiliyle birleşirken <u>ses düşmesi</u> meydana gelmiştir?", "Yıllardır aradığı huzuru nihayet bu sakin kasabada <u>keşfetti</u>.", ["Kendisine yapılan bu büyük jesti ömür boyu unutmadı.", "Zor durumdaki komşusuna tereddüt etmeden yardım etti.", "Görevli memur evrakları dikkatle kontrol etti.", "Hastalanan arkadaşını dün hastanede ziyaret etti."], "Keşif + etti -> keşfetti sözcüğünde 'i' ünlüsü düşmüştür."),
    ("Aşağıdaki cümlelerin hangisinde <u>ünlü daralması</u> örneği vardır?", "Girdiği sınavın sonucunu öğrenmek için sabırsızlıkla <u>özlüyor</u>.", ["Pencereden dışarıdaki yağmuru izliyor.", "Koşucular bitiş çizgisine doğru hızla koşuyor.", "Radyodaki güzel şarkıyı keyifle dinliyor.", "Usta elindeki tahtayı özenle yontuyor."], "Özle-mek fiili -yor alınca 'e' ünlüsü 'ü'ye daralmıştır."),
    ("Aşağıdaki cümlelerin hangisinde aşınma (iki ünlünün birleşmesiyle ünlü düşmesi) yoluyla oluşmuş bir sözcük vardır?", "Hafta sonu arkadaşlarıyla birlikte piknik yapmak için <u>Cumartesi</u> gününü seçtiler.", ["Pazardan taze sebze ve meyveler satın aldılar.", "Okulun bahçesindeki çınarın gölgesinde oturdular.", "Akşam olunca köy meydanındaki kahvehanede toplandılar.", "Tarihi köprünün üzerinden ağır vasıtalar geçiyordu."], "Cuma + ertesi -> Cumartesi sözcüğünde aşınma olmuştur."),
    ("Aşağıdaki cümlelerin hangisinde altı çizili sözcükte <u>ünlü düşmesi</u> YOKTUR?", "Bahçedeki <u>çiçeğin</u> kokusu tüm odayı sarmıştı.", ["Toplantıda alınan kararlara <u>fikren</u> katılıyordu.", "Olayın <u>aslını</u> öğrenmeden kimseyi suçlamayınız.", "Müfettiş tüm dosyaları <u>kaydetti</u>.", "Kafasındaki <u>resmi</u> tabloya aktarmaya çalıştı."], "Çiçeğin sözcüğünde yumuşama vardır, ünlü düşmesi yoktur.")
]

virgul_islev = [
    ("Aşağıdaki cümlelerin hangisinde virgül (,) <u>sıralı cümleleri</u> birbirinden ayırmak amacıyla kullanılmıştır?", "Güneş yavaşça battı, ufuk kızıla boyandı.", ["Pazardan elma, armut ve üzüm aldı.", "Genç doktor, hastalarını kapıda güler yüzle karşıladı.", "Akşam, yine akşam, yine akşam...", "Evet, ben de sizinle aynı fikirdeyim."], "İki ayrı yüklemli cümleyi birbirine bağlamıştır."),
    ("Aşağıdaki cümlelerin hangisinde noktalı virgül (;) <u>ögeleri arasında virgül bulunan sıralı cümleleri</u> ayırmak için kullanılmıştır?", "At ölür, meydan kalır; yiğit ölür, şan kalır.", ["Sevinçten, heyecandan içim içime sığmıyor; bağırmak, ağlamak istiyorum.", "Türkiye, Azerbaycan; Bakü, Ankara.", "Ali; Hasan, Mehmet ve Can'dan daha uzundur.", "Roman, hikâye olay anlatır; makale, deneme fikir yazısıdır."], "Ögeleri arasında virgül bulunan sıralı cümleleri ayırmıştır."),
    ("Aşağıdaki cümlelerin hangisinde virgül <u>anlam karışıklığını önlemek</u> amacıyla kullanılmıştır?", "İhtiyar, polise meraklı gözlerle baktı.", ["Bahçedeki sarı, kırmızı ve beyaz güller açmıştı.", "Koştu, yetişti, trene bindi.", "Değerli konuklar, hoş geldiniz.", "Yarın erkenden yola çıkacağız, dedi."], "Virgül kalkarsa 'ihtiyar polis' sıfat tamlaması oluşur."),
    ("Aşağıdaki cümlelerin hangisinde iki nokta (:) yanlış kullanılmıştır?", "En sevdiği meyveler şunlardı; çilek, kiraz ve vişne.", ["Aklıma gelen ilk soru şuydu: Neden daha önce düşünemedik?", "Atatürk şöyle demiştir: 'Ne mutlu Türk'üm diyene!'", "Kütüphanede iki tür kitap vardı: Romanlar ve ansiklopediler.", "Kendimi tanıtayım: Ben bu okulun rehber öğretmeniyim."], "Açıklamadan önce noktalı virgül değil, iki nokta (:) konur."),
    ("Aşağıdaki cümlelerin hangisinde kesme işareti (') YANLIŞ kullanılmıştır?", "Ahmetler'in evinde bu akşam toplantı yapılacakmış.", ["Cumhurbaşkanı'nın açıklaması yankı buldu.", "TBMM'nin kararları Resmi Gazete'de yayımlandı.", "1923'te kurulan cumhuriyetimizle gurur duyuyoruz.", "Boğaz Köprüsü'nün bakımı tamamlandı."], "Çoğul eki (-ler) kesmeyle ayrılmaz (Ahmetlerin)."),
    ("Aşağıdaki cümlelerin hangisinde tırnak işareti (\") yanlış kullanılmıştır?", "Toplantı salonundaki herkes 'büyük bir merakla' bekliyordu.", ["Yazarın son kitabındaki 'yalnızlık' teması dikkat çekiyor.", "Öğretmenimiz: 'Ders kitaplarınızı açın.' dedi.", "Atatürk'ün 'Yurtta sulh, cihanda sulh' sözü evrenseldir.", "Bu konuda 'bilimsel' araştırmaların sayısı yetersizdir."], "Sıradan bir zarf tümleci tırnak içine alınmaz."),
    ("Aşağıdaki cümlelerin hangisinde üç nokta (...) KULLANILMAZ?", "Söylediklerimi dikkatle dinleyen genç adam hızla uzaklaştı...", ["Ufukta mor dağlar, masmavi bir gökyüzü...", "Kılavuzu karga olanın burnu ... çıkmaz.", "Bizi karşılayan yetkili sordu: Adınız, memleketiniz...", "Karşı kıyıda küçük balıkçı tekneleri, martı çığlıkları..."], "Yüklemi olan tamamlanmış cümlenin sonuna nokta konur."),
    ("Aşağıdaki cümlelerin hangisinde virgül <u>ara sözü</u> ayırmak amacıyla kullanılmıştır?", "Doğup büyüdüğüm o şirin kasabayı, çocukluğumun cennetini, hiç unutamam.", ["Kitapları, defterleri ve kalemleri çantasına yerleştirdi.", "Gülümseyerek içeri girdi, ceketini askıya astı.", "Ahmet, sınıfın en çalışkan öğrencisiydi.", "Yarın sabah, saat tam sekizde burada toplanıyoruz."], "'çocukluğumun cennetini' nesnenin açıklayıcısı bir ara sözdür."),
    ("Aşağıdaki cümlelerin hangisinde soru işareti (?) YANLIŞ kullanılmıştır?", "Bunu bana neden daha önce söylemediğini bir türlü anlayamadım?", ["Bu zor soruların hepsini tek başına mı çözdün?", "Yunus Emre (1240?-1320) tasavvufun öncüsüdür.", "Ankara'dan Konya'ya 1,5 saatte (?) gitmiş.", "Sınav sonuçları ne zaman açıklanacak acaba?"], "Cümle soru cümlesi değildir, sonuna nokta konmalıdır."),
    ("Aşağıdaki cümlelerin hangisinde ünlem işareti (!) alay anlamı katmak için parantez içinde [(!)] kullanılmıştır?", "Bu dahi arkadaşımız sınavda sıfır puan almayı başarmış (!)", ["Aşk olsun sana, nasıl böyle düşünürsün!", "Dur, yolcu! Bilmeden gelip bastığın bu toprak...", "Ey Türk gençliği! Birinci vazifen...", "Vah vah, zavallı kedi çok üşümüş!"] , "Parantez içi ünlem alay ve kinaye için kullanılır.")
]

ses_unsuz = [
    ("Aşağıdaki cümlelerin hangisinde <u>ünsüz sertleşmesi</u> kuralına uyulmamasından kaynaklanan bir yazım yanlışı vardır?", "Otobüs terminalden saat 14.00'<u>de</u> hareket edecekmiş.", ["Sınıftaki öğrenciler öğretmeni dikkatle dinliyordu.", "Ağaçtaki elmalar olgunlaşınca toplandı.", "Sokaktaki lambalar akşam yandı.", "Kitapta anlatılan olaylar beni etkiledi."], "14'te sertleşme kuralı olmalıydı: 14.00'te."),
    ("Aşağıdaki cümlelerin hangisinde <u>ünsüz yumuşaması</u> kuralına aykırı bir durum vardır?", "Girdiği sınavda <u>hukukun</u> üstünlüğünü savundu.", ["Dolabın kapağını yavaşça araladı.", "Yüreğindeki sevgiyi herkese hissettirirdi.", "Ekmeğin bayatlamaması için poşete koydu.", "Çocuğun elindeki balonu havaya bıraktı."], "'Hukuk' yabancı kökenli olup yumuşamaya aykırıdır."),
    ("Aşağıdaki altı çizili sözcüklerin hangisinde <u>ünsüz türemesi</u> vardır?", "Mahkemenin verdiği bu haksız kararı <u>reddetti</u>.", ["Yaptığı fedakârlığı herkes takdir etti.", "Kendisine verilen emanete sahip çıktı.", "Dostunun zor gününde yanında yer aldı.", "Sorulan tüm sorulara içtenlikle cevap verdi."], "Red + etti -> reddetti eyleminde 'd' türemiştir."),
    ("Aşağıdaki cümlelerin hangisinde hem <u>ünsüz benzeşmesi</u> hem de <u>ünsüz yumuşaması</u> vardır?", "Köylüler sabah erkenden kalkıp <u>yaptıkları</u> işleri gözden geçirdiler.", ["Güneş batarken sahil boyunca yürüdü.", "Kütüphanedeki eski kitapları inceledi.", "Sınav salonundaki sessizlik herkesi gerdi.", "Bahar gelince kırlar çiçek açtı."], "yap-tık (benzeşme) ve tık-ı -> tığı (yumuşama) vardır."),
    ("Aşağıdaki cümlelerin hangisinde <u>kaynaştırma ünsüzü</u> KULLANILMAMIŞTIR?", "Dün akşam kütüphaneden üç kitap ödünç aldım.", ["Bahçedeki ağacın dalına kuşlar konmuştu.", "İkişer ikişer sıraya geçip içeri girdiler.", "Çantasını masanın üzerine bıraktı.", "Suyun sıcaklığını parmağıyla kontrol etti."], "A seçeneğinde kaynaştırma harfi bulunmamaktadır."),
    ("Aşağıdaki cümlelerin hangisinde <u>ünsüz düşmesi</u> örneği vardır?", "Gözlerinin önünde büyüyen <u>minicik</u> yavru kedi sevimli hareketler yapıyordu.", ["Büyük bir özveriyle projeyi tamamladılar.", "Soğuk havada elleri üşümüştü.", "Hızlı adımlarla durağa doğru yürüdü.", "Okulun bahçesi temizlendi."], "Minik-cik -> minicik sözcüğünde 'k' ünsüzü düşmüştür."),
    ("Aşağıdaki cümlelerin hangisinde <u>ünsüz sertleşmesine</u> uğramış birden fazla sözcük vardır?", "Kışın <u>soğukta</u> <u>sertçe</u> esen rüzgâr camları sarsıyordu.", ["Pazardan taze sebzeler aldık.", "Sabah erkenden yola koyulduk.", "Kitabın sayfalarını tek tek çevirdi.", "Güzel bir tatil planı yaptık."], "'Soğukta' (k-t) ve 'sertçe' (t-ç) her ikisinde benzeşme vardır."),
    ("Aşağıdaki cümlelerin hangisinde büyük ünlü uyumuna UYMAYAN bir sözcük vardır?", "Şehrin merkezindeki tarihi <u>tiyatro</u> binası restore edildi.", ["Bahçedeki sarı güller açtı.", "Ormandaki ulu ağaçlar rüzgârda sallanıyordu.", "Akşam serinliğinde yürüyüşe çıktık.", "Çocuklar sokakta oyun oynuyordu."], "'Tiyatro' (i-a-o) büyük ünlü uyumuna uymaz."),
    ("Aşağıdaki sözcüklerin hangisinde küçük ünlü uyumuna AYKIRILIK vardır?", "Köyün hemen yanındaki tarlaya <u>karpuz</u> ekmişlerdi.", ["Odunları sobaya attı.", "Gözlerini ufka dikti.", "Gülümseyerek içeri girdi.", "Kapıyı usulca kapattı."], "'karpuz' (a'dan sonra u gelmesi) küçük ünlü uyumuna aykırıdır."),
    ("Aşağıdaki cümlelerin hangisinde <u>ulama</u> örneği vardır?", "Dün akşam eve dönerken <u>yoldan bir</u> arkadaşımla karşılaştım.", ["Kış mevsimi bu yıl oldukça sert geçti.", "Pencereden dışarıdaki yağmuru seyrettik.", "Çocuklar neşeyle parka koştu.", "Kuşlar yüksek ağaçların dallarına yuva yaptı."], "'Dün akşam' ifadesinde ünsüzle bitip ünlüyle başlayan sözcükte ulama vardır.")
]
