# turkce_data_5.py - Q25 to Q30
ikiye_bolme = [
    ("(I) Göbeklitepe Şanlıurfa'da neolitik bir yerleşimdir. (II) 12 bin yıl öncesine tarihlenen T biçimli dikilitaşlar bulunmuştur. (III) Taşlarda leopar ve tilki kabartmaları vardır. (IV) Arkeolojik keşiflerin turizme kazandırılması bölge için büyük fırsattır. (V) Şanlıurfa'da modern oteller ziyaretçi sayısını katlamıştır. (VI) Turizm esnafın yüzünü güldürmektedir.\n\nİkinci paragraf hangi cümleyle başlar?", "IV", ["II", "III", "V", "VI"], "IV'ten itibaren turizm ve ekonomi boyutuna geçilmiştir."),
    ("(I) Selçuklu çini sanatı camileri süsleyen bir sanattır. (II) Turkuaz ve kobalt mavisi temel renklerdir. (III) Kubadabad Sarayı çinileri saray yaşamını gösterir. (IV) Osmanlı çini sanatı 16. yüzyılda İznik'te zirveye çıkmıştır. (V) Mercan kırmızısının kullanımı çığır açmıştır. (VI) Sultanahmet Camii bu çinilerle donatılmıştır.\n\nİkinci paragraf hangisiyle başlar?", "IV", ["II", "III", "V", "VI"], "IV'te Osmanlı ve İznik çinisine geçilmiştir."),
    ("(I) Çocuk edebiyatı zihinsel gelişime uygun eserlerin üretildiği alandır. (II) Kitaplar hayal gücünü beslemelidir. (III) Masallar soyut kavramları somutlaştırır. (IV) Kitabın fiziksel tasarımı ve resim kalitesi de önemlidir. (V) Canlı renkler çocuğun kitaba ilgisini artırır. (VI) Resimler görsel okuma becerisi kazandırır.\n\nİkinci paragraf hangisiyle başlar?", "IV", ["II", "III", "V", "VI"], "IV'te fiziksel tasarıma geçilmiştir."),
    ("(I) Karadeniz'de çay tarımı 1930'larda başlatılmıştır. (II) Rize'nin nemli iklimi çaya uygundur. (III) Çay bölgedeki göçü önleyen temel etmendir. (IV) Çayın fabrikada işlenmesi ustalık gerektirir. (V) Toplanan yapraklar soldurulup kıvrılır. (VI) Fırınlanan çaylar paketlenir.\n\nİkinci paragraf hangisiyle başlar?", "IV", ["II", "III", "V", "VI"], "IV'te fabrikadaki işleme aşamasına geçilmiştir."),
    ("(I) İpek Yolu antik bir ticaret ağıdır. (II) Bu yolla bilimsel buluşlar kıtalar arasında taşınmıştır. (III) Kervansaraylar güvenliği sağlamıştır. (IV) Günümüzde modern 'Kuşak ve Yol' projesi başlatılmıştır. (V) Asya ve Avrupa arasında demir yolları yapılmaktadır. (VI) Türkiye bu projede kilit aktördür.\n\nİkinci paragraf hangisiyle başlar?", "IV", ["II", "III", "V", "VI"], "IV'te günümüz modern projesine geçilmiştir."),
    ("(I) Doğal beslenme işlenmemiş gıdalar alma esasına dayanır. (II) Taze sebzeler bağışıklığı güçlendirir. (III) Fermente ürünler bağırsakları korur. (IV) Sağlıklı yaşam için uyku düzeni de vazgeçilmezdir. (V) Melatonin hormonu hücreleri yeniler. (VI) Yedi saat uyumak vücudu dinç tutar.\n\nİkinci paragraf hangisiyle başlar?", "IV", ["II", "III", "V", "VI"], "IV'te uyku düzenine geçilmiştir."),
    ("(I) Yunus Emre tasavvuf şiirinin büyük kurucusudur. (II) Şiirlerinde sevgiyi duru Türkçeyle anlatmıştır. (III) Dergâhta olgunlaşmıştır. (IV) 'Risaletü'n-Nushiyye' ahlaki bir mesnevidir. (V) Eserde akıl ve sabır sembolik dille işlenmiştir. (VI) Nasihatname türünün ilk örneğidir.\n\nİkinci paragraf hangisiyle başlar?", "IV", ["II", "III", "V", "VI"], "IV'te doğrudan esere geçilmiştir."),
    ("(I) Türk halı sanatı bin yıllık bir gelenektir. (II) Pazırık Kurganı'ndaki halı Türk düğümünün kanıtıdır. (III) Motifler inançları yansıtır. (IV) Halılarda kullanılan kök boyalar doğaldır. (V) Nar kabuğu canlı renkler verir. (VI) Doğal boyalar sağlığa dosttur.\n\nİkinci paragraf hangisiyle başlar?", "IV", ["II", "III", "V", "VI"], "IV'te kök boyaya geçilmiştir."),
    ("(I) İstiklal Marşı milli orduya moral vermek için yazılmıştır. (II) Mehmet Akif para ödülü olduğu için ilk başta katılmamıştır. (III) Para ödülü almamak şartıyla şiiri kaleme almıştır. (IV) 12 Mart 1921'de mecliste alkışlarla kabul edilmiştir. (V) Marşın bestesini Osman Zeki Üngör yapmıştır. (VI) Törenlerde bu beste çalınmaktadır.\n\nİkinci paragraf hangisiyle başlar?", "IV", ["II", "III", "V", "VI"], "IV'te mecliste kabulüne geçilmiştir."),
    ("(I) Türk tiyatrosunun modernleşmesi Tanzimat'ta başlamıştır. (II) Şinasi'nin 'Şair Evlenmesi' ilk piyestir. (III) Ahmet Vefik Paşa Moliere uyarlamaları yapmıştır. (IV) Geleneksel Türk tiyatrosu doğaçlama oyunlardır. (V) Karagöz ve ortaoyunu temel türlerdir. (VI) Şive taklitleri ön plandadır.\n\nİkinci paragraf hangisiyle başlar?", "IV", ["II", "III", "V", "VI"], "IV'te geleneksel tiyatroya geçilmiştir.")
]

bosluk_doldurma = [
    ("Sanatçı toplumun acılarına ayna tutarken geleceğe dair umutları canlı tutar. Bu yüzden bir toplumun sanatçıları susturulduğunda ----.\n\nParçanın sonuna düşüncenin akışına göre hangisi getirilmelidir?", "o toplum hem geçmiş hafızasını hem de geleceğe yön veren pusulasını kaybeder", ["o toplumda ekonomik refah hızla artar", "sanat eserlerinin piyasa değeri rekor kırar", "gençler edebiyata daha fazla ilgi duyar", "bilimsel araştırmalar kendiliğinden hız kazanır"], "Pusula ve hafızanın kaybolması tamamlar."),
    ("Tarihçi belgelere sıkı sıkıya bağlı kalır. Oysa romancı ----. Belge onun için sadece bir çıkış noktasıdır; insan ruhunu hayal gücüyle yeniden inşa eder.\n\nParçada boş bırakılan yere hangisi getirilmelidir?", "tarihi olayları hayal gücünün süzgecinden geçirerek yeniden kurgular", ["tarihçinin yazdıklarını kelimesi kelimesine kopyalar", "sadece resmi antlaşmaları konu edinir", "resmi arşiv belgelerinden asla dışarı çıkmaz", "tarihleri harfiyen ezberletmeye çalışır"], "Hayal gücüyle kurgulama getirilir."),
    ("İyi konuşmacı olmanın şartı iyi bir dinleyici olabilmektir. Karşısındakini dinlemeyen biri ----. Çünkü iletişim çift yönlüdür.\n\nBoş bırakılan yere hangisi getirilmelidir?", "ne kadar süslü cümleler kurarsa kursun etkili bir iletişim kuramaz", ["her ortamda liderlik koltuğuna oturabilir", "dinleyicileri hemen ikna etmeyi başarır", "tezlerini herkese kolayca kabul ettirir", "en zor krizleri tek başına yönetir"], "İletişim kuramayacağı ifadesi tamamlar."),
    ("Gelenek ile bağ kuramayanlar kimlik bunalımı yaşar. Köklerinden kopan bir ağaç nasıl fırtınada devrilirse ----.\n\nBoş bırakılan yere hangisi getirilmelidir?", "kendi kültür ve değerlerini terk eden toplumlar da savrulup dağılır", ["geleneklerine bağlı olanlar lider olur", "yabancı kültürlerin tamamı taklit edilmelidir", "tarihi binaların yıkılması kalkınmadır", "genç kuşaklara geçmiş anlatılmamalıdır"], "Savrulup dağılma benzetmesi uygundur."),
    ("Eğitim sadece okul binalarıyla sınırlı değildir. Hayatın her anı bir öğrenme fırsatıdır. Bu gerçeği fark eden bir insan için ----.\n\nParçanın sonuna hangisi getirilmelidir?", "bütün dünya kocaman bir sınıfa, her insan da bir öğretmene dönüşür", ["okul diploması tek ve nihai hedef olur", "kitap okumaya artık ihtiyaç kalmaz", "sınavlardan yüksek not almak anlamsızlaşır", "çocukluk çağı eğitimin bittiği yerdir"], "Dünyanın sınıfa dönüşmesi tamamlar."),
    ("Bir yazar için tehlike aynı kalıpları tekrar etmesidir. Rehavete kapılan sanatçı ----. Oysa ustalık her eserde sıfırdan başlamaktır.\n\nBoş bırakılan yere hangisi getirilmelidir?", "zamanla üretkenliğini kaybederek kendi kendini taklit eden bir kopyacıya dönüşür", ["dünya çapında ölümsüz bir şöhrete kavuşur", "her eserinde daha özgün teknikler geliştirir", "okuyucu kitlesini hızla ikiye katlar", "eleştirmenlerden tam not alır"], "Kendi kopyacısı olma uyarısı tamamlar."),
    ("Teknoloji bilgiye ulaşmayı kolaylaştırdı. Ancak her şeye çabucak ulaşmaya alışan modern insan ----. Oysa derin bilgi sabır ister.\n\nBoş bırakılan yere hangisi getirilmelidir?", "sabretme, derinlemesine düşünme ve odaklanma yetisini kaybetmektedir", ["tarihteki en bilge ve sabırlı kuşak olmuştur", "kitap okuma oranlarını rekor düzeyde artırmıştır", "sosyal ilişkilerini daha güçlü kılmıştır", "doğayla iç içe yaşamayı alışkanlık edinmiştir"], "Odaklanma kaybı tamamlar."),
    ("Şiirde biçim ile içerik madalyonun iki yüzü gibidir. Usta bir şair ----.\n\nBoş bırakılan yere hangisi getirilmelidir?", "söyleyeceği düşünceyle onu ifade edeceği musiki ve biçimi dengede buluşturur", ["daima biçimsel kuralları içeriğin üzerinde tutar", "şiirlerinde yalnızca soyut konuları işler", "kafiye ve redif kurallarını tamamen terk eder", "okuyucunun anlamayacağı kapalı bir dil seçer"], "Denge tamamlar."),
    ("Çeviri sadece kelime taşımacılığı değildir. Başarılı bir çevirmen ----.\n\nBoş bırakılan yere hangisi getirilmelidir?", "sadece kelimeleri değil, metnin taşıdığı kültürel ruhu ve duyguyu da aktarır", ["sözlükteki ilk anlamları alt alta dizer", "orijinal cümle yapılarını aynen korur", "kendi fikirlerini kaynak metnin yerine koyar", "yazarın üslubunu görmezden gelir"], "Ruhu ve duyguyu aktarma uygundur."),
    ("Hatalarının söylenmesinden rahatsız olan liderler ----. Zira hataları görmek düzeltmenin ilk adımıdır.\n\nBoş bırakılan yere hangisi getirilmelidir?", "kendi yanılgılarının esiri olarak er ya da geç felaketlerle yüzleşirler", ["kurumlarını her zaman başarıya taşırlar", "çalışanlarının sevgisini tam kazanırlar", "kararlarında daima isabetli sonuç alırlar", "kriz dönemlerini en az hasarla atlatırlar"], "Yanılgıların esiri olma ifadesi tamamlar.")
]

anlatim_bicimleri = [
    ("Köyün çıkışındaki dik patikayı tırmandıkça manzara genişliyordu. Aşağıda nehir gümüş bir şerit gibi parıldıyordu. Kırmızı kiremitli evlerin bacalarından dumanlar tütüyordu.\n\nParçada hangi anlatım biçimi ağır basmaktadır?", "Betimleme", ["Tartışma", "Açıklama", "Öyküleme", "Örneklendirme"], "Gözle canlandırılan görsel tasvir (betimleme) yapılmıştır."),
    ("Bazı yazarlar romanın sadece vakit geçirtmek için yazıldığını iddia eder. Bu görüşe kesinlikle katılmıyorum. Roman, insanın varoluşunu sorgulatan derin bir aynadır.\n\nParçada hangi anlatım biçimi ağır basmaktadır?", "Tartışmacı anlatım", ["Öyküleyici anlatım", "Betimleyici anlatım", "Destansı anlatım", "Mizahi anlatım"], "Karşıt fikre tez sunularak tartışmacı anlatım yapılmıştır."),
    ("Sabah çantamı sırtlayıp istasyona koştum. Gişeden son bileti alıp hareket eden trene nefes nefese atladım. Kompartımanda kitabımı çıkarıp okumaya koyuldum.\n\nParçada hangi anlatım biçimi ağır basmaktadır?", "Öyküleme", ["Açıklama", "Tanımlama", "Tartışma", "Betimleme"], "Olay zinciri ve hareket akışı (öyküleme) vardır."),
    ("Fotosentez, klorofil taşıyan canlıların ışık enerjisini kullanarak besin üretmesi sürecidir. Bitkiler karbondioksit ve su alarak oksijen üretirler.\n\nParçada hangi anlatım biçimi ağır basmaktadır?", "Açıklayıcı anlatım", ["Öyküleyici anlatım", "Tartışmacı anlatım", "Betimleyici anlatım", "Emredici anlatım"], "Bilimsel bilgi veren açıklayıcı anlatımdır."),
    ("Edebiyatımızda milli bilincin uyanmasında şairler rol oynamıştır. Mehmet Akif İstiklal Marşı ile, Namık Kemal Vatan yahut Silistre ile bu ateşi yakmıştır.\n\nParçada hangi düşünceyi geliştirme yolu kullanılmıştır?", "Örneklendirme", ["Tanık gösterme", "Sayısal veri", "Benzetme", "Tanımlama"], "İsim ve eser örnekleri verilmiştir."),
    ("Roman ile hikâye arasındaki fark olay örgüsündedir. Hikâye tek bir olayı ele alırken roman iç içe geçmiş olaylar zincirini inceler.\n\nParçada hangi yol ağır basmaktadır?", "Karşılaştırma", ["Tanık gösterme", "Benzetme", "Örneklendirme", "Alıntı yapma"], "İki edebi tür kıyaslanmıştır."),
    ("Kitap okumak insanın iç dünyasını aydınlatan en güçlü fenerdir. O fener olmaksızın karanlık dehlizlerde insan tökezler.\n\nParçada hangi düşünceyi geliştirme yolu belirgindir?", "Benzetme", ["Sayısal veri", "Tanık gösterme", "Örneklendirme", "Tanımlama"], "Kitap fenere benzetilmiştir."),
    ("Sanatçının görevi topluma ayna tutmaktır. Nitekim Tolstoy da şöyle der: 'Sanat, bir insanın yaşadığı duyguyu başkalarına aktarmasıdır.'\n\nParçada hangi yol kullanılmıştır?", "Tanık gösterme (Alıntı yapma)", ["Benzetme", "Sayısal veri", "Tanımlama", "Betimleme"], "Yazarın sözü doğrudan alıntılanmıştır."),
    ("TÜİK verilerine göre, halk kütüphanelerinden yararlanan kişi sayısı bir önceki yıla göre %15 artarak 25 milyona ulaşmıştır.\n\nParçada hangi yol kullanılmıştır?", "Sayısal verilerden yararlanma", ["Tanık gösterme", "Benzetme", "Karşılaştırma", "Tartışma"], "İstatistiki rakamlar kullanılmıştır."),
    ("Lirik şiir, şairin coşkulu duygularını, aşkını ve hüznünü dile getiren duygusal şiir türüdür.\n\nParçada hangi yol kullanılmıştır?", "Tanımlama", ["Örneklendirme", "Tanık gösterme", "Sayısal veri", "Benzetme"], "'Lirik şiir nedir?' sorusunun yanıtı verilmiştir.")
]

anlatim_nitelikleri = [
    ("Bir yazarın eserlerinde gereksiz tek bir sözcüğe dahi yer vermemesi hangi anlatım niteliğidir?", "Duruluk", ["Özgünlük", "Akıcılık", "Açıklık", "Evrensellik"], "Gereksiz sözcük bulundurmama duruluktur."),
    ("Metnin hiçbir engele takılmadan, telaffuzu zor sözcükler olmadan akıp gitmesi hangi niteliktir?", "Akıcılık", ["Özgünlük", "Yoğunluk", "Ulusalcılık", "Tutarlılık"], "Ses ve söyleyiş kolaylığı akıcılıktır."),
    ("Bir sanatçının başkalarına benzememesi, taklitten uzak kendine has üslubu hangi niteliktir?", "Özgünlük", ["Duruluk", "Doğallık", "Açıklık", "Yalınlık"], "Kendine has olma özgünlüktür."),
    ("Metnin okuyan herkes tarafından aynı şekilde anlaşılması, kapalılık içermemesi hangi niteliktir?", "Açıklık", ["Özgünlük", "Özlülük", "Akıcılık", "Sürükleyicilik"], "Tek ve net anlam açıklıktır."),
    ("Az sözle çok şey anlatma, atasözleri gibi derin anlamlar barındırma hangi niteliktir?", "Özlülük (Yoğunluk)", ["Duruluk", "Yalınlık", "Akıcılık", "Evrensellik"], "Az sözcükle çok anlam özlülüktür."),
    ("Yapmacıklıktan uzak, samimi, içten üslup hangi niteliği gösterir?", "Doğallık (İçtenlik)", ["Özgünlük", "Duruluk", "Kapalılık", "Yoğunluk"], "Samimiyet doğallıktır."),
    ("Söz sanatlarından ve ağdalı sözcüklerden uzak sade dil hangi niteliktir?", "Yalınlık (Sadelik)", ["Duruluk", "Özgünlük", "Akıcılık", "Açıklık"], "Süssüzlük yalınlıktır."),
    ("Bir eserin tüm insanlığı ilgilendiren değerleri konu edinmesi hangi niteliktir?", "Evrensellik", ["Yerellik", "Duruluk", "Yalınlık", "Özlülük"], "Tüm dünyaya hitap evrenselliktir."),
    ("Eserin aradan yüzyıllar geçse bile değerini yitirmemesi hangi niteliktir?", "Kalıcılık (Ölümsüzlük)", ["Doğallık", "Yalınlık", "Duruluk", "Açıklık"], "Zamana direnme kalıcılıktır."),
    ("İleri sürülen düşüncelerin birbiriyle çelişmemesi hangi anlatım niteliğidir?", "Tutarlılık", ["Özgünlük", "Akıcılık", "Yalınlık", "Özlülük"], "Mantıksal uyum tutarlılıktır.")
]

sozel_mantik_1 = [
    ("Ali, Burak, Ceren, Derya ve Elif hafta içi nöbet tutacaktır:\n- Ceren çarşamba nöbetçidir.\n- Ali'nin nöbeti Burak'tan hemen öncedir.\n- Elif cuma günü değildir.\n\nBuna göre Ali hangi gün nöbetçi OLAMAZ?", "Cuma", ["Pazartesi", "Salı", "Çarşamba", "Perşembe"], "Ali cuma olursa Burak için gün kalmaz."),
    ("A, B, C, D ve E koşucuları yarışmıştır:\n- A yarışı B'den önce, C'den sonra bitirmiştir.\n- E yarışı birinci bitirmiştir.\n- D yarışı sonuncu bitirmemiştir.\n\nSonuncu kimdir?", "B", ["A", "C", "D", "E"], "Sıralama E > C > A > D > B'dir; sonuncu B'dir."),
    ("1'den 5'e masalara Ahmet, Banu, Can, Deniz, Ece oturacaktır:\n- Can 3 numaradadır.\n- Ahmet ve Banu yan yanadır.\n- Deniz 1'de değildir.\n\n1 numaralı masada kim oturmaktadır?", "Ece", ["Ahmet", "Banu", "Can", "Deniz"], "1'e Ece kalır."),
    ("Matematik, Türkçe, Tarih, Coğrafya, Felsefe sınavları yapılacaktır:\n- Tarih Türkçe'den hemen sonradır.\n- Matematik çarşambadır.\n- Felsefe cuma değildir.\n\nCuma günü hangi sınav vardır?", "Coğrafya", ["Matematik", "Türkçe", "Tarih", "Felsefe"], "Cuma gününe Coğrafya kalır."),
    ("Beş katlı binada Ali, Bekir, Cemil, Davut, Enes oturmaktadır:\n- Cemil 3. kattadır.\n- Davut Ali'nin hemen üstündedir.\n- Bekir 5. katta değildir.\n\n5. katta kim oturmaktadır?", "Enes", ["Ali", "Bekir", "Cemil", "Davut"], "5. kata Enes oturur."),
    ("K, L, M, N, P filmleri yarışmıştır:\n- P birinci olmuştur.\n- K filmi L'den yüksektir.\n- M filmi K'den sonra üçüncü olmuştur.\n\nDördüncü film hangisidir?", "L", ["K", "M", "N", "P"], "Dördüncü L'dir."),
    ("1-5 park yerlerine Sarı, Kırmızı, Mavi, Beyaz, Siyah araç park etmiştir:\n- Sarı 3'tedir.\n- Kırmızı ve Mavi yan yanadır.\n- Beyaz 5'te değildir.\n\n5 numarada hangi araç vardır?", "Siyah", ["Kırmızı", "Mavi", "Sarı", "Beyaz"], "5 numarada Siyah araç vardır."),
    ("A, B, C, D, E boy sırasındadır:\n- C en uzundur.\n- A, B'den uzun fakat D'den kısadır.\n- E en kısa değildir.\n\nEn kısa kimdir?", "B", ["A", "C", "D", "E"], "En kısa B'dir."),
    ("Aslı, Bora, Ceyda, Deren, Emre 1-5 grup lideridir:\n- Ceyda 2. gruptadır.\n- Aslı ile Bora ardışıktır.\n- Emre sonuncu değildir.\n\n5. grup lideri kimdir?", "Deren", ["Aslı", "Bora", "Ceyda", "Emre"], "5. grup Deren'dir."),
    ("İzmir, Ankara, Bursa, Antalya, Trabzon seferleri vardır:\n- Ankara çarşambadır.\n- İzmir Bursa'dan hemen öncedir.\n- Antalya cuma değildir.\n\nCuma günü hangi sefer vardır?", "Trabzon", ["İzmir", "Ankara", "Bursa", "Antalya"], "Cuma gününe Trabzon kalır.")
]

sozel_mantik_2 = [
    ("Gişe ve kredi departmanlarında 6 kişi çalışmaktadır (Ali, Burak, Can, Deniz, Ece, Ferhat):\n- Her grupta 3 kişi vardır.\n- Ali ve Burak aynı gruptadır.\n- Ece gişededir.\n\nAli ve Burak gişedeyse kredi grubunda KESİNLİKLE kim vardır?", "Ferhat", ["Can", "Deniz", "Ece", "Ali"], "Gişe dolmuştur; Ferhat kesinlikle kredidedir."),
    ("Voleybol ve basketbolda 3'er sporcu vardır (A, B, C, D, E, F):\n- A ve B basketboldadır.\n- C ve D aynı branştadır.\n\nVoleybol branşındaki sporcular kimlerdir?", "C, D ve E/F", ["A, B, C", "B, C, D", "A, E, F", "B, D, E"], "C ve D voleybola gider."),
    ("A ve B dersliklerinde 3'er öğrenci sınava girecektir (K, L, M, N, O, P):\n- K ve L, A'dadır.\n- M ve N farklı sınıftadır.\n- P, B'dedir.\n\nA dersliğindeki üçüncü öğrenci kim olabilir?", "M veya N", ["O", "P", "K", "L"], "M veya N'den biridir."),
    ("6 müşteri çay ve kahve siparişi vermiştir (1-6):\n- 1, 2, 5 kahve almıştır.\n- 3, 4 çay almıştır.\n\n6 numaralı müşteri ne almıştır?", "Çay", ["Kahve", "Meyve suyu", "Limonata", "Soda"], "Kahve 3 kişiyle dolmuştur; çay kalır."),
    ("A-F 6 kişiye altın, gümüş, bronz madalya verilmiştir:\n- A ve B altın almıştır.\n- C gümüş almıştır.\n- D ve E aynı renk madalya almıştır.\n\nF hangi madalyayı almıştır?", "Gümüş", ["Altın", "Bronz", "Platin", "Demir"], "F gümüş madalya almıştır."),
    ("Roma ve Paris turlarında 3'er kişi vardır:\n- Ali, Veli, Can Roma turundadır.\n\nCem hangi tura katılmıştır?", "Paris", ["Roma", "Londra", "Madrid", "Berlin"], "Roma dolmuştur, Paris'e katılmıştır."),
    ("Sabah ve öğle oturumunda 3'er konuşmacı vardır:\n- Ahmet ve Bekir sabahtadır.\n- Dursun ve Enver aynı oturumdadır.\n\nFaruk hangi oturumdadır?", "Sabah oturumu", ["Öğle oturumu", "Akşam oturumu", "Açılış", "Kapanış"], "Faruk sabah oturumundadır."),
    ("Zemin ve 1. katta 3'er reyon vardır:\n- Kozmetik, Kırtasiye, Elektronik 1. kattadır.\n\nZüccaciye hangi kattadır?", "Zemin kat", ["1. kat", "2. kat", "Bodrum", "Çatı"], "1. kat doludur; zemin kattadır."),
    ("Yüzme ve teniste 3'er öğrenci vardır:\n- D ve E yüzmededir.\n- F tenistedir.\n\nYüzmedeki üçüncü kişi kimdir?", "A, B veya C'den biri", ["F", "D", "E", "Hiçbiri"], "A, B veya C'den biridir."),
    ("Tenor ve basta 3'er solist vardır:\n- Can, Dursun, Emre bas grubundadır.\n\nFerhat hangi gruptadır?", "Tenor", ["Bas", "Soprano", "Alto", "Bariton"], "Bas dolmuştur, tenordur.")
]
