# turkce_data_3.py - Q12 to Q18
yapi_qs = [
    ("Aşağıdaki cümlelerin hangisinde altı çizili sözcük <u>hem yapım hem çekim eki</u> almıştır?", "Yazarın son romanındaki <u>gözlemleri</u> okuru derinden etkiledi.", ["Masanın üzerindeki kitapları topladı.", "Okulun bahçesinde çiçekler açtı.", "Sokak lambaları akşamları yanar.", "Dostluk insan hayatının en değerli bağıdır."], "Göz-le-m (yapım) + ler-i (çekim) ekleri almıştır."),
    ("Aşağıdaki sözcüklerden hangisinin kökü <u>türü bakımından (isim/fiil)</u> diğerlerinden farklıdır?", "Koşucu", ["Gözlükçü", "Tuzluk", "Evcil", "Kışlık"], "'Koşucu' kökü 'koş-' fiilidir; diğerlerininki isimdir."),
    ("Aşağıdaki cümlelerin hangisinde birleşik sözcük oluşurken <u>tür kayması</u> yoluyla oluşmuştur?", "Bahçeye diktiğimiz <u>gecekondu</u> hızla tamamlandı.", ["Meydandaki <u>kuşburnu</u> çalıları budandı.", "Gökyüzünde parlayan <u>samanyolu</u> harikaydı.", "Kahvaltıda <u>vişneçürüğü</u> reçel yedik.", "Deniz kenarındaki <u>karatavuk</u> uçtu."], "Gece (isim) ve kondu (fiil) birleşerek isimleşmiştir."),
    ("Aşağıdaki altı çizili sözcüklerden hangisi yapısı bakımından <u>basit</u> bir sözcüktür?", "Odanın <u>duvarları</u> yeni boyanmıştı.", ["Tarihi eserleri <u>korumalıyız</u>.", "Yolcular terminalde <u>bekleşiyordu</u>.", "Kuşlar yükseklerde <u>süzülüyordu</u>.", "Yaptığı hatayı hemen <u>düzellti</u>."], "Duvar-lar-ı sadece çekim ekleri almıştır."),
    ("Aşağıdaki altı çizili sözcüklerden hangisi fiilden isim yapım eki almıştır?", "Şehrin merkezindeki büyük <u>yıkım</u> herkesi üzdü.", ["Köydeki evleri taştan yapmışlar.", "Gözündeki yaşları mendiliyle sildi.", "Denizin dalgaları sahile vuruyordu.", "Yolcular otobüse sırayla bindi."], "Yık- (fiil) + ım -> yıkım (isim yapım eki)."),
    ("Aşağıdaki cümlelerin hangisinde yansımadan türemiş bir sözcük vardır?", "Mutfaktaki tencere durmaksızın <u>fısıldıyordu</u>.", ["Çocuklar sokakta bağırıyordu.", "Kuşlar kanat çırpıyordu.", "Rüzgâr sertçe esiyordu.", "Deniz kıyısında martılar uçuyordu."], "'fıs' yansıma sesinden türemiştir."),
    ("Aşağıdaki altı çizili sözcüklerden hangisi isimden fiil yapım eki almıştır?", "Kış yaklaşırken odunları <u>istifledi</u>.", ["Ders çalışırken notlar alıyordu.", "Kitabın sayfalarını çevirdi.", "Koşucular bitiş çizgisine yaklaştı.", "Usta tahtaları testereyle biçti."], "İstif (isim) + le- (isimden fiil)."),
    ("Aşağıdaki cümlelerin hangisinde '-da/-de' eki diğerlerinden <u>farklı bir işlevde</u> kullanılmıştır?", "Yıllardır görmediği arkadaşıyla <u>sözde</u> bir samimiyet kurdu.", ["Okulda yeni bir kütüphane açıldı.", "Bahçede rengârenk çiçekler vardı.", "Sokakta koşan çocukları izledi.", "Mutfakta lezzetli yemekler pişiyordu."], "'sözde' yapım eki olarak sıfat türetmiştir."),
    ("Aşağıdaki altı çizili sözcüklerden hangisi kökünün türü bakımından fiildir?", "Tarih boyunca bu topraklarda <u>sevgi</u> tohumları ekildi.", ["Tuzlu yemeklerden uzak durun.", "Sulak arazilerde tarım yapılır.", "Gözlükçüden çerçeve aldı.", "Evdeki temizlik işleri bitti."], "'Sevgi' sözcüğü 'sev-' fiil kökünden türemiştir."),
    ("Aşağıdaki birleşik sözcüklerden hangisi anlam kayması yoluyla oluşmuştur?", "Pazardan bir demet <u>aslanağzı</u> çiçeği aldı.", ["Şehrin üzerinden <u>uçaksavar</u> geçti.", "Mutfak tezgâhına <u>bulaşıkçı</u> geldi.", "Yol kenarında <u>akaryakıt</u> istasyonu vardı.", "Meydandaki <u>kahvehane</u> doluydu."], "Aslanağzı çiçeğinde her iki sözcük de anlamını yitirmiştir.")
]

tamlamalar = [
    ("Aşağıdaki cümlelerin hangisinde <u>zincirleme isim tamlaması</u> kullanılmıştır?", "Şehrin tarihi sokaklarının güzelliği turistleri büyülüyordu.", ["Eski bir ahşap konağın önünde durduk.", "Masanın üzerindeki sarı örtü kirlenmişti.", "Köyün berrak suları dereden akıyordu.", "Genç doktor hastalarını güler yüzle karşıladı."], "Üç isim birbirine bağlanmıştır."),
    ("Aşağıdaki cümlelerin hangisinde <u>belirtisiz isim tamlaması</u> sıfat görevinde kullanılmıştır?", "Gözleri <u>deniz mavisi</u> bir kazak giymişti.", ["Okulun kapısı sabah erkenden açıldı.", "Kapı kolu aniden kırıldı.", "Türk edebiyatı zengin bir mirasa sahiptir.", "Çocuk parkı seslerle doluydu."], "'deniz mavisi' belirtisiz isim tamlaması sıfat olmuştur."),
    ("Aşağıdaki cümlelerin hangisinde tamlayanı ile tamlananı arasına sıfat girmiş bir <u>belirtili isim tamlaması</u> vardır?", "Köyün <u>yemyeşil</u> yaylalarında koyunlar otluyordu.", ["Bahçedeki ulu çınar gölge veriyordu.", "Sokağın başında eski bir araba duruyordu.", "Tarihi köprünün kemerleri onarıldı.", "Öğretmenin defteri masanın üstündeydi."], "'Köyün yaylaları' arasına 'yemyeşil' sıfatı girmiştir."),
    ("Aşağıdaki tamlamalardan hangisi türü bakımından diğerlerinden FARKIDIR?", "Yemyeşil vadiler", ["Kapı kolu", "Masa örtüsü", "Gözlük camı", "Köy meydanı"], "'Yemyeşil vadiler' sıfat tamlamasıdır; diğerleri belirtisiz isim tamlamasıdır."),
    ("Aşağıdaki cümlelerin hangisinde tamlayanı düşmüş bir isim tamlaması vardır?", "Yıllardır görmediği <u>arkadaşını</u> görünce gözleri doldu.", ["Kitap okumayı çok seviyordu.", "Sınav soruları açıklandı.", "Bahçedeki güller sulandı.", "Güneş yavaşça batıyordu."], "'onun arkadaşını' tamlayanı düşmüştür."),
    ("Aşağıdaki cümlelerin hangisinde hem niteleme hem belirtme sıfatı almış bir isim vardır?", "Masanın üzerinde <u>bir eski defter</u> duruyordu.", ["Büyük bir kalabalık meydanda toplandı.", "Soğuk su içmekten boğazı ağrıdı.", "Üç çalışkan öğrenci ödül aldı.", "Şu tarihi konak restore edilecek."], "'eski' niteleme ve 'bir' belirtme sıfatıdır."),
    ("Aşağıdaki cümlelerin hangisinde işaret sıfatı kullanılmıştır?", "<u>Bu</u> zor günleri hep birlikte el ele vererek aşacağız.", ["Onu dün kütüphanede gördüm.", "Şunları masaya bırak.", "Burada herkes saygılıdır.", "Kimse ne düşündüğünü bilmiyordu."], "'Bu zor günler' tamlamasında 'bu' işaret sıfatıdır."),
    ("Aşağıdaki cümlelerin hangisinde soru anlamı bir sıfatla sağlanmıştır?", "Sınava hazırlanırken <u>kaçıncı</u> sayfaya kadar geldiniz?", ["Bize ne zaman geleceksiniz?", "Bu soruları nasıl çözdün?", "Kütüphanede kimi arıyordun?", "Neden bana haber vermedin?"], "'Kaçıncı sayfa' sıra sayı sıfatıyla soru sorulmuştur."),
    ("Aşağıdaki cümlelerin hangisinde küçültme sıfatı kullanılmıştır?", "Yol kenarında <u>küçücük</u> bir kulübede yaşıyordu.", ["Bahçedeki taşları taşıdılar.", "Geniş caddelerden geçtik.", "Sıcak bir çorba içti.", "Uzun bir yolculuk bitti."], "Küçük-cük -> küçücük küçültme sıfatıdır."),
    ("Aşağıdaki cümlelerin hangisinde unvan sıfatı kullanılmıştır?", "Toplantıya <u>Avukat Selim Bey</u> de katıldı.", ["Müdür evrakları inceliyordu.", "Öğretmen konuyu yazdı.", "Doktor hastayı muayene etti.", "Mühendis projeyi teslim etti."], "'Avukat Selim Bey' unvan sıfatıdır.")
]

zamirler = [
    ("Aşağıdaki cümlelerin hangisinde <u>belgisiz zamir</u> kullanılmıştır?", "Öğrencilerin <u>birkaçı</u> sınavın zor olduğunu dile getirdi.", ["Birkaç öğrenci kütüphanede ders çalışıyordu.", "Bazı günler sahilde uzun yürüyüşler yapardı.", "Her insan kendi geleceğini inşa eder.", "Kimi konular daha fazla tekrar gerektirir."], "'Birkaçı' ismin yerini belirsiz tuttuğundan belgisiz zamirdir."),
    ("Aşağıdaki cümlelerin hangisinde <u>dönüşlülük zamiri</u> pekiştirme göreviyle kullanılmıştır?", "Bu zor projeyi mimar <u>kendisi</u> tek başına çizdi.", ["Kendine iyi bakmayı hiçbir zaman ihmal etmezdi.", "İnsan önce kendini tanımalı ve geliştirmelidir.", "Kendi düşen ağlamaz derler atalarımız.", "Olayları sadece kendi penceresinden değerlendiriyordu."], "'mimar kendisi' özneyi pekiştirmektedir."),
    ("Aşağıdaki cümlelerin hangisinde 'o' sözcüğü <u>işaret zamiri</u> olarak kullanılmıştır?", "Cebinden çıkardığı anahtarı usulca çevirip <u>onu</u> masaya bıraktı.", ["O, dürüstlüğü ve çalışkanlığıyla tanınan bir insandı.", "O kitabı geçen hafta bir solukta okuyup bitirdim.", "O günlerde herkes geleceğe umutla bakıyordu.", "O adamın ne dediğini kimse anlayamadı."], "Bir nesnenin yerini tuttuğu için işaret zamiridir."),
    ("Aşağıdaki cümlelerin hangisinde soru anlamı bir <u>zamirle</u> sağlanmıştır?", "Masanın üzerindeki bu güzel hediyeyi sana <u>kim</u> getirdi?", ["Yarınki konferansa nasıl gideceksiniz?", "Bu kitabı kaç günde bitirdin?", "Neden bizimle sinemaya gelmiyorsun?", "Hangi otobüs Kadıköy'e gider?"], "'Kim' sözcüğü soru zamiridir."),
    ("Aşağıdaki cümlelerin hangisinde ilgi zamiri (-ki) kullanılmıştır?", "Benim notlarım yüksek, <u>seninki</u> nasıl geldi?", ["Evdeki hesap çarşıya uymadı.", "Sokaktaki lambalar akşam yandı.", "Bahçedeki ağaçlar çiçek açtı.", "Duydum ki unutmuşsun beni."], "'Seninki' tamlananın yerini tutan ilgi zamiridir."),
    ("Aşağıdaki cümlelerin hangisinde birden fazla zamir kullanılmıştır?", "<u>Bunu</u> <u>bana</u> daha önce neden anlatmadın?", ["Kitaplarını çantasına özenle yerleştirdi.", "Sınavdan yüksek not almak için çok çalıştı.", "Bahçedeki sarı gülleri tek tek suladı.", "Güneş batarken sahil boyunca yürüdük."], "'Bunu' ve 'bana' iki zamirdir."),
    ("Aşağıdaki cümlelerin hangisinde belgisiz zamir cümlenin öznesi görevindedir?", "Salondaki dinleyicilerin <u>hepsi</u> konuşmacıyı ayakta alkışladı.", ["Bunu herkese açıkça ilan etti.", "Birçoğunu daha önce görmüştüm.", "Kimi insanları anlamak zordur.", "Hiçbir soruyu yanıtsız bırakmadı."], "'Hepsi' belgisiz zamiri öznedir."),
    ("Aşağıdaki cümlelerin hangisinde işaret zamiri ek eylem alarak yüklem olmuştur?", "Yıllardır arayıp da bulamadığım eşsiz huzur meğer <u>buradaymış</u>.", ["Bu kitap benim en sevdiğim eserdir.", "Şunları dolaba yerleştirmelisin.", "Olayların buraya geleceğini tahmin etmemiştim.", "Bunu yapmak herkesin harcı değildir."], "'Buradaymış' ek eylem almış işaret zamiridir."),
    ("Aşağıdaki cümlelerin hangisinde kişi zamiri bir isim tamlamasında tamlayan görevindedir?", "<u>Bizim</u> evimiz şehrin gürültüsünden uzak, sakin bir tepedeydi.", ["Ali'nin defteri masada kalmış.", "Okulun kapısı kapalıydı.", "Bahçenin duvarı boyandı.", "Gölün suları çekilmişti."], "'Bizim evimiz' tamlamasında tamlayandır."),
    ("Aşağıdaki cümlelerin hangisinde zamir kullanılmamıştır?", "Tarihi köprünün kemerleri usta mimarlar tarafından onarıldı.", ["Kendi işini kendin yapmalısın.", "Biri bize doğru koşarak geliyordu.", "Onları raftan indirip temizledi.", "Bunu sana kim söyledi?"] , "A seçeneğinde zamir yoktur.")
]

fiilimsiler = [
    ("Aşağıdaki cümlelerin hangisinde <u>üç farklı fiilimsi türü</u> bir arada kullanılmıştır?", "Sınavı <u>kazanıp</u> üniversiteye <u>giden</u> genç, <u>çalışmayı</u> hiç bırakmadı.", ["Kitap okuyarak kendini geliştirenler başarılı olur.", "Koşup gelen çocuk masaya oturdu.", "Yaz aylarında yüzmek çok keyiflidir.", "Güneş doğarken yola çıkmayı planlıyordu."], "'kazanıp' (zarf-fiil), 'giden' (sıfat-fiil), 'çalışmayı' (isim-fiil)."),
    ("Aşağıdaki cümlelerin hangisinde geçen altı çizili sözcük <u>kalıcı isim</u> olmuştur?", "Pazardan iki kilo taze <u>dolma</u> ve sarma aldık.", ["Ders çalışırken müzik dinlemeyi severdi.", "Gelen konukları kapıda karşıladı.", "Koşarak durağa yetişmeye çalıştı.", "Yarın sabah yola çıkacak."], "Dolma yemek adı olarak kalıcı isim olmuştur."),
    ("Aşağıdaki cümlelerin hangisinde <u>zarf-fiil</u> cümleye <u>zaman</u> anlamı katmıştır?", "Hocanın anlattığı dersi <u>dinlerken</u> önemli noktaları not ediyordu.", ["Soruları düşünerek çözdü.", "Koşa koşa yanımıza geldi.", "Gülerek bize el salladı.", "İşlerini bitirip gitti."], "'Ne zaman?' sorusuna cevap verir."),
    ("Aşağıdaki cümlelerin hangisinde <u>sıfat-fiil</u> adlaşmış sıfat-fiil olarak kullanılmıştır?", "Toplantıda <u>konuşanları</u> dikkatle dinleyip notlar aldı.", ["Gelen misafirleri salona buyur etti.", "Okunacak kitapları masaya dizdi.", "Akan sular duruldu nihayet.", "Yıkılan binalar onarılacak."], "'Konuşan insanları' yerine 'konuşanları' denmiştir."),
    ("Aşağıdaki altı çizili sözcüklerden hangisi fiilimsi DEĞİLDİR?", "Pazardan aldığımız taze sebzeleri buzdolabına <u>koydu</u>.", ["Kitap <u>okumak</u> insanı zenginleştirir.", "Yolda <u>yürürken</u> eski bir dosta rastladım.", "<u>Bilinmedik</u> diyarlara gitmeyi severdi.", "Bize <u>bakıp</u> tebessüm etti."], "'koydu' çekimli bir fiildir."),
    ("Aşağıdaki cümlelerin hangisinde bir nesneye kalıcı ad olmuş bir isim-fiil vardır?", "Bina girişindeki <u>çakmak</u> ile mumu yaktı.", ["Gülmek insana sağlık verir.", "Yazı yazmayı severdi.", "Ders çalışmak için gitti.", "Yürümek güzeldir."], "'çakmak' kalıcı alet ismidir."),
    ("Aşağıdaki cümlelerin hangisinde zarf-fiil cümleye 'durum' anlamı katmıştır?", "Olay yerindeki tanıklar <u>ağlayarak</u> polise bilgi verdi.", ["Güneş doğduğunda yola çıktık.", "Zil çalınca öğrenciler fırladı.", "Okuldan çıkar çıkmaz eve gitti.", "Akşam olunca lambalar yandı."], "'Nasıl?' sorusuna cevap verir."),
    ("Aşağıdaki cümlelerin hangisinde sıfat-fiil bir ismi nitelemiştir?", "Gelecek <u>günlerin</u> bize huzur getireceğine inanıyorum.", ["Gelenler salonda yerini aldı.", "Bildiğini kimseden saklamazdı.", "Yaptıklarını anlattı.", "Gördüklerime inanamadım."], "'Gelecek günler' niteleme sıfatıdır."),
    ("Aşağıdaki cümlelerin hangisinde fiilimsi kullanılmamıştır?", "Akşam serinliğinde bahçedeki ahşap bankta uzun süre oturduk.", ["Koşup gelen çocuklara sarıldı.", "Kitap okumayı alışkanlık edindi.", "Gülerek el salladı.", "Biten maçın ardından stadyum boşaldı."], "A seçeneğinde fiilimsi yoktur."),
    ("Aşağıdaki cümlelerin hangisinde '-mış/-miş' eki sıfat-fiil göreviyle kullanılmıştır?", "Dolaptaki <u>bozulmuş</u> yemekleri dökmek zorunda kaldık.", ["Dün akşam bize uğramış.", "Yolculuk uzun sürmüş.", "Sınav sonuçları yüklenmiş.", "Tüm hazırlıklar bitirilmiş."], "'bozulmuş yemekler' sıfat-fiildir.")
]

ogeler = [
    ("\"Genç araştırmacı, tozlu raflardan seçtiği eski elyazmalarını büyük bir dikkatle inceledi.\"\n\nBu cümlenin ögeleri sırasıyla aşağıdakilerin hangisinde doğru verilmiştir?", "Özne - Belirtili Nesne - Zarf Tümleci - Yüklem", ["Özne - Yer Tamlayıcısı - Belirtisiz Nesne - Yüklem", "Zarf Tümleci - Özne - Belirtili Nesne - Yüklem", "Özne - Zarf Tümleci - Belirtili Nesne - Yüklem", "Belirtili Nesne - Özne - Zarf Tümleci - Yüklem"], "İnceledi (Yüklem), Genç araştırmacı (Özne), elyazmalarını (Belirtili Nesne), büyük bir dikkatle (Zarf Tümleci)."),
    ("Aşağıdaki cümlelerin hangisinde <u>ara söz</u> nesnenin açıklayıcısı olarak kullanılmıştır?", "Doğup büyüdüğüm o kenti, çocukluğumun başkentini, hiç unutamam.", ["Ali, sınıfın en çalışkanı, gelmedi.", "Yarın sabah, saat tam onda, buluşacağız.", "Ankara'ya, Türkiye'nin kalbine, doğru yola çıktık.", "Eski dostum, can yoldaşım, aradı."], "'çocukluğumun başkentini' belirtili nesnenin açıklayıcısıdır."),
    ("Aşağıdaki cümlelerin hangisinde soru <u>özneyi</u> buldurmaya yöneliktir?", "Bu zor sorunun doğru cevabını tahtaya <u>kim</u> yazdı?", ["Dün akşam ne izledin?", "Toplantı nerede yapılacak?", "Bize ne zaman geleceksiniz?", "Otobüs durağında kimi bekliyordun?"], "'Kim' sorusu doğrudan özneyi buldurur."),
    ("Aşağıdaki cümlelerin hangisinde soru <u>yüklemi</u> buldurmaya yöneliktir?", "Dün akşamdan beri odasında ne <u>yapıyor</u>?", ["Kütüphaneden hangi kitabı aldın?", "Bize kim haber verdi?", "Toplantıya ne zaman katılacaksınız?", "Ankara'ya nasıl gittiniz?"], "Verilen yanıt doğrudan yüklemdir."),
    ("Aşağıdaki cümlelerin hangisinde <u>zarf tümleci</u> KULLANILMAMIŞTIR?", "Kütüphanedeki eski masanın üzerinde kalın bir ansiklopedi duruyordu.", ["Güneş doğarken yola çıktık.", "Soruları dikkatle çözdü.", "Hava kararınca lambalar yandı.", "Koşarak durağa yetişti."], "Duruyordu (Yüklem), masanın üzerinde (Yer tamlayıcısı), ansiklopedi (Özne). Zarf tümleci yoktur."),
    ("Aşağıdaki cümlelerin hangisi <u>özne ve yüklemden</u> oluşmuştur?", "Edebiyat, insan ruhunun derinliklerine tutulan sihirli bir aynadır.", ["Bahçedeki ağaçlar çiçek açtı.", "Öğrenciler dersi dinliyordu.", "Müdür Bey evrakları imzaladı.", "Dün akşam arkadaşıyla gitti."], "Özne ve tamlama halindeki yüklemden oluşur."),
    ("Aşağıdaki cümlelerin hangisinde <u>yer tamlayıcısı</u> vardır?", "Yıllardır görmediği eski dostuna sımsıkı sarıldı.", ["Yağmur aralıksız yağdı.", "Çocuklar neşeyle koşuyordu.", "Bu güzel kitabı okudu.", "Güneş yavaşça batıyordu."], "'eski dostuna' (-e hali) yer tamlayıcısıdır."),
    ("Aşağıdaki cümlelerin hangisinde vurgu <u>yüklem üzerindedir</u>?", "Dün akşam bizi ziyaret eden nihayet <u>sendin</u>.", ["Ali dün okula otobüsle gitti.", "Bu tabloyu Ayşe çizdi.", "Yarın erkenden yola çıkacağız.", "Kütüphanede çalışan Ahmet'ti."], "İsim cümlelerinde vurgu yüklemdedir."),
    ("Aşağıdaki cümlelerin hangisinde nesne <u>açıklayıcısıyla birlikte</u> verilmiştir?", "En sevdiğim mevsimi, sonbaharı, hüznüyle kucaklarım.", ["Babam, o koca yürekli adam, geldi.", "Doğduğum şehre, İzmir'e, döndüm.", "Dün akşam, saat dokuzda, kesildi.", "Öğretmenimiz, o fedakâr insan, konuştu."], "Neyi? -> En sevdiğim mevsimi (sonbaharı)."),
    ("Aşağıdaki cümlelerin hangisinde ögelere ayırmada bir <u>yanlışlık</u> yapılmıştır?", "Okulun bahçesindeki / ulu çınar / rüzgârda sallanıyordu.", ["Genç yazar / ilk romanını / geçen ay / yayımladı.", "Kütüphanedeki öğrenciler / sessizce / ders / çalışıyordu.", "Güneş / dağların ardından / yavaşça / yükseldi.", "Öğretmenimiz / dersi / sabırla / anlattı."], "'Okulun bahçesindeki ulu çınar' bir bütündür, bölünemez.")
]

cumle_turleri = [
    ("Aşağıdaki cümlelerin hangisi <u>yapısına göre birleşik</u> bir cümledir?", "Hava güzelleşince parktaki banklarda oturanların sayısı arttı.", ["Güneş battı ve sokak lambaları yandı.", "Sabah erkenden kalktı, kahvaltısını yaptı.", "Tarihi köprünün üzerinden ağır vasıtalar geçiyordu.", "Kütüphanedeki eski kitaplar raflara dizilmişti."], "İçinde fiilimsiler bulunan girişik birleşik cümledir."),
    ("Aşağıdaki cümlelerin hangisi <u>bağlı bir cümledir</u>?", "Hava oldukça soğuktu ama kimse dışarı çıkmaktan vazgeçmedi.", ["Kitap okumayı sevenler kendilerini iyi ifade eder.", "Koşarak durağa yetişti, otobüse bindi.", "Güneş doğarken bütün köy ahalisi uyandı.", "Sınavda başarılı olmak için gece gündüz çalıştı."], "'ama' bağlacıyla bağlanmış iki cümledir."),
    ("Aşağıdaki cümlelerin hangisi <u>sıralı bir cümledir</u>?", "Güneş ufukta kayboldu, ortalığa derin bir sessizlik çöktü.", ["Bahçedeki güller ilkbaharda açtı.", "Sınavı kazanmak için gayret gösterdi.", "Kitabı okudu ve hediye etti.", "Yağmur dindiğinde gökkuşağı belirdi."], "Virgülle bağlanmış iki yüklemli cümledir."),
    ("Aşağıdaki cümlelerin hangisi <u>biçimce olumsuz, anlamca olumlu</u> bir cümledir?", "Söylediklerinin doğruluğundan hiçbirimiz şüphe etmiyor değiliz.", ["Bu soğuk havada dışarı çıkmak istemiyorum.", "Sınav sorularının hiçbirini çözemedi.", "Toplantıya ne Ahmet geldi ne Mehmet.", "Verilen sözlerin hiçbiri tutulmadı."], "'şüphe etmiyor değiliz' = 'şüphe ediyoruz'."),
    ("Aşağıdaki cümlelerin hangisi <u>biçimce olumlu, anlamca olumsuz</u> bir cümledir?", "Ben bu vefasız insanlara bir daha güvenir miyim hiç!", ["Sınavı kazanmak için elinden geleni yaptı.", "Bahçedeki ağaçlar meyve verdi.", "Tüm soruları eksiksiz yanıtladı.", "Yarın sabah erkenden yola çıkacak."], "'Güvenir miyim hiç!' = 'Güvenmem'."),
    ("Aşağıdaki cümlelerin hangisi <u>yükleminin türüne göre isim cümlesidir</u>?", "Bize huzur veren tek sığınak, çocukluğumuzun geçtiği bu kasabaydı.", ["Sabah kalkıp sahilde yürüdü.", "Kütüphanedeki eski kitapları inceledi.", "Soruları okuyup çözdü.", "Güneş batarken sahil boyunca ilerledi."], "'kasabaydı' ek fiil almış isimdir."),
    ("Aşağıdaki cümlelerin hangisi <u>yükleminin yerine göre kurallı</u> bir cümledir?", "Eski bir dostun tebessümü insanın yorgunluğunu unutturur.", ["Unutturur yorgunluğu bir dost tebessümü.", "Gördüm dün akşam sahilde seni.", "Açıldı bahçedeki güller nihayet.", "Dökülüyor sonbaharda yapraklar."], "Yüklemi cümlenin sonundadır."),
    ("Aşağıdaki cümlelerin hangisi <u>şartlı birleşik cümledir</u>?", "Düzenli ve disiplinli çalışırsan hedeflerine kolaylıkla ulaşırsın.", ["Okula gitmek için erkenden kalktı.", "Güneş doğdu ve kuşlar öttü.", "Eve geldi, hemen ders çalıştı.", "Kitap okuyan insan dünyayı daha iyi anlar."], "-sa/-se şart kipiyle kurulmuştur."),
    ("Aşağıdaki cümlelerin hangisi <u>iç içe birleşik cümledir</u>?", "Usta yazar, 'Gerçek sanatçı çağının tanığıdır.' derdi.", ["Hava kararınca yola çıktık.", "Ders çalışırken müzik dinlerdi.", "Sınavı kazanınca ailesi sevindi.", "Yağmur dindiğinde dışarı çıktık."], "İçinde alıntı cümle yer alır."),
    ("Aşağıdaki cümlelerin hangisi yapısı bakımından <u>basit</u> bir cümledir?", "Masanın üzerindeki porselen vazo dün akşam kırıldı.", ["Koşarak gelen çocuk masaya oturdu.", "Güneş batınca köye döndük.", "Kitap okumayı çok severdi.", "Çalışırsan başarılı olursun."], "Tek yüklemi vardır, yan cümlecik yoktur.")
]

cati = [
    ("Aşağıdaki cümlelerin hangisinin yüklemi <u>geçişsiz</u> bir fiildir?", "Tüm gün süren yorucu toplantının ardından hemen <u>uyudu</u>.", ["Masanın üzerindeki evrakları inceledi.", "Biriktirdiği hatıraları kitaba aktardı.", "Dünkü maçın özetini anlattı.", "Kütüphaneden yeni romanı ödünç aldı."], "Uyudu fiili nesne alamaz (Neyi uyudu? denmez)."),
    ("Aşağıdaki cümlelerin hangisinde yüklem <u>edilgen çatılıdır</u>?", "Okulun bahçesindeki ulu çınar ağaçları belediyece <u>budandı</u>.", ["Genç sporcu madalyayı boynuna taktı.", "Öğrenciler sınavı bekledi.", "Usta tahtayı zımparaladı.", "Yolcular otobüsü bekledi."], "Budandı eylemini yapan başkasıdır (-n eki)."),
    ("Aşağıdaki cümlelerin hangisinin yüklemi <u>dönüşlü çatılıdır</u>?", "Sınavı kazandığını öğrenen genç kız çok <u>sevindi</u>.", ["Olay yerindeki deliller toplandı.", "Yemek masası akşam için hazırlandı.", "Şehrin caddeleri süslendi.", "Yeni alınan kitaplar taşındı."], "İşi yapan ve etkilenen aynı kişidir."),
    ("Aşağıdaki cümlelerin hangisinde yüklem <u>işteş çatılıdır</u>?", "Eski iki dost yıllar sonra havaalanında karşılaşıp <u>kucaklaştı</u>.", ["Çocuklar bahçede top oynadı.", "Öğretmen yeni formülü yazdı.", "Kuşlar gökyüzünde kanat çırptı.", "Rüzgâr sertçe esmeye başladı."], "Karşılıklı yapılan eylemdir (-ş eki)."),
    ("Aşağıdaki cümlelerin hangisinin yüklemi <u>ettirgen çatılıdır</u>?", "Müdür Bey hazırlanan raporu sekreterine hızla <u>yazdırdı</u>.", ["Bütün gün kitap okudu.", "Akşam serinliğinde yürüdü.", "Soruları dikkatle inceledi.", "Bahçedeki gülleri suladı."], "Geçişli fiilin derecesi artırılmıştır."),
    ("Aşağıdaki cümlelerin hangisinin yüklemi <u>oldurgan çatılıdır</u>?", "Anlattığı fıkrayla salondaki herkesi kahkahalarla <u>güldürdü</u>.", ["Yemeği afiyetle yedi.", "Kitabın sayfalarını çevirdi.", "Arkadaşına mektup yazdı.", "Eski fotoğraflara baktı."], "Geçişsiz 'gülmek' fiili geçişli yapılmıştır."),
    ("Aşağıdaki cümlelerin hangisinde yüklemde çatı özelliği <u>aranmaz</u>?", "Bize rehberlik eden kişi, üniversitenin en kıdemli profesörüydü.", ["Tüm soruları eksiksiz yanıtladı.", "Kitapları dolaba yerleştirdi.", "Sabah erkenden yola çıktı.", "Bahçedeki çiçekleri suladı."], "İsim cümlelerinde çatı aranmaz."),
    ("Aşağıdaki cümlelerin hangisinde fiil hem <u>geçişli hem etken</u>dir?", "Genç mühendis fabrikanın projesini büyük bir titizlikle <u>çizdi</u>.", ["Bebek sabaha kadar uyudu.", "Toplantı salonu erkenden temizlendi.", "Yolcular durağa doğru yürüdü.", "Yağmur şiddetle yağdı."], "Öznesi bellidir ve nesne alabilir."),
    ("Aşağıdaki cümlelerin hangisinde 'birlikte yapılma' anlamı taşıyan bir <u>işteş fiil</u> vardır?", "Korku dolu patlama sesini duyan güvercinler aniden <u>uçuştu</u>.", ["İki boksör ringde dövüştü.", "Taraflar uzun süre tartıştı.", "Eski dostlar selamlaştı.", "İki lider sınırda tokalaştı."], "Kuşların topluca birlikte yaptığı eylemdir."),
    ("Aşağıdaki cümlelerin hangisinde örtülü özne kullanılmıştır?", "Yasa tasarısı meclis genel kurulunca oy birliğiyle <u>onaylandı</u>.", ["Milletvekilleri tasarıyı tartıştı.", "Başkan oturumu açtı.", "Komisyon raporunu sundu.", "Bakan açıklama yaptı."], "'meclis genel kurulunca' örtülü öznedir.")
]
