# vatandaslik_data_1.py - Q106 to Q113 (80 questions)

# Q106: Temel Hukuk - Kurallar ve Yaptırımlar
q106_list = [
    ("Hukuk kurallarını diğer toplumsal düzen kurallarından (din, ahlak, görgü) ayıran EN TEMEL belirleyici özellik hangisidir?", "Maddi (devlet gücüne dayalı) yaptırımlı olması", ["Yazısız olması", "Soyut olması", "Kişiye özel olması", "Sadece vicdana hitap etmesi"], "Hukuk kurallarına uyulmaması durumunda devlet zor kullanma gücünü (maddi müeyyide) devreye sokar."),
    ("Borcunu kendi rızasıyla ödemeyen borçlunun mallarına devlet icra dairesi aracılığıyla el konulup satılarak alacağın tahsil edilmesine hangi hukuki yaptırım denir?", "Cebri İcra", ["Tazminat", "Ceza", "İptal", "Yokluk"], "Kamu gücüyle borcun zorla yerine getirilmesidir."),
    ("Hukuka aykırı bir fiille başkasına maddi veya manevi zarar veren kişinin bu zararı para ile ödemekle yükümlü tutulması yaptırımına ne ad verilir?", "Tazminat", ["Cebri icra", "İptal", "Müsadere", "Hükümsüzlük"], "Maddi ve manevi tazminat olarak ikiye ayrılır."),
    ("İdarenin hukuka aykırı olarak tesis ettiği idari işlemlerin (örneğin haksız bir tayin veya disiplin cezası) idare mahkemesi kararıyla geçmişe etkili olarak ortadan kaldırılmasına ne ad verilir?", "İptal", ["Ceza", "Tazminat", "Fesih", "Yokluk"], "İdari işlemlere karşı uygulanan temel yaptırım iptal davasıdır."),
    ("Bir hukuki işlemin kurucu unsurlarından birinin (örneğin evlendirme memuru olmadan imam nikâhı yapılması) eksik olması durumunda o işlem hiç doğmamış kabul edilir. Bu yaptırım hangisidir?", "Yokluk", ["Mutlak Butlan", "Nisbi Butlan", "Fesih", "İptal"], "Hukuken işlem baştan itibaren hiç var olmamış sayılır."),
    ("Kurucu unsurları tam olmakla birlikte, kanunun emredici hükümlerine, kamu düzenine veya ahlaka aykırı olan işlemlerin (örneğin amca ile yeğenin evlenmesi) baştan itibaren geçersiz olmasına ne ad verilir?", "Mutlak Butlan", ["Yokluk", "Nisbi Butlan", "Tek taraflı bağlamazlık", "Fesih"], "İşlem baştan itibaren ölü doğmuştur; hâkim re'sen dikkate alır."),
    ("İrade sakatlığı (hata, hile, korkutma) sonucu yapılan bir sözleşmenin zarar gören tarafça dava açılarak geçersiz kılınabilmesine ne ad verilir?", "Nisbi Butlan (İptal Edilebilirlik)", ["Mutlak Butlan", "Yokluk", "Cebri İcra", "Cezai Şart"], "Mağdur taraf bir yıl içinde sözleşmeyi iptal ettirebilir, aksi halde geçerli kalır."),
    ("Yetkisi olmayan bir temsilcinin veya 16 yaşındaki bir küçüğün velisinin izni olmadan yaptığı bisiklet satış sözleşmesinin durumuna ne ad verilir?", "Askıda hükümsüzlük (Tek taraflı bağlamazlık)", ["Yokluk", "Mutlak Butlan", "Nisbi Butlan", "İptal"], "Veli onay verirse sözleşme geçerli hale gelir, onay vermezse geçersiz kalır."),
    ("Kişinin kendisine veya başkasına yönelik gerçekleşen haksız bir saldırıyı o anda defetmek için yaptığı ve hukuka uygunluk sebebi sayılan fiile ne ad verilir?", "Meşru Müdafaa (Yasal Savunma)", ["Zaruret Hali (Iztırar)", "Kuvvet Kullanma", "Hakkın Kötüye Kullanılması", "Gasp"], "Orantılı savunma ceza sorumluluğunu tamamen kaldırır."),
    ("Kişinin kendisini veya başkasını bilerek neden olmadığı ağır bir tehlikeden korumak için üçüncü bir kişinin malına zarar vermesi haline (örneğin kuduz köpekten kaçarken komşunun kapısını kırmak) ne ad verilir?", "Zaruret Hali (Iztırar Hali)", ["Meşru Müdafaa", "Hakkın Kullanılması", "Kuvvet Kullanma", "İcbar"], "Ceza verilmez ancak verilen maddi zarar tazmin edilir.")
]

# Q107: Haklar ve Ehliyetler
q107_list = [
    ("Hukuk düzeni tarafından kişilere tanınan ve korunması devlet gücüyle güvence altına alınan yetkilere ne ad verilir?", "Hak", ["Ödev", "Yetki", "Sorumluluk", "İmtiyaz"], "Hukukun koruduğu menfaat haktır."),
    ("Medeni Kanun'a göre bir hakkın kazanılmasında geçerli olan, kişinin bir durumu bilmemesi ve bilmesinin gerekmemesi ilkesine ne ad verilir?", "Subjektif İyiniyet (İyiniyet Kuralı)", ["Objektif İyiniyet (Dürüstlük)", "Ahlak Kuralı", "Adalet Kuralı", "Kuvvet İlkesi"], "Medeni Kanun Madde 3: İyiniyet asıldır."),
    ("Herkesin haklarını kullanırken ve borçlarını yerine getirirken dürüst, makul ve namuslu bir insan gibi davranmak zorunda olduğunu belirten temel kural hangisidir?", "Dürüstlük Kuralı (Objektif İyiniyet)", ["Subjektif İyiniyet", "Meşru Müdafaa", "Kuvvet Kullanma", "Hak Ehliyeti"], "Medeni Kanun Madde 2: Hakkın açıkça kötüye kullanılmasını hukuk düzeni korumaz."),
    ("Kişilerin haklara ve borçlara sahip olabilme yeteneğine ne ad verilir ve bu yetenek NE ZAMAN başlar?", "Hak Ehliyeti - Tam ve sağ doğumla başlar", ["Fiil Ehliyeti - 18 yaşında başlar", "Medeni Hak - Erginlikle başlar", "Vatandaşlık - Nüfus kaydıyla başlar", "Siyasi Hak - Seçmen olunca başlar"], "Sağ doğmak şartıyla ana rahmine düşüldüğü andan itibaren hak ehliyeti kazanılır."),
    ("Bir kişinin kendi fiilleriyle haklar kazanabilme ve borç altına girebilme yeteneğine ne ad verilir?", "Fiil Ehliyeti", ["Hak Ehliyeti", "Vesayet Ehliyeti", "Kişilik Hakkı", "Seçilme Ehliyeti"], "Sözleşme yapabilme, suç işlediğinde cezalandırılabilme yeteneğidir."),
    ("Medeni Kanun'a göre fiil ehliyetinin ÜÇ temel şartı aşağıdakilerden hangisinde bir arada verilmiştir?", "Ayırt etme gücüne sahip olmak, ergin olmak, kısıtlı olmamak", ["Hak ehliyetine sahip olmak, okur-yazar olmak, 18 yaşını doldurmak", "Türk vatandaşı olmak, memur olmak, akıllı olmak", "Evli olmak, askerliğini yapmış olmak, reşit olmak", "Mal varlığı bulunmak, 20 yaşında olmak, sağlıklı olmak"], "Bu üç şartı taşıyan kişi 'Tam Ehliyetli' kabul edilir."),
    ("Türkiye'de olağan erginlik yaşı Medeni Kanun'a göre kaç yaşın doldurulmasıyla başlar?", "18 yaşın doldurulmasıyla", ["15 yaş", "16 yaş", "17 yaş", "21 yaş"], "18 yaşını dolduran herkes kural olarak ergindir."),
    ("Ayırt etme gücüne sahip olmak şartıyla olağanüstü durumlarda mahkeme kararıyla evlenme erginliği EN ERKEN kaç yaşında kazanılabilir?", "16 yaşın doldurulmasıyla (Hâkim kararıyla)", ["15 yaş", "17 yaş", "14 yaş", "18 yaş"], "Olağan evlenme yaşı 17, olağanüstü evlenme yaşı 16'dır."),
    ("Ayırt etme gücü bulunmayan (örneğin akıl hastaları, küçük bebekler) kişilerin hukuki ehliyet sınıfı hangisidir?", "Tam Ehliyetsizler", ["Sınırlı Ehliyetliler", "Sınırlı Ehliyetsizler", "Tam Ehliyetliler", "Yarı Ehliyetliler"], "Yaptıkları hukuki işlemler baştan itibaren kesin hükümsüzdür (butlan)."),
    ("Ayırt etme gücüne sahip küçükler (14 yaşındaki çocuk) ve kısıtlılar hangi ehliyet grubunda yer alır?", "Sınırlı Ehliyetsizler", ["Tam Ehliyetsizler", "Sınırlı Ehliyetliler", "Tam Ehliyetliler", "Mutlak Ehliyetliler"], "Kendi başlarına borç altına giremezler, yasal temsilcilerinin onayı gerekir; ancak bağış kabul edebilirler.")
]

# Q108: Devlet Biçimleri ve Hükümet Sistemleri
q108_list = [
    ("Devlet sınırları içinde tek bir anayasa, tek bir yasama meclisi ve tek bir yargı sisteminin geçerli olduğu devlet biçimine ne ad verilir?", "Üniter Devlet", ["Federal Devlet", "Konfederal Devlet", "Bileşik Devlet", "Feodal Devlet"], "Türkiye Cumhuriyeti Devleti üniter bir devlettir."),
    ("Kendi anayasaları ve parlamentoları olan federe devletlerin ortak bir anayasa altında birleşerek oluşturduğu devlete (ABD, Almanya gibi) ne ad verilir?", "Federal Devlet", ["Üniter Devlet", "Konfederasyon", "Monarşi", "Oligarşi"], "Dış politikada tek bir federal merkez temsil eder."),
    ("Devlet başkanının miras yoluyla (saltanat/hanedan) başa geçtiği ve ömür boyu görevde kaldığı devlet biçimi hangisidir?", "Monarşi", ["Cumhuriyet", "Teokrasi", "Oligarşi", "Demokrasi"], "Yetkiler anayasa ile kısıtlanmışsa meşruti monarşi, sınırsızsa mutlak monarşidir."),
    ("Yürütme organının halk tarafından doğrudan seçilen tek bir kişide (Devlet Başkanı) toplandığı, yasama ile yürütmenin katı şekilde ayrıldığı hükümet sistemi hangisidir?", "Başkanlık Sistemi", ["Parlamenter Sistem", "Meclis Hükümeti Sistemi", "Yarı Başkanlık Sistemi", "Mutlakiyet"], "Bakanlar meclis dışından atanır ve meclise karşı sorumlu değildir."),
    ("Yürütme organının yasamadan kaynaklandığı, başbakan ve bakanların meclise karşı sorumlu olduğu, meclisin güvenoyuyla hükümeti düşürebildiği sistem hangisidir?", "Parlamenter Sistem", ["Başkanlık Sistemi", "Meclis Hükümeti", "Konfederal Sistem", "Oligarşik Sistem"], "Türkiye 2017 anayasa değişikliğine kadar parlamenter sistemi uygulamıştır."),
    ("Devlet başkanının doğrudan halk tarafından seçildiği, ancak yürütmede cumhurbaşkanının yanında meclise karşı sorumlu bir başbakanın da bulunduğu ikili sisteme (Fransa örneği) ne ad verilir?", "Yarı Başkanlık Sistemi", ["Başkanlık Sistemi", "Parlamenter Sistem", "Meclis Hükümeti", "Monarşi"], "Cumhurbaşkanı ve başbakan yürütme yetkisini paylaşır."),
    ("I. TBMM döneminde uygulanan, yasama ve yürütme yetkilerinin tamamen mecliste toplandığı, meclis başkanının aynı zamanda hükümet başkanı olduğu sisteme ne ad verilir?", "Meclis Hükümeti Sistemi", ["Başkanlık Sistemi", "Parlamenter Sistem", "Kabine Sistemi", "Kuvvetler Ayrılığı"], "Bakanlar meclis içinden tek tek oylanarak seçilirdi."),
    ("Kuvvetler ayrılığı ilkesinin (yasama, yürütme, yargı erklerinin birbirinden bağımsız olması) temel felsefi amacı nedir?", "Devlet iktidarını dengeleyerek kişisel hak ve özgürlükleri korumak", ["Bürokrasiyi yavaşlatmak", "Kanun yapımını zorlaştırmak", "Yargı organını devlete hâkim kılmak", "Padişahın yetkilerini genişletmek"], "Montesquieu tarafından geliştirilen hürriyet teminatıdır."),
    ("Egemenliğin kaynağının ilahi kurallara (din kurallarına) dayandığı ve din adamlarının yönettiği devlet biçimine ne ad verilir?", "Teokrasi", ["Monarşi", "Oligarşi", "Cumhuriyet", "Plütokrasi"], "Hukuk kuralları kutsal kitaplara dayanır."),
    ("Egemenliğin belirli bir zümrenin, aristokrat sınıfın veya küçük bir grubun elinde bulunduğu yönetim biçimi hangisidir?", "Oligarşi", ["Demokrasi", "Monarşi", "Teokrasi", "Cumhuriyet"], "Grup veya zümre hâkimiyetidir.")
]

# Q109: Türk Anayasa Tarihi
q109_list = [
    ("23 Aralık 1876'da II. Abdülhamid tarafından ilan edilen Türk tarihinin İLK anayasası hangisidir?", "Kanun-i Esasi", ["Teşkilat-ı Esasiye", "1924 Anayasası", "Sened-i İttifak", "Tanzimat Fermanı"], "Türk parlamento hayatı Meclis-i Mebusan ile başlamıştır."),
    ("Türkiye Cumhuriyeti'nin kurulduğu dönemde hazırlanan, 23 maddelik en kısa, tek YUMUŞAK ve ÇERÇEVE anayasamız hangisidir?", "1921 Anayasası (Teşkilat-ı Esasiye)", ["1924 Anayasası", "1961 Anayasası", "1982 Anayasası", "Kanun-i Esasi"], "Savaş şartlarında olağanüstü yetkilerle hazırlanmış, değiştirilmesi özel çoğunluk gerektirmeyen yumuşak anayasadır."),
    ("1924 Anayasası'nda 1928 yılında yapılan EN ÖNEMLİ anayasa değişikliği hangisidir?", "'Devletin dini İslam'dır' ibaresinin anayasadan çıkarılması", ["Kadınlara oy hakkı verilmesi", "Laiklik ilkesinin anayasaya girmesi", "Çok partili hayata geçilmesi", "Cumhurbaşkanının halkça seçilmesi"], "Devletin laikleşmesi yolundaki en kritik adımdır (Laiklik ilkesi ise 1937'de anayasaya girmiştir)."),
    ("Atatürk'ün altı temel ilkesi (Cumhuriyetçilik, Milliyetçilik, Halkçılık, Devletçilik, Laiklik, İnkılapçılık) hangi yıl anayasaya girmiştir?", "1937 yılında", ["1924", "1928", "1934", "1961"], "1924 Anayasası'nda yapılan 1937 değişikliğiyle anayasal hüküm olmuştur."),
    ("Türkiye tarihinde İLK KEZ halkoylamasıyla (referandum) kabul edilen, Anayasa Mahkemesi'ni kuran ve Cumhuriyet Senatosu ile Millet Meclisi'nden oluşan ÇİFT MECLİSLİ anayasa hangisidir?", "1961 Anayasası", ["1924 Anayasası", "1982 Anayasası", "1921 Anayasası", "Kanun-i Esasi"], "Temel hak ve özgürlükleri en geniş düzenleyen anayasadır."),
    ("1982 Anayasası'nın 1961 Anayasası'na göre yürütme organını ve Cumhurbaşkanını daha da güçlendirmesi, kanunları çok ayrıntılı düzenlemesi onun hangi özelliğidir?", "Kazuistik (Ayrıntıcı) ve Sert (Katı) anayasa olması", ["Yumuşak anayasa olması", "Çerçeve anayasa olması", "Meclis hükümeti olması", "Halkçı anayasa olması"], "Madde metinleri çok uzun, değiştirilmesi zorlaştırılmıştır."),
    ("1982 Anayasası'nda Cumhurbaşkanının doğrudan halk tarafından 5 yıllığına seçilmesi kuralı hangi yıl yapılan anayasa referandumu ile kabul edilmiştir?", "2007 Anayasa Değişikliği", ["2010 Referandumu", "2017 Referandumu", "1999 Değişikliği", "2004 Değişikliği"], "367 krizinin ardından cumhurbaşkanını halkın seçmesi kabul edilmiştir."),
    ("Başbakanlık makamının ve Bakanlar Kurulu'nun kaldırılarak Cumhurbaşkanlığı Hükümet Sistemi'ne geçildiği tarihi anayasa değişikliği hangi yıl yapılmıştır?", "2017 Anayasa Değişikliği (16 Nisan Referandumu)", ["2010 Referandumu", "2007 Değişikliği", "2014 Değişikliği", "2020 Değişikliği"], "2018 genel seçimleriyle birlikte yürürlüğe girmiştir."),
    ("2010 Anayasa Değişiklikleri ile Türk hukuk sistemine kazandırılan yeni kurum ve haklar hangileridir?", "Anayasa Mahkemesi'ne Bireysel Başvuru hakkı ve Kamu Denetçiliği (Ombudsmanlık)", ["İdam cezasının kaldırılması", "Seçilme yaşının 18 olması", "Cumhurbaşkanının halkça seçilmesi", "Devlet Güvenlik Mahkemelerinin kurulması"], "Vatandaşlara temel hak ihlallerinde AYM'ye doğrudan başvuru yolu açılmıştır."),
    ("2004 yılında anayasada yapılan değişiklikle idam cezası ve hangi özel yetkili mahkemeler tamamen kaldırılmıştır?", "Devlet Güvenlik Mahkemeleri (DGM)", ["İdare Mahkemeleri", "Vergi Mahkemeleri", "Sulh Ceza Mahkemeleri", "Asliye Hukuk Mahkemeleri"], "AB uyum yasaları çerçevesinde DGM'ler ve ölüm cezası kaldırılmıştır.")
]

# Q110: 1982 Anayasası Genel Esaslar ve Devletin Nitelikleri
q110_list = [
    ("1982 Anayasası'nın 1. maddesinde devletin şekli nasıl tanımlanmıştır?", "'Türkiye Devleti bir Cumhuriyettir.'", ["Türkiye Devleti bir Monarşidir.", "Türkiye Devleti Federaldir.", "Türkiye bir Teokrasidir.", "Türkiye Karma Devlettir."], "Devletin yönetim biçiminin cumhuriyet olduğu belirtilmiştir."),
    ("1982 Anayasası'nın 2. maddesinde belirtilen Türkiye Cumhuriyeti'nin temel nitelikleri arasında aşağıdakilerden hangisi YER ALMAZ?", "Teokratik devlet", ["Demokratik devlet", "Laik devlet", "Sosyal devlet", "Hukuk devleti"], "Türkiye dini kurallarla yönetilen teokratik bir devlet değildir."),
    ("Anayasa'nın 3. maddesinde başkent, bayrak, milli marş ve dile ilişkin hükümlerden hangisi DOĞRUDUR?", "Başkenti Ankara'dır, dili Türkçedir, bayrağı al bayraktır, marşı İstiklal Marşı'dır.", ["Başkenti İstanbul'dur.", "Dili Osmanlıcadır.", "Marşı Gençlik Marşı'dır.", "Bayrağı yeşildir."], "3. madde devletin bütünlüğü ve sembollerini düzenler."),
    ("1982 Anayasası'nın ilk üç maddesinin değiştirilemeyeceğini ve değiştirilmesinin teklif dahi edilemeyeceğini hükme bağlayan koruyucu madde hangisidir?", "4. Madde", ["5. Madde", "6. Madde", "10. Madde", "13. Madde"], "Cumhuriyetin niteliklerini güvenceye alan kilit maddedir."),
    ("Anayasa'nın 6. maddesinde egemenlik ilkesi nasıl formüle edilmiştir?", "'Egemenlik, kayıtsız şartsız Milletindir.'", ["Egemenlik cumhurbaşkanınındır.", "Egemenlik hükümetindir.", "Egemenlik meclis başkanınındır.", "Egemenlik partilerindir."], "Millet bu egemenliğini anayasanın koyduğu esaslara göre yetkili organlar eliyle kullanır."),
    ("Devletin vatandaşlarına asgari geçim düzeyi sağlaması, fırsat eşitliği yaratması, yoksulları, kimsesizleri ve engellileri koruması hangi devlet ilkesinin gereğidir?", "Sosyal Devlet İlkesi", ["Laik Devlet", "Demokratik Devlet", "Üniter Devlet", "Monarşik Devlet"], "Sosyal güvenlik, adil gelir dağılımı ve kamusal hizmetler sosyal devlet gereğidir."),
    ("Devletin bütün eylem ve işlemlerinin yargı denetimine açık olması, yasaların anayasaya uygun olması, mahkemelerin bağımsızlığı hangi ilkeyi ifade eder?", "Hukuk Devleti İlkesi", ["Sosyal Devlet", "Laik Devlet", "Polis Devleti", "Bürokratik Devlet"], "Hukuk güvenliği ve adil yargılanma hukuk devletinin temelidir."),
    ("Devletin tüm inanç ve dinlere eşit mesafede durması, din ve vicdan hürriyetini güvenceye alması, resmi bir devlet dininin bulunmaması hangi ilkedir?", "Laiklik İlkesi", ["Sosyalizm", "Demokrasi", "Milliyetçilik", "Halkçılık"], "Din ile devlet işlerinin ayrılmasıdır."),
    ("Anayasa'nın 10. maddesinde düzenlenen 'Herkes, dil, ırk, renk, cinsiyet, siyasi düşünce, felsefi inanç, din, mezhep ayrımı gözetilmeksizin kanun önünde eşittir' kuralı hangi ilkedir?", "Kanun Önünde Eşitlik İlkesi", ["Mülkiyet Hakkı", "Kuvvetler Ayrılığı", "Hak Arama Hürriyeti", "Masumiyet Karinesi"], "Hiçbir kişiye, aileye, zümreye imtiyaz tanınamaz."),
    ("Anayasa hükümlerinin yasama, yürütme ve yargı organlarını, idare makamlarını ve diğer kuruluş ve kişileri bağlayan temel hukuk kuralları olduğunu belirten kurala ne ad verilir?", "Anayasanın Üstünlüğü ve Bağlayıcılığı (Madde 11)", ["Kanun üstünlüğü", "Yargı dokunulmazlığı", "Bürokratik bağ", "Yönetmelik ilkesi"], "Kanunlar anayasaya aykırı olamaz.")
]

# Q111: Temel Hak ve Hürriyetler
q111_list = [
    ("Jellinek'in haklar tasnifine göre devletin karışamayacağı, bireyin dokunulmaz alanını koruyan haklara 'Koruyucu Haklar (Kişi Hak ve Ödevleri / Negatif Statü)' denir. Aşağıdakilerden hangisi bir 'kişi hakkıdır'?", "Kişi hürriyeti ve güvenliği, Yaşama hakkı, Konut dokunulmazlığı", ["Seçme ve seçilme hakkı", "Dilekçe hakkı", "Vergi ödevi", "Kamu hizmetine girme hakkı"], "Bireyin kişisel özgürlük alanıdır."),
    ("Devletten olumlu bir edim, hizmet ve yardım talep etme yetkisi veren 'İstem Hakları (Sosyal ve Ekonomik Haklar / Pozitif Statü)' grubuna hangisi girer?", "Eğitim ve öğrenim hakkı, Sağlık hakkı, Sendika kurma hakkı", ["Vatandaşlık hakkı", "Seçilme hakkı", "Yaşama hakkı", "Mülkiyet hakkı"], "Sosyal devletin vatandaşa sunduğu hizmet haklarıdır."),
    ("Vatandaşın devlet yönetimine katılmasına imkân tanıyan 'Katılma Hakları (Siyasi Hak ve Ödevler / Aktif Statü)' grubuna hangisi girer?", "Seçme ve seçilme hakkı, Siyasi parti kurma, Vatandaşlık, Dilekçe hakkı", ["Eğitim hakkı", "Konut hakkı", "Çalışma hakkı", "Sağlık hakkı"], "Yönetime iştirak haklarıdır."),
    ("1982 Anayasası'nın 13. maddesine göre temel hak ve hürriyetler ANCAK ne ile sınırlandırılabilir?", "Ancak Kanun ile sınırlanabilir", ["Cumhurbaşkanlığı Kararnamesi ile", "Yönetmelik ile", "Genelge ile", "Bakan onayıyla"], "Temel haklar tüzük veya yönetmelikle kısıtlanamaz, sadece TBMM kanunuyla sınırlanabilir."),
    ("Temel hak ve hürriyetlerin sınırlanmasında sınırlandırmanın demokratik toplum düzeninin gereklerine ve ulaşılmak istenen amaçla orantılı olmasına ne ad verilir?", "Ölçülülük İlkesi", ["Laiklik İlkesi", "Kanunilik İlkesi", "Kuvvet İlkesi", "Gereklilik İlkesi"], "Hakkın özüne dokunulamaz ve orantısız tedbir alınamaz."),
    ("Savaş, seferberlik veya olağanüstü hallerde dahi DOKUNULAMAYACAK olan 'Çekirdek Haklar' arasında aşağıdakilerden hangisi YER ALMAZ?", "Mülkiyet hakkı", ["Kişinin yaşama hakkı", "Maddi ve manevi varlığının bütünlüğü", "Kimsenin din, vicdan, düşünce ve kanaatlerini açıklamaya zorlanamaması", "Suç ve cezaların geçmişe yürütülememesi ve Masumiyet Karinesi"], "Mülkiyet hakkı çekirdek hak değildir; savaşta el konulabilir."),
    ("Suçluluğu hükmen sabit oluncaya kadar hiç kimsenin suçlu sayılamayacağını ifade eden evrensel ceza hukuku ilkesi hangisidir?", "Masumiyet Karinesi (Suçsuzluk Karinesi)", ["Tabii Hâkim İlkesi", "Kanunilik İlkesi", "Kuvvetler Ayrılığı", "Şahsilik İlkesi"], "Kesinleşmiş mahkeme kararı olmadan kimse suçlu ilan edilemez."),
    ("Ceza sorumluluğunun şahsiliği ilkesine göre ceza hukuku alanında aşağıdakilerden hangisi KESİNLİKLE yasaktır?", "Başkası yerine hapis yatılması veya kolektif ceza verilmesi", ["Para cezası kesilmesi", "Hapis cezası verilmesi", "Kamu haklarından mahrumiyet", "Tazminat ödenmesi"], "Kimse başkasının işlediği fiilden dolayı cezalandırılamaz."),
    ("Türkiye Cumhuriyeti Anayasası'na göre vatandaşlıktan çıkarma kararlarına karşı hangi yargı yolu AÇIKTIR?", "Yargı yolu kapatılamaz (Danıştay'a iptal davası açılabilir)", ["Yargı yolu kesin olarak kapalıdır.", "Sadece TBMM'ye itiraz edilebilir.", "Sadece Cumhurbaşkanına başvurulur.", "Uyuşmazlık Mahkemesi bakar."], "Vatandaşlıktan çıkarma işlemine karşı yargı denetimi anayasal teminattır."),
    ("Kişinin haklarının ihlal edilmesi durumunda yargı mercileri önünde davacı veya davalı olarak iddia ve savunmada bulunabilme hakkına ne ad verilir?", "Hak Arama Hürriyeti ve Adil Yargılanma Hakkı (Madde 36)", ["Dilekçe Hakkı", "Seçilme Hakkı", "Sosyal Güvenlik Hakkı", "Vatandaşlık Hakkı"], "Meşru vasıta ve yollardan faydalanma hürriyetidir.")
]

# Q112: TBMM Yapısı ve Milletvekilliği
q112_list = [
    ("1982 Anayasası'na göre (2017 değişikliğiyle) Türkiye Büyük Millet Meclisi kaç milletvekilinden oluşur?", "600 milletvekili", ["550 milletvekili", "450 milletvekili", "500 milletvekili", "650 milletvekili"], "2017 anayasa değişikliği ile üye sayısı 550'den 600'e çıkarılmıştır."),
    ("Türkiye'de milletvekili seçilme yaşı 2017 anayasa değişikliği ile kaç yaşa indirilmiştir?", "18 yaşını doldurmuş olmak", ["21 yaş", "25 yaş", "30 yaş", "19 yaş"], "18 yaşını dolduran her Türk vatandaşı milletvekili seçilebilir."),
    ("TBMM ve Cumhurbaşkanlığı seçimleri kural olarak kaç yılda bir aynı gün yapılır?", "5 yılda bir", ["4 yılda bir", "3 yılda bir", "6 yılda bir", "2 yılda bir"], "Olağan seçim dönemi 5 yıldır."),
    ("TBMM seçimleri ANCAK hangi gerekçeyle ve en fazla ne kadar süreyle geriye bırakılabilir (ertelenir)?", "Savaş sebebiyle - 1 yıl ertelenebilir", ["Ekonomik kriz sebebiyle - 6 ay", "Deprem sebebiyle - 2 yıl", "Salgın hastalık sebebiyle - 3 ay", "Cumhurbaşkanı kararıyla - 5 yıl"], "Seçimleri erteleme yetkisi sadece TBMM'ye aittir ve sadece savaş halinde 1 yıl geriye bırakılabilir."),
    ("Milletvekilinin meclis çalışmalarındaki oy, söz ve düşünce açıklamalarından dolayı ömür boyu ceza kovuşturmasına uğramamasını sağlayan MUTLAK korumaya ne ad verilir?", "Yasama Sorumsuzluğu", ["Yasama Dokunulmazlığı", "Bakan Dokunulmazlığı", "Diplomatik Muafiyet", "Yargı Muafiyeti"], "Meclis tarafından dahi kaldırılamayan mutlak haktır."),
    ("Ağır cezayı gerektiren suçüstü hali ve anayasanın 14. maddesindeki durumlar hariç, milletvekilinin meclis kararı olmadıkça tutuklanamaması ve yargılanamamasına ne ad verilir?", "Yasama Dokunulmazlığı (Nisbi Korumadır)", ["Yasama Sorumsuzluğu", "Milletvekili Maaşı", "Genel Af", "Beraat"], "TBMM Genel Kurulu kararıyla dokunulmazlık kaldırılabilir."),
    ("Yasama dokunulmazlığı kaldırılan veya milletvekilliği düşürülen bir mebus kaç gün içinde nereye itiraz edebilir?", "7 gün içinde Anayasa Mahkemesi'ne (AYM 15 gün içinde karara bağlar)", ["10 gün içinde Danıştay'a", "30 gün içinde Yargıtay'a", "15 gün içinde TBMM Başkanlığı'na", "5 gün içinde YSK'ya"], "Anayasa Mahkemesi iptal başvurusunu kesin olarak karara bağlar."),
    ("Bir milletvekilinin istifa etmesi halinde milletvekilliğinin düşmesine kim karar verir?", "TBMM Genel Kurulu (üye tamsayısının salt çoğunluğuyla)", ["Cumhurbaşkanı", "Anayasa Mahkemesi", "Yargıtay", "Meclis Başkanı tek başına"], "İstifanın geçerliliği meclis genel kurulunca kabul edilmelidir."),
    ("TBMM her yıl hangi gün kendiliğinden toplanır ve bir yasama yılında en çok kaç ay tatil yapabilir?", "1 Ekim'de toplanır - En çok 3 ay tatil yapar", ["1 Eylül'de toplanır - 2 ay tatil", "29 Ekim'de toplanır - 1 ay tatil", "1 Ocak'ta toplanır - 4 ay tatil", "23 Nisan'da toplanır - 15 gün tatil"], "Tatil döneminde meclis toplantıya çağrılabilir."),
    ("TBMM'de siyasi parti grupları en az kaç milletvekilinden oluşur?", "En az 20 milletvekili", ["10 milletvekili", "30 milletvekili", "15 milletvekili", "25 milletvekili"], "Parti grubu kurabilmek için en az 20 vekil gerekir.")
]

# Q113: TBMM'nin Görev ve Yetkileri
q113_list = [
    ("Aşağıdakilerden hangisi Türkiye Büyük Millet Meclisi'nin (TBMM) görev ve yetkileri arasında YER ALMAZ?", "Bakanları ve Cumhurbaşkanı yardımcılarını atamak ve görevden almak", ["Kanun koymak, değiştirmek ve kaldırmak", "Bütçe ve kesinhesap kanun tekliflerini görüşmek ve kabul etmek", "Para basılmasına ve savaş ilanına karar vermek", "Genel ve özel af ilanına karar vermek"], "Bakanları atamak ve görevden almak tamamen Cumhurbaşkanının yetkisindedir."),
    ("TBMM'nin genel veya özel af ilan edebilmesi için karar yeter sayısı ne kadardır?", "Üye tamsayısının beşte üç (3/5) çoğunluğu (360 milletvekili)", ["Üye tamsayısının salt çoğunluğu (301)", "Üye tamsayısının üçte iki çoğunluğu (400)", "Toplantıya katılanların salt çoğunluğu", "Meclis Başkanının tek başına onayı"], "Nitelikli çoğunluk olan 360 oy şarttır."),
    ("Milletlerarası antlaşmaların onaylanmasını bir kanunla UYGUN BULMA yetkisi kime aittir?", "Türkiye Büyük Millet Meclisi'ne (TBMM)", ["Cumhurbaşkanı tek başına", "Dışişleri Bakanı", "Anayasa Mahkemesi", "Danıştay"], "Meclis uygun bulma kanunu çıkarır, antlaşmayı onaylayıp yayımlayan ise Cumhurbaşkanıdır."),
    ("TBMM'nin kanun yapma sürecinde kanun teklif etmeye kimler yetkilidir?", "Yalnızca Milletvekilleri (Tek bir milletvekili dahi teklif verebilir)", ["Cumhurbaşkanı (Bütçe hariç teklif veremez)", "Bakanlar", "Vatandaşlar doğrudan", "Valiler"], "Bütçe Kanun Teklifi hariç tüm kanun tekliflerini sadece milletvekilleri verir."),
    ("TBMM tarafından kabul edilen kanunları kaç gün içinde Resmi Gazete'de yayımlamak veya meclise geri göndermek (veto etmek) Cumhurbaşkanının görevidir?", "15 gün içinde", ["10 gün içinde", "30 gün içinde", "7 gün içinde", "20 gün içinde"], "Cumhurbaşkanı 15 gün içinde ya onaylar ya veto eder."),
    ("Cumhurbaşkanının veto edemeyeceği, meclise geri gönderemeyeceği TEK KANUN hangisidir?", "Bütçe Kanunu", ["Af Kanunu", "Vergi Kanunu", "Seçim Kanunu", "Medeni Kanun"], "Bütçe Kanunu kamu hizmetlerinin aksamaması için veto edilemez."),
    ("Cumhurbaşkanı tarafından veto edilerek meclise geri gönderilen bir kanunun aynen kabul edilebilmesi için TBMM'de aranan çoğunluk nedir?", "Üye tamsayısının salt çoğunluğu (En az 301 oy)", ["Toplantıya katılanların salt çoğunluğu", "Üye tamsayısının 3/5 çoğunluğu", "Üye tamsayısının 2/3 çoğunluğu", "Basit çoğunluk"], "2017 değişikliğiyle en az 301 milletvekilinin oyu şart koşulmuştur."),
    ("TBMM'nin iç çalışma düzenini, komisyonlarını, disiplin cezalarını düzenleyen ve Anayasa Mahkemesi denetimine tabi olan parlamento kararı hangisidir?", "TBMM İçtüzüğü", ["Bakanlar Kurulu Kararı", "Genelge", "Yönetmelik", "Kanun Hükmünde Kararname"], "Meclisin kendi çalışmalarını düzenlediği temel kuraldır."),
    ("TBMM Genel Kurulu'nda bir konunun görüşülebilmesi için gereken asgari toplantı yeter sayısı kaçtır?", "Üye tamsayısının en az üçte biri (200 milletvekili)", ["Salt çoğunluk (301)", "150 milletvekili", "250 milletvekili", "100 milletvekili"], "200 milletvekili hazır bulunmadan meclis açılamaz."),
    ("TBMM'de kural olarak (özel çoğunluk aranmayan hallerde) karar yeter sayısı nedir?", "Toplantıya katılanların salt çoğunluğu (Ancak üye tamsayısının 1/4'ünün bir fazlasından yani 151'den az olamaz)", ["Her zaman 301", "Her zaman 200", "En az 100", "En az 180"], "Meclis hiçbir zaman 151'den az oyla karar alamaz.")
]
