# vatandaslik_data_2.py - Q114 to Q120 (70 questions)

# Q114: Yürütme - Cumhurbaşkanı Nitelikleri ve Seçimi
q114_list = [
    ("1982 Anayasası'na göre Cumhurbaşkanı seçilebilmek için kaç yaşını doldurmuş olmak ve hangi eğitim düzeyine sahip olmak şarttır?", "40 yaşını doldurmuş olmak ve Yükseköğrenim mezunu olmak", ["30 yaş - Lise mezunu", "35 yaş - Üniversite mezunu", "45 yaş - Doktora mezunu", "18 yaş - İlkokul mezunu"], "40 yaş ve 4 yıllık üniversite diploması anayasal zorunluluktur."),
    ("Cumhurbaşkanının görev süresi kaç yıldır ve bir kimse en fazla kaç defa Cumhurbaşkanı seçilebilir?", "5 yıldır - En fazla 2 defa seçilebilir", ["4 yıldır - Sınırsız", "7 yıldır - 1 defa", "6 yıldır - 2 defa", "5 yıldır - Sınırsız"], "Cumhurbaşkanlığı süresi 5 yıldır, en fazla iki kez seçilebilir."),
    ("Cumhurbaşkanlığına aday gösterebilmek için gerekli şartlar arasında aşağıdakilerden hangisi YER ALMAZ?", "Herhangi bir sivil toplum kuruluşunun veya sendikanın başvurusu", ["TBMM'de grubu bulunan siyasi partiler", "Son milletvekili seçiminde toplam geçerli oyların tek başına veya birlikte en az %5'ini almış olan partiler", "En az 100 bin seçmenin imzası", "Üniversitelerarası Kurul kararı"], "Sendikalar veya dernekler doğrudan cumhurbaşkanı adayı gösteremez."),
    ("Cumhurbaşkanı seçiminde birinci oylamada geçerli oyların salt çoğunluğu (yüzde 50 + 1 oy) sağlanamazsa ne yapılır?", "İlk oylamayı takip eden ikinci pazar günü en çok oy alan iki aday arasında ikinci oylama yapılır.", ["Seçim iptal edilir ve meclis seçer.", "En yaşlı aday cumhurbaşkanı olur.", "Üçüncü oylamaya tüm adaylar tekrar katılır.", "TBMM Başkanı cumhurbaşkanı atanır."], "İkinci turda en çok oyu alan aday seçilmiş olur."),
    ("Cumhurbaşkanlığı makamının herhangi bir nedenle boşalması halinde (istifa, vefat vb.) yenisi seçilene kadar Cumhurbaşkanlığına kim vekâlet eder?", "Cumhurbaşkanı Yardımcısı", ["TBMM Başkanı", "Adalet Bakanı", "Anayasa Mahkemesi Başkanı", "En yaşlı milletvekili"], "2017 anayasa değişikliğiyle vekâlet görevi Meclis Başkanından alınıp Cumhurbaşkanı Yardımcısına verilmiştir."),
    ("Cumhurbaşkanı, yürütme yetkisine ilişkin konularda hangi düzenleyici işlemi çıkarabilir?", "Cumhurbaşkanlığı Kararnamesi (CBK)", ["Kanun Hükmünde Kararname", "Tüzük", "Yasa", "Hükümet Bildirisi"], "CBK'lar doğrudan Anayasa Mahkemesi'nin yargı denetimine tabidir."),
    ("Cumhurbaşkanlığı Kararnamesi ile aşağıdakilerden hangisi KESİNLİKLE düzenlenemez?", "Anayasa'da münhasıran kanunla düzenlenmesi öngörülen konular ve Kişi/Siyasi Haklar", ["Bakanlıkların teşkilat yapısı", "Üst düzey kamu yöneticilerinin atanması", "Cumhurbaşkanlığı Genel Sekreterliği", "Sosyal ve ekonomik haklar"], "Kanunda açıkça düzenlenen konularda ve çekirdek haklarda kararname çıkarılamaz; kanun ile CBK çatışırsa kanun uygulanır."),
    ("Cumhurbaşkanı hakkında bir suç işlediği iddiasıyla TBMM'de soruşturma açılabilmesi için teklif ve kabul yeter sayıları nelerdir?", "Üye tamsayısının salt çoğunluğuyla (301) teklif - Üye tamsayısının beşte üçüyle (360) kabul", ["100 vekille teklif - 200 ile kabul", "200 ile teklif - 301 ile kabul", "360 ile teklif - 400 ile kabul", "Basit çoğunlukla teklif ve kabul"], "Cezai sorumluluk soruşturma komisyonu kurulmasını gerektirir."),
    ("Hakkında soruşturma açılan Cumhurbaşkanının Yüce Divan'a (Anayasa Mahkemesi) sevk edilebilmesi için TBMM'de aranan nihai çoğunluk kaçtır?", "Üye tamsayısının üçte iki (2/3) çoğunluğu (400 milletvekili)", ["360 milletvekili", "301 milletvekili", "450 milletvekili", "Salt çoğunluk"], "Gizli oylamayla 400 milletvekilinin oyu gerekir."),
    ("Cumhurbaşkanlığı Kararnameleri ve kanunlar aksi belirtilmedikçe ne zaman yürürlüğe girer?", "Resmi Gazete'de yayımlandığı gün", ["Yayımlandıktan 45 gün sonra", "Yayımlandıktan 1 ay sonra", "Mecliste kabul edildiği gün", "Yılbaşında"], "Metinde özel bir tarih belirtilmemişse yayımlandığı gün yürürlüğe girer.")
]

# Q115: Cumhurbaşkanlığı Hükümet Sistemi ve OHAL
q115_list = [
    ("Cumhurbaşkanı yardımcıları ve bakanlar kim tarafından atanır ve görevden alınır?", "Cumhurbaşkanı tarafından", ["TBMM tarafından", "Başbakan tarafından", "Danıştay onayıyla", "Halk oylamasıyla"], "Tamamen Cumhurbaşkanının takdirindedir; meclisten güvenoyu almazlar."),
    ("Milletvekili olan bir kişi Cumhurbaşkanı Yardımcısı veya Bakan olarak atanırsa milletvekilliği durumu ne olur?", "Milletvekilliği kendiliğinden sona erer (düşer)", ["Hem vekil hem bakan olmaya devam eder.", "Görevi bitince vekilliğe geri dönemez.", "Meclis oylamasıyla düşürülür.", "Maaşını vekillikten alır."], "Kuvvetler ayrılığı gereği bakan olan vekilin meclis üyeliği anında düşer."),
    ("1982 Anayasası'na göre savaş, doğal afet, tehlikeli salgın hastalık veya kamu düzeninin bozulması durumlarında Olağanüstü Hal (OHAL) ilan etme yetkisi kime aittir?", "Cumhurbaşkanına", ["TBMM Başkanına", "İçişleri Bakanına", "Milli Savunma Bakanına", "Genelkurmay Başkanına"], "Cumhurbaşkanı yurdun tamamında veya bir bölgesinde OHAL ilan edebilir."),
    ("Cumhurbaşkanı tarafından ilan edilen OHAL kararı en fazla kaç ay için ilan edilebilir ve ne zaman meclis onayına sunulur?", "En fazla 6 ay için ilan edilir - Aynı gün TBMM onayına sunulur", ["1 yıl için - 30 gün içinde", "3 ay için - 1 hafta içinde", "2 yıl için - Hemen", "4 ay için - Ertesi gün"], "İlan edildiği gün Resmi Gazete'de yayımlanır ve TBMM onayına gider."),
    ("TBMM, Cumhurbaşkanının ilan ettiği OHAL süresini değiştirebilir, kaldırabilir veya her defasında en fazla ne kadar süreyle uzatabilir?", "Her defasında en fazla 4 ay uzatabilir (Savaş halinde 4 aylık sınır aranmaz)", ["6 ay uzatabilir", "1 yıl uzatabilir", "2 ay uzatabilir", "1 ay uzatabilir"], "Uzatma yetkisi sadece meclise aittir."),
    ("OHAL döneminde çıkarılan Cumhurbaşkanlığı Kararnamelerinin olağan CBK'lardan en temel farkı nedir?", "Temel hak ve hürriyetlerin (çekirdek haklar hariç) durdurulabilmesi veya sınırlanabilmesi", ["Yargı denetimine tabi olmaması", "Resmi Gazete'de yayımlanmaması", "Bakanların imzalaması", "Meclise sunulmaması"], "OHAL kararnameleriyle kişi hakları da kısıtlanabilir."),
    ("Cumhurbaşkanı, bakanlıklar ve kamu tüzel kişileri kendi görev alanlarını ilgilendiren kanunların ve cumhurbaşkanlığı kararnamelerinin uygulanmasını sağlamak amacıyla ne çıkarabilirler?", "Yönetmelik", ["Kanun Hükmünde Kararname", "Tüzük (kaldırıldı)", "Ferman", "İçtüzük"], "Kanunlara ve CBK'lara aykırı olamaz."),
    ("Ülke çapında uygulanacak yönetmeliklerin yargısal iptal denetimi hangi yüksek mahkemede yapılır?", "Danıştay", ["Yargıtay", "Anayasa Mahkemesi", "Uyuşmazlık Mahkemesi", "Sayıştay"], "Ülke geneli yönetmelikleri Danıştay, yerel yönetmelikleri idare mahkemeleri denetler."),
    ("Milli Güvenlik Kurulu (MGK) hangi aralıklarla ve kimin başkanlığında toplanır?", "İki ayda bir - Cumhurbaşkanının başkanlığında", ["Her ay - Başbakanın başkanlığında", "Üç ayda bir - Genelkurmay Başkanı başkanlığında", "Altı ayda bir - Meclis Başkanı başkanlığında", "Haftada bir - İçişleri Bakanı başkanlığında"], "Cumhurbaşkanının katılamadığı hallerde Cumhurbaşkanı Yardımcısı başkanlık eder."),
    ("Milli Güvenlik Kurulu (MGK) üyeleri arasında aşağıdakilerden hangisi YER ALMAZ?", "TBMM Başkanı", ["Cumhurbaşkanı Yardımcıları", "Adalet, İçişleri, Dışişleri, Milli Savunma Bakanları", "Genelkurmay Başkanı", "Kara, Deniz ve Hava Kuvvetleri Komutanları"], "TBMM Başkanı yasama organı başkanı olduğu için yürütme danışma organı olan MGK'da yer almaz.")
]

# Q116: Yargı - Yüksek Mahkemeler, AYM, HSK
q116_list = [
    ("1982 Anayasası'nda düzenlenen DÖRT yüksek mahkeme hangi seçenekte eksiksiz verilmiştir?", "Anayasa Mahkemesi, Yargıtay, Danıştay, Uyuşmazlık Mahkemesi", ["Sayıştay, YSK, Askeri Yargıtay, AYM", "Danıştay, Sayıştay, HSK, Yargıtay", "Yüksek Seçim Kurulu, AYM, Yargıtay, İdare", "Yargıtay, Danıştay, Askeri Yüksek İdare, AYM"], "2017 değişikliğiyle Askeri Yargıtay ve AYİM kaldırılmış, geriye 4 yüksek mahkeme kalmıştır."),
    ("Anayasa Mahkemesi kaç üyeden oluşur ve üyelerin görev süresi kaç yıldır?", "15 üyeden oluşur - Görev süresi 12 yıldır (Tekrar seçilemezler)", ["17 üye - 10 yıl", "11 üye - Ömür boyu", "21 üye - 5 yıl", "15 üye - 6 yıl"], "Cumhurbaşkanı 12 üye, TBMM 3 üye seçer."),
    ("Anayasa Mahkemesi üyeliğine seçilebilmek için kaç yaşını doldurmuş olmak gerekir?", "45 yaşını doldurmuş olmak", ["40 yaş", "35 yaş", "50 yaş", "30 yaş"], "Yüksek yargıç tecrübesi için 45 yaş şartı vardır."),
    ("Kanunların, Cumhurbaşkanlığı Kararnamelerinin ve TBMM İçtüzüğü'nün anayasaya şekil ve esas bakımından uygunluğunu denetleyen yüksek yargı organı hangisidir?", "Anayasa Mahkemesi", ["Yargıtay", "Danıştay", "Sayıştay", "Uyuşmazlık Mahkemesi"], "Norm denetimi yapan yargı organıdır."),
    ("Siyasi partilerin kapatılması davalarına Yargıtay Cumhuriyet Başsavcısı'nın açtığı dava üzerine hangi mahkeme bakar?", "Anayasa Mahkemesi", ["Yargıtay Ceza Genel Kurulu", "Danıştay", "Yüce Divan", "Ağır Ceza Mahkemesi"], "Siyasi parti kapatma veya hazine yardımından yoksun bırakma kararını AYM verir."),
    ("Cumhurbaşkanı, TBMM Başkanı, Bakanlar ve yüksek yargı mensuplarını görevleriyle ilgili suçlardan dolayı yargılayan 'Yüce Divan' sıfatını hangi mahkeme kullanır?", "Anayasa Mahkemesi", ["Yargıtay", "Danıştay", "Sayıştay", "HSK"], "Yüce Divan yargılamasını AYM Genel Kurulu yürütür."),
    ("Adliye mahkemelerince (hukuk ve ceza mahkemeleri) verilen karar ve hükümlerin son inceleme mercii olan yüksek mahkeme hangisidir?", "Yargıtay", ["Danıştay", "Anayasa Mahkemesi", "Uyuşmazlık Mahkemesi", "Bölge Adliye Mahkemesi"], "Adli yargının temyiz merciidir; başsavcısını Cumhurbaşkanı seçer."),
    ("İdari mahkemelerce (idare ve vergi) verilen kararların son inceleme mercii olan ve kamu hizmeti imtiyaz sözleşmelerini inceleyen yüksek mahkeme hangisidir?", "Danıştay", ["Yargıtay", "Sayıştay", "Uyuşmazlık Mahkemesi", "Anayasa Mahkemesi"], "İdari yargının en üst temyiz organıdır; üyelerinin 3/4'ünü HSK, 1/4'ünü Cumhurbaşkanı seçer."),
    ("Adli ve idari yargı mercileri arasındaki görev ve hüküm uyuşmazlıklarını KESİN olarak çözmeye yetkili yüksek mahkeme hangisidir?", "Uyuşmazlık Mahkemesi", ["Danıştay", "Yargıtay", "Anayasa Mahkemesi", "Sayıştay"], "Başkanını Anayasa Mahkemesi kendi üyeleri arasından seçer."),
    ("Hâkim ve savcıların mesleğe kabulü, atanması, nakli, disiplin cezaları ve meslekten çıkarılması işlemlerini yürüten 13 üyeli kurul hangisidir?", "Hâkimler ve Savcılar Kurulu (HSK)", ["Adalet Bakanlığı Müsteşarlığı", "Yüksek Disiplin Kurulu", "Yargıtay Başkanlar Kurulu", "Sayıştay"], "Başkanı Adalet Bakanı'dır; Adalet Bakanı Yardımcısı tabii üyedir.")
]

# Q117: İdare Hukuku - Teşkilat Yapısı ve Vesayet
q117_list = [
    ("Merkezi idarenin taşradaki en büyük mülki amiri olan, devleti ve Cumhurbaşkanını temsil eden ve 'Yetki Genişliği'ne sahip olan kamu görevlisi kimdir?", "Vali", ["Kaymakam", "Belediye Başkanı", "Muhtar", "İl Genel Meclisi Başkanı"], "Vali Cumhurbaşkanı kararıyla atanır ve yetki genişliğini tek başına kullanır."),
    ("Türkiye'de ilçelerin başında bulunan ve Cumhurbaşkanı onayıyla atanan mülki amir olan Kaymakam'ın Vali'den EN ÖNEMLİ farkı nedir?", "Yetki genişliğine sahip olmaması ve sadece hükümeti temsil etmesi", ["Yargı yetkisinin bulunması", "Belediye başkanı olması", "Seçimle iş başına gelmesi", "Milletvekili olması"], "Kaymakam devleti değil sadece hükümeti temsil eder ve yetki genişliği yoktur."),
    ("Merkezi idare ile yerinden yönetim kuruluşları arasındaki bütünlüğü sağlamak amacıyla merkezi idarenin yerel yönetimler üzerindeki hukuki denetimine ne ad verilir?", "İdari Vesayet Denetimi", ["Hiyerarşik Denetim", "Yargısal Denetim", "Siyasi Denetim", "Mali Denetim"], "Örneğin İçişleri Bakanı'nın belediye başkanını geçici uzaklaştırması veya Valinin köy kararlarını onaylaması idari vesayettir."),
    ("Aynı kamu tüzel kişiliği içerisindeki üst makamın alt makama emir, talimat verme ve işlemlerini iptal etme yetkisine ne ad verilir?", "Hiyerarşi Yetkisi", ["İdari Vesayet", "Yetki Genişliği", "Kamu Yararı", "Regülasyon"], "Örneğin Bakanın müsteşara veya Valinin kaymakama emir vermesi hiyerarşidir."),
    ("Anayasa'ya göre Türkiye'de Mahalli İdareler (Yerel Yönetimler) hangileridir?", "İl Özel İdaresi, Belediye, Büyükşehir Belediyesi, Köy", ["İl genel idaresi, İlçe idaresi, Bucak", "Bakanlıklar, Valilikler, Kaymakamlıklar", "Üniversiteler, TRT, Barolar", "KİT'ler, Merkez Bankası, TÜBİTAK"], "Karar organları halk tarafından seçilen özerk kamu tüzel kişilikleridir."),
    ("Bir yerleşim yerinde belediye kurulabilmesi için nüfusun en az kaç olması ve ne ile kurulması gerekir?", "Nüfusun en az 5.000 olması - Cumhurbaşkanı kararı ile kurulması", ["Nüfus 2.000 - Kanun ile", "Nüfus 10.000 - Vali onayı ile", "Nüfus 50.000 - İçişleri Bakanı kararı ile", "Nüfus 1.000 - Referandum ile"], "5.000 nüfus şartı aranır ve Cumhurbaşkanı kararı gerekir."),
    ("Türkiye'de bir ilin 'Büyükşehir Belediyesi' statüsü kazanabilmesi için toplam nüfusunun en az kaç olması ve ne ile kurulması şarttır?", "Nüfusu en az 750.000 olmalı - Kanun ile kurulmalıdır", ["Nüfusu 500.000 - Cumhurbaşkanı kararı", "Nüfusu 1.000.000 - Bakanlık onayı", "Nüfusu 250.000 - Valilik kararı", "Nüfusu 300.000 - Meclis kararı"], "Büyükşehirler yalnızca TBMM tarafından çıkarılan kanunla kurulabilir."),
    ("Köyün yerel yönetim organları aşağıdakilerden hangisinde eksiksiz verilmiştir?", "Köy Derneği (seçmenler), İhtiyar Meclisi ve Muhtar", ["Vali, Kaymakam, Muhtar", "Belediye Meclisi, Encümen, Başkan", "Kaymakam, İhtiyar Heyeti, İmam", "Köy İdare Kurulu ve Bekçi"], "Köy derneği köydeki tüm kadın ve erkek seçmenlerden oluşur."),
    ("Köyün isteğe bağlı işlerini zorunlu hale getirme yetkisi köyün hangi organına aittir?", "Köy İhtiyar Meclisi", ["Muhtar tek başına", "Köy Derneği", "Kaymakam", "İlçe Tarım Müdürü"], "İhtiyar meclisi kararıyla imece ve salma gibi zorunlu uygulamalar getirilir."),
    ("Türkiye'de kamu hizmeti yürüten memur ve kamu görevlilerinin kusurlu eylemleri sonucu vatandaşın uğradığı zararlar nedeniyle tazminat davası kime karşı açılır?", "Kural olarak doğrudan İdareye (Devlete) karşı açılır", ["Kişisel olarak doğrudan memura açılır.", "Kaymakamlığa açılır.", "Ceza mahkemesine açılır.", "İtiraz komisyonuna açılır."], "Anayasa m. 129: Zarar idarece tazmin edilir, idare sorumlu memura rücu eder.")
]

# Q118: 657 Sayılı Devlet Memurları Kanunu
q118_list = [
    ("657 Sayılı Devlet Memurları Kanunu'na göre memurluğa alınmada, ilerlemede ve yükselmede liyakat ve başarı ilkelerinin esas alınmasına ne ad verilir?", "Liyakat İlkesi", ["Kariyer İlkesi", "Sınıflandırma İlkesi", "Eşitlik İlkesi", "Sadakat İlkesi"], "Görevin gerektirdiği ehliyete göre işe alma ve yükselmedir."),
    ("Memurların yaptıkları hizmetler için lüzumlu bilgilere ve yetişme şartlarına uygun şekilde, sınıfları içinde en yüksek derecelere kadar ilerleme imkânına sahip olmasına ne ad verilir?", "Kariyer İlkesi", ["Liyakat İlkesi", "Sınıflandırma", "Tarafsızlık", "Güvence"], "Kariyer planlaması ve basamak yükselmesidir."),
    ("657 sayılı kanuna göre devlet memurluğuna ilk defa atanan bir kişinin adaylık süresi EN AZ ve EN ÇOK ne kadar olabilir?", "En az 1 yıl - En çok 2 yıl", ["En az 6 ay - En çok 1 yıl", "En az 2 yıl - En çok 3 yıl", "En az 3 ay - En çok 6 ay", "Sabit 1 yıl"], "Adaylık devresi içinde başarısız olanların memurlukla ilişiği kesilir."),
    ("Devlet memuruna görevinde ve davranışlarında daha dikkatli olması gerektiğinin YAZILI olarak bildirilmesine hangi disiplin cezası denir?", "Uyarma cezası", ["Kınama cezası", "Aylıktan kesme", "Kademe ilerlemesini durdurma", "İhtar"], "En hafif disiplin cezasıdır."),
    ("Devlet memuruna görevinde ve davranışlarında kusurlu sayıldığının YAZILI olarak bildirilmesine hangi disiplin cezası denir?", "Kınama cezası", ["Uyarma cezası", "Aylıktan kesme", "Tevbih", "İhraç"], "Kusurlu bulunduğunun bildirilmesidir."),
    ("Memurun brüt aylığından 1/30 ile 1/8 arasında kesinti yapılması şeklindeki disiplin cezası hangisidir?", "Aylıktan Kesme cezası", ["Kınama", "Kademe durdurma", "Para cezası", "Maaş dondurma"], "Disiplin amiri tarafından verilir."),
    ("Bulunulan kademedeki ilerlemenin fiilin ağırlık derecesine göre 1 - 3 yıl süreyle durdurulmasına ne ad verilir?", "Kademe İlerlemesinin Durdurulması", ["Aylıktan kesme", "Derece düşürme", "Kınama", "Kıdem cezası"], "İl disiplin kurulu kararıyla verilir."),
    ("Bir daha devlet memurluğuna atanmamak üzere memurluk statüsünün tamamen sona erdirilmesine ne ad verilir ve bu cezayı KİM verir?", "Devlet Memurluğundan Çıkarma - Yüksek Disiplin Kurulu kararıyla verilir", ["Kademe durdurma - Bakan verir", "İstifa - Vali verir", "Görevden uzaklaştırma - Müfettiş verir", "Re'sen emeklilik - Başbakan verir"], "Yüksek Disiplin Kurulu'nun kararıyla en ağır ceza olarak tesis edilir."),
    ("Devlet memurlarına verilen TÜM disiplin cezalarına karşı (uyarma ve kınama dahil) yargı yolu AÇIK MIDIR?", "Evet, tüm disiplin cezalarına karşı idari yargı yolu açıktır.", ["Hayır, uyarma ve kınamaya dava açılamaz.", "Sadece memurluktan çıkarmaya dava açılır.", "Yalnızca Anayasa Mahkemesi bakar.", "Yargı yolu tamamen kapalıdır."], "2010 Anayasa değişikliği ile uyarma ve kınama cezaları da yargı denetimine açılmıştır."),
    ("Hizmet süresi 1 yıldan 10 yıla kadar (10 yıl dahil) olan devlet memurlarının yıllık ücretli izin süresi kaç gündür?", "20 gün (10 yıldan fazla olanlar için 30 gündür)", ["15 gün", "25 gün", "10 gün", "14 gün"], "Kıdem arttıkça yıllık izin süresi uzar.")
]

# Q119: Uluslararası Kuruluşlar
q119_list = [
    ("1945 yılında dünya barışını ve güvenliğini korumak amacıyla kurulan, Türkiye'nin de kurucu üye olduğu Birleşmiş Milletler'in (BM) genel merkezi nerededir?", "New York (ABD)", ["Cenevre (İsviçre)", "Brüksel (Belçika)", "Paris (Fransa)", "Londra (İngiltere)"], "BM Genel Merkezi New York'ta yer alır."),
    ("Birleşmiş Milletler Güvenlik Konseyi'nde (BMGK) alınan kararları tek başına VETO etme hakkına sahip 5 daimi üye ülke (FİRÇA şifresi) hangileridir?", "Fransa, İngiltere, Rusya, Çin, ABD", ["Almanya, Japonya, İtalya, Rusya, ABD", "Türkiye, Fransa, İngiltere, Çin, Almanya", "Kanada, Hindistan, Brezilya, Rusya, Çin", "İspanya, İtalya, ABD, Fransa, İngiltere"], "Bu 5 daimi üyenin tek bir vetosu kararı engeller."),
    ("Kuzey Atlantik Antlaşması Örgütü (NATO) savunma ittifakına Türkiye Cumhuriyeti hangi yıl üye olmuştur ve genel merkezi neresidir?", "1952 yılında üye olmuştur - Genel merkezi Brüksel'dedir (Belçika)", ["1949 - New York", "1950 - Londra", "1974 - Paris", "1991 - Berlin"], "Türkiye Yunanistan ile birlikte 1952'de NATO'ya üye olmuştur."),
    ("Avrupa İnsan Hakları Mahkemesi (AİHM) hangi uluslararası teşkilata bağlı olarak faaliyet gösterir ve merkezi neresidir?", "Avrupa Konseyi - Strazburg (Fransa)", ["Avrupa Birliği - Brüksel", "Birleşmiş Milletler - Lahey", "NATO - Cenevre", "OECD - Paris"], "Türkiye Avrupa Konseyi'nin kurucu üyelerindendir."),
    ("Merkezi İstanbul'da bulunan, Türk dünyası arasındaki iş birliğini ve entegrasyonu güçlendiren uluslararası örgüt hangisidir?", "Türk Devletleri Teşkilatı (TDT)", ["TÜRKSOY", "Karadeniz Ekonomik İşbirliği", "D-8", "İslam İşbirliği Teşkilatı"], "Azerbaycan, Kazakistan, Kırgızistan, Türkiye ve Özbekistan tam üyedir."),
    ("1997 yılında Başbakan Necmettin Erbakan öncülüğünde kurulan, gelişmekte olan 8 Müslüman ülkenin ekonomik iş birliği teşkilatı hangisidir?", "D-8 (Gelişen Sekiz Ülke)", ["G-20", "G-7", "OPEC", "OECD"], "Türkiye, İran, Pakistan, Bangladeş, Malezya, Endonezya, Mısır ve Nijerya'dan oluşur."),
    ("Uluslararası Para Fonu (IMF) ve Dünya Bankası'nın (World Bank) genel merkezleri hangi şehirde yer almaktadır?", "Washington D.C. (ABD)", ["New York", "Cenevre", "Zürih", "Londra"], "Bretton Woods ikizleri olarak bilinen kurumların merkezi Washington'dadır."),
    ("Petrol İhraç Eden Ülkeler Örgütü'nün (OPEC) genel merkezi nerede yer alır?", "Viyana (Avusturya)", ["Riyad (Suudi Arabistan)", "Kuveyt", "Bağdat", "Dubai"], "Avusturya üye olmamasına rağmen merkez Viyana'dadır."),
    ("Birleşmiş Milletler Eğitim, Bilim ve Kültür Örgütü (UNESCO) genel merkezi neresidir?", "Paris (Fransa)", ["Roma", "Cenevre", "Viyana", "Madrid"], "Dünya kültür miraslarını tescil eden kurumdur."),
    ("Dünya Sağlık Örgütü (WHO) ve Uluslararası Çalışma Örgütü'nün (ILO) genel merkezleri hangi şehirdedir?", "Cenevre (İsviçre)", ["New York", "Brüksel", "Lahey", "Strazburg"], "BM'nin uzmanlık kuruluşlarının merkezi Cenevre'dir.")
]

# Q120: Güncel Bilgiler ve Genel Kültür
q120_list = [
    ("Türkiye'nin İLK insanlı uzay misyonunu gerçekleştirerek Uluslararası Uzay İstasyonu'nda (ISS) 13 bilimsel deney yapan ilk Türk astronot kimdir?", "Alper Gezeravcı (Axiom Mission 3)", ["Tuva Cihangir Atasever", "Hulusi Akar", "Selçuk Bayraktar", "Vecihi Hürkuş"], "Ocak 2024'te uzay görevini başarıyla tamamlamıştır."),
    ("2015 yılında hücrelerin hasar gören DNA'ları nasıl onardığını haritalandıran araştırmalarıyla Nobel Kimya Ödülü'nü kazanan Türk bilim insanı kimdir?", "Prof. Dr. Aziz Sancar", ["Prof. Dr. Oktay Sinanoğlu", "Prof. Dr. Gazi Yaşargil", "Cahit Arf", "Ali Erdemir"], "Mardin Savur doğumlu gururumuz Aziz Sancar'dır."),
    ("2006 yılında Nobel Edebiyat Ödülü'nü kazanan ilk ve tek Türk yazar kimdir?", "Orhan Pamuk", ["Yaşar Kemal", "Ahmet Hamdi Tanpınar", "Nazım Hikmet", "Oğuz Atay"], "Benim Adım Kırmızı ve Kara Kitap yazarı Orhan Pamuk'tur."),
    ("Yüzyılın Beyin Cerrahı seçilen ve mikrocerrahinin kurucusu kabul edilen ünlü Türk bilim insanı kimdir?", "Prof. Dr. Gazi Yaşargil", ["Prof. Dr. Aziz Sancar", "Prof. Dr. Mehmet Öz", "Prof. Dr. Canan Dağdeviren", "Ord. Prof. Hulusi Behçet"], "Dünya Nöroşirürji dernekleri tarafından yüzyılın cerrahı ilan edilmiştir."),
    ("Türkiye'nin yerli ve milli ilk elektrikli otomobili olan Togg'un üretim tesisi hangi il ve ilçemizde açılmıştır?", "Bursa Gemlik", ["Kocaeli Gebze", "Sakarya Arifiye", "İzmir Torbalı", "Eskişehir Tepebaşı"], "Togg Teknoloji Kampüsü Gemlik'te kurulmuştur."),
    ("Cumhuriyet tarihinin en büyük arkeolojik keşiflerinden biri olarak kabul edilen ve Şanlıurfa'da Neolitik Çağ araştırmalarını kapsayan çatı projenin adı nedir?", "Taş Tepeler Projesi (Göbeklitepe, Karahantepe vb.)", ["Göbeklitepe Projesi", "Fırat Havzası Projesi", "Mezopotamya Kazıları", "GAP Kültür Yolu"], "Karahantepe ve çevresindeki 12 arkeolojik alanı kapsar."),
    ("Avrupa Voleybol Şampiyonası'nda altın madalya kazanarak Avrupa Şampiyonu olan ve 'Filenin Sultanları' olarak bilinen A Milli Kadın Voleybol Takımımızın yıldızları hangi başarıyı elde etmiştir?", "Avrupa Şampiyonluğu ve FIVB Milletler Ligi Şampiyonluğu", ["Dünya Kupası İkinciliği", "Olimpiyat Gümüşü", "Akdeniz Oyunları Dördüncülüğü", "Balkan Üçüncülüğü"], "2023 yılında peş peşe tarihi kupalar kazanmışlardır."),
    ("UNESCO Somut Olmayan Kültürel Miras Listesi'ne 2023 yılında Türkiye adına tescil edilen geleneksel lezzet ve kültür unsuru hangisidir?", "İftar ve İftar ile İlgili Sosyo-Kültürel Gelenekler", ["Türk Kahvesi", "Ebru Sanatı", "Kırkpınar Yağlı Güreşleri", "Meddahlık"], "Çok uluslu dosya olarak UNESCO listesine kaydedilmiştir."),
    ("Kendi geliştirdiği matematik teoremiyle 'Arf Değişmezi' ve 'Arf Halkaları' kavramlarını dünya literatürüne kazandıran ve 10 TL banknotunun arkasında resmi bulunan bilim insanı kimdir?", "Cahit Arf", ["Oktay Sinanoğlu", "Feza Gürsey", "Kerim Erim", "Ali Kuşçu"], "'Matematik de resim ve müzik gibi bir sanattır' diyen büyük matematikçidir."),
    ("2024 yılında Avrupa Yeşil Başkenti seçilen ve çevre projeleriyle öne çıkan İspanya şehri neresidir?", "Valensiya", ["Madrid", "Barselona", "Sevilla", "Bilbao"], "Sürdürülebilir kalkınma ve çevre projeleriyle Avrupa Yeşil Başkenti unvanını almıştır.")
]
